<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:tns="http://soa.estrellaroja.com.mx/ReceiptBiz" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://soa.estrellaroja.com.mx/SOAUtilitiesTec/types" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns4="http://soa.estrellaroja.com.mx/StructureReceipt" xmlns:ns3="http://schemas.oracle.com/bpel/extension" xmlns:client="http://soa.estrellaroja.com.mx/ReceiptBiz/bpelDigitalStampReceipts">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/SOAUtilitiesTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetHtmlControlRq" namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelDigitalStampReceipts.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DigitalStampReceiptsRs" namespace="http://soa.estrellaroja.com.mx/ReceiptBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI JAN 19 11:39:14 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:DigitalStampReceiptsRs>
         <tns:Return>
            <tns:GetHtmlControlRq>
               <tns:TotalSucceeded>
                  <xsl:value-of select="/ns0:GetHtmlControlRq/ns0:TotalSucceeded"/>
               </tns:TotalSucceeded>
               <tns:TotalErrors>
                  <xsl:value-of select="/ns0:GetHtmlControlRq/ns0:TotalErrors"/>
               </tns:TotalErrors>
               <tns:ErrorsDetails>
                  <xsl:for-each select="/ns0:GetHtmlControlRq/ns0:ErrorsDetails/ns0:ErrorDetail">
                     <tns:ErrorDetail>
                        <tns:DataValue>
                           <xsl:value-of select="ns0:DataValue"/>
                        </tns:DataValue>
                        <tns:ErrorMessage>
                           <xsl:value-of select="ns0:ErrorMessage"/>
                        </tns:ErrorMessage>
                     </tns:ErrorDetail>
                  </xsl:for-each>
               </tns:ErrorsDetails>
            </tns:GetHtmlControlRq>
         </tns:Return>
      </tns:DigitalStampReceiptsRs>
   </xsl:template>
</xsl:stylesheet>