<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://www.sat.gob.mx/cfd/3" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.sat.gob.mx/cfd/4" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:consumodecombustibles11="http://www.sat.gob.mx/ConsumoDeCombustibles11" xmlns:ns2="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos" xmlns:ns4="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/ComExt" xmlns:catCFDI="http://www.sat.gob.mx/sitio_internet/cfd/catalogos" xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" xmlns:ecc12="http://www.sat.gob.mx/EstadoDeCuentaCombustible12" xmlns:ns1="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina" xmlns:ns3="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte" xmlns:cartaporte20="http://www.sat.gob.mx/CartaPorte20" xmlns:nomina12="http://www.sat.gob.mx/nomina12" xmlns:ns5="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Combustible" xmlns:tdCFDI="http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI" xmlns:pago20="http://www.sat.gob.mx/Pagos20" xmlns:pago10="http://www.sat.gob.mx/Pagos">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Common/XSD/CFDI40/cfdv40.xsd"/>
        <oracle-xsl-mapper:rootElement name="Comprobante" namespace="http://www.sat.gob.mx/cfd/4"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Common/XSD/CFDI/cfdv33.xsd"/>
        <oracle-xsl-mapper:rootElement name="Comprobante" namespace="http://www.sat.gob.mx/cfd/3"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON MAR 14 14:54:43 CST 2022].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Comprobante Version="{/ns0:Comprobante/@Version}" Fecha="{/ns0:Comprobante/@Fecha}" Sello="{/ns0:Comprobante/@Sello}" NoCertificado="{/ns0:Comprobante/@NoCertificado}" Certificado="{/ns0:Comprobante/@Certificado}" SubTotal="{/ns0:Comprobante/@SubTotal}" Moneda="{/ns0:Comprobante/@Moneda}" Total="{/ns0:Comprobante/@Total}" TipoDeComprobante="{/ns0:Comprobante/@TipoDeComprobante}" LugarExpedicion="{/ns0:Comprobante/@LugarExpedicion}">
      <xsl:if test="/ns0:Comprobante/@Serie">
        <xsl:attribute name="Serie">
          <xsl:value-of select="/ns0:Comprobante/@Serie"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:Comprobante/@Folio">
        <xsl:attribute name="Folio">
          <xsl:value-of select="/ns0:Comprobante/@Folio"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:Comprobante/@FormaPago">
        <xsl:attribute name="FormaPago">
          <xsl:value-of select="/ns0:Comprobante/@FormaPago"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:Comprobante/@CondicionesDePago">
        <xsl:attribute name="CondicionesDePago">
          <xsl:value-of select="/ns0:Comprobante/@CondicionesDePago"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:Comprobante/@Descuento">
        <xsl:attribute name="Descuento">
          <xsl:value-of select="/ns0:Comprobante/@Descuento"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:Comprobante/@TipoCambio">
        <xsl:attribute name="TipoCambio">
          <xsl:value-of select="/ns0:Comprobante/@TipoCambio"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:Comprobante/@MetodoPago">
        <xsl:attribute name="MetodoPago">
          <xsl:value-of select="/ns0:Comprobante/@MetodoPago"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/ns0:Comprobante/@Confirmacion">
        <xsl:attribute name="Confirmacion">
          <xsl:value-of select="/ns0:Comprobante/@Confirmacion"/>
        </xsl:attribute>
      </xsl:if>
      <tns:CfdiRelacionados TipoRelacion="{/ns0:Comprobante/ns0:CfdiRelacionados/@TipoRelacion}">
        <xsl:for-each select="/ns0:Comprobante/ns0:CfdiRelacionados/ns0:CfdiRelacionado">
          <tns:CfdiRelacionado UUID="{@UUID}">
            <xsl:value-of select="."/>
          </tns:CfdiRelacionado>
        </xsl:for-each>
      </tns:CfdiRelacionados>
      <tns:Emisor Rfc="{/ns0:Comprobante/ns0:Emisor/@Rfc}" Nombre="{/ns0:Comprobante/ns0:Emisor/@Nombre}" RegimenFiscal="{/ns0:Comprobante/ns0:Emisor/@RegimenFiscal}">
        <xsl:value-of select="/ns0:Comprobante/ns0:Emisor"/>
      </tns:Emisor>
      <tns:Receptor Rfc="{/ns0:Comprobante/ns0:Receptor/@Rfc}" Nombre="{/ns0:Comprobante/ns0:Receptor/@Nombre}" UsoCFDI="{/ns0:Comprobante/ns0:Receptor/@UsoCFDI}">
        <xsl:if test="/ns0:Comprobante/ns0:Receptor/@ResidenciaFiscal">
          <xsl:attribute name="ResidenciaFiscal">
            <xsl:value-of select="/ns0:Comprobante/ns0:Receptor/@ResidenciaFiscal"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:if test="/ns0:Comprobante/ns0:Receptor/@NumRegIdTrib">
          <xsl:attribute name="NumRegIdTrib">
            <xsl:value-of select="/ns0:Comprobante/ns0:Receptor/@NumRegIdTrib"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:Comprobante/ns0:Receptor"/>
      </tns:Receptor>
      <tns:Conceptos>
        <xsl:for-each select="/ns0:Comprobante/ns0:Conceptos/ns0:Concepto">
          <tns:Concepto ClaveProdServ="{@ClaveProdServ}" Cantidad="{@Cantidad}" ClaveUnidad="{@ClaveUnidad}" Descripcion="{@Descripcion}" ValorUnitario="{@ValorUnitario}" Importe="{@Importe}">
            <xsl:if test="@NoIdentificacion">
              <xsl:attribute name="NoIdentificacion">
                <xsl:value-of select="@NoIdentificacion"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="@Unidad">
              <xsl:attribute name="Unidad">
                <xsl:value-of select="@Unidad"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="@Descuento">
              <xsl:attribute name="Descuento">
                <xsl:value-of select="@Descuento"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:Impuestos">
              <tns:Impuestos>
                <xsl:if test="ns0:Impuestos/ns0:Traslados">
                  <tns:Traslados>
                    <xsl:for-each select="ns0:Impuestos/ns0:Traslados/ns0:Traslado">
                      <tns:Traslado Base="{@Base}" Impuesto="{@Impuesto}" TipoFactor="{@TipoFactor}">
                        <xsl:if test="@TasaOCuota">
                          <xsl:attribute name="TasaOCuota">
                            <xsl:value-of select="@TasaOCuota"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="@Importe">
                          <xsl:attribute name="Importe">
                            <xsl:value-of select="@Importe"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="."/>
                      </tns:Traslado>
                    </xsl:for-each>
                  </tns:Traslados>
                </xsl:if>
                <xsl:if test="ns0:Impuestos/ns0:Retenciones">
                  <tns:Retenciones>
                    <xsl:for-each select="ns0:Impuestos/ns0:Retenciones/ns0:Retencion">
                      <tns:Retencion Base="{@Base}" Impuesto="{@Impuesto}" TipoFactor="{@TipoFactor}" TasaOCuota="{@TasaOCuota}" Importe="{@Importe}">
                        <xsl:value-of select="."/>
                      </tns:Retencion>
                    </xsl:for-each>
                  </tns:Retenciones>
                </xsl:if>
              </tns:Impuestos>
            </xsl:if>
            <xsl:for-each select="ns0:InformacionAduanera">
              <tns:InformacionAduanera NumeroPedimento="{@NumeroPedimento}">
                <xsl:value-of select="."/>
              </tns:InformacionAduanera>
            </xsl:for-each>
            <xsl:if test="ns0:CuentaPredial">
              <tns:CuentaPredial Numero="{ns0:CuentaPredial/@Numero}">
                <xsl:value-of select="ns0:CuentaPredial"/>
              </tns:CuentaPredial>
            </xsl:if>
            <xsl:for-each select="ns0:Parte">
              <tns:Parte ClaveProdServ="{@ClaveProdServ}" Cantidad="{@Cantidad}" Descripcion="{@Descripcion}">
                <xsl:if test="@NoIdentificacion">
                  <xsl:attribute name="NoIdentificacion">
                    <xsl:value-of select="@NoIdentificacion"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="@Unidad">
                  <xsl:attribute name="Unidad">
                    <xsl:value-of select="@Unidad"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="@ValorUnitario">
                  <xsl:attribute name="ValorUnitario">
                    <xsl:value-of select="@ValorUnitario"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="@Importe">
                  <xsl:attribute name="Importe">
                    <xsl:value-of select="@Importe"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:for-each select="ns0:InformacionAduanera">
                  <tns:InformacionAduanera NumeroPedimento="{@NumeroPedimento}">
                    <xsl:value-of select="."/>
                  </tns:InformacionAduanera>
                </xsl:for-each>
              </tns:Parte>
            </xsl:for-each>
          </tns:Concepto>
        </xsl:for-each>
      </tns:Conceptos>
      <xsl:if test="/ns0:Comprobante/ns0:Impuestos">
        <tns:Impuestos>
          <xsl:if test="/ns0:Comprobante/ns0:Impuestos/@TotalImpuestosRetenidos">
            <xsl:attribute name="TotalImpuestosRetenidos">
              <xsl:value-of select="/ns0:Comprobante/ns0:Impuestos/@TotalImpuestosRetenidos"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="/ns0:Comprobante/ns0:Impuestos/@TotalImpuestosTrasladados">
            <xsl:attribute name="TotalImpuestosTrasladados">
              <xsl:value-of select="/ns0:Comprobante/ns0:Impuestos/@TotalImpuestosTrasladados"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="/ns0:Comprobante/ns0:Impuestos/ns0:Retenciones">
            <tns:Retenciones>
              <xsl:for-each select="/ns0:Comprobante/ns0:Impuestos/ns0:Retenciones/ns0:Retencion">
                <tns:Retencion Impuesto="{@Impuesto}" Importe="{@Importe}">
                  <xsl:value-of select="."/>
                </tns:Retencion>
              </xsl:for-each>
            </tns:Retenciones>
          </xsl:if>
          <xsl:if test="/ns0:Comprobante/ns0:Impuestos/ns0:Traslados">
            <tns:Traslados>
              <xsl:for-each select="/ns0:Comprobante/ns0:Impuestos/ns0:Traslados/ns0:Traslado">
                <tns:Traslado Impuesto="{@Impuesto}" TipoFactor="{@TipoFactor}" TasaOCuota="{@TasaOCuota}" Importe="{@Importe}">
                  <xsl:value-of select="."/>
                </tns:Traslado>
              </xsl:for-each>
            </tns:Traslados>
          </xsl:if>
        </tns:Impuestos>
      </xsl:if>
      <tns:Complemento>
        <tfd:TimbreFiscalDigital Version="{/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@Version}" UUID="{/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@UUID}" FechaTimbrado="{/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@FechaTimbrado}" RfcProvCertif="{/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@RfcProvCertif}" SelloCFD="{/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@SelloCFD}" NoCertificadoSAT="{/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@NoCertificadoSAT}" SelloSAT="{/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@SelloSAT}">
          <xsl:if test="/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@Leyenda">
            <xsl:attribute name="Leyenda">
              <xsl:value-of select="/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@Leyenda"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital"/>
        </tfd:TimbreFiscalDigital>
        <pago10:Pagos Version="{/ns0:Comprobante/ns0:Complemento/pago20:Pagos/@Version}">
          <xsl:for-each select="/ns0:Comprobante/ns0:Complemento/pago20:Pagos/pago20:Pago">
            <pago10:Pago FechaPago="{@FechaPago}" FormaDePagoP="{@FormaDePagoP}" MonedaP="{@MonedaP}" Monto="{/ns0:Comprobante/ns0:Complemento/pago20:Pagos/pago20:Totales/@MontoTotalPagos}">
              <xsl:if test="@TipoCambioP">
                <xsl:attribute name="TipoCambioP">
                  <xsl:value-of select="@TipoCambioP"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@NumOperacion">
                <xsl:attribute name="NumOperacion">
                  <xsl:value-of select="@NumOperacion"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@RfcEmisorCtaOrd">
                <xsl:attribute name="RfcEmisorCtaOrd">
                  <xsl:value-of select="@RfcEmisorCtaOrd"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@NomBancoOrdExt">
                <xsl:attribute name="NomBancoOrdExt">
                  <xsl:value-of select="@NomBancoOrdExt"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@CtaOrdenante">
                <xsl:attribute name="CtaOrdenante">
                  <xsl:value-of select="@CtaOrdenante"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@RfcEmisorCtaBen">
                <xsl:attribute name="RfcEmisorCtaBen">
                  <xsl:value-of select="@RfcEmisorCtaBen"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@CtaBeneficiario">
                <xsl:attribute name="CtaBeneficiario">
                  <xsl:value-of select="@CtaBeneficiario"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@TipoCadPago">
                <xsl:attribute name="TipoCadPago">
                  <xsl:value-of select="@TipoCadPago"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@CertPago">
                <xsl:attribute name="CertPago">
                  <xsl:value-of select="@CertPago"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@CadPago">
                <xsl:attribute name="CadPago">
                  <xsl:value-of select="@CadPago"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="@SelloPago">
                <xsl:attribute name="SelloPago">
                  <xsl:value-of select="@SelloPago"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:for-each select="pago20:DoctoRelacionado">
                <pago10:DoctoRelacionado IdDocumento="{@IdDocumento}" MonedaDR="{@MonedaDR}" NumParcialidad="{@NumParcialidad}" ImpSaldoAnt="{@ImpSaldoAnt}" ImpPagado="{@ImpPagado}" ImpSaldoInsoluto="{@ImpSaldoInsoluto}">
                  <xsl:if test="@Folio">
                    <xsl:attribute name="Folio">
                      <xsl:value-of select="@Folio"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@Serie">
                    <xsl:attribute name="Serie">
                      <xsl:value-of select="@Serie"/>
                    </xsl:attribute>
                  </xsl:if>
                </pago10:DoctoRelacionado>
              </xsl:for-each>
              <pago10:Impuestos>
                <pago10:Retenciones>
                  <xsl:for-each select="pago20:ImpuestosP/pago20:RetencionesP/pago20:RetencionP">
                    <pago10:Retencion Impuesto="{@ImpuestoP}" Importe="{@ImporteP}">
                      <xsl:value-of select="."/>
                    </pago10:Retencion>
                  </xsl:for-each>
                </pago10:Retenciones>
                <pago10:Traslados>
                  <xsl:for-each select="pago20:ImpuestosP/pago20:TrasladosP/pago20:TrasladoP">
                    <pago10:Traslado Impuesto="{@ImpuestoP}" TipoFactor="{@TipoFactorP}" TasaOCuota="{@TasaOCuotaP}" Importe="{@ImporteP}">
                      <xsl:value-of select="."/>
                    </pago10:Traslado>
                  </xsl:for-each>
                </pago10:Traslados>
              </pago10:Impuestos>
            </pago10:Pago>
          </xsl:for-each>
        </pago10:Pagos>
      </tns:Complemento>
    </tns:Comprobante>
  </xsl:template>
</xsl:stylesheet>