<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationBiz" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns1="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/ERPIntegrationBiz/bpelGenerateReport" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec/types" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://xmlns.oracle.com/bruleGenerateReport/bruleGenerateReportDS">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../../WSDLs/bpelGenerateReport.wsdl"/>
        <oracle-xsl-mapper:rootElement name="GenerateReportRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/OSB/ERPIntegrationServiceTec/ERPIntegrationServiceTec.wsdl"/>
        <oracle-xsl-mapper:rootElement name="RunDataModelRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [TUE MAR 21 16:54:05 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:RunDataModelRq>
      <tns:reportRequest>
        <tns:parameterNameValues>
          <tns:listOfParamNameValues>
            <xsl:if test="/ns0:GenerateReportRq/ns0:parameterNameValues/@xsi:nil">
              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                <xsl:value-of select="/ns0:GenerateReportRq/ns0:parameterNameValues/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:for-each select="/ns0:GenerateReportRq/ns0:parameterNameValues/ns0:item">
              <tns:item>
                <tns:name>
                  <xsl:value-of select="ns0:name"/>
                </tns:name>
                <tns:values>
                  <xsl:if test="ns0:values/@xsi:nil">
                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                      <xsl:value-of select="ns0:values/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:for-each select="ns0:values/ns0:item">
                    <tns:item>
                      <xsl:value-of select="."/>
                    </tns:item>
                  </xsl:for-each>
                </tns:values>
              </tns:item>
            </xsl:for-each>
          </tns:listOfParamNameValues>
        </tns:parameterNameValues>
        <tns:reportAbsolutePath>
          <xsl:value-of select="/ns0:GenerateReportRq/ns0:ReportName"/>
        </tns:reportAbsolutePath>
      </tns:reportRequest>
    </tns:RunDataModelRq>
  </xsl:template>
</xsl:stylesheet>