<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationBiz" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationBiz/types" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ERPIntegrationBiz/ERPIntegrationBiz.wsdl"/>
            <oracle-xsl-mapper:rootElement name="BRuleImportToERPCloudRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ERPIntegrationBiz/ERPIntegrationBiz.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ImportToERPCloudRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"/>
            <oracle-xsl-mapper:param name="inputVariable.payload"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ERPIntegrationBiz/ERPIntegrationBiz.wsdl"/>
            <oracle-xsl-mapper:rootElement name="BRuleImportToERPCloudRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI MAR 09 18:23:47 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="inputVariable.payload"/>
   <xsl:template match="/">
      <ns0:BRuleImportToERPCloudRs>
         <ns0:DocumentAuthor>
            <xsl:value-of select="/ns0:BRuleImportToERPCloudRs/ns0:DocumentAuthor"/>
         </ns0:DocumentAuthor>
         <ns0:DocumentSecurityGroup>
            <xsl:value-of select="/ns0:BRuleImportToERPCloudRs/ns0:DocumentSecurityGroup"/>
         </ns0:DocumentSecurityGroup>
         <ns0:DocumentAccount>
            <xsl:value-of select="/ns0:BRuleImportToERPCloudRs/ns0:DocumentAccount"/>
         </ns0:DocumentAccount>
         <ns0:JobPackageName>
            <xsl:value-of select="/ns0:BRuleImportToERPCloudRs/ns0:JobPackageName"/>
         </ns0:JobPackageName>
         <ns0:JobDefinitionName>
            <xsl:value-of select="/ns0:BRuleImportToERPCloudRs/ns0:JobDefinitionName"/>
         </ns0:JobDefinitionName>
         <ns0:paramListInterface>
            <xsl:value-of select="/ns0:BRuleImportToERPCloudRs/ns0:paramListInterface"/>
         </ns0:paramListInterface>
         <ns0:paramListStandar>
          <xsl:value-of select="strClass:replaceAll(/ns0:BRuleImportToERPCloudRs/ns0:paramListStandar,'B',$inputVariable.payload/ns0:ImportToERPCloudRq/ns0:File/ns0:DocumentId)"/> 
         </ns0:paramListStandar>
      </ns0:BRuleImportToERPCloudRs>
   </xsl:template>
</xsl:stylesheet>