<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/DailyRatesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/DailyRatesBiz/nxsdDailyRates"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://soa.estrellaroja.com.mx/DailyRatesBiz/bpelCreateDailyRates"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns4="http://soa.estrellaroja.com.mx/SOAUtilitiesTec/types">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelCreateDailyRates.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DailyRatesRs" namespace="http://soa.estrellaroja.com.mx/DailyRatesBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/External/SOAUtilitiesTecWrapper1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetHtmlControlRq" namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [FRI MAR 12 12:49:38 CST 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetHtmlControlRq>
         <xsl:choose>
            <xsl:when test="string-length (/ns0:DailyRatesRs/ns1:Errors/ns1:Error/ns1:ShortDescription)=0">
            <tns:TotalSucceeded>1</tns:TotalSucceeded>
            <tns:TotalErrors>0</tns:TotalErrors>
            <tns:TotalProcessed>1</tns:TotalProcessed>
            </xsl:when>
            <xsl:otherwise>
            <tns:TotalSucceeded>0</tns:TotalSucceeded>
            <tns:TotalErrors>1</tns:TotalErrors>
            <tns:TotalProcessed>1</tns:TotalProcessed>
            <tns:ErrorsDetails>
            <tns:ErrorDetail>
                     <tns:DataValue>
                        <xsl:value-of select="/ns0:DailyRatesRs/ns1:Errors/ns1:Error/ns1:ErrorCode"/>
                     </tns:DataValue>
                     <tns:ErrorMessage>
                        <xsl:value-of select="/ns0:DailyRatesRs/ns1:Errors/ns1:Error/ns1:ShortDescription"/>
                     </tns:ErrorMessage>
                  </tns:ErrorDetail>
         </tns:ErrorsDetails>
            </xsl:otherwise>
         </xsl:choose>
      </tns:GetHtmlControlRq>
   </xsl:template>
</xsl:stylesheet>
