<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://soa.estrellaroja.com.mx/DailyRatesBiz/nxsdDailyRates" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/BanxicoTec" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://soa.estrellaroja.com.mx/BanxicoTec/types"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns4="http://schemas.oracle.com/bpel/extension"
                xmlns:client="http://soa.estrellaroja.com.mx/DailyRatesBiz/bpelCreateDailyRates"
                xmlns:ns3="http://soa.estrellaroja.com.mx/DailyRatesBiz">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/External/BanxicoTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetExchangeRateRs" namespace="http://soa.estrellaroja.com.mx/BanxicoTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelCreateDailyRates.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DailyRates" namespace="http://soa.estrellaroja.com.mx/DailyRatesBiz/nxsdDailyRates"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON MAR 01 13:21:37 CST 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="v_day"/>
   <xsl:param name="v_dayDomingo"/>
   <xsl:template match="/">
      <tns:DailyRates>
         <tns:DailyRate>
            <tns:fromCurrency>USD</tns:fromCurrency>
            <tns:toCurrency>MXN</tns:toCurrency>
            <tns:fromDate>
               <xsl:value-of select="$v_day"/>
            </tns:fromDate>
            <tns:toDate>
               <xsl:value-of select="$v_day"/>
            </tns:toDate>
            <tns:classExchangeRate>Corporate</tns:classExchangeRate>
            <tns:fromExchangeRate>
               <xsl:value-of select="/ns0:GetExchangeRateRs/ns0:series/ns0:datos/ns0:dato"/>
            </tns:fromExchangeRate>
         </tns:DailyRate>
         <tns:DailyRate>
            <tns:fromCurrency>USD</tns:fromCurrency>
            <tns:toCurrency>MXN</tns:toCurrency>
            <tns:fromDate>
               <xsl:value-of select="$v_dayDomingo"/>
            </tns:fromDate>
            <tns:toDate>
               <xsl:value-of select="$v_dayDomingo"/>
            </tns:toDate>
            <tns:classExchangeRate>Corporate</tns:classExchangeRate>
            <tns:fromExchangeRate>
               <xsl:value-of select="/ns0:GetExchangeRateRs/ns0:series/ns0:datos/ns0:dato"/>
            </tns:fromExchangeRate>
         </tns:DailyRate>
      </tns:DailyRates>
   </xsl:template>
</xsl:stylesheet>
