<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://soa.estrellaroja.com.mx/AuditControlTec/types"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ElectronicInvoiceAP"
                xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelValidatePaymentComplements">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelValidatePaymentComplements.wsdl"/>
            <oracle-xsl-mapper:rootElement name="LogPaymentComplement" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/AuditControlTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MergeIncPaymentComplementRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI DEC 22 13:05:33 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:MergeIncPaymentComplementRq>
         <tns:IncPaymentComplementId>
            <xsl:value-of select="/ns0:LogPaymentComplement/ns0:IncPaymentComplementId"/>
         </tns:IncPaymentComplementId>
         <xsl:if test="/ns0:LogPaymentComplement/ns0:Status">
            <tns:Status>
               <xsl:value-of select="/ns0:LogPaymentComplement/ns0:Status"/>
            </tns:Status>
         </xsl:if>
         <xsl:if test="/ns0:LogPaymentComplement/ns0:StatusDesc">
            <tns:StatusDesc>
               <xsl:value-of select="/ns0:LogPaymentComplement/ns0:StatusDesc"/>
            </tns:StatusDesc>
         </xsl:if>
         <xsl:for-each select="/ns0:LogPaymentComplement/ns0:Invoice">
            <tns:Invoice>
               <tns:IncPaymentCmpInvoiceId>
                  <xsl:value-of select="ns0:IncPaymentCmpInvoiceId"/>
               </tns:IncPaymentCmpInvoiceId>
            </tns:Invoice>
         </xsl:for-each>
      </tns:MergeIncPaymentComplementRq>
   </xsl:template>
</xsl:stylesheet>
