<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://soa.estrellaroja.com.mx/InvoicesBiz" xmlns:ns0="http://soa.estrellaroja.com.mx/FinancialsTec" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns2="http://soa.estrellaroja.com.mx/FinancialsTec/types"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelBuildInvoicesZip"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns4="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns3="http://schemas.oracle.com/bpel/extension"
                xmlns:ns5="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns6="http://soa.estrellaroja.com.mx/InvoicesBiz/StructursInvoicesBiz"
                xmlns:ns7="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/FinancialsTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetReceiptOrInvoicesRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelBuildInvoicesZip.wsdl"/>
            <oracle-xsl-mapper:rootElement name="invoicesToCsv" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED JAN 03 19:19:18 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:invoicesToCsv>
         <xsl:for-each select="/ns0:GetReceiptOrInvoicesRs/ns0:Return/ns0:Invoices/ns0:Invoice">
            <tns:InvoicesList>
               <tns:Notes_from_Source>
                  <xsl:value-of select="ns0:NotesFromSource"/>
               </tns:Notes_from_Source>
               <tns:Transaction_Batch_Source_Name>
                  <xsl:value-of select="ns0:TransactionBatchSourceName"/>
               </tns:Transaction_Batch_Source_Name>
               <tns:Transaction_Type_Name>
                  <xsl:value-of select="ns0:TransactionTypeName"/>
               </tns:Transaction_Type_Name>
               <tns:Payment_Terms>
                  <xsl:value-of select="ns0:PaymentTerms"/>
               </tns:Payment_Terms>
               <tns:Transaction_Date>
                  <!--<xsl:value-of select="ns0:TransactionDate"/>-->
                  <xsl:value-of select="concat (substring (ns0:TransactionDate, 1, 4 ), &quot;/&quot;, substring (ns0:TransactionDate, 6, 2 ), &quot;/&quot;, substring (ns0:TransactionDate, 9, 2 ) )"/>                  
               </tns:Transaction_Date>
               <tns:Accounting_Date>
                  <!--<xsl:value-of select="ns0:AccountingDate"/>-->
                  <xsl:value-of select="concat (substring (ns0:AccountingDate, 1, 4 ), &quot;/&quot;, substring (ns0:AccountingDate, 6, 2 ), &quot;/&quot;, substring (ns0:AccountingDate, 9, 2 ) )"/>
               </tns:Accounting_Date>
               <tns:Transaction_Number>
                  <xsl:value-of select="ns0:TransactionNumber"/>
               </tns:Transaction_Number>
               <tns:Original_System_Bill_to_Customer_Reference>
                  <xsl:value-of select="ns0:OriginalSystemBillToCustomerRef"/>
               </tns:Original_System_Bill_to_Customer_Reference>
               <tns:Original_System_Bill_to_Customer_Address_Reference>
                  <xsl:value-of select="ns0:OriginalSystemBillToCustomerAddressRef"/>
               </tns:Original_System_Bill_to_Customer_Address_Reference>
               <tns:Original_System_Bill_to_Customer_Contact_Reference>
                  <xsl:value-of select="ns0:OriginalSystemBillToCustomerContactRef"/>
               </tns:Original_System_Bill_to_Customer_Contact_Reference>
               <tns:Original_System_Ship_to_Customer_Reference>
                  <xsl:value-of select="ns0:OriginalSystemShipToCustomerRef"/>
               </tns:Original_System_Ship_to_Customer_Reference>
               <tns:Original_System_Ship_to_Customer_Address_Reference>
                  <xsl:value-of select="ns0:OriginalSystemShipToCustomerAddressRef"/>
               </tns:Original_System_Ship_to_Customer_Address_Reference>
               <tns:Original_System_Ship_to_Customer_Contact_Reference>
                  <xsl:value-of select="ns0:OriginalSystemShipToCustomerContactRef"/>
               </tns:Original_System_Ship_to_Customer_Contact_Reference>
               <tns:Original_System_Ship_to_Customer_Account_Reference>
                  <xsl:value-of select="ns0:OriginalSystemShipToCustomerAccountRef"/>
               </tns:Original_System_Ship_to_Customer_Account_Reference>
               <tns:Original_System_Ship_to_Customer_Account_Address_Reference>
                  <xsl:value-of select="ns0:OriginalSystemShipToCustomerAccountAddressRef"/>
               </tns:Original_System_Ship_to_Customer_Account_Address_Reference>
               <tns:Original_System_Ship_to_Customer_Account_Contact_Reference>
                  <xsl:value-of select="ns0:OriginalSystemShipToCustomerAccountContactRef"/>
               </tns:Original_System_Ship_to_Customer_Account_Contact_Reference>
               <tns:Original_System_Sold_to_Customer_Reference>
                  <xsl:value-of select="ns0:OriginalSystemSoldToCustomerRef"/>
               </tns:Original_System_Sold_to_Customer_Reference>
               <tns:Original_System_Sold_to_Customer_Account_Reference>
                  <xsl:value-of select="ns0:OriginalSystemSoldToCustomerAccountRef"/>
               </tns:Original_System_Sold_to_Customer_Account_Reference>
               <tns:Bill_to_Customer_Account_Number>
                  <xsl:value-of select="ns0:BillToCustomerAccountNumber"/>
               </tns:Bill_to_Customer_Account_Number>
               <tns:Bill_to_Customer_Site_Number>
                  <xsl:value-of select="ns0:BillToCustomerSiteNumber"/>
               </tns:Bill_to_Customer_Site_Number>
               <tns:Bill_to_Contact_Party_Number>
                  <xsl:value-of select="ns0:BillToContactPartyNumber"/>
               </tns:Bill_to_Contact_Party_Number>
               <tns:Ship_to_Customer_Account_Number>
                  <xsl:value-of select="ns0:ShipToCustomerAccountNumber"/>
               </tns:Ship_to_Customer_Account_Number>
               <tns:Ship_to_Customer_Site_Number>
                  <xsl:value-of select="ns0:ShipToCustomerSiteNumber"/>
               </tns:Ship_to_Customer_Site_Number>
               <tns:Ship_to_Contact_Party_Number>
                  <xsl:value-of select="ns0:ShipToContactPartyNumber"/>
               </tns:Ship_to_Contact_Party_Number>
               <tns:Sold_to_Customer_Account_Number>
                  <xsl:value-of select="ns0:SoldToCustomerAccountNumber"/>
               </tns:Sold_to_Customer_Account_Number>
               <tns:Transaction_Line_Type>
                  <xsl:value-of select="ns0:TransactionLineType"/>
               </tns:Transaction_Line_Type>
               <tns:Transaction_Line_Description>
                  <xsl:value-of select="ns0:TransactionLineDescription"/>
               </tns:Transaction_Line_Description>
               <tns:Currency_Code>
                  <xsl:value-of select="ns0:CurrencyCode"/>
               </tns:Currency_Code>
               <tns:Currency_Conversion_Type>
                  <xsl:value-of select="ns0:CurrencyConversionType"/>
               </tns:Currency_Conversion_Type>
               <tns:Currency_Conversion_Date>
                  <!--<xsl:value-of select="ns0:CurrencyConversionDate"/>-->
                  <xsl:value-of select="concat (substring (ns0:CurrencyConversionDate, 1, 4 ), &quot;/&quot;, substring (ns0:CurrencyConversionDate, 6, 2 ), &quot;/&quot;, substring (ns0:CurrencyConversionDate, 9, 2 ) )"/>
               </tns:Currency_Conversion_Date>
               <tns:Currency_Conversion_Rate>
                  <xsl:value-of select="ns0:CurrencyConversionRate"/>
               </tns:Currency_Conversion_Rate>
               <tns:Transaction_Line_Amount>
                  <xsl:value-of select="ns0:TransactionLineAmount"/>
               </tns:Transaction_Line_Amount>
               <tns:Transaction_Line_Quantity>
                  <xsl:value-of select="ns0:TransactionLineQuantity"/>
               </tns:Transaction_Line_Quantity>
               <tns:Customer_Ordered_Quantity>
                  <xsl:value-of select="ns0:CustomerOrderedQuantity"/>
               </tns:Customer_Ordered_Quantity>
               <tns:Unit_Selling_Price>
                  <xsl:value-of select="ns0:UnitSellingPrice"/>
               </tns:Unit_Selling_Price>
               <tns:Unit_Standard_Price>
                  <xsl:value-of select="ns0:UnitStandarPrice"/>
               </tns:Unit_Standard_Price>
               <tns:Line_Transactions_Flexfield_Context>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledContext"/>
               </tns:Line_Transactions_Flexfield_Context>
               <tns:Line_Transactions_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment1"/>
               </tns:Line_Transactions_Flexfield_Segment_1>
               <tns:Line_Transactions_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment2"/>
               </tns:Line_Transactions_Flexfield_Segment_2>
               <tns:Line_Transactions_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment3"/>
               </tns:Line_Transactions_Flexfield_Segment_3>
               <tns:Line_Transactions_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment4"/>
               </tns:Line_Transactions_Flexfield_Segment_4>
               <tns:Line_Transactions_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment5"/>
               </tns:Line_Transactions_Flexfield_Segment_5>
               <tns:Line_Transactions_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment6"/>
               </tns:Line_Transactions_Flexfield_Segment_6>
               <tns:Line_Transactions_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment7"/>
               </tns:Line_Transactions_Flexfield_Segment_7>
               <tns:Line_Transactions_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment8"/>
               </tns:Line_Transactions_Flexfield_Segment_8>
               <tns:Line_Transactions_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment9"/>
               </tns:Line_Transactions_Flexfield_Segment_9>
               <tns:Line_Transactions_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment10"/>
               </tns:Line_Transactions_Flexfield_Segment_10>
               <tns:Line_Transactions_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment11"/>
               </tns:Line_Transactions_Flexfield_Segment_11>
               <tns:Line_Transactions_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment12"/>
               </tns:Line_Transactions_Flexfield_Segment_12>
               <tns:Line_Transactions_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment13"/>
               </tns:Line_Transactions_Flexfield_Segment_13>
               <tns:Line_Transactions_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment14"/>
               </tns:Line_Transactions_Flexfield_Segment_14>
               <tns:Line_Transactions_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:LineTransactionsFlexfiledSegment15"/>
               </tns:Line_Transactions_Flexfield_Segment_15>
               <tns:Primary_Salesperson_Number>
                  <xsl:value-of select="ns0:PrimarySalesPersonNumber"/>
               </tns:Primary_Salesperson_Number>
               <tns:Tax_Classification_Code>
                  <xsl:value-of select="ns0:TaxCassificationCode"/>
               </tns:Tax_Classification_Code>
               <tns:Legal_Entity_Identifier>
                  <xsl:value-of select="ns0:LegalEntityIdentifier"/>
               </tns:Legal_Entity_Identifier>
               <tns:Accounted_Amount_in_Ledger_Currency>
                  <xsl:value-of select="ns0:AccountedAmountInLedgerCurrency"/>
               </tns:Accounted_Amount_in_Ledger_Currency>
               <tns:Sales_Order_Number>
                  <xsl:value-of select="ns0:SalesOrderNumber"/>
               </tns:Sales_Order_Number>
               <tns:Sales_Order_Date>
                  <xsl:value-of select="ns0:SalesOrderDate"/>
               </tns:Sales_Order_Date>
               <tns:Actual_Ship_Date>
                  <xsl:value-of select="ns0:ActualShipDate"/>
               </tns:Actual_Ship_Date>
               <tns:Warehouse_Code>
                  <xsl:value-of select="ns0:WarehouseCode"/>
               </tns:Warehouse_Code>
               <tns:Unit_of_Measure_Code>
                  <xsl:value-of select="ns0:UnitOfMeasureCode"/>
               </tns:Unit_of_Measure_Code>
               <tns:Unit_of_Measure_Name>
                  <xsl:value-of select="ns0:UnitOfMeasureName"/>
               </tns:Unit_of_Measure_Name>
               <tns:Invoicing_Rule_Name>
                  <xsl:value-of select="ns0:InvoicingRuleName"/>
               </tns:Invoicing_Rule_Name>
               <tns:Revenue_Scheduling_Rule_Name>
                  <xsl:value-of select="ns0:RevenueSchedulingRuleName"/>
               </tns:Revenue_Scheduling_Rule_Name>
               <tns:Number_of_Revenue_Periods>
                  <xsl:value-of select="ns0:NumberOfRevenuePeriods"/>
               </tns:Number_of_Revenue_Periods>
               <tns:Revenue_Scheduling_Rule_Start_Date>
                  <xsl:value-of select="ns0:RevenueSchedulingRuleStartDate"/>
               </tns:Revenue_Scheduling_Rule_Start_Date>
               <tns:Revenue_Scheduling_Rule_End_Date>
                  <xsl:value-of select="ns0:RevenueSchedulingRuleEndDate"/>
               </tns:Revenue_Scheduling_Rule_End_Date>
               <tns:Reason_Code_Meaning>
                  <xsl:value-of select="ns0:ReasonCodeMeaning"/>
               </tns:Reason_Code_Meaning>
               <tns:Last_Period_to_Credit>
                  <xsl:value-of select="ns0:LastPeriodToCredit"/>
               </tns:Last_Period_to_Credit>
               <tns:Transaction_Business_Category_Code>
                  <xsl:value-of select="ns0:TransactionBusinessCategoryCode"/>
               </tns:Transaction_Business_Category_Code>
               <tns:Product_Fiscal_Classification_Code>
                  <xsl:value-of select="ns0:ProductFiscalClassicationCode"/>
               </tns:Product_Fiscal_Classification_Code>
               <tns:Product_Category_Code>
                  <xsl:value-of select="ns0:ProductCategoryCode"/>
               </tns:Product_Category_Code>
               <tns:Product_Type>
                  <xsl:value-of select="ns0:ProductType"/>
               </tns:Product_Type>
               <tns:Line_Intended_Use_Code>
                  <xsl:value-of select="ns0:LineIntendedUseCode"/>
               </tns:Line_Intended_Use_Code>
               <tns:Assessable_Value>
                  <xsl:value-of select="ns0:AssessableValue"/>
               </tns:Assessable_Value>
               <tns:Document_Sub_Type>
                  <xsl:value-of select="ns0:DocumentSubType"/>
               </tns:Document_Sub_Type>
               <tns:Default_Taxation_Country>
                  <xsl:value-of select="ns0:DefaultTaxationCountry"/>
               </tns:Default_Taxation_Country>
               <tns:User_Defined_Fiscal_Classification>
                  <xsl:value-of select="ns0:UserDefinedFiscalClassification"/>
               </tns:User_Defined_Fiscal_Classification>
               <tns:Tax_Invoice_Number>
                  <xsl:value-of select="ns0:TaxInvoiceNumber"/>
               </tns:Tax_Invoice_Number>
               <tns:Tax_Invoice_Date>
                  <xsl:value-of select="ns0:TaxInvoiceDate"/>
               </tns:Tax_Invoice_Date>
               <tns:Tax_Regime_Code>
                  <xsl:value-of select="ns0:TaxRegimeCode"/>
               </tns:Tax_Regime_Code>
               <tns:Tax>
                  <xsl:value-of select="ns0:TAX"/>
               </tns:Tax>
               <tns:Tax_Status_Code>
                  <xsl:value-of select="ns0:TaxStatusCode"/>
               </tns:Tax_Status_Code>
               <tns:Tax_Rate_Code>
                  <xsl:value-of select="ns0:TaxRateCode"/>
               </tns:Tax_Rate_Code>
               <tns:Tax_Jurisdiction_Code>
                  <xsl:value-of select="ns0:TaxJuridictionCode"/>
               </tns:Tax_Jurisdiction_Code>
               <tns:First_Party_Registration_Number>
                  <xsl:value-of select="ns0:FirstPartyRegistrationNumber"/>
               </tns:First_Party_Registration_Number>
               <tns:Third_Party_Registration_Number>
                  <xsl:value-of select="ns0:ThirdPartyRegistrationNumber"/>
               </tns:Third_Party_Registration_Number>
               <tns:Final_Discharge_Location>
                  <xsl:value-of select="ns0:FinalDischargeLocation"/>
               </tns:Final_Discharge_Location>
               <tns:Taxable_Amount>
                  <xsl:value-of select="ns0:TaxableAmount"/>
               </tns:Taxable_Amount>
               <tns:Taxable_Flag>
                  <xsl:value-of select="ns0:TaxableFlag"/>
               </tns:Taxable_Flag>
               <tns:Tax_Exemption_Flag>
                  <xsl:value-of select="ns0:TaxExemptionFlag"/>
               </tns:Tax_Exemption_Flag>
               <tns:TTax_Exemption_Reason_Code>
                  <xsl:value-of select="ns0:TaxExemptionReasonCode"/>
               </tns:TTax_Exemption_Reason_Code>
               <tns:Tax_Exemption_Reason_Code_Meaning>
                  <xsl:value-of select="ns0:TaxExemptionReasonCodeMeaning"/>
               </tns:Tax_Exemption_Reason_Code_Meaning>
               <tns:Tax_Exemption_Certificate_Number>
                  <xsl:value-of select="ns0:TaxExemptionCertificateNumber"/>
               </tns:Tax_Exemption_Certificate_Number>
               <tns:Line_Amount_Includes_Tax_Flag>
                  <xsl:value-of select="ns0:LineAmountIncludes_TaxFlag"/>
               </tns:Line_Amount_Includes_Tax_Flag>
               <tns:Tax_Precedence>
                  <xsl:value-of select="ns0:TaxPrecedent"/>
               </tns:Tax_Precedence>
               <tns:Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules>
                  <xsl:value-of select="ns0:CreditMethodToBeUserForLinesWithRevenueSchedulingRules"/>
               </tns:Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules>
               <tns:Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms>
                  <xsl:value-of select="ns0:CreditMethodToBeUserForTransactionsWithSpritPaymentTerms"/>
               </tns:Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms>
               <tns:Reason_Code>
                  <xsl:value-of select="ns0:ReasonCode"/>
               </tns:Reason_Code>
               <tns:Tax_Rate>
                  <xsl:value-of select="ns0:TaxRate"/>
               </tns:Tax_Rate>
               <tns:FOB_Point>
                  <xsl:value-of select="ns0:FobPoint"/>
               </tns:FOB_Point>
               <tns:Carrier>
                  <xsl:value-of select="ns0:Carrier"/>
               </tns:Carrier>
               <tns:Shipping_Reference>
                  <xsl:value-of select="ns0:ShippingReference"/>
               </tns:Shipping_Reference>
               <tns:Sales_Order_Line_Number>
                  <xsl:value-of select="ns0:SalesOrderLineNumber"/>
               </tns:Sales_Order_Line_Number>
               <tns:Sales_Order_Source>
                  <xsl:value-of select="ns0:SalesOrderSource"/>
               </tns:Sales_Order_Source>
               <tns:Sales_Order_Revision_Number>
                  <xsl:value-of select="ns0:SalesOrderRevisionNumber"/>
               </tns:Sales_Order_Revision_Number>
               
                <tns:Purchase_Order_Number>
                  <xsl:value-of select="ns0:PurchaseOrderNumber"/>
               </tns:Purchase_Order_Number>
               <tns:Purchase_Order_Revision_Number>
                  <xsl:value-of select="ns0:PurchaseOrder_RevisionNumber"/>
               </tns:Purchase_Order_Revision_Number>
               <tns:Purchase_Order_Date>
                  <xsl:value-of select="ns0:PurchaseOrderDate"/>
               </tns:Purchase_Order_Date>
               <tns:Agreement_Name>
                  <xsl:value-of select="ns0:AgreementName"/>
               </tns:Agreement_Name>
               <tns:Memo_Line_Name>
                  <xsl:value-of select="ns0:MemoLineName"/>
               </tns:Memo_Line_Name>
               <tns:Document_Number>
                  <xsl:value-of select="ns0:DocumentNumber"/>
               </tns:Document_Number>
               <tns:Original_System_Batch_Name>
                  <xsl:value-of select="ns0:OriginalSystemBatchName"/>
               </tns:Original_System_Batch_Name>
               <tns:Link_to_Transactions_Flexfield_Context>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldContext"/>
               </tns:Link_to_Transactions_Flexfield_Context>
               <tns:Link_to_Transactions_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment1"/>
               </tns:Link_to_Transactions_Flexfield_Segment_1>
               <tns:Link_to_Transactions_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment2"/>
               </tns:Link_to_Transactions_Flexfield_Segment_2>
               <tns:Link_to_Transactions_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment3"/>
               </tns:Link_to_Transactions_Flexfield_Segment_3>
               <tns:Link_to_Transactions_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment4"/>
               </tns:Link_to_Transactions_Flexfield_Segment_4>
               <tns:Link_to_Transactions_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment5"/>
               </tns:Link_to_Transactions_Flexfield_Segment_5>
               <tns:Link_to_Transactions_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment6"/>
               </tns:Link_to_Transactions_Flexfield_Segment_6>
               <tns:Link_to_Transactions_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment7"/>
               </tns:Link_to_Transactions_Flexfield_Segment_7>
               <tns:Link_to_Transactions_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment8"/>
               </tns:Link_to_Transactions_Flexfield_Segment_8>
               <tns:Link_to_Transactions_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment9"/>
               </tns:Link_to_Transactions_Flexfield_Segment_9>
               <tns:Link_to_Transactions_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment10"/>
               </tns:Link_to_Transactions_Flexfield_Segment_10>
               <tns:Link_to_Transactions_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment11"/>
               </tns:Link_to_Transactions_Flexfield_Segment_11>
               <tns:Link_to_Transactions_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment12"/>
               </tns:Link_to_Transactions_Flexfield_Segment_12>
               <tns:Link_to_Transactions_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment13"/>
               </tns:Link_to_Transactions_Flexfield_Segment_13>
               <tns:Link_to_Transactions_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment14"/>
               </tns:Link_to_Transactions_Flexfield_Segment_14>
               <tns:Link_to_Transactions_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:LinkToTransactionsFlexfieldSegment15"/>
               </tns:Link_to_Transactions_Flexfield_Segment_15>
               <tns:Reference_Transactions_Flexfield_Context>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldContext"/>
               </tns:Reference_Transactions_Flexfield_Context>
               <tns:Reference_Transactions_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment1"/>
               </tns:Reference_Transactions_Flexfield_Segment_1>
               <tns:Reference_Transactions_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment2"/>
               </tns:Reference_Transactions_Flexfield_Segment_2>
               <tns:Reference_Transactions_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment3"/>
               </tns:Reference_Transactions_Flexfield_Segment_3>
               <tns:Reference_Transactions_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment4"/>
               </tns:Reference_Transactions_Flexfield_Segment_4>
               <tns:Reference_Transactions_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment5"/>
               </tns:Reference_Transactions_Flexfield_Segment_5>
               <tns:Reference_Transactions_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment6"/>
               </tns:Reference_Transactions_Flexfield_Segment_6>
               <tns:Reference_Transactions_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment7"/>
               </tns:Reference_Transactions_Flexfield_Segment_7>
               <tns:Reference_Transactions_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment8"/>
               </tns:Reference_Transactions_Flexfield_Segment_8>
               <tns:Reference_Transactions_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment9"/>
               </tns:Reference_Transactions_Flexfield_Segment_9>
               <tns:Reference_Transactions_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment10"/>
               </tns:Reference_Transactions_Flexfield_Segment_10>
               <tns:Reference_Transactions_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment11"/>
               </tns:Reference_Transactions_Flexfield_Segment_11>
               <tns:Reference_Transactions_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment12"/>
               </tns:Reference_Transactions_Flexfield_Segment_12>
               <tns:Reference_Transactions_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment13"/>
               </tns:Reference_Transactions_Flexfield_Segment_13>

               <tns:Reference_Transactions_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment14"/>
               </tns:Reference_Transactions_Flexfield_Segment_14>

               <tns:Reference_Transactions_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:ReferenceTransationsFlexfieldSegment15"/>
               </tns:Reference_Transactions_Flexfield_Segment_15>

               <tns:Link_To_Parent_Line_Context>
                  <xsl:value-of select="ns0:LinkToParentLineContext"/>
               </tns:Link_To_Parent_Line_Context>

               <tns:Link_To_Parent_Line_Segment_1>
                  <xsl:value-of select="ns0:LinkToParentLineSegment1"/>
               </tns:Link_To_Parent_Line_Segment_1>

               <tns:Link_To_Parent_Line_Segment_2>
                  <xsl:value-of select="ns0:LinkToParentLineSegment2"/>
               </tns:Link_To_Parent_Line_Segment_2>

               <tns:Link_To_Parent_Line_Segment_3>
                  <xsl:value-of select="ns0:LinkToParentLineSegment3"/>
               </tns:Link_To_Parent_Line_Segment_3>

               <tns:Link_To_Parent_Line_Segment_4>
                  <xsl:value-of select="ns0:LinkToParentLineSegment4"/>
               </tns:Link_To_Parent_Line_Segment_4>

               <tns:Link_To_Parent_Line_Segment_5>
                  <xsl:value-of select="ns0:LinkToParentLineSegment5"/>
               </tns:Link_To_Parent_Line_Segment_5>

               <tns:Link_To_Parent_Line_Segment_6>
                  <xsl:value-of select="ns0:LinkToParentLineSegment6"/>
               </tns:Link_To_Parent_Line_Segment_6>

               <tns:Link_To_Parent_Line_Segment_7>
                  <xsl:value-of select="ns0:LinkToParentLineSegment7"/>
               </tns:Link_To_Parent_Line_Segment_7>

               <tns:Link_To_Parent_Line_Segment_8>
                  <xsl:value-of select="ns0:LinkToParentLineSegment8"/>
               </tns:Link_To_Parent_Line_Segment_8>

               <tns:Link_To_Parent_Line_Segment_9>
                  <xsl:value-of select="ns0:LinkToParentLineSegment9"/>
               </tns:Link_To_Parent_Line_Segment_9>

               <tns:Link_To_Parent_Line_Segment_10>
                  <xsl:value-of select="ns0:LinkToParentLineSegment10"/>
               </tns:Link_To_Parent_Line_Segment_10>

               <tns:Link_To_Parent_Line_Segment_11>
                  <xsl:value-of select="ns0:LinkToParentLineSegment11"/>
               </tns:Link_To_Parent_Line_Segment_11>

               <tns:Link_To_Parent_Line_Segment_12>
                  <xsl:value-of select="ns0:LinkToParentLineSegment12"/>
               </tns:Link_To_Parent_Line_Segment_12>

               <tns:Link_To_Parent_Line_Segment_13>
                  <xsl:value-of select="ns0:LinkToParentLineSegment13"/>
               </tns:Link_To_Parent_Line_Segment_13>

               <tns:Link_To_Parent_Line_Segment_14>
                  <xsl:value-of select="ns0:LinkToParentLineSegment14"/>
               </tns:Link_To_Parent_Line_Segment_14>

               <tns:Link_To_Parent_Line_Segment_15>
                  <xsl:value-of select="ns0:LinkToParentLineSegment15"/>
               </tns:Link_To_Parent_Line_Segment_15>

               <tns:Receipt_Method_Name>
                  <xsl:value-of select="ns0:ReceiptMethodName"/>
               </tns:Receipt_Method_Name>

               <tns:Printing_Option>
                  <xsl:value-of select="ns0:PrintingOption"/>
               </tns:Printing_Option>

               <tns:Related_Batch_Source_Name>
                  <xsl:value-of select="ns0:RelatedBatchSourceName"/>
               </tns:Related_Batch_Source_Name>

               <tns:Related_Transaction_Number>
                  <xsl:value-of select="ns0:RelatedTransactionNumber"/>
               </tns:Related_Transaction_Number>

               <tns:Inventory_Item_Number>
                  <xsl:value-of select="ns0:InventoryItemNumber"/>
               </tns:Inventory_Item_Number>

               <tns:Inventory_Item_Segment_2>
                  <xsl:value-of select="ns0:InventoryItemSegment2"/>
               </tns:Inventory_Item_Segment_2>

               <tns:Inventory_Item_Segment_3>
                  <xsl:value-of select="ns0:InventoryItemSegment3"/>
               </tns:Inventory_Item_Segment_3>

               <tns:Inventory_Item_Segment_4>
                  <xsl:value-of select="ns0:InventoryItemSegment4"/>
               </tns:Inventory_Item_Segment_4>

               <tns:Inventory_Item_Segment_5>
                  <xsl:value-of select="ns0:InventoryItemSegment5"/>
               </tns:Inventory_Item_Segment_5>

               <tns:Inventory_Item_Segment_6>
                  <xsl:value-of select="ns0:InventoryItemSegment6"/>
               </tns:Inventory_Item_Segment_6>

               <tns:Inventory_Item_Segment_7>
                  <xsl:value-of select="ns0:InventoryItemSegment7"/>
               </tns:Inventory_Item_Segment_7>

               <tns:Inventory_Item_Segment_8>
                  <xsl:value-of select="ns0:InventoryItemSegment8"/>
               </tns:Inventory_Item_Segment_8>

               <tns:Inventory_Item_Segment_9>
                  <xsl:value-of select="ns0:InventoryItemSegment9"/>
               </tns:Inventory_Item_Segment_9>

               <tns:Inventory_Item_Segment_10>
                  <xsl:value-of select="ns0:InventoryItemSegment10"/>
               </tns:Inventory_Item_Segment_10>

               <tns:Inventory_Item_Segment_11>
                  <xsl:value-of select="ns0:InventoryItemSegment11"/>
               </tns:Inventory_Item_Segment_11>

               <tns:Inventory_Item_Segment_12>
                  <xsl:value-of select="ns0:InventoryItemSegment12"/>
               </tns:Inventory_Item_Segment_12>

               <tns:Inventory_Item_Segment_13>
                  <xsl:value-of select="ns0:InventoryItemSegment13"/>
               </tns:Inventory_Item_Segment_13>

               <tns:Inventory_Item_Segment_14>
                  <xsl:value-of select="ns0:InventoryItemSegment14"/>
               </tns:Inventory_Item_Segment_14>

               <tns:Inventory_Item_Segment_15>
                  <xsl:value-of select="ns0:InventoryItemSegment15"/>
               </tns:Inventory_Item_Segment_15>

               <tns:Inventory_Item_Segment_16>
                  <xsl:value-of select="ns0:InventoryItemSegment16"/>
               </tns:Inventory_Item_Segment_16>

               <tns:Inventory_Item_Segment_17>
                  <xsl:value-of select="ns0:InventoryItemSegment17"/>
               </tns:Inventory_Item_Segment_17>

               <tns:Inventory_Item_Segment_18>
                  <xsl:value-of select="ns0:InventoryItemSegment18"/>
               </tns:Inventory_Item_Segment_18>

               <tns:Inventory_Item_Segment_19>
                  <xsl:value-of select="ns0:InventoryItemSegment19"/>
               </tns:Inventory_Item_Segment_19>

               <tns:Inventory_Item_Segment_20>
                  <xsl:value-of select="ns0:InventoryItemSegment20"/>
               </tns:Inventory_Item_Segment_20>

               <tns:Bill_To_Customer_Bank_Account_Name>
                  <xsl:value-of select="ns0:BillToCustomerBankAccountName"/>
               </tns:Bill_To_Customer_Bank_Account_Name>

               <tns:Reset_Transaction_Date_Flag>
                  <xsl:value-of select="ns0:ResetTransactionDateFlag"/>
               </tns:Reset_Transaction_Date_Flag>

               <tns:Payment_Server_Order_Number>
                  <xsl:value-of select="ns0:PaymentServerOrderNumber"/>
               </tns:Payment_Server_Order_Number>

               <tns:Last_Transaction_on_Debit_Authorization>
                  <xsl:value-of select="ns0:LastTransactionOnDebitAuthorization"/>
               </tns:Last_Transaction_on_Debit_Authorization>

               <tns:Approval_Code>
                  <xsl:value-of select="ns0:ApprovalCode"/>
               </tns:Approval_Code>

               <tns:Address_Verification_Code>
                  <xsl:value-of select="ns0:AddressVerificationCode"/>
               </tns:Address_Verification_Code>

               <tns:Transaction_Line_Translated_Description>
                  <xsl:value-of select="ns0:TransactionLineTranslatedDescription"/>
               </tns:Transaction_Line_Translated_Description>

               <tns:Consolidated_Billing_Number>
                  <xsl:value-of select="ns0:ConsolidatedBillingNumber"/>
               </tns:Consolidated_Billing_Number>

               <tns:Promised_Commitment_Amount>
                  <xsl:value-of select="ns0:PromisedCommitmentAmount"/>
               </tns:Promised_Commitment_Amount>

               <tns:Payment_Set_Identifier>
                  <xsl:value-of select="ns0:PaymentSetIdentifier"/>
               </tns:Payment_Set_Identifier>

               <tns:Original_Accounting_Date>
                  <xsl:value-of select="ns0:OriginalAccountingDate"/>
               </tns:Original_Accounting_Date>

               <tns:Invoiced_Line_Accounting_Level>
                  <xsl:value-of select="ns0:InvoicedLineAccountingLivel"/>
               </tns:Invoiced_Line_Accounting_Level>

               <tns:Override_AutoAccounting_Flag>
                  <xsl:value-of select="ns0:OverrideAutoAccountingFlag"/>
               </tns:Override_AutoAccounting_Flag>

               <tns:Historical_Flag>
                  <xsl:value-of select="ns0:HistoricalFlag"/>
               </tns:Historical_Flag>

               <tns:Deferral_Exclusion_Flag>
                  <xsl:value-of select="ns0:DeferralExclusionFlag"/>
               </tns:Deferral_Exclusion_Flag>

               <tns:Payment_Attributes>
                  <xsl:value-of select="ns0:PaymentAttributes"/>
               </tns:Payment_Attributes>

               <tns:Invoice_Billing_Date>
                  <xsl:value-of select="ns0:InvoiceBillingDate"/>
               </tns:Invoice_Billing_Date>

               <tns:Invoice_Lines_Flexfield_Context>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldContext"/>
               </tns:Invoice_Lines_Flexfield_Context>

               <tns:Invoice_Lines_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment1"/>
               </tns:Invoice_Lines_Flexfield_Segment_1>

               <tns:Invoice_Lines_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment2"/>
               </tns:Invoice_Lines_Flexfield_Segment_2>

               <tns:Invoice_Lines_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment3"/>
               </tns:Invoice_Lines_Flexfield_Segment_3>

               <tns:Invoice_Lines_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment4"/>
               </tns:Invoice_Lines_Flexfield_Segment_4>

               <tns:Invoice_Lines_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment5"/>
               </tns:Invoice_Lines_Flexfield_Segment_5>

               <tns:Invoice_Lines_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment6"/>
               </tns:Invoice_Lines_Flexfield_Segment_6>

               <tns:Invoice_Lines_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment7"/>
               </tns:Invoice_Lines_Flexfield_Segment_7>

               <tns:Invoice_Lines_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment8"/>
               </tns:Invoice_Lines_Flexfield_Segment_8>

               <tns:Invoice_Lines_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment9"/>
               </tns:Invoice_Lines_Flexfield_Segment_9>

               <tns:Invoice_Lines_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment10"/>
               </tns:Invoice_Lines_Flexfield_Segment_10>

               <tns:Invoice_Lines_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment11"/>
               </tns:Invoice_Lines_Flexfield_Segment_11>

               <tns:Invoice_Lines_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment12"/>
               </tns:Invoice_Lines_Flexfield_Segment_12>

               <tns:Invoice_Lines_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment13"/>
               </tns:Invoice_Lines_Flexfield_Segment_13>

               <tns:Invoice_Lines_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment14"/>
               </tns:Invoice_Lines_Flexfield_Segment_14>

               <tns:Invoice_Lines_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:InvoiceLinesFlexfieldSegment15"/>
               </tns:Invoice_Lines_Flexfield_Segment_15>

               <tns:Invoice_Transactions_Flexfield_Context>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldContext"/>
               </tns:Invoice_Transactions_Flexfield_Context>

               <tns:Invoice_Transactions_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment1"/>
               </tns:Invoice_Transactions_Flexfield_Segment_1>

               <tns:Invoice_Transactions_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment2"/>
               </tns:Invoice_Transactions_Flexfield_Segment_2>

               <tns:Invoice_Transactions_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment3"/>
               </tns:Invoice_Transactions_Flexfield_Segment_3>

               <tns:Invoice_Transactions_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment4"/>
               </tns:Invoice_Transactions_Flexfield_Segment_4>

               <tns:Invoice_Transactions_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment5"/>
               </tns:Invoice_Transactions_Flexfield_Segment_5>

               <tns:Invoice_Transactions_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment6"/>
               </tns:Invoice_Transactions_Flexfield_Segment_6>
			   
               <tns:Invoice_Transactions_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment7"/>
               </tns:Invoice_Transactions_Flexfield_Segment_7>

               <tns:Invoice_Transactions_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment8"/>
               </tns:Invoice_Transactions_Flexfield_Segment_8>
                  
               <tns:Invoice_Transactions_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment9"/>
               </tns:Invoice_Transactions_Flexfield_Segment_9>

               <tns:Invoice_Transactions_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment10"/>
               </tns:Invoice_Transactions_Flexfield_Segment_10>

               <tns:Invoice_Transactions_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment11"/>
               </tns:Invoice_Transactions_Flexfield_Segment_11>

               <tns:Invoice_Transactions_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment12"/>
               </tns:Invoice_Transactions_Flexfield_Segment_12>

               <tns:Invoice_Transactions_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment13"/>
               </tns:Invoice_Transactions_Flexfield_Segment_13>

               <tns:Invoice_Transactions_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment14"/>
               </tns:Invoice_Transactions_Flexfield_Segment_14>

               <tns:Invoice_Transactions_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:InvoiceTransactionsFlexfieldSegment15"/>
               </tns:Invoice_Transactions_Flexfield_Segment_15>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Context>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldContext"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Context>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment1"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_1>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment2"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_2>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment3"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_3>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment4"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_4>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment5"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_5>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment6"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_6>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment7"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_7>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment8"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_8>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment9"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_9>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment10"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_10>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment11"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_11>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment12"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_12>

               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment13"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_13>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment14"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_14>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment15"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_15>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_16>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment16"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_16>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_17>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment17"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_17>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_18>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment18"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_18>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_19>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment19"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_19>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_20>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment20"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_20>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_21>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment21"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_21>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_22>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment22"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_22>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_23>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment23"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_23>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_24>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment24"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_24>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_25>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment25"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_25>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_26>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment26"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_26>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_27>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment27"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_27>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_28>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment28"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_28>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_29>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment29"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_29>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_30>
                  <xsl:value-of select="ns0:ReceivablesTransactionRegionInformationFlexfieldSegment30"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_30>
               <tns:Line_Global_Descriptive_Flexfield_Attribute_Category>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldAttributeCategory"/>
               </tns:Line_Global_Descriptive_Flexfield_Attribute_Category>
               <tns:Line_Global_Descriptive_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment1"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_1>
               <tns:Line_Global_Descriptive_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment2"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_2>
               <tns:Line_Global_Descriptive_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment3"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_3>
               <tns:Line_Global_Descriptive_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment4"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_4>
               <tns:Line_Global_Descriptive_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment5"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_5>
               <tns:Line_Global_Descriptive_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment6"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_6>
               <tns:Line_Global_Descriptive_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment7"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_7>
               <tns:Line_Global_Descriptive_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment8"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_8>
               <tns:Line_Global_Descriptive_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment9"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_9>
               <tns:Line_Global_Descriptive_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment10"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_10>
               <tns:Line_Global_Descriptive_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment11"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_11>
               <tns:Line_Global_Descriptive_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment12"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_12>
               <tns:Line_Global_Descriptive_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment13"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_13>
               <tns:Line_Global_Descriptive_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment14"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_14>
               <tns:Line_Global_Descriptive_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment15"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_15>
               <tns:Line_Global_Descriptive_Flexfield_Segment_16>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment16"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_16>
               <tns:Line_Global_Descriptive_Flexfield_Segment_17>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment17"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_17>
               <tns:Line_Global_Descriptive_Flexfield_Segment_18>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment18"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_18>
               <tns:Line_Global_Descriptive_Flexfield_Segment_19>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment19"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_19>
               <tns:Line_Global_Descriptive_Flexfield_Segment_20>
                  <xsl:value-of select="ns0:LineGlobalDescriptiveFlexfieldSegment20"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_20>
               <tns:Business_Unit_Name>
                  <xsl:value-of select="ns0:BusinessUnitName"/>
               </tns:Business_Unit_Name>
               <tns:Comments>
                  <xsl:value-of select="ns0:Comments"/>
               </tns:Comments>
               <tns:Enforce_Chronological_Document_Sequencing>
                  <xsl:value-of select="ns0:EnforceChronologicalDocSequencing"/>
               </tns:Enforce_Chronological_Document_Sequencing>
               <tns:Aux>
                  <xsl:value-of select="ns0:EnforceChronologicalDocSequencing"/>
               </tns:Aux>
               <tns:C291>
                  <xsl:value-of select='"END"'/>
               </tns:C291>
            </tns:InvoicesList>
         </xsl:for-each>
      </tns:invoicesToCsv>
   </xsl:template>
</xsl:stylesheet>
