<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://soa.estrellaroja.com.mx/XMLValidatorBiz" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://soa.estrellaroja.com.mx/Tables/XXER_CONF_VALIDADOR_XML_TBL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/ftp/GER_SOA_OCI/XMLValidatorEnt/ftpValidadorZAM"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
                xmlns:ns3="http://soa.estrellaroja.com.mx/CartaPorte"
                xmlns:ns4="http://soa.estrellaroja.com.mx/XMLValidatorBiz/types"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ftpValidadorZAM.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XXER_CONF_VALIDADOR_XML_TBL" namespace="http://soa.estrellaroja.com.mx/Tables/XXER_CONF_VALIDADOR_XML_TBL"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/XMLValidatorBiz/XMLValidatorBiz.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ValidaCartaPorteRq" namespace="http://soa.estrellaroja.com.mx/XMLValidatorBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE APR 18 20:43:23 CDT 2023].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ValidaCartaPorteRq>
         <tns:Configuraciones>
            <xsl:for-each select="/ns0:XXER_CONF_VALIDADOR_XML_TBL/ns0:ROW">
               <tns:ROW>
                  <xsl:if test="ns0:ID">
                     <ns0:ID>
                        <xsl:if test="ns0:ID/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:ID/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:ID"/>
                     </ns0:ID>
                  </xsl:if>
                  <xsl:if test="ns0:INTEGRACION">
                     <ns0:INTEGRACION>
                        <xsl:if test="ns0:INTEGRACION/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:INTEGRACION/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:INTEGRACION"/>
                     </ns0:INTEGRACION>
                  </xsl:if>
                  <xsl:if test="ns0:CODE">
                     <ns0:CODE>
                        <xsl:if test="ns0:CODE/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:CODE/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:CODE"/>
                     </ns0:CODE>
                  </xsl:if>
                  <xsl:if test="ns0:PROCCESS">
                     <ns0:PROCCESS>
                        <xsl:if test="ns0:PROCCESS/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:PROCCESS/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:PROCCESS"/>
                     </ns0:PROCCESS>
                  </xsl:if>
                  <xsl:if test="ns0:ACTION">
                     <ns0:ACTION>
                        <xsl:if test="ns0:ACTION/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:ACTION/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:ACTION"/>
                     </ns0:ACTION>
                  </xsl:if>
                  <xsl:if test="ns0:ORDER">
                     <ns0:ORDER>
                        <xsl:if test="ns0:ORDER/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:ORDER/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:ORDER"/>
                     </ns0:ORDER>
                  </xsl:if>
                  <xsl:if test="ns0:NAME">
                     <ns0:NAME>
                        <xsl:if test="ns0:NAME/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:NAME/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:NAME"/>
                     </ns0:NAME>
                  </xsl:if>
                  <xsl:if test="ns0:TYPE">
                     <ns0:TYPE>
                        <xsl:if test="ns0:TYPE/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:TYPE/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:TYPE"/>
                     </ns0:TYPE>
                  </xsl:if>
                  <xsl:if test="ns0:VERSION">
                     <ns0:VERSION>
                        <xsl:if test="ns0:VERSION/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:VERSION/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:VERSION"/>
                     </ns0:VERSION>
                  </xsl:if>
                  <xsl:if test="ns0:MESSAGE">
                     <ns0:MESSAGE>
                        <xsl:if test="ns0:MESSAGE/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:MESSAGE/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:MESSAGE"/>
                     </ns0:MESSAGE>
                  </xsl:if>
                  <xsl:if test="ns0:DESC">
                     <ns0:DESC>
                        <xsl:if test="ns0:DESC/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:DESC/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:DESC"/>
                     </ns0:DESC>
                  </xsl:if>
                  <xsl:if test="ns0:PARAMETER1">
                     <ns0:PARAMETER1>
                        <xsl:if test="ns0:PARAMETER1/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:PARAMETER1/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:PARAMETER1"/>
                     </ns0:PARAMETER1>
                  </xsl:if>
                  <xsl:if test="ns0:PARAMETER2">
                     <ns0:PARAMETER2>
                        <xsl:if test="ns0:PARAMETER2/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:PARAMETER2/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:PARAMETER2"/>
                     </ns0:PARAMETER2>
                  </xsl:if>
                  <xsl:if test="ns0:PARAMETER3">
                     <ns0:PARAMETER3>
                        <xsl:if test="ns0:PARAMETER3/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:PARAMETER3/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:PARAMETER3"/>
                     </ns0:PARAMETER3>
                  </xsl:if>
                  <xsl:if test="ns0:PARAMETER4">
                     <ns0:PARAMETER4>
                        <xsl:if test="ns0:PARAMETER4/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:PARAMETER4/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:PARAMETER4"/>
                     </ns0:PARAMETER4>
                  </xsl:if>
                  <xsl:if test="ns0:PARAMETER5">
                     <ns0:PARAMETER5>
                        <xsl:if test="ns0:PARAMETER5/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:PARAMETER5/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:PARAMETER5"/>
                     </ns0:PARAMETER5>
                  </xsl:if>
                  <xsl:if test="ns0:CREATION_DATE">
                     <ns0:CREATION_DATE>
                        <xsl:if test="ns0:CREATION_DATE/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:CREATION_DATE/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:CREATION_DATE"/>
                     </ns0:CREATION_DATE>
                  </xsl:if>
                  <xsl:if test="ns0:CREATED_BY">
                     <ns0:CREATED_BY>
                        <xsl:if test="ns0:CREATED_BY/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:CREATED_BY/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:CREATED_BY"/>
                     </ns0:CREATED_BY>
                  </xsl:if>
                  <xsl:if test="ns0:LAST_UPDATE_DATE">
                     <ns0:LAST_UPDATE_DATE>
                        <xsl:if test="ns0:LAST_UPDATE_DATE/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:LAST_UPDATE_DATE/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:LAST_UPDATE_DATE"/>
                     </ns0:LAST_UPDATE_DATE>
                  </xsl:if>
                  <xsl:if test="ns0:LAST_UPDATED_BY">
                     <ns0:LAST_UPDATED_BY>
                        <xsl:if test="ns0:LAST_UPDATED_BY/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:LAST_UPDATED_BY/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:LAST_UPDATED_BY"/>
                     </ns0:LAST_UPDATED_BY>
                  </xsl:if>
               </tns:ROW>
            </xsl:for-each>
         </tns:Configuraciones>
      </tns:ValidaCartaPorteRq>
   </xsl:template>
</xsl:stylesheet>
