<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://conciliationspringbiz.soa.estrellaroja.com.mx/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/ConciliationBiz" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ConciliationSpringBiz/Types">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BpelConciliationCashTp.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ConciliationCashTPRq" namespace="http://soa.estrellaroja.com.mx/ConciliationBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/External/IConciliationSpringBiz.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetPaymentsCashPage" namespace="http://conciliationspringbiz.soa.estrellaroja.com.mx/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON JUN 21 11:10:26 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetPaymentsCashPage>
         <arg0>
            <xsl:for-each select="/ns0:ConciliationCashTPRq/ns0:Conciliate">
               <ns2:Payments>
                  <ns2:ReceiptMethod>
                     <xsl:value-of select="ns0:ReceiptMethod"/>
                  </ns2:ReceiptMethod>
                  <ns2:PaymentReference>
                     <xsl:value-of select="ns0:PaymentReference"/>
                  </ns2:PaymentReference>
                  <ns2:PaymentDate>
                     <xsl:value-of select="ns0:PaymentDate"/>
                  </ns2:PaymentDate>
               </ns2:Payments>
            </xsl:for-each>
         </arg0>
      </tns:GetPaymentsCashPage>
   </xsl:template>
</xsl:stylesheet>
