<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/ConciliationBiz" xmlns:tns="http://soa.estrellaroja.com.mx/ConciliationTec" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://soa.estrellaroja.com.mx/ConciliationBiz/BpelGetCreditMemo"
                xmlns:ns2="http://soa.estrellaroja.com.mx/Reports/XXER_AR_NOTA_CREDITO"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BpelGetCreditMemo.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetCreditMemoRs" namespace="http://soa.estrellaroja.com.mx/ConciliationBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BpelGetCreditMemo.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ConciliationTransactionsRq" namespace="http://soa.estrellaroja.com.mx/ConciliationTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SAT JUN 19 14:02:02 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ConciliationTransactionsRq>
         <xsl:for-each select="/ns0:GetCreditMemoRs/ns0:CreditMemosResults">
            <xsl:variable name="v_receiptMethod" select="ns0:ReceiptMethod"/>
   <xsl:variable name="v_paymentReference" select="ns0:PaymentReference"/>

            <xsl:for-each select="ns0:CreditMemoResult">
               <tns:ConciliationTransaction>
                  <tns:REFERENCE_PAYMENT>
                     <xsl:value-of select="$v_paymentReference"/>
                  </tns:REFERENCE_PAYMENT>
                  <tns:RECEIPT_METHOD>
                     <xsl:value-of select="$v_receiptMethod"/>
                  </tns:RECEIPT_METHOD>
                  <tns:REFERENCE_TRANSACTIONS_ID>
                     <xsl:value-of select="ns0:CustomerTrxId"/>
                  </tns:REFERENCE_TRANSACTIONS_ID>
                  <tns:REFERENCE_TRANSACTIONS>
                     <xsl:value-of select="ns0:NUMERO_DOCUMENTO"/>
                  </tns:REFERENCE_TRANSACTIONS>
                  <tns:TOTAL>
                     <xsl:value-of select="ns0:CreditMemoTotal"/>
                  </tns:TOTAL>
               </tns:ConciliationTransaction>
            </xsl:for-each>
         </xsl:for-each>
      </tns:ConciliationTransactionsRq>
   </xsl:template>
</xsl:stylesheet>
