<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/ConciliationBiz" xmlns:tns="http://soa.estrellaroja.com.mx/ConciliationTec" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://soa.estrellaroja.com.mx/ConciliationBiz/BpelGetPaymentsCash"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BpelGetPaymentsCash.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetPaymentsCashRs" namespace="http://soa.estrellaroja.com.mx/ConciliationBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BpelGetPaymentsCash.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ConciliationCashRq" namespace="http://soa.estrellaroja.com.mx/ConciliationTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SAT JUN 19 09:36:35 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ConciliationCashRq>
         <xsl:for-each select="/ns0:GetPaymentsCashRs/ns0:PaymentsResults">
            <tns:ConciliationCash>
               <tns:REFERENCE_PAYMENT>
                  <xsl:value-of select="ns0:PaymentReference"/>
               </tns:REFERENCE_PAYMENT>
               <tns:PAYMENT_NUMBER>
                  <xsl:value-of select="ns0:PaymentNumber"/>
               </tns:PAYMENT_NUMBER>
               <tns:RECEIPT_METHOD>
                  <xsl:value-of select="ns0:ReceiptMethod"/>
               </tns:RECEIPT_METHOD>
               <tns:TOTAL>
                  <xsl:value-of select="sum (ns0:PaymentResult/ns0:Total )"/>
               </tns:TOTAL>
               <tns:PAYMENT_DATE>
                  <xsl:value-of select="substring (ns0:PaymentResult/ns0:PaymentDate, 1,10 )"/>
               </tns:PAYMENT_DATE>
            </tns:ConciliationCash>
         </xsl:for-each>
      </tns:ConciliationCashRq>
   </xsl:template>
</xsl:stylesheet>
