<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://soa.estrellaroja.com.mx/AuditControlTec"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:WL5G3N1="http://soa.estrellaroja.com.mx/AuditControlTec"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="wsAuditControlTec">
        <plnk:role name="AuditControlTecPortType" portType="WL5G3N1:AuditControlTecPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soa.estrellaroja.com.mx/AuditControlTec" location="oramds:/apps/OSB/AuditControlTec/AuditControlTec.wsdl"/>
</wsdl:definitions>
