<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="bpelManagementsStatementsBankBanamex" targetNamespace="http://xmlns.oracle.com/SFTPEstrellaRojaEnt/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankBanamex" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/SFTPEstrellaRojaEnt/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankBanamex" xmlns:ns1="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StatementsBankBanamex" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationBiz" xmlns:ns3="http://soa.estrellaroja.com.mx/StructureCodeBank" xmlns:ns4="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails" xmlns:ns5="http://soa.estrellaroja.com.mx/MessageBiz" xmlns:ns6="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns7="http://soa.estrellaroja.com.mx/ERPManagementOfLoadImportBiz">
   <plnk:partnerLinkType name="bpelManagementsStatementsBankBanamex">
      <plnk:role name="bpelManagementsStatementsBankBanamexProvider" portType="client:bpelManagementsStatementsBankBanamex"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/ERPIntegrationBiz" location="oramds:/apps/SOA/ERPIntegrationBiz/ERPIntegrationBiz.wsdl"/>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/MessageBiz" location="oramds:/apps/SOA/MessageBiz/MessageBiz.wsdl"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/SFTPEstrellaRojaEnt/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankBanamex" xmlns:ns1="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationBiz" xmlns:ns3="http://soa.estrellaroja.com.mx/StructureCodeBank" xmlns:ns4="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails" xmlns:ns5="http://soa.estrellaroja.com.mx/MessageBiz" xmlns:ns6="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
         <import namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StatementsBankBanamex" schemaLocation="../Schemas/Banks/StatementsBankBanamex.xsd"/>
      </schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/SFTPEstrellaRojaEnt/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankBanamex" xmlns:ns1="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationBiz" xmlns:ns3="http://soa.estrellaroja.com.mx/StructureCodeBank" xmlns:ns4="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails" xmlns:ns5="http://soa.estrellaroja.com.mx/MessageBiz" xmlns:ns6="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
         <xsd:import namespace="http://soa.estrellaroja.com.mx/StructureCodeBank" schemaLocation="../Schemas/StructureBankCode.xsd"/>
      </xsd:schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/SFTPEstrellaRojaEnt/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankBanamex" xmlns:ns1="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationBiz" xmlns:ns3="http://soa.estrellaroja.com.mx/StructureCodeBank" xmlns:ns4="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails" xmlns:ns5="http://soa.estrellaroja.com.mx/MessageBiz" xmlns:ns6="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
         <xsd:import namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails" schemaLocation="../Schemas/StructureBankDetails.xsd"/>
      </xsd:schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/SFTPEstrellaRojaEnt/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankBanamex" xmlns:ns1="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationBiz" xmlns:ns3="http://soa.estrellaroja.com.mx/StructureCodeBank" xmlns:ns4="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails" xmlns:ns5="http://soa.estrellaroja.com.mx/MessageBiz" xmlns:ns6="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
         <xsd:import namespace="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" schemaLocation="oramds:/apps/Common/XSD/EstrellaRojaCommons.xsd"/>
      </xsd:schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://soa.estrellaroja.com.mx/ERPManagementOfLoadImportBiz" schemaLocation="oramds:/apps/SOA/ERPManagementOfLoadImportBiz/ERPManagementOfLoadImportBiz.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="bpelManagementsStatementsBankBanamexRequestMessage">
      <wsdl:part name="payload" element="ns1:StatementsBankBanamex"/>
   </wsdl:message>
   <wsdl:portType name="bpelManagementsStatementsBankBanamex">
      <wsdl:operation name="ManagementsStatementsBankBanamex">
         <wsdl:input message="client:bpelManagementsStatementsBankBanamexRequestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
