<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ERPManagementOfLoadImportBiz" targetNamespace="http://soa.estrellaroja.com.mx/ERPManagementOfLoadImportBiz" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://soa.estrellaroja.com.mx/ERPManagementOfLoadImportBiz" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="wsERPManagementOfLoadImportBiz">
      <plnk:role name="ERPManagementOfLoadImportBizPortType" portType="tns:ERPManagementOfLoadImportBizPortType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/ERPManagementOfLoadImportBiz" location="oramds:/apps/SOA/ERPManagementOfLoadImportBiz/ERPManagementOfLoadImportBiz.wsdl"/>
</wsdl:definitions>
