<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="MessageBiz" targetNamespace="http://soa.estrellaroja.com.mx/MessageBiz" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://soa.estrellaroja.com.mx/MessageBiz" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="wsMessageBiz">
      <plnk:role name="MessageBizCallbackPortType" portType="tns:MessageBizCallbackPortType"/>
      <plnk:role name="MessageBizPortType" portType="tns:MessageBizPortType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/MessageBiz" location="oramds:/apps/SOA/MessageBiz/MessageBiz.wsdl"/>
</wsdl:definitions>
