<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://soa.estrellaroja.com.mx/ConciliationBiz"
                xmlns:ns0="http://soa.estrellaroja.com.mx/ConciliationTec"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/OSB/DEV_ConciliationTec/ConciliationTec.xsd"/>
        <oracle-xsl-mapper:rootElement name="GetConciliationsRs"
                                       namespace="http://soa.estrellaroja.com.mx/ConciliationTec"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/SOA/DEV_ConciliationBiz/ConciliationBiz.xsd"/>
        <oracle-xsl-mapper:rootElement name="ConciliationCashTPRq"
                                       namespace="http://soa.estrellaroja.com.mx/ConciliationBiz"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SAT JUN 19 02:48:45 CDT 2021].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ConciliationCashTPRq>
      <xsl:for-each select="/ns0:GetConciliationsRs/ns0:XXER_AR_GET_CASH_CONC">
        <tns:Conciliate>
          <tns:ReceiptMethod>
            <xsl:value-of select="ns0:RECEIPT_METHOD"/>
          </tns:ReceiptMethod>
          <tns:PaymentReference>
            <xsl:value-of select="ns0:REFERENCE_PAYMENT"/>
          </tns:PaymentReference>
          <tns:PaymentDate>
            <xsl:value-of select="ns0:PAYMENT_DATE"/>
          </tns:PaymentDate>
        </tns:Conciliate>
      </xsl:for-each>
    </tns:ConciliationCashTPRq>
  </xsl:template>
</xsl:stylesheet>
