<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="http://soa.estrellaroja.com.mx/ConciliationTec" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/ConciliationEnt/NXSDBankAmexPayments" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:ns1="http://soa.estrellaroja.com.mx/ConciliationTec/types"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/nxsd_paymentsAmex.xsd"/>
            <oracle-xsl-mapper:rootElement name="PaymentsAmex" namespace="http://soa.estrellaroja.com.mx/ConciliationEnt/NXSDBankAmexPayments"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/External/ConciliationTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="SendConciliationBankAMEXRq" namespace="http://soa.estrellaroja.com.mx/ConciliationTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [FRI AUG 27 19:10:15 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:SendConciliationBankAMEXRq>
         <xsl:for-each select="/ns0:PaymentsAmex/ns0:ADJUSTMENT">
            <tns:ADJUSTMENT>
               <tns:NUM_ESTABLECIMIENTO>
                  <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO"/>
               </tns:NUM_ESTABLECIMIENTO>
               <tns:CODIGO_TIPO_CUENTA>
                  <xsl:value-of select="ns0:CODIGO_TIPO_CUENTA"/>
               </tns:CODIGO_TIPO_CUENTA>
               <tns:NUM_PAGO_AMEX>
                  <xsl:value-of select="ns0:NUM_PAGO_AMEX"/>
               </tns:NUM_PAGO_AMEX>
               <tns:FECHA_PAGO>
                  <xsl:value-of select="ns0:FECHA_PAGO"/>
               </tns:FECHA_PAGO>
               <tns:MONEDA_PAGO>
                  <xsl:value-of select="ns0:MONEDA_PAGO"/>
               </tns:MONEDA_PAGO>
               <tns:NUM_ESTABLECIMIENTO_PRESENTACION>
                  <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO_PRESENTACION"/>
               </tns:NUM_ESTABLECIMIENTO_PRESENTACION>
               <tns:FECHA_ENVIO>
                  <xsl:value-of select="ns0:FECHA_ENVIO"/>
               </tns:FECHA_ENVIO>
               <tns:UBICACION_ESTABLECIMIENTO>
                  <xsl:value-of select="ns0:UBICACION_ESTABLECIMIENTO"/>
               </tns:UBICACION_ESTABLECIMIENTO>
               <tns:NUM_FACTURA_REFERENCIA>
                  <xsl:value-of select="ns0:NUM_FACTURA_REFERENCIA"/>
               </tns:NUM_FACTURA_REFERENCIA>
               <tns:IDENTIFICACION_VENDEDOR>
                  <xsl:value-of select="ns0:IDENTIFICACION_VENDEDOR"/>
               </tns:IDENTIFICACION_VENDEDOR>
               <tns:NUM_TARJETA>
                  <xsl:value-of select="ns0:NUM_TARJETA"/>
               </tns:NUM_TARJETA>
               <tns:NUM_REFERENCIA_INDUSTRIA>
                  <xsl:value-of select="ns0:NUM_REFERENCIA_INDUSTRIA"/>
               </tns:NUM_REFERENCIA_INDUSTRIA>
               <tns:FECHA_PROCESAMIENTO_AMEX>
                  <xsl:value-of select="ns0:FECHA_PROCESAMIENTO_AMEX"/>
               </tns:FECHA_PROCESAMIENTO_AMEX>
               <tns:NUM_FACTURA>
                  <xsl:value-of select="ns0:NUM_FACTURA"/>
               </tns:NUM_FACTURA>
               <tns:MONEDA_PRESENTACION>
                  <xsl:value-of select="ns0:MONEDA_PRESENTACION"/>
               </tns:MONEDA_PRESENTACION>
               <tns:NUM_AJUSTE>
                  <xsl:value-of select="ns0:NUM_AJUSTE"/>
               </tns:NUM_AJUSTE>
               <tns:CODIGO_MOTIVO_AJUSTE>
                  <xsl:value-of select="ns0:CODIGO_MOTIVO_AJUSTE"/>
               </tns:CODIGO_MOTIVO_AJUSTE>
               <tns:DESCRIPCION_MOTIVO_AJUSTE>
                  <xsl:value-of select="ns0:DESCRIPCION_MOTIVO_AJUSTE"/>
               </tns:DESCRIPCION_MOTIVO_AJUSTE>
               <tns:MONTO_BRUTO>
                  <xsl:value-of select="ns0:MONTO_BRUTO"/>
               </tns:MONTO_BRUTO>
               <tns:MONTO_DESCUENTO>
                  <xsl:value-of select="ns0:MONTO_DESCUENTO"/>
               </tns:MONTO_DESCUENTO>
               <tns:MONTO_CARGO_SERVICIO>
                  <xsl:value-of select="ns0:MONTO_CARGO_SERVICIO"/>
               </tns:MONTO_CARGO_SERVICIO>
               <tns:MONTO_IMPUESTO>
                  <xsl:value-of select="ns0:MONTO_IMPUESTO"/>
               </tns:MONTO_IMPUESTO>
               <tns:MONTO_NETO>
                  <xsl:value-of select="ns0:MONTO_NETO"/>
               </tns:MONTO_NETO>
               <tns:TASA_DESCUENTO>
                  <xsl:value-of select="ns0:TASA_DESCUENTO"/>
               </tns:TASA_DESCUENTO>
               <tns:TASA_CARGO_SERVICIO>
                  <xsl:value-of select="ns0:TASA_CARGO_SERVICIO"/>
               </tns:TASA_CARGO_SERVICIO>
               <tns:CODIGO_LOTE>
                  <xsl:value-of select="ns0:CODIGO_LOTE"/>
               </tns:CODIGO_LOTE>
               <tns:CODIGO_FACTURA>
                  <xsl:value-of select="ns0:CODIGO_FACTURA"/>
               </tns:CODIGO_FACTURA>
            </tns:ADJUSTMENT>
         </xsl:for-each>
         <xsl:for-each select="/ns0:PaymentsAmex/ns0:HEADER">
            <tns:HEADER>
               <tns:FECHA_CREACION_ARCHIVO>
                  <xsl:value-of select="ns0:FECHA_CREACION_ARCHIVO"/>
               </tns:FECHA_CREACION_ARCHIVO>
               <tns:HORA_CREACION_ARCHIVO>
                  <xsl:value-of select="ns0:HORA_CREACION_ARCHIVO"/>
               </tns:HORA_CREACION_ARCHIVO>
               <tns:NUM_SECUENCIAL>
                  <xsl:value-of select="ns0:NUM_SECUENCIAL"/>
               </tns:NUM_SECUENCIAL>
               <tns:IDENTIDIACION_ARCHIVO>
                  <xsl:value-of select="ns0:IDENTIDIACION_ARCHIVO"/>
               </tns:IDENTIDIACION_ARCHIVO>
               <tns:NOMBRE_ARCHIVO>
                  <xsl:value-of select="ns0:NOMBRE_ARCHIVO"/>
               </tns:NOMBRE_ARCHIVO>
               <tns:NUM_VERSION_ARCHIVO>
                  <xsl:value-of select="ns0:NUM_VERSION_ARCHIVO"/>
               </tns:NUM_VERSION_ARCHIVO>
            </tns:HEADER>
         </xsl:for-each>
         <xsl:for-each select="/ns0:PaymentsAmex/ns0:CHARGEBACK">
            <tns:CHARGEBACK>
               <tns:NUM_ESTABLECIMIENTO>
                  <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO"/>
               </tns:NUM_ESTABLECIMIENTO>
               <tns:CODIGO_TIPO_CUENTA_>
                  <xsl:value-of select="ns0:CODIGO_TIPO_CUENTA_"/>
               </tns:CODIGO_TIPO_CUENTA_>
               <tns:NUM_PAGO_AMERICAN_EXPRESS>
                  <xsl:value-of select="ns0:NUM_PAGO_AMERICAN_EXPRESS"/>
               </tns:NUM_PAGO_AMERICAN_EXPRESS>
               <tns:FECHA_PAGO>
                  <xsl:value-of select="ns0:FECHA_PAGO"/>
               </tns:FECHA_PAGO>
               <tns:MONEDA_PAGO>
                  <xsl:value-of select="ns0:MONEDA_PAGO"/>
               </tns:MONEDA_PAGO>
               <tns:NUM_ESTABLECIMIENTO_PRESENTACION>
                  <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO_PRESENTACION"/>
               </tns:NUM_ESTABLECIMIENTO_PRESENTACION>
               <tns:FECHA_PRESENTACION>
                  <xsl:value-of select="ns0:FECHA_PRESENTACION"/>
               </tns:FECHA_PRESENTACION>
               <tns:UBICACION_ESTABLECIMIENTO>
                  <xsl:value-of select="ns0:UBICACION_ESTABLECIMIENTO"/>
               </tns:UBICACION_ESTABLECIMIENTO>
               <tns:NUM_FACTURA_O_REFERENCIA>
                  <xsl:value-of select="ns0:NUM_FACTURA_O_REFERENCIA"/>
               </tns:NUM_FACTURA_O_REFERENCIA>
               <tns:IDENTIFICACION_VENDEDOR>
                  <xsl:value-of select="ns0:IDENTIFICACION_VENDEDOR"/>
               </tns:IDENTIFICACION_VENDEDOR>
               <tns:NUM_TARJETA>
                  <xsl:value-of select="ns0:NUM_TARJETA"/>
               </tns:NUM_TARJETA>
               <tns:NUM_REFERENCIA_INDUSTRIA>
                  <xsl:value-of select="ns0:NUM_REFERENCIA_INDUSTRIA"/>
               </tns:NUM_REFERENCIA_INDUSTRIA>
               <tns:FECHA_PROCESAMIENTO_AMERICAN_EXPRESS>
                  <xsl:value-of select="ns0:FECHA_PROCESAMIENTO_AMERICAN_EXPRESS"/>
               </tns:FECHA_PROCESAMIENTO_AMERICAN_EXPRESS>
               <tns:NUM_FACTURA>
                  <xsl:value-of select="ns0:NUM_FACTURA"/>
               </tns:NUM_FACTURA>
               <tns:MONEDA_PRESENTACION>
                  <xsl:value-of select="ns0:MONEDA_PRESENTACION"/>
               </tns:MONEDA_PRESENTACION>
               <tns:NUM_CONTRACARGO>
                  <xsl:value-of select="ns0:NUM_CONTRACARGO"/>
               </tns:NUM_CONTRACARGO>
               <tns:CODIGO_MOTIVO_CONTRACARGO>
                  <xsl:value-of select="ns0:CODIGO_MOTIVO_CONTRACARGO"/>
               </tns:CODIGO_MOTIVO_CONTRACARGO>
               <tns:DESCRIPCION_MOTIVO_CONTRACARGO>
                  <xsl:value-of select="ns0:DESCRIPCION_MOTIVO_CONTRACARGO"/>
               </tns:DESCRIPCION_MOTIVO_CONTRACARGO>
               <tns:MONTO_BRUTO>
                  <xsl:value-of select="ns0:MONTO_BRUTO"/>
               </tns:MONTO_BRUTO>
               <tns:MONTO_DESCUENTO>
                  <xsl:value-of select="ns0:MONTO_DESCUENTO"/>
               </tns:MONTO_DESCUENTO>
               <tns:MONTO_CARGO_SERVICIO>
                  <xsl:value-of select="ns0:MONTO_CARGO_SERVICIO"/>
               </tns:MONTO_CARGO_SERVICIO>
               <tns:MONTO_IMPUESTO>
                  <xsl:value-of select="ns0:MONTO_IMPUESTO"/>
               </tns:MONTO_IMPUESTO>
               <tns:MONTO_NETO>
                  <xsl:value-of select="ns0:MONTO_NETO"/>
               </tns:MONTO_NETO>
               <tns:TASA_DESCUENTO>
                  <xsl:value-of select="ns0:TASA_DESCUENTO"/>
               </tns:TASA_DESCUENTO>
               <tns:TASA_CARGO_SERVICIO>
                  <xsl:value-of select="ns0:TASA_CARGO_SERVICIO"/>
               </tns:TASA_CARGO_SERVICIO>
               <tns:CODIGO_LOTE>
                  <xsl:value-of select="ns0:CODIGO_LOTE"/>
               </tns:CODIGO_LOTE>
               <tns:CODIGO_FACTURA>
                  <xsl:value-of select="ns0:CODIGO_FACTURA"/>
               </tns:CODIGO_FACTURA>
            </tns:CHARGEBACK>
         </xsl:for-each>
         <xsl:for-each select="/ns0:PaymentsAmex/ns0:SUBMISSION">
            <tns:SUBMISSION>
               <tns:NUM_ESTABLECIMIENTO>
                  <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO"/>
               </tns:NUM_ESTABLECIMIENTO>
               <tns:CODIGO_TIPO_CUENTA>
                  <xsl:value-of select="ns0:CODIGO_TIPO_CUENTA"/>
               </tns:CODIGO_TIPO_CUENTA>
               <tns:NUM_PAGO_AMEX>
                  <xsl:value-of select="ns0:NUM_PAGO_AMEX"/>
               </tns:NUM_PAGO_AMEX>
               <tns:FECHA_PAGO>
                  <xsl:value-of select="ns0:FECHA_PAGO"/>
               </tns:FECHA_PAGO>
               <tns:MONEDA_PAGO>
                  <xsl:value-of select="ns0:MONEDA_PAGO"/>
               </tns:MONEDA_PAGO>
               <tns:NUM_ESTABLECIMIENTO_PRESENTION>
                  <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO_PRESENTION"/>
               </tns:NUM_ESTABLECIMIENTO_PRESENTION>
               <tns:FECHA_ENVIO_COMERCIAL>
                  <xsl:value-of select="ns0:FECHA_ENVIO_COMERCIAL"/>
               </tns:FECHA_ENVIO_COMERCIAL>
               <tns:FECHA_PROCESAMIENTO_AMEX>
                  <xsl:value-of select="ns0:FECHA_PROCESAMIENTO_AMEX"/>
               </tns:FECHA_PROCESAMIENTO_AMEX>
               <tns:NUM_FACTURA>
                  <xsl:value-of select="ns0:NUM_FACTURA"/>
               </tns:NUM_FACTURA>
               <tns:MONEDA>
                  <xsl:value-of select="ns0:MONEDA"/>
               </tns:MONEDA>
               <tns:RELLENO>
                  <xsl:value-of select="ns0:RELLENO"/>
               </tns:RELLENO>
               <tns:TASA_CAMBIO>
                  <xsl:value-of select="ns0:TASA_CAMBIO"/>
               </tns:TASA_CAMBIO>
               <tns:MONTO_BRUTO_MONEDA_PRESENTACION>
                  <xsl:value-of select="ns0:MONTO_BRUTO_MONEDA_PRESENTACION"/>
               </tns:MONTO_BRUTO_MONEDA_PRESENTACION>
               <tns:MONTO_BRUTO_MONEDA_PAGO>
                  <xsl:value-of select="ns0:MONTO_BRUTO_MONEDA_PAGO"/>
               </tns:MONTO_BRUTO_MONEDA_PAGO>
               <tns:MONTO_DESCUENTO_RSENTCION>
                  <xsl:value-of select="ns0:MONTO_DESCUENTO_RSENTCION"/>
               </tns:MONTO_DESCUENTO_RSENTCION>
               <tns:MONTO_CARGO_SERVICIO>
                  <xsl:value-of select="ns0:MONTO_CARGO_SERVICIO"/>
               </tns:MONTO_CARGO_SERVICIO>
               <tns:MONTO_IMPUESTO>
                  <xsl:value-of select="ns0:MONTO_IMPUESTO"/>
               </tns:MONTO_IMPUESTO>
               <tns:MONTO_NETO>
                  <xsl:value-of select="ns0:MONTO_NETO"/>
               </tns:MONTO_NETO>
               <tns:TASA_DESCUENTO>
                  <xsl:value-of select="ns0:TASA_DESCUENTO"/>
               </tns:TASA_DESCUENTO>
               <tns:TASA_IMPUESTO>
                  <xsl:value-of select="ns0:TASA_IMPUESTO"/>
               </tns:TASA_IMPUESTO>
               <tns:SUMA_TRANSACCIONES>
                  <xsl:value-of select="ns0:SUMA_TRANSACCIONES"/>
               </tns:SUMA_TRANSACCIONES>
               <tns:IDENTIFICACION_SEGUIMIENTO>
                  <xsl:value-of select="ns0:IDENTIFICACION_SEGUIMIENTO"/>
               </tns:IDENTIFICACION_SEGUIMIENTO>
               <tns:NUM_CUOTA>
                  <xsl:value-of select="ns0:NUM_CUOTA"/>
               </tns:NUM_CUOTA>
               <tns:NUM_ACELERACION>
                  <xsl:value-of select="ns0:NUM_ACELERACION"/>
               </tns:NUM_ACELERACION>
               <tns:FECHA_LIQUIDACION_ORIGINAL>
                  <xsl:value-of select="ns0:FECHA_LIQUIDACION_ORIGINAL"/>
               </tns:FECHA_LIQUIDACION_ORIGINAL>
               <tns:FECHA_ACELERACION>
                  <xsl:value-of select="ns0:FECHA_ACELERACION"/>
               </tns:FECHA_ACELERACION>
               <tns:CANTIDAD_DIAS_ADELANTADOS>
                  <xsl:value-of select="ns0:CANTIDAD_DIAS_ADELANTADOS"/>
               </tns:CANTIDAD_DIAS_ADELANTADOS>
               <tns:MONTO_CARGO_ACELERACION>
                  <xsl:value-of select="ns0:MONTO_CARGO_ACELERACION"/>
               </tns:MONTO_CARGO_ACELERACION>
               <tns:MONTO_NETO_CARGO_ACELERACION>
                  <xsl:value-of select="ns0:MONTO_NETO_CARGO_ACELERACION"/>
               </tns:MONTO_NETO_CARGO_ACELERACION>
               <tns:MONTO_BRUTO_DEBITO>
                  <xsl:value-of select="ns0:MONTO_BRUTO_DEBITO"/>
               </tns:MONTO_BRUTO_DEBITO>
               <tns:MONTO_BRUTO_CREDITO>
                  <xsl:value-of select="ns0:MONTO_BRUTO_CREDITO"/>
               </tns:MONTO_BRUTO_CREDITO>
            </tns:SUBMISSION>
         </xsl:for-each>
         <xsl:for-each select="/ns0:PaymentsAmex/ns0:SUMMARY">
            <tns:SUMMARY>
               <tns:IDENTIFICACION_ESTABLECIMIENTO>
                  <xsl:value-of select="ns0:IDENTIFICACION_ESTABLECIMIENTO"/>
               </tns:IDENTIFICACION_ESTABLECIMIENTO>
               <tns:CODIGO_TIPO_CUENTA>
                  <xsl:value-of select="ns0:CODIGO_TIPO_CUENTA"/>
               </tns:CODIGO_TIPO_CUENTA>
               <tns:NUM_PAGO>
                  <xsl:value-of select="ns0:NUM_PAGO"/>
               </tns:NUM_PAGO>
               <tns:FECHA_PAGO>
                  <xsl:value-of select="ns0:FECHA_PAGO"/>
               </tns:FECHA_PAGO>
               <tns:MONEDA_PAGO>
                  <xsl:value-of select="ns0:MONEDA_PAGO"/>
               </tns:MONEDA_PAGO>
               <tns:NUM_UNICO_REFERENCIA_PAGO>
                  <xsl:value-of select="ns0:NUM_UNICO_REFERENCIA_PAGO"/>
               </tns:NUM_UNICO_REFERENCIA_PAGO>
               <tns:MONTO_NETO_PAGO>
                  <xsl:value-of select="ns0:MONTO_NETO_PAGO"/>
               </tns:MONTO_NETO_PAGO>
               <tns:MONTO_BRUTO_PAGO>
                  <xsl:value-of select="ns0:MONTO_BRUTO_PAGO"/>
               </tns:MONTO_BRUTO_PAGO>
               <tns:MONTO_DESCUENTO>
                  <xsl:value-of select="ns0:MONTO_DESCUENTO"/>
               </tns:MONTO_DESCUENTO>
               <tns:MONTO_SERVICIO>
                  <xsl:value-of select="ns0:MONTO_SERVICIO"/>
               </tns:MONTO_SERVICIO>
               <tns:MONTO_AJUSTE>
                  <xsl:value-of select="ns0:MONTO_AJUSTE"/>
               </tns:MONTO_AJUSTE>
               <tns:MONTO_IMPUESTOS>
                  <xsl:value-of select="ns0:MONTO_IMPUESTOS"/>
               </tns:MONTO_IMPUESTOS>
               <tns:MONTO_SALDO_DEBITO_INICIAL>
                  <xsl:value-of select="ns0:MONTO_SALDO_DEBITO_INICIAL"/>
               </tns:MONTO_SALDO_DEBITO_INICIAL>
               <tns:NUM_DEPOSITO_DIRECTO>
                  <xsl:value-of select="ns0:NUM_DEPOSITO_DIRECTO"/>
               </tns:NUM_DEPOSITO_DIRECTO>
               <tns:NUM_CUENTA_BANCARIA>
                  <xsl:value-of select="ns0:NUM_CUENTA_BANCARIA"/>
               </tns:NUM_CUENTA_BANCARIA>
               <tns:NUM_CUENTA_BANCARIA_INTERNACIONAL>
                  <xsl:value-of select="ns0:NUM_CUENTA_BANCARIA_INTERNACIONAL"/>
               </tns:NUM_CUENTA_BANCARIA_INTERNACIONAL>
               <tns:CODIGO_BANCO>
                  <xsl:value-of select="ns0:CODIGO_BANCO"/>
               </tns:CODIGO_BANCO>
            </tns:SUMMARY>
         </xsl:for-each>
         <xsl:for-each select="/ns0:PaymentsAmex/ns0:TRAILER">
            <tns:TRAILER>
               <tns:NUM_SECUENCIAL>
                  <xsl:value-of select="ns0:NUM_SECUENCIAL"/>
               </tns:NUM_SECUENCIAL>
               <tns:SUMA_TOTAL_REGISTROS>
                  <xsl:value-of select="ns0:SUMA_TOTAL_REGISTROS"/>
               </tns:SUMA_TOTAL_REGISTROS>
            </tns:TRAILER>
         </xsl:for-each>
         <xsl:for-each select="/ns0:PaymentsAmex/ns0:TRANSACTN">
            <tns:TRANSACTN>
               <tns:NUM_ESTABLECIMIENTO>
                  <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO"/>
               </tns:NUM_ESTABLECIMIENTO>
               <tns:CODIGO_TIPO_CUENTA>
                  <xsl:value-of select="ns0:CODIGO_TIPO_CUENTA"/>
               </tns:CODIGO_TIPO_CUENTA>
               <tns:NUM_PAGO_AMEX>
                  <xsl:value-of select="ns0:NUM_PAGO_AMEX"/>
               </tns:NUM_PAGO_AMEX>
               <tns:FECHA_PAGO>
                  <xsl:value-of select="ns0:FECHA_PAGO"/>
               </tns:FECHA_PAGO>
               <tns:MONEDA_PAGO>
                  <xsl:value-of select="ns0:MONEDA_PAGO"/>
               </tns:MONEDA_PAGO>
               <tns:NUM_ESTABLECIMIENTO2>
                  <xsl:value-of select="ns0:NUM_ESTABLECIMIENTO2"/>
               </tns:NUM_ESTABLECIMIENTO2>
               <tns:FECHA_PRESENTACION>
                  <xsl:value-of select="ns0:FECHA_PRESENTACION"/>
               </tns:FECHA_PRESENTACION>
               <tns:FECHA_PROCESAMIENTO_AMEX>
                  <xsl:value-of select="ns0:FECHA_PROCESAMIENTO_AMEX"/>
               </tns:FECHA_PROCESAMIENTO_AMEX>
               <tns:NUM_FACTURA>
                  <xsl:value-of select="ns0:NUM_FACTURA"/>
               </tns:NUM_FACTURA>
               <tns:MONEDA_PRESENTACION>
                  <xsl:value-of select="ns0:MONEDA_PRESENTACION"/>
               </tns:MONEDA_PRESENTACION>
               <tns:IDENTIFICACION_UBICACION_ESTABLECIMIENTO>
                  <xsl:value-of select="ns0:IDENTIFICACION_UBICACION_ESTABLECIMIENTO"/>
               </tns:IDENTIFICACION_UBICACION_ESTABLECIMIENTO>
               <tns:NUM_FACTURA_REFERENCIA>
                  <xsl:value-of select="ns0:NUM_FACTURA_REFERENCIA"/>
               </tns:NUM_FACTURA_REFERENCIA>
               <tns:NUM_VENDEDOR>
                  <xsl:value-of select="ns0:NUM_VENDEDOR"/>
               </tns:NUM_VENDEDOR>
               <tns:NUM_TARJETA>
                  <xsl:value-of select="ns0:NUM_TARJETA"/>
               </tns:NUM_TARJETA>
               <tns:NUM_REFERENCIA_ESPECIFICO_INDUSTRIA>
                  <xsl:value-of select="ns0:NUM_REFERENCIA_ESPECIFICO_INDUSTRIA"/>
               </tns:NUM_REFERENCIA_ESPECIFICO_INDUSTRIA>
               <tns:MONTO_BRUTO_PRESENTACION>
                  <xsl:value-of select="ns0:MONTO_BRUTO_PRESENTACION"/>
               </tns:MONTO_BRUTO_PRESENTACION>
               <tns:MONTO_TRANSACCION>
                  <xsl:value-of select="ns0:MONTO_TRANSACCION"/>
               </tns:MONTO_TRANSACCION>
               <tns:FECHA_TRANSACCION>
                  <xsl:value-of select="ns0:FECHA_TRANSACCION"/>
               </tns:FECHA_TRANSACCION>
               <tns:HORA_TRANSACCION>
                  <xsl:value-of select="ns0:HORA_TRANSACCION"/>
               </tns:HORA_TRANSACCION>
               <tns:NUM_TRANSACCION>
                  <xsl:value-of select="ns0:NUM_TRANSACCION"/>
               </tns:NUM_TRANSACCION>
               <tns:CODIGO_APROBACION>
                  <xsl:value-of select="ns0:CODIGO_APROBACION"/>
               </tns:CODIGO_APROBACION>
               <tns:NUM_TERMINAL>
                  <xsl:value-of select="ns0:NUM_TERMINAL"/>
               </tns:NUM_TERMINAL>
               <tns:CODIGO_CATEGORIA_ESTABLECIMIENTO>
                  <xsl:value-of select="ns0:CODIGO_CATEGORIA_ESTABLECIMIENTO"/>
               </tns:CODIGO_CATEGORIA_ESTABLECIMIENTO>
               <tns:NUM_REFERENCIA_SOCIO>
                  <xsl:value-of select="ns0:NUM_REFERENCIA_SOCIO"/>
               </tns:NUM_REFERENCIA_SOCIO>
               <tns:NUM_REFERENCIA_ADQUIRENTE>
                  <xsl:value-of select="ns0:NUM_REFERENCIA_ADQUIRENTE"/>
               </tns:NUM_REFERENCIA_ADQUIRENTE>
               <tns:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS>
                  <xsl:value-of select="ns0:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS"/>
               </tns:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS>
               <tns:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS1>
                  <xsl:value-of select="ns0:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS1"/>
               </tns:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS1>
               <tns:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS2>
                  <xsl:value-of select="ns0:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS2"/>
               </tns:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS2>
               <tns:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS3>
                  <xsl:value-of select="ns0:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS3"/>
               </tns:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS3>
               <tns:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS4>
                  <xsl:value-of select="ns0:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS4"/>
               </tns:CODIGO_ERROR_INCUMPLIMIENTO_CALIDAD_DATOS4>
               <tns:INDICADOR_LECTURA_BANDA>
                  <xsl:value-of select="ns0:INDICADOR_LECTURA_BANDA"/>
               </tns:INDICADOR_LECTURA_BANDA>
               <tns:INDICADOR_TRANSACCION_RECHAZADA>
                  <xsl:value-of select="ns0:INDICADOR_TRANSACCION_RECHAZADA"/>
               </tns:INDICADOR_TRANSACCION_RECHAZADA>
               <tns:MONTO_PRIMERA_CUOTA>
                  <xsl:value-of select="ns0:MONTO_PRIMERA_CUOTA"/>
               </tns:MONTO_PRIMERA_CUOTA>
               <tns:MONTO_CUOTA_SIGUIENTE>
                  <xsl:value-of select="ns0:MONTO_CUOTA_SIGUIENTE"/>
               </tns:MONTO_CUOTA_SIGUIENTE>
               <tns:CANTIDAD_CUOTAS>
                  <xsl:value-of select="ns0:CANTIDAD_CUOTAS"/>
               </tns:CANTIDAD_CUOTAS>
               <tns:NUM_CUOTA>
                  <xsl:value-of select="ns0:NUM_CUOTA"/>
               </tns:NUM_CUOTA>
               <tns:RELLENO>
                  <xsl:value-of select="ns0:RELLENO"/>
               </tns:RELLENO>
               <tns:MONTO_SERVICIO>
                  <xsl:value-of select="ns0:MONTO_SERVICIO"/>
               </tns:MONTO_SERVICIO>
               <tns:MONTO_ACELERACION>
                  <xsl:value-of select="ns0:MONTO_ACELERACION"/>
               </tns:MONTO_ACELERACION>
            </tns:TRANSACTN>
         </xsl:for-each>
         <xsl:for-each select="/ns0:PaymentsAmex/ns0:TXNPRICING">
            <tns:TXNPRICING>
               <tns:NUMERO_ESTABLCIMIENTO>
                  <xsl:value-of select="ns0:NUMERO_ESTABLCIMIENTO"/>
               </tns:NUMERO_ESTABLCIMIENTO>
               <tns:CODIGO_CUENTA>
                  <xsl:value-of select="ns0:CODIGO_CUENTA"/>
               </tns:CODIGO_CUENTA>
               <tns:NUM_PAGO_AMEX>
                  <xsl:value-of select="ns0:NUM_PAGO_AMEX"/>
               </tns:NUM_PAGO_AMEX>
               <tns:FECHA_PAGO>
                  <xsl:value-of select="ns0:FECHA_PAGO"/>
               </tns:FECHA_PAGO>
               <tns:MONEDA_PAGO>
                  <xsl:value-of select="ns0:MONEDA_PAGO"/>
               </tns:MONEDA_PAGO>
               <tns:NUM_ESTABLECIMENTO_PRESENTACION>
                  <xsl:value-of select="ns0:NUM_ESTABLECIMENTO_PRESENTACION"/>
               </tns:NUM_ESTABLECIMENTO_PRESENTACION>
               <tns:UBICACION_ESTABLECIMIENTO>
                  <xsl:value-of select="ns0:UBICACION_ESTABLECIMIENTO"/>
               </tns:UBICACION_ESTABLECIMIENTO>
               <tns:RELLENO>
                  <xsl:value-of select="ns0:RELLENO"/>
               </tns:RELLENO>
               <tns:NUM_FACTURA_REFERENCIA>
                  <xsl:value-of select="ns0:NUM_FACTURA_REFERENCIA"/>
               </tns:NUM_FACTURA_REFERENCIA>
               <tns:NUMERO_VENDEDOR>
                  <xsl:value-of select="ns0:NUMERO_VENDEDOR"/>
               </tns:NUMERO_VENDEDOR>
               <tns:NUM_TARJETA>
                  <xsl:value-of select="ns0:NUM_TARJETA"/>
               </tns:NUM_TARJETA>
               <tns:MONTO_TRANSACCION>
                  <xsl:value-of select="ns0:MONTO_TRANSACCION"/>
               </tns:MONTO_TRANSACCION>
               <tns:FECHA_TRANSACCION>
                  <xsl:value-of select="ns0:FECHA_TRANSACCION"/>
               </tns:FECHA_TRANSACCION>
               <tns:CODIGO_CARGO>
                  <xsl:value-of select="ns0:CODIGO_CARGO"/>
               </tns:CODIGO_CARGO>
               <tns:RELLENO2>
                  <xsl:value-of select="ns0:RELLENO2"/>
               </tns:RELLENO2>
               <tns:MONTO_CARGO>
                  <xsl:value-of select="ns0:MONTO_CARGO"/>
               </tns:MONTO_CARGO>
               <tns:TASA_DESCUENTO>
                  <xsl:value-of select="ns0:TASA_DESCUENTO"/>
               </tns:TASA_DESCUENTO>
               <tns:MONTO_DESCUENTO>
                  <xsl:value-of select="ns0:MONTO_DESCUENTO"/>
               </tns:MONTO_DESCUENTO>
            </tns:TXNPRICING>
         </xsl:for-each>
      </tns:SendConciliationBankAMEXRq>
   </xsl:template>
</xsl:stylesheet>
