<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://soa.estrellaroja.com.mx/ConciliationTec"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="http://soa.estrellaroja.com.mx/ConciliationEnt"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ConciliationTec/types"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/BpelGetConciliation.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ConciliationEntRq"
                                       namespace="http://soa.estrellaroja.com.mx/ConciliationEnt"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/External/ConciliationTecWrapper.wsdl"/>
        <oracle-xsl-mapper:rootElement name="GetConciliationsRq"
                                       namespace="http://soa.estrellaroja.com.mx/ConciliationTec"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE OCT 19 19:56:58 CDT 2021].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:GetConciliationsRq>
      <xsl:if test="/ns0:ConciliationEntRq/BussinessUnit">
        <tns:P_BUSINESSUNIT>
          <xsl:value-of select="/ns0:ConciliationEntRq/BussinessUnit"/>
        </tns:P_BUSINESSUNIT>
      </xsl:if>
      <xsl:if test="/ns0:ConciliationEntRq/FromDate">
        <tns:P_FROMDATE>
          <xsl:if test="/ns0:ConciliationEntRq/ns0:FromDate/@xsi:nil">
            <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
              <xsl:value-of select="/ns0:ConciliationEntRq/FromDate/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:ConciliationEntRq/FromDate"/>
        </tns:P_FROMDATE>
      </xsl:if>
      <xsl:if test="/ns0:ConciliationEntRq/PaymentReference">
        <tns:P_PAYMENTREFERENCE>
          <xsl:if test="/ns0:ConciliationEntRq/ns0:PaymentReference/@xsi:nil">
            <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
              <xsl:value-of select="/ns0:ConciliationEntRq/ns0:PaymentReference/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:ConciliationEntRq/PaymentReference"/>
        </tns:P_PAYMENTREFERENCE>
      </xsl:if>
      <xsl:if test="/ns0:ConciliationEntRq/ReceiptMethod">
        <tns:P_METODO_RECIBO>
          <xsl:value-of select="/ns0:ConciliationEntRq/ReceiptMethod"/>
        </tns:P_METODO_RECIBO>
      </xsl:if>
    </tns:GetConciliationsRq>
  </xsl:template>
</xsl:stylesheet>
