<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://soa.estrellaroja.com.mx/PaymentComplementBiz" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/PaymentComplementBiz/bpelHandleMergedStamping" xmlns:ns3="http://soa.estrellaroja.com.mx/DigitalStampTec" xmlns:ns4="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:ns5="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns6="http://soa.estrellaroja.com.mx/PaymentComplementBiz/bpelStampPaymentComplement"
                xmlns:ns7="http://soa.estrellaroja.com.mx/CommonPaymentsTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelHandleMergedStamping.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ContextInfo" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelHandleMergedStamping.wsdl"/>
            <oracle-xsl-mapper:rootElement name="HandleMergedStampingRs" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI DEC 15 15:59:52 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:HandleMergedStampingRs>
         <xsl:if test="string-length (/ns0:ContextInfo/ns0:LastError/ns1:ErrorCode ) = 0">
            <ns1:Success/>
         </xsl:if>
         <xsl:if test="string-length (/ns0:ContextInfo/ns0:LastError/ns1:ErrorCode ) > 0">
            <ns1:Errors>
               <ns1:Error>
                  <ns1:ErrorCode>
                     <xsl:value-of select="/ns0:ContextInfo/ns0:LastError/ns1:ErrorCode"/>
                  </ns1:ErrorCode>
                  <ns1:ShortDescription>
                     <xsl:value-of select="/ns0:ContextInfo/ns0:LastError/ns1:ShortDescription"/>
                  </ns1:ShortDescription>
                  <ns1:Description>
                     <xsl:value-of select="/ns0:ContextInfo/ns0:LastError/ns1:Description"/>
                  </ns1:Description>
                  <ns1:BusinessProcess>
                     <xsl:value-of select="/ns0:ContextInfo/ns0:LastError/ns1:BusinessProcess"/>
                  </ns1:BusinessProcess>
                  <ns1:FailedService>
                     <xsl:value-of select="/ns0:ContextInfo/ns0:LastError/ns1:FailedService"/>
                  </ns1:FailedService>
                  <ns1:TimeStamp>
                     <xsl:value-of select="/ns0:ContextInfo/ns0:LastError/ns1:TimeStamp"/>
                  </ns1:TimeStamp>
               </ns1:Error>
            </ns1:Errors>
         </xsl:if>
      </ns0:HandleMergedStampingRs>
   </xsl:template>
</xsl:stylesheet>