<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://soa.estrellaroja.com.mx/PaymentComplementBiz" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:strClass="http://www.oracle.com/XSL/Transform/java/java.lang.String"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns5="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:client="http://soa.estrellaroja.com.mx/PaymentComplementBiz/bpelStampPaymentComplement"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://soa.estrellaroja.com.mx/CommonPaymentsTec"
                xmlns:ns4="http://soa.estrellaroja.com.mx/AuditControlTec"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns1="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec/types">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelHandleMergedStamping.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CurrentHeader" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelHandleMergedStamping.wsdl"/>
            <oracle-xsl-mapper:rootElement name="StampData" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
            <oracle-xsl-mapper:param name="varDataUUID"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ERPIntegrationServiceTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="UploadAttachmentRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED DEC 20 12:28:37 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varDataUUID"/>
   <xsl:template match="/">
      <tns:UploadAttachmentRq>
         <tns:entityName>
            <xsl:value-of select="dvm:lookupValue (&quot;Dvms/Configuration.dvm&quot;, &quot;PropertyName&quot;, &quot;ENTITY_NAME&quot;, &quot;PropertyValue&quot;, &quot;&quot; )"/>
         </tns:entityName>
         <tns:categoryName>
            <xsl:value-of select="dvm:lookupValue (&quot;Dvms/Configuration.dvm&quot;, &quot;PropertyName&quot;, &quot;CATEGORY_NAME&quot;, &quot;PropertyValue&quot;, &quot;&quot; )"/>
         </tns:categoryName>
         <tns:allowDuplicate>
            <xsl:value-of select="dvm:lookupValue (&quot;Dvms/Configuration.dvm&quot;, &quot;PropertyName&quot;, &quot;ALLOW_DUPLICATE&quot;, &quot;PropertyValue&quot;, &quot;&quot; )"/>
         </tns:allowDuplicate>
         <tns:attachmentRows>
            <tns:UserKeyA>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:BusinessUnit"/>
            </tns:UserKeyA>
            <tns:UserKeyB>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:ReceiptNumber"/>
            </tns:UserKeyB>
            <tns:UserKeyC>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:ReceiptMethod"/>
            </tns:UserKeyC>
            <tns:UserKeyD>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:CashReceiptId"/>
            </tns:UserKeyD>
            <tns:AttachmentType>TEXT</tns:AttachmentType>
            <tns:Title>
               <xsl:value-of select="concat (&quot;UUID_&quot;, $varDataUUID/ns0:StampData/ns0:UUID )"/>
            </tns:Title>
            <tns:Content>
               <xsl:value-of select="$varDataUUID/ns0:StampData/ns0:UUID"/>
            </tns:Content>
         </tns:attachmentRows>
            <tns:attachmentRows>
            <tns:UserKeyA>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:BusinessUnit"/>
            </tns:UserKeyA>
            <tns:UserKeyB>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:ReceiptNumber"/>
            </tns:UserKeyB>
            <tns:UserKeyC>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:ReceiptMethod"/>
            </tns:UserKeyC>
            <tns:UserKeyD>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:CashReceiptId"/>
            </tns:UserKeyD>
            <tns:AttachmentType>URL</tns:AttachmentType>
            <tns:Title>PDF Document</tns:Title>
            <tns:Content>
               <xsl:value-of select="$varDataUUID/ns0:StampData/ns0:UrlPDF"/>
            </tns:Content>
         </tns:attachmentRows>
            <tns:attachmentRows>
            <tns:UserKeyA>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:BusinessUnit"/>
            </tns:UserKeyA>
            <tns:UserKeyB>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:ReceiptNumber"/>
            </tns:UserKeyB>
            <tns:UserKeyC>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:ReceiptMethod"/>
            </tns:UserKeyC>
            <tns:UserKeyD>
               <xsl:value-of select="/ns0:CurrentHeader/ns0:CashReceiptId"/>
            </tns:UserKeyD>
            <tns:AttachmentType>URL</tns:AttachmentType>
            <tns:Title>XML Document</tns:Title>
            <tns:Content>
               <xsl:value-of select="$varDataUUID/ns0:StampData/ns0:UrlXML"/>
            </tns:Content>
         </tns:attachmentRows>
        
      </tns:UploadAttachmentRq>
   </xsl:template>
</xsl:stylesheet>