<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://soa.estrellaroja.com.mx/PaymentComplementBiz" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/PaymentComplementBiz/bpelHandleMergedStamping" xmlns:ns3="http://soa.estrellaroja.com.mx/DigitalStampTec" xmlns:ns4="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:ns5="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns6="http://soa.estrellaroja.com.mx/PaymentComplementBiz/bpelStampPaymentComplement"
                xmlns:ns7="http://soa.estrellaroja.com.mx/CommonPaymentsTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelHandleMergedStamping.wsdl"/>
            <oracle-xsl-mapper:rootElement name="StampPaymentComplementRq" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelHandleMergedStamping.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RetriableHeaders" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
            <oracle-xsl-mapper:param name="retriableHeaders"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelHandleMergedStamping.wsdl"/>
            <oracle-xsl-mapper:rootElement name="HandleMergedStampingRq" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON DEC 11 11:46:57 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="retriableHeaders"/>
   <xsl:template match="/">
      <ns0:HandleMergedStampingRq>
         <xsl:for-each select="/ns0:StampPaymentComplementRq/ns0:Header">
            <ns0:MergedHeader>
               <ns0:Header>
                  <ns0:CashReceiptId>
                     <xsl:value-of select="ns0:CashReceiptId"/>
                  </ns0:CashReceiptId>
                  <ns0:ReceiptNumber>
                     <xsl:value-of select="ns0:ReceiptNumber"/>
                  </ns0:ReceiptNumber>
                  <ns0:IssuerRfc>
                     <xsl:value-of select="ns0:IssuerRfc"/>
                  </ns0:IssuerRfc>
                  <ns0:IssuerName>
                     <xsl:value-of select="ns0:IssuerName"/>
                  </ns0:IssuerName>
                  <ns0:IssuerZipCode>
                     <xsl:value-of select="ns0:IssuerZipCode"/>
                  </ns0:IssuerZipCode>
                  <ns0:IssuerStreet>
                     <xsl:value-of select="ns0:IssuerStreet"/>
                  </ns0:IssuerStreet>
                  <ns0:IssuerColony>
                     <xsl:value-of select="ns0:IssuerColony"/>
                  </ns0:IssuerColony>
                  <ns0:IssuerMunicipality>
                     <xsl:value-of select="ns0:IssuerMunicipality"/>
                  </ns0:IssuerMunicipality>
                  <ns0:IssuerState>
                     <xsl:value-of select="ns0:IssuerState"/>
                  </ns0:IssuerState>
                  <ns0:IssuerCountry>
                     <xsl:value-of select="ns0:IssuerCountry"/>
                  </ns0:IssuerCountry>
                  <ns0:InvoiceDate>
                     <xsl:value-of select="ns0:InvoiceDate"/>
                  </ns0:InvoiceDate>
                  <ns0:DocumentType>
                     <xsl:value-of select="ns0:DocumentType"/>
                  </ns0:DocumentType>
                  <ns0:AdditionalInformation>
                     <xsl:value-of select="ns0:AdditionalInformation"/>
                  </ns0:AdditionalInformation>
                  <ns0:TotalWords>
                     <xsl:value-of select="ns0:TotalWords"/>
                  </ns0:TotalWords>
                  <ns0:DescriptionItm>
                     <xsl:value-of select="ns0:DescriptionItm"/>
                  </ns0:DescriptionItm>
                  <ns0:ProdservkeyItm>
                     <xsl:value-of select="ns0:ProdservkeyItm"/>
                  </ns0:ProdservkeyItm>
                  <ns0:QuantityItm>
                     <xsl:value-of select="ns0:QuantityItm"/>
                  </ns0:QuantityItm>
                  <ns0:VatPercentageItm>
                     <xsl:value-of select="ns0:VatPercentageItm"/>
                  </ns0:VatPercentageItm>
                  <ns0:UnitKeyItm>
                     <xsl:value-of select="ns0:UnitKeyItm"/>
                  </ns0:UnitKeyItm>
                  <ns0:AmountItm>
                     <xsl:value-of select="ns0:AmountItm"/>
                  </ns0:AmountItm>
                  <ns0:SubtotalItm>
                     <xsl:value-of select="ns0:SubtotalItm"/>
                  </ns0:SubtotalItm>
                  <ns0:VatItm>
                     <xsl:value-of select="ns0:VatItm"/>
                  </ns0:VatItm>
                  <ns0:TotalItm>
                     <xsl:value-of select="ns0:TotalItm"/>
                  </ns0:TotalItm>
                  <ns0:TaxObjectItm>
                     <xsl:value-of select="ns0:TaxObjectItm"/>
                  </ns0:TaxObjectItm>
                  <ns0:TotalVat>
                     <xsl:value-of select="ns0:TotalVat"/>
                  </ns0:TotalVat>
                  <ns0:Subtotal>
                     <xsl:value-of select="ns0:Subtotal"/>
                  </ns0:Subtotal>
                  <ns0:Total>
                     <xsl:value-of select="ns0:Total"/>
                  </ns0:Total>
                  <ns0:Serie>
                     <xsl:value-of select="ns0:Serie"/>
                  </ns0:Serie>
                  <ns0:BranchName>
                     <xsl:value-of select="ns0:BranchName"/>
                  </ns0:BranchName>
                  <ns0:BranchZipCode>
                     <xsl:value-of select="ns0:BranchZipCode"/>
                  </ns0:BranchZipCode>
                  <ns0:ReceiverName>
                     <xsl:value-of select="ns0:ReceiverName"/>
                  </ns0:ReceiverName>
                  <ns0:ReceiverRfc>
                     <xsl:value-of select="ns0:ReceiverRfc"/>
                  </ns0:ReceiverRfc>
                  <ns0:ReceiverPhone>
                     <xsl:value-of select="ns0:ReceiverPhone"/>
                  </ns0:ReceiverPhone>
                  <ns0:ReceiverAddress>
                     <xsl:value-of select="ns0:ReceiverAddress"/>
                  </ns0:ReceiverAddress>
                  <ns0:ReceiverCounty>
                     <xsl:value-of select="ns0:ReceiverCounty"/>
                  </ns0:ReceiverCounty>
                  <ns0:ReceiverExtNumber>
                     <xsl:value-of select="ns0:ReceiverExtNumber"/>
                  </ns0:ReceiverExtNumber>
                  <ns0:ReceiverIntNumber>
                     <xsl:value-of select="ns0:ReceiverIntNumber"/>
                  </ns0:ReceiverIntNumber>
                  <ns0:ReceiverStreet>
                     <xsl:value-of select="ns0:ReceiverStreet"/>
                  </ns0:ReceiverStreet>
                  <ns0:ReceiverMunicipality>
                     <xsl:value-of select="ns0:ReceiverMunicipality"/>
                  </ns0:ReceiverMunicipality>
                  <ns0:ReceiverState>
                     <xsl:value-of select="ns0:ReceiverState"/>
                  </ns0:ReceiverState>
                  <ns0:ReceiverCountry>
                     <xsl:value-of select="ns0:ReceiverCountry"/>
                  </ns0:ReceiverCountry>
                  <ns0:ReceiverColony>
                     <xsl:value-of select="ns0:ReceiverColony"/>
                  </ns0:ReceiverColony>
                  <ns0:ReceiverCfdiUse>
                     <xsl:value-of select="ns0:ReceiverCfdiUse"/>
                  </ns0:ReceiverCfdiUse>
                  <ns0:ReceiverTaxRegime>
                     <xsl:value-of select="ns0:ReceiverTaxRegime"/>
                  </ns0:ReceiverTaxRegime>
                  <ns0:ReceiverZipCode>
                     <xsl:value-of select="ns0:ReceiverZipCode"/>
                  </ns0:ReceiverZipCode>
                  <ns0:Currency>
                     <xsl:value-of select="ns0:Currency"/>
                  </ns0:Currency>
                  <ns0:IssuerTaxRegime>
                     <xsl:value-of select="ns0:IssuerTaxRegime"/>
                  </ns0:IssuerTaxRegime>
                  <ns0:Comments>
                     <xsl:value-of select="ns0:Comments"/>
                  </ns0:Comments>
                  <ns0:Service>
                     <xsl:value-of select="ns0:Service"/>
                  </ns0:Service>
                  <ns0:PaymentDatePc>
                     <xsl:value-of select="ns0:PaymentDatePc"/>
                  </ns0:PaymentDatePc>
                  <ns0:PaymentWayPc>
                     <xsl:value-of select="ns0:PaymentWayPc"/>
                  </ns0:PaymentWayPc>
                  <ns0:CurrencyPc>
                     <xsl:value-of select="ns0:CurrencyPc"/>
                  </ns0:CurrencyPc>
                  <ns0:CurrencyExchangePc>
                     <xsl:value-of select="ns0:CurrencyExchangePc"/>
                  </ns0:CurrencyExchangePc>
                  <ns0:AmountPc>
                     <xsl:value-of select="ns0:AmountPc"/>
                  </ns0:AmountPc>
                  <ns0:OperationNumberPc>
                     <xsl:value-of select="ns0:OperationNumberPc"/>
                  </ns0:OperationNumberPc>
                  <ns0:BankNamePc>
                     <xsl:value-of select="ns0:BankNamePc"/>
                  </ns0:BankNamePc>
                  <ns0:PayerAccountPc>
                     <xsl:value-of select="ns0:PayerAccountPc"/>
                  </ns0:PayerAccountPc>
                  <ns0:BenAccIssuerRfcPc>
                     <xsl:value-of select="ns0:BenAccIssuerRfcPc"/>
                  </ns0:BenAccIssuerRfcPc>
                  <ns0:BeneficiaryAccountPc>
                     <xsl:value-of select="ns0:BeneficiaryAccountPc"/>
                  </ns0:BeneficiaryAccountPc>
                  <ns0:PaymentStringTypePc>
                     <xsl:value-of select="ns0:PaymentStringTypePc"/>
                  </ns0:PaymentStringTypePc>
                  <ns0:PaymentCertPc>
                     <xsl:value-of select="ns0:PaymentCertPc"/>
                  </ns0:PaymentCertPc>
                  <ns0:PaymentStringPc>
                     <xsl:value-of select="ns0:PaymentStringPc"/>
                  </ns0:PaymentStringPc>
                  <ns0:PaymentSealPc>
                     <xsl:value-of select="ns0:PaymentSealPc"/>
                  </ns0:PaymentSealPc>
                  <ns0:VersionPc>
                     <xsl:value-of select="ns0:VersionPc"/>
                  </ns0:VersionPc>
                  <ns0:CustomerNumber>
                     <xsl:value-of select="ns0:CustomerNumber"/>
                  </ns0:CustomerNumber>
                  <ns0:AccountNumber>
                     <xsl:value-of select="ns0:AccountNumber"/>
                  </ns0:AccountNumber>
                  <ns0:SiteNumber>
                     <xsl:value-of select="ns0:SiteNumber"/>
                  </ns0:SiteNumber>
                  <ns0:LastUpdateDate>
                     <xsl:value-of select="ns0:LastUpdateDate"/>
                  </ns0:LastUpdateDate>
                  <ns0:LastUpatedby>
                     <xsl:value-of select="ns0:LastUpatedby"/>
                  </ns0:LastUpatedby>
                  <ns0:BusinessUnit>
                     <xsl:value-of select="ns0:BusinessUnit"/>
                  </ns0:BusinessUnit>
                  <ns0:EstatusCFDI>
                     <xsl:value-of select="ns0:EstatusCFDI"/>
                  </ns0:EstatusCFDI>
                  <ns0:Exportacion>
                     <xsl:value-of select="ns0:Exportacion"/>
                  </ns0:Exportacion>
                  <ns0:ReceiptMethod>
                     <xsl:value-of select="ns0:ReceiptMethod"/>
                  </ns0:ReceiptMethod>
                  <xsl:for-each select="ns0:Lines">
                     <ns0:Lines>
                        <ns0:CashReceiptId>
                           <xsl:value-of select="ns0:CashReceiptId"/>
                        </ns0:CashReceiptId>
                        <ns0:InvoiceNumber>
                           <xsl:value-of select="ns0:InvoiceNumber"/>
                        </ns0:InvoiceNumber>
                        <ns0:DocumentId>
                           <xsl:value-of select="ns0:DocumentId"/>
                        </ns0:DocumentId>
                        <ns0:Serie>
                           <xsl:value-of select="ns0:Serie"/>
                        </ns0:Serie>
                        <ns0:Folio>
                           <xsl:value-of select="ns0:Folio"/>
                        </ns0:Folio>
                        <ns0:Currency>
                           <xsl:value-of select="ns0:Currency"/>
                        </ns0:Currency>
                        <ns0:CurrencyExchange>
                           <xsl:value-of select="ns0:CurrencyExchange"/>
                        </ns0:CurrencyExchange>
                        <xsl:if test="ns0:PaymentMethod">
                           <ns0:PaymentMethod>
                              <xsl:value-of select="ns0:PaymentMethod"/>
                           </ns0:PaymentMethod>
                        </xsl:if>
                        <ns0:PartialityNumber>
                           <xsl:value-of select="ns0:PartialityNumber"/>
                        </ns0:PartialityNumber>
                        <ns0:PreviousBalance>
                           <xsl:value-of select="ns0:PreviousBalance"/>
                        </ns0:PreviousBalance>
                        <ns0:PaidAmount>
                           <xsl:value-of select="ns0:PaidAmount"/>
                        </ns0:PaidAmount>
                        <ns0:OutStandingBalance>
                           <xsl:value-of select="ns0:OutStandingBalance"/>
                        </ns0:OutStandingBalance>
                        <ns0:CustomerTrxLineId>
                           <xsl:value-of select="ns0:CustomerTrxLineId"/>
                        </ns0:CustomerTrxLineId>
                        <ns0:ReceiptNumber>
                           <xsl:value-of select="ns0:ReceiptNumber"/>
                        </ns0:ReceiptNumber>
                        <ns0:InstallmentNumber>
                           <xsl:value-of select="ns0:InstallmentNumber"/>
                        </ns0:InstallmentNumber>
                        <ns0:ReceivableApplicationId>
                           <xsl:value-of select="ns0:ReceivableApplicationId"/>
                        </ns0:ReceivableApplicationId>
                        <ns0:TrxNumber>
                           <xsl:value-of select="ns0:TrxNumber"/>
                        </ns0:TrxNumber>
                        <ns0:Exportacion>
                           <xsl:value-of select="ns0:Exportacion"/>
                        </ns0:Exportacion>
                        <ns0:TaxObject>
                           <xsl:value-of select="ns0:TaxObject"/>
                        </ns0:TaxObject>
                        <ns0:RetainedTaxBase>
                           <xsl:value-of select="ns0:RetainedTaxBase"/>
                        </ns0:RetainedTaxBase>
                        <ns0:RetainedTax>
                           <xsl:value-of select="ns0:RetainedTax"/>
                        </ns0:RetainedTax>
                        <ns0:RetainedRateFee>
                           <xsl:value-of select="ns0:RetainedRateFee"/>
                        </ns0:RetainedRateFee>
                        <ns0:RetainedFactorType>
                           <xsl:value-of select="ns0:RetainedFactorType"/>
                        </ns0:RetainedFactorType>
                        <ns0:RetainedAmount>
                           <xsl:value-of select="ns0:RetainedAmount"/>
                        </ns0:RetainedAmount>
                        <ns0:TransferredsTaxBase>
                           <xsl:value-of select="ns0:TransferredsTaxBase"/>
                        </ns0:TransferredsTaxBase>
                        <ns0:TransferredsTax>
                           <xsl:value-of select="ns0:TransferredsTax"/>
                        </ns0:TransferredsTax>
                        <ns0:TransferredsRateFee>
                           <xsl:value-of select="ns0:TransferredsRateFee"/>
                        </ns0:TransferredsRateFee>
                        <ns0:TransferredsFactorType>
                           <xsl:value-of select="ns0:TransferredsFactorType"/>
                        </ns0:TransferredsFactorType>
                        <ns0:TransferredsAmount>
                           <xsl:value-of select="ns0:TransferredsAmount"/>
                        </ns0:TransferredsAmount>
                     </ns0:Lines>
                  </xsl:for-each>
               </ns0:Header>
               <ns0:Restored>
                  <xsl:value-of select="false ( )"/>
               </ns0:Restored>
            </ns0:MergedHeader>
         </xsl:for-each>
         <xsl:for-each select="$retriableHeaders/ns0:RetriableHeaders/ns0:CurrentHeader">
            <ns0:MergedHeader>
               <ns0:Header>
                  <ns0:CashReceiptId>
                     <xsl:value-of select="ns0:CashReceiptId"/>
                  </ns0:CashReceiptId>
                  <ns0:ReceiptNumber>
                     <xsl:value-of select="ns0:ReceiptNumber"/>
                  </ns0:ReceiptNumber>
                  <ns0:IssuerRfc>
                     <xsl:value-of select="ns0:IssuerRfc"/>
                  </ns0:IssuerRfc>
                  <ns0:IssuerName>
                     <xsl:value-of select="ns0:IssuerName"/>
                  </ns0:IssuerName>
                  <ns0:IssuerZipCode>
                     <xsl:value-of select="ns0:IssuerZipCode"/>
                  </ns0:IssuerZipCode>
                  <ns0:InvoiceDate>
                     <xsl:value-of select="ns0:InvoiceDate"/>
                  </ns0:InvoiceDate>
                  <ns0:DocumentType>
                     <xsl:value-of select="ns0:DocumentType"/>
                  </ns0:DocumentType>
                  <ns0:AdditionalInformation>
                     <xsl:value-of select="ns0:AdditionalInformation"/>
                  </ns0:AdditionalInformation>
                  <ns0:TotalWords>
                     <xsl:value-of select="ns0:TotalWords"/>
                  </ns0:TotalWords>
                  <ns0:DescriptionItm>
                     <xsl:value-of select="ns0:DescriptionItm"/>
                  </ns0:DescriptionItm>
                  <ns0:ProdservkeyItm>
                     <xsl:value-of select="ns0:ProdservkeyItm"/>
                  </ns0:ProdservkeyItm>
                  <ns0:QuantityItm>
                     <xsl:value-of select="ns0:QuantityItm"/>
                  </ns0:QuantityItm>
                  <ns0:VatPercentageItm>
                     <xsl:value-of select="ns0:VatPercentageItm"/>
                  </ns0:VatPercentageItm>
                  <ns0:UnitKeyItm>
                     <xsl:value-of select="ns0:UnitKeyItm"/>
                  </ns0:UnitKeyItm>
                  <ns0:AmountItm>
                     <xsl:value-of select="ns0:AmountItm"/>
                  </ns0:AmountItm>
                  <ns0:SubtotalItm>
                     <xsl:value-of select="ns0:SubtotalItm"/>
                  </ns0:SubtotalItm>
                  <ns0:VatItm>
                     <xsl:value-of select="ns0:VatItm"/>
                  </ns0:VatItm>
                  <ns0:TotalItm>
                     <xsl:value-of select="ns0:TotalItm"/>
                  </ns0:TotalItm>
                  <ns0:TaxObjectItm>
                     <xsl:value-of select="ns0:TaxObjectItm"/>
                  </ns0:TaxObjectItm>
                  <ns0:TotalVat>
                     <xsl:value-of select="ns0:TotalVat"/>
                  </ns0:TotalVat>
                  <ns0:Subtotal>
                     <xsl:value-of select="ns0:Subtotal"/>
                  </ns0:Subtotal>
                  <ns0:Total>
                     <xsl:value-of select="ns0:Total"/>
                  </ns0:Total>
                  <ns0:Serie>
                     <xsl:value-of select="ns0:Serie"/>
                  </ns0:Serie>
                  <ns0:BranchName>
                     <xsl:value-of select="ns0:BranchName"/>
                  </ns0:BranchName>
                  <ns0:BranchZipCode>
                     <xsl:value-of select="ns0:BranchZipCode"/>
                  </ns0:BranchZipCode>
                  <ns0:ReceiverName>
                     <xsl:value-of select="ns0:ReceiverName"/>
                  </ns0:ReceiverName>
                  <ns0:ReceiverRfc>
                     <xsl:value-of select="ns0:ReceiverRfc"/>
                  </ns0:ReceiverRfc>
                  <ns0:ReceiverPhone>
                     <xsl:value-of select="ns0:ReceiverPhone"/>
                  </ns0:ReceiverPhone>
                  <ns0:ReceiverAddress>
                     <xsl:value-of select="ns0:ReceiverAddress"/>
                  </ns0:ReceiverAddress>
                  <ns0:ReceiverExtNumber>
                     <xsl:value-of select="ns0:ReceiverExtNumber"/>
                  </ns0:ReceiverExtNumber>
                  <ns0:ReceiverIntNumber>
                     <xsl:value-of select="ns0:ReceiverIntNumber"/>
                  </ns0:ReceiverIntNumber>
                  <ns0:ReceiverColony>
                     <xsl:value-of select="ns0:ReceiverColony"/>
                  </ns0:ReceiverColony>
                  <ns0:ReceiverCounty>
                     <xsl:value-of select="ns0:ReceiverCounty"/>
                  </ns0:ReceiverCounty>
                  <ns0:ReceiverCfdiUse>
                     <xsl:value-of select="ns0:ReceiverCfdiUse"/>
                  </ns0:ReceiverCfdiUse>
                  <ns0:ReceiverTaxRegime>
                     <xsl:value-of select="ns0:ReceiverTaxRegime"/>
                  </ns0:ReceiverTaxRegime>
                  <ns0:Currency>
                     <xsl:value-of select="ns0:Currency"/>
                  </ns0:Currency>
                  <ns0:IssuerTaxRegime>
                     <xsl:value-of select="ns0:IssuerTaxRegime"/>
                  </ns0:IssuerTaxRegime>
                  <ns0:Comments>
                     <xsl:value-of select="ns0:Comments"/>
                  </ns0:Comments>
                  <ns0:Service>
                     <xsl:value-of select="ns0:Service"/>
                  </ns0:Service>
                  <ns0:PaymentDatePc>
                     <xsl:value-of select="ns0:PaymentDatePc"/>
                  </ns0:PaymentDatePc>
                  <ns0:PaymentWayPc>
                     <xsl:value-of select="ns0:PaymentWayPc"/>
                  </ns0:PaymentWayPc>
                  <ns0:CurrencyPc>
                     <xsl:value-of select="ns0:CurrencyPc"/>
                  </ns0:CurrencyPc>
                  <ns0:CurrencyExchangePc>
                     <xsl:value-of select="ns0:CurrencyExchangePc"/>
                  </ns0:CurrencyExchangePc>
                  <ns0:AmountPc>
                     <xsl:value-of select="ns0:AmountPc"/>
                  </ns0:AmountPc>
                  <ns0:OperationNumberPc>
                     <xsl:value-of select="ns0:OperationNumberPc"/>
                  </ns0:OperationNumberPc>
                  <ns0:BankNamePc>
                     <xsl:value-of select="ns0:BankNamePc"/>
                  </ns0:BankNamePc>
                  <ns0:PayerAccountPc>
                     <xsl:value-of select="ns0:PayerAccountPc"/>
                  </ns0:PayerAccountPc>
                  <ns0:BenAccIssuerRfcPc>
                     <xsl:value-of select="ns0:BenAccIssuerRfcPc"/>
                  </ns0:BenAccIssuerRfcPc>
                  <ns0:BeneficiaryAccountPc>
                     <xsl:value-of select="ns0:BeneficiaryAccountPc"/>
                  </ns0:BeneficiaryAccountPc>
                  <ns0:PaymentStringTypePc>
                     <xsl:value-of select="ns0:PaymentStringTypePc"/>
                  </ns0:PaymentStringTypePc>
                  <ns0:PaymentCertPc>
                     <xsl:value-of select="ns0:PaymentCertPc"/>
                  </ns0:PaymentCertPc>
                  <ns0:PaymentStringPc>
                     <xsl:value-of select="ns0:PaymentStringPc"/>
                  </ns0:PaymentStringPc>
                  <ns0:PaymentSealPc>
                     <xsl:value-of select="ns0:PaymentSealPc"/>
                  </ns0:PaymentSealPc>
                  <ns0:VersionPc>
                     <xsl:value-of select="ns0:VersionPc"/>
                  </ns0:VersionPc>
                  <ns0:CustomerNumber>
                     <xsl:value-of select="ns0:CustomerNumber"/>
                  </ns0:CustomerNumber>
                  <ns0:AccountNumber>
                     <xsl:value-of select="ns0:AccountNumber"/>
                  </ns0:AccountNumber>
                  <ns0:SiteNumber>
                     <xsl:value-of select="ns0:SiteNumber"/>
                  </ns0:SiteNumber>
                  <ns0:LastUpdateDate>
                     <xsl:value-of select="ns0:LastUpdateDate"/>
                  </ns0:LastUpdateDate>
                  <ns0:LastUpatedby>
                     <xsl:value-of select="ns0:LastUpatedby"/>
                  </ns0:LastUpatedby>
                  <ns0:BusinessUnit>
                     <xsl:value-of select="ns0:BusinessUnit"/>
                  </ns0:BusinessUnit>
                  <ns0:EstatusCFDI>
                     <xsl:value-of select="ns0:EstatusCFDI"/>
                  </ns0:EstatusCFDI>
                  <ns0:Exportacion>
                     <xsl:value-of select="ns0:Exportacion"/>
                  </ns0:Exportacion>
                  <ns0:ReceiptMethod>
                     <xsl:value-of select="ns0:ReceiptMethod"/>
                  </ns0:ReceiptMethod>
                  <xsl:for-each select="ns0:Lines">
                     <ns0:Lines>
                        <ns0:CashReceiptId>
                           <xsl:value-of select="ns0:CashReceiptId"/>
                        </ns0:CashReceiptId>
                        <ns0:InvoiceNumber>
                           <xsl:value-of select="ns0:InvoiceNumber"/>
                        </ns0:InvoiceNumber>
                        <ns0:DocumentId>
                           <xsl:value-of select="ns0:DocumentId"/>
                        </ns0:DocumentId>
                        <ns0:Serie>
                           <xsl:value-of select="ns0:Serie"/>
                        </ns0:Serie>
                        <ns0:Folio>
                           <xsl:value-of select="ns0:Folio"/>
                        </ns0:Folio>
                        <ns0:Currency>
                           <xsl:value-of select="ns0:Currency"/>
                        </ns0:Currency>
                        <ns0:CurrencyExchange>
                           <xsl:value-of select="ns0:CurrencyExchange"/>
                        </ns0:CurrencyExchange>
                        <xsl:if test="ns0:PaymentMethod">
                           <ns0:PaymentMethod>
                              <xsl:value-of select="ns0:PaymentMethod"/>
                           </ns0:PaymentMethod>
                        </xsl:if>
                        <ns0:PartialityNumber>
                           <xsl:value-of select="ns0:PartialityNumber"/>
                        </ns0:PartialityNumber>
                        <ns0:PreviousBalance>
                           <xsl:value-of select="ns0:PreviousBalance"/>
                        </ns0:PreviousBalance>
                        <ns0:PaidAmount>
                           <xsl:value-of select="ns0:PaidAmount"/>
                        </ns0:PaidAmount>
                        <ns0:OutStandingBalance>
                           <xsl:value-of select="ns0:OutStandingBalance"/>
                        </ns0:OutStandingBalance>
                        <ns0:CustomerTrxLineId>
                           <xsl:value-of select="ns0:CustomerTrxLineId"/>
                        </ns0:CustomerTrxLineId>
                        <ns0:ReceiptNumber>
                           <xsl:value-of select="ns0:ReceiptNumber"/>
                        </ns0:ReceiptNumber>
                        <ns0:InstallmentNumber>
                           <xsl:value-of select="ns0:InstallmentNumber"/>
                        </ns0:InstallmentNumber>
                        <ns0:ReceivableApplicationId>
                           <xsl:value-of select="ns0:ReceivableApplicationId"/>
                        </ns0:ReceivableApplicationId>
                        <ns0:TrxNumber>
                           <xsl:value-of select="ns0:TrxNumber"/>
                        </ns0:TrxNumber>
                        <ns0:Exportacion>
                           <xsl:value-of select="ns0:Exportacion"/>
                        </ns0:Exportacion>
                        <ns0:TaxObject>
                           <xsl:value-of select="ns0:TaxObject"/>
                        </ns0:TaxObject>
                        <ns0:RetainedTaxBase>
                           <xsl:value-of select="ns0:RetainedTaxBase"/>
                        </ns0:RetainedTaxBase>
                        <ns0:RetainedTax>
                           <xsl:value-of select="ns0:RetainedTax"/>
                        </ns0:RetainedTax>
                        <ns0:RetainedRateFee>
                           <xsl:value-of select="ns0:RetainedRateFee"/>
                        </ns0:RetainedRateFee>
                        <ns0:RetainedFactorType>
                           <xsl:value-of select="ns0:RetainedFactorType"/>
                        </ns0:RetainedFactorType>
                        <ns0:RetainedAmount>
                           <xsl:value-of select="ns0:RetainedAmount"/>
                        </ns0:RetainedAmount>
                        <ns0:TransferredsTaxBase>
                           <xsl:value-of select="ns0:TransferredsTaxBase"/>
                        </ns0:TransferredsTaxBase>
                        <ns0:TransferredsTax>
                           <xsl:value-of select="ns0:TransferredsTax"/>
                        </ns0:TransferredsTax>
                        <ns0:TransferredsRateFee>
                           <xsl:value-of select="ns0:TransferredsRateFee"/>
                        </ns0:TransferredsRateFee>
                        <ns0:TransferredsFactorType>
                           <xsl:value-of select="ns0:TransferredsFactorType"/>
                        </ns0:TransferredsFactorType>
                        <ns0:TransferredsAmount>
                           <xsl:value-of select="ns0:TransferredsAmount"/>
                        </ns0:TransferredsAmount>
                     </ns0:Lines>
                  </xsl:for-each>
               </ns0:Header>
               <ns0:Restored>
                  <xsl:value-of select="true ( )"/>
               </ns0:Restored>
            </ns0:MergedHeader>
         </xsl:for-each>
      </ns0:HandleMergedStampingRq>
   </xsl:template>
</xsl:stylesheet>