<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://soa.estrellaroja.com.mx/PaymentComplementBiz" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns5="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/PaymentComplementBiz/bpelHandleMergedStamping" xmlns:ns3="http://soa.estrellaroja.com.mx/DigitalStampTec" xmlns:ns4="http://soa.estrellaroja.com.mx/AuditControlTec"
                xmlns:ns6="http://soa.estrellaroja.com.mx/PaymentComplementBiz/bpelStampPaymentComplement"
                xmlns:ns7="http://soa.estrellaroja.com.mx/CommonPaymentsTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelHandleMergedStamping.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ContextInfo" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelHandleMergedStamping.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CurrentHeader" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
            <oracle-xsl-mapper:param name="currentHeader"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelHandleMergedStamping.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DetailErrors" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 28 19:27:22 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="currentHeader"/>
   <xsl:template match="/">
      <ns0:DetailErrors>
         <xsl:for-each select="">
            <ns0:DetailType>
               <ns0:ReceiptNumber>
                  <xsl:value-of select="$currentHeader/ns0:CurrentHeader/ns0:ReceiptNumber"/>
               </ns0:ReceiptNumber>
               <ns0:ErrorDescription>
                  <xsl:value-of select="/ns0:ContextInfo/ns0:LastError/ns1:ErrorCode"/>
               </ns0:ErrorDescription>
            </ns0:DetailType>
         </xsl:for-each>
      </ns0:DetailErrors>
   </xsl:template>
</xsl:stylesheet>