<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:tns="http://soa.estrellaroja.com.mx/AssetMetricReadings" xmlns:ns0="http://soa.estrellaroja.com.mx/ReadingsCommon" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 tns oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://soa.estrellaroja.com.mx/RecordUnitMterics" xmlns:ns2="http://soa.estrellaroja.com.mx/ReportReadings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://soa.estrellaroja.com.mx/ReportAsset" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/EAMOriginPriority" xmlns:ns6="http://soa.estrellaroja.com.mx/AssetMetricReadingExcel">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/RecordUnitMterics.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MetricsReading" namespace="http://soa.estrellaroja.com.mx/ReadingsCommon"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/RecordUnitMterics.wsdl"/>
            <oracle-xsl-mapper:rootElement name="AssetMetricReading" namespace="http://soa.estrellaroja.com.mx/AssetMetricReadings"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU JAN 09 12:49:16 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:key match="ns0:Reading" name="assetNumber" use="ns0:assetNumber"/>
   <xsl:template match="/">
      <tns:AssetMetricReading>
      <xsl:for-each select="/ns0:MetricsReading/ns0:Reading[count(. | key('assetNumber', ns0:assetNumber)[1]) = 1]">
                <xsl:sort order="descending" select="ns0:assetNumber"/>
                <tns:Reading>
                    <tns:assetNumber>
                  <xsl:value-of select="ns0:assetNumber"/>
               </tns:assetNumber>
                    <xsl:for-each select="key (&quot;assetNumber&quot;, ns0:assetNumber )">
                        <xsl:sort order="descending" select="ns0:readingDate"/>    
                        <tns:Records>
                            <tns:readingDate>
                        <xsl:value-of select="ns0:readingDate"/>
                     </tns:readingDate>
                            <tns:readingValue>
                        <xsl:value-of select="ns0:readingValue"/>
                     </tns:readingValue>
                            <tns:origin>
                        <xsl:value-of select="ns0:origin"/>
                     </tns:origin>
                        </tns:Records>
                    </xsl:for-each>
                </tns:Reading>
            </xsl:for-each>
            </tns:AssetMetricReading>
   </xsl:template>
</xsl:stylesheet>