<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl socket dvm mhdr oraxsl oraext xp20 xref" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns4="http://soa.estrellaroja.com.mx/AssetMetricReadings" xmlns:client="http://soa.estrellaroja.com.mx/RecordUnitMterics" xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/EAMOriginPriority" xmlns:ns2="http://soa.estrellaroja.com.mx/ReportReadings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns3="http://soa.estrellaroja.com.mx/ReadingsCommon" xmlns:ns1="http://soa.estrellaroja.com.mx/ReportAsset" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns6="http://soa.estrellaroja.com.mx/AssetMetricReadingExcel">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/RecordUnitMterics.wsdl"/>
            <oracle-xsl-mapper:rootElement name="G_2" namespace=""/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/RecordUnitMterics.wsdl"/>
            <oracle-xsl-mapper:rootElement name="G_2" namespace=""/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED JAN 15 10:53:06 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <G_2>
         <FECHA>
            <xsl:value-of select="//G_2[1]/FECHA"/>
         </FECHA>
         <VALOR_CARGA>
            <xsl:value-of select="//G_2[1]/VALOR_CARGA"/>
         </VALOR_CARGA>
         <VALOR_MOSTRADO>
            <xsl:value-of select="//G_2[1]/VALOR_MOSTRADO"/>
         </VALOR_MOSTRADO>
         <NUMERO_ITEM>
            <xsl:value-of select="//G_2[1]/NUMERO_ITEM"/>
         </NUMERO_ITEM>
         <FECHA_EJECUCION>
            <xsl:value-of select="//G_2[1]/FECHA_EJECUCION"/>
         </FECHA_EJECUCION>
         <CODIGO>
            <xsl:value-of select="//G_2[1]/CODIGO"/>
         </CODIGO>
         <NAME>
            <xsl:value-of select="//G_2[1]/NAME"/>
         </NAME>
         <ASSET_NUMBER>
            <xsl:value-of select="//G_2[1]/ASSET_NUMBER"/>
         </ASSET_NUMBER>
         <NAME_UM>
            <xsl:value-of select="//G_2[1]/NAME_UM"/>
         </NAME_UM>
         <ORGANIZATION_ID>
            <xsl:value-of select="//G_2[1]/ORGANIZATION_ID"/>
         </ORGANIZATION_ID>
         <NOMBRE_ORGANIZACION>
            <xsl:value-of select="//G_2[1]/NOMBRE_ORGANIZACION"/>
         </NOMBRE_ORGANIZACION>
         <ACTIVE_START_DATE>
            <xsl:value-of select="//G_2[1]/ACTIVE_START_DATE"/>
         </ACTIVE_START_DATE>
         <ACTIVE_END_DATE>
            <xsl:value-of select="//G_2[1]/ACTIVE_END_DATE"/>
         </ACTIVE_END_DATE>
         <METER_ID>
            <xsl:value-of select="//G_2[1]/METER_ID"/>
         </METER_ID>
      </G_2>
   </xsl:template>
</xsl:stylesheet>