<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://soa.estrellaroja.com.mx/AssetMetricReadings" xmlns:tns="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/EAMSelectErrorRecord" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:ns6="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_ESTRELLA_ROJA/DEV_EAMUnitMetricsTec/EAMSelectErrorRecord" xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/EAMOriginPriority" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns4="http://soa.estrellaroja.com.mx/ReadingsCommon" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://soa.estrellaroja.com.mx/RecordUnitMterics" xmlns:ns3="http://soa.estrellaroja.com.mx/ReportReadings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://soa.estrellaroja.com.mx/ReportAsset" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:ns7="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns8="http://soa.estrellaroja.com.mx/SOAUtilitiesTec/types" xmlns:ns9="http://soa.estrellaroja.com.mx/AssetMetricReadingExcel">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/RecordUnitMterics.wsdl"/>
            <oracle-xsl-mapper:rootElement name="AssetMetricReading" namespace="http://soa.estrellaroja.com.mx/AssetMetricReadings"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ErrorRecord/EAMSelectErrorRecord.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EAMSelectErrorRecordOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EAMSelectErrorRecord"/>
            <oracle-xsl-mapper:param name="Out_EAMSelectErrorRecord.EAMSelectErrorRecordOutputCollection"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SOAUtilitiesTec.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetHtmlControlRq" namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI JAN 17 16:53:05 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="Out_EAMSelectErrorRecord.EAMSelectErrorRecordOutputCollection"/>
   <xsl:template match="/">
      <tns:GetHtmlControlRq>
         <tns:TotalSucceeded>
            <xsl:value-of select="count ($Out_EAMSelectErrorRecord.EAMSelectErrorRecordOutputCollection/ns1:EAMSelectErrorRecordOutputCollection/ns1:EAMSelectErrorRecordOutput[(./ns1:ERROR_MESSAGE = &quot;Sucess&quot;)] )"/>
         </tns:TotalSucceeded>
         <tns:TotalErrors>
            <xsl:value-of select="count ($Out_EAMSelectErrorRecord.EAMSelectErrorRecordOutputCollection/ns1:EAMSelectErrorRecordOutputCollection/ns1:EAMSelectErrorRecordOutput[(./ns1:ERROR_MESSAGE != &quot;Sucess&quot;)] )"/>
         </tns:TotalErrors>
         <tns:TotalProcessed>
            <xsl:value-of select="count ($Out_EAMSelectErrorRecord.EAMSelectErrorRecordOutputCollection/ns1:EAMSelectErrorRecordOutputCollection/ns1:EAMSelectErrorRecordOutput )"/>
         </tns:TotalProcessed>
         <tns:ErrorsDetails>
            <xsl:for-each select="$Out_EAMSelectErrorRecord.EAMSelectErrorRecordOutputCollection/ns1:EAMSelectErrorRecordOutputCollection/ns1:EAMSelectErrorRecordOutput">
               <tns:ErrorDetail>
                  <tns:DataValue>
                     <xsl:value-of select="ns1:ASSET_NUMBER"/>
                  </tns:DataValue>
                  <tns:ErrorMessage>
                     <xsl:value-of select="ns1:ERROR_MESSAGE"/>
                  </tns:ErrorMessage>
               </tns:ErrorDetail>
            </xsl:for-each>
         </tns:ErrorsDetails>
      </tns:GetHtmlControlRq>
   </xsl:template>
</xsl:stylesheet>