<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:tns="http://soa.estrellaroja.com.mx/AssetMetricReadingExcel" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/EAMOriginDataByAsset" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_ESTRELLA_ROJA/DEV_EAMUnitMetricsTec/EAMOriginDataByAsset" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns6="http://xmlns.oracle.com/pcbpel/adapter/db/EAMOriginPriority" xmlns:ns4="http://soa.estrellaroja.com.mx/ReadingsCommon" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns5="http://soa.estrellaroja.com.mx/AssetMetricReadings" xmlns:client="http://soa.estrellaroja.com.mx/RecordUnitMterics" xmlns:ns3="http://soa.estrellaroja.com.mx/ReportReadings" xmlns:ns2="http://soa.estrellaroja.com.mx/ReportAsset">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DataOrigin/EAMOriginDataByAsset.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EAMOriginDataByAssetOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EAMOriginDataByAsset"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/RecordUnitMterics.wsdl"/>
            <oracle-xsl-mapper:rootElement name="AssetMetricReading" namespace="http://soa.estrellaroja.com.mx/AssetMetricReadingExcel"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [SAT JAN 18 14:54:19 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:AssetMetricReading>
         <tns:Reading>
            <tns:assetNumber>
               <xsl:value-of select="/ns0:EAMOriginDataByAssetOutputCollection/ns0:EAMOriginDataByAssetOutput/ns0:ASSET_NUMBER"/>
            </tns:assetNumber>
            <xsl:for-each select="/ns0:EAMOriginDataByAssetOutputCollection/ns0:EAMOriginDataByAssetOutput">
               <tns:Records>
                  <tns:readingDate>
                     <xsl:value-of select="ns0:READING_DATE"/>
                  </tns:readingDate>
                  <tns:readingValue>
                     <xsl:value-of select="ns0:READING_VALUE"/>
                  </tns:readingValue>
                  <tns:origin>
                     <xsl:value-of select="ns0:ORIGIN"/>
                  </tns:origin>
               </tns:Records>
            </xsl:for-each>
         </tns:Reading>
      </tns:AssetMetricReading>
   </xsl:template>
</xsl:stylesheet>