<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://soa.estrellaroja.com.mx/XMLValidatorBiz" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/XXER_ERRORES_TEMP_TBL" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns2="http://soa.estrellaroja.com.mx/CartaPorte" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns4="http://soa.estrellaroja.com.mx/XMLValidatorBiz/types"
                xmlns:ns3="http://soa.estrellaroja.com.mx/Tables/XXER_CONF_VALIDADOR_XML_TBL"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/GER_SOA_OCI/XMLValidatorBiz/XXER_ERRORES_TEMP_TBL">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/XMLValidatorBiz/XMLValidatorBiz.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ValidaCartaPorteRq" namespace="http://soa.estrellaroja.com.mx/XMLValidatorBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/XXER_ERRORES_TEMP_TBL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxerErroresTempTblCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/XXER_ERRORES_TEMP_TBL"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON APR 24 23:38:27 CDT 2023].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <tns:XxerErroresTempTblCollection>
          <xsl:variable name="v_idCarga" select="/ns0:ValidaCartaPorteRq/ns2:CartaPorte/ns2:ID_Carga_WTMS"/>
          <xsl:for-each select="/ns0:ValidaCartaPorteRq/ns2:CartaPorte/ns2:trasladoMercancias/ns2:Remolque/ns2:Traslados/ns2:Traslado">
            <xsl:variable name="v_idFactura" select="ns2:FacturaDestino"/>
            <xsl:for-each select="ns2:Mercancias/ns2:Mercancia">
              <xsl:variable name="v_producto" select="ns2:BienesTransp"/>
                  <tns:XxerErroresTempTbl>
                    <tns:id>
                      <xsl:value-of select="concat ($v_idCarga,$v_idFactura ,$v_producto )"/>
                    </tns:id>
                  </tns:XxerErroresTempTbl>
            </xsl:for-each>
      </xsl:for-each>
          <xsl:for-each select="/ns0:ValidaCartaPorteRq/ns2:CartaPorte/ns2:trasladoMercancias/ns2:Remolque/ns2:Traslados/ns2:Traslado">
            <xsl:variable name="v_idFactura" select="ns2:FacturaDestino"/>
            <xsl:variable name="v_codigoPostal" select="ns2:DireccionDestino/ns2:CodigoPostal"/>
                <tns:XxerErroresTempTbl>
                  <tns:id>
                    <xsl:value-of select="concat ($v_idCarga,$v_idFactura ,$v_codigoPostal)"/>
                  </tns:id>
                </tns:XxerErroresTempTbl>			
          </xsl:for-each>
          <xsl:for-each select="/ns0:ValidaCartaPorteRq/ns2:CartaPorte/ns2:trasladoMercancias/ns2:Remolque/ns2:Traslados/ns2:Traslado">
            <xsl:variable name="v_idFactura" select="ns2:FacturaDestino"/>
            <xsl:variable name="v_codigoPostal" select="ns2:DireccionOrigen/ns2:CodigoPostal"/>
                <tns:XxerErroresTempTbl>
                  <tns:id>
                    <xsl:value-of select="concat ($v_idCarga,$v_idFactura ,$v_codigoPostal)"/>
                  </tns:id>
                </tns:XxerErroresTempTbl>			
          </xsl:for-each>
    </tns:XxerErroresTempTblCollection>
    </xsl:template>
</xsl:stylesheet>
