<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://soa.estrellaroja.com.mx/InventoryBiz/nxsdTransactionInventory" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/FinancialsTec" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns2="http://soa.estrellaroja.com.mx/FinancialsTec/types"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/InventoryBiz"
                xmlns:client="http://soa.estrellaroja.com.mx/InventoryBiz/bpelInventoryBiz"
                xmlns:ns4="http://schemas.oracle.com/bpel/extension"
                xmlns:ns6="http://soa.estrellaroja.com.mx/InventoryBiz/NxsdInventoryTransaction"
                xmlns:ns5="http://soa.estrellaroja.com.mx/InventoryBiz/nxsdInventoryTransaction"
                xmlns:ns7="http://www.w3.org/2000/xmlns/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/FinancialsTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetInventoryTransactionsRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelInventoryBiz.wsdl"/>
            <oracle-xsl-mapper:rootElement name="nxsdTransactionInventory" namespace="http://soa.estrellaroja.com.mx/InventoryBiz/nxsdTransactionInventory"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI DEC 15 00:12:46 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:nxsdTransactionInventory>
         <xsl:for-each select="/ns0:GetInventoryTransactionsRs/ns0:Return/ns0:InventoryTransaction">
            <tns:nxsdTransactionInventoryType>
               <tns:ORGANIZATION_NAME>
                  <xsl:value-of select="ns0:OrganizationName"/>
               </tns:ORGANIZATION_NAME>
               <tns:TRANSACTION_GROUP_ID/>
               <tns:TRANSACTION_GROUP_SEQ/>
               <tns:TRANSACTION_BATCH_ID/>
               <tns:TRANSACTION_BATCH_SEQ/>
               <tns:PROCESS_FLAG>
                  <xsl:value-of select="ns0:ProcessFlag"/>
               </tns:PROCESS_FLAG>
               <tns:INVENTORY_ITEM/>
               <tns:ITEM_NUMBER>
                  <xsl:value-of select="ns0:ItemNumber"/>
               </tns:ITEM_NUMBER>
               <tns:REVISION/>
               <tns:INV_LOTSERIAL_INTERFACE_NUM/>
               <tns:SUBINVENTORY_CODE>
                  <xsl:value-of select="ns0:SubinvetoryCode"/>
               </tns:SUBINVENTORY_CODE>
               <tns:LOCATOR_NAME>
                  <xsl:value-of select="ns0:LocatorName"/>
               </tns:LOCATOR_NAME>
               <tns:LOC_SEGMENT1/>
               <tns:LOC_SEGMENT2/>
               <tns:LOC_SEGMENT3/>
               <tns:LOC_SEGMENT4/>
               <tns:LOC_SEGMENT5/>
               <tns:LOC_SEGMENT6/>
               <tns:LOC_SEGMENT7/>
               <tns:LOC_SEGMENT8/>
               <tns:LOC_SEGMENT9/>
               <tns:LOC_SEGMENT10/>
               <tns:LOC_SEGMENT11/>
               <tns:LOC_SEGMENT12/>
               <tns:LOC_SEGMENT13/>
               <tns:LOC_SEGMENT14/>
               <tns:LOC_SEGMENT15/>
               <tns:LOC_SEGMENT16/>
               <tns:LOC_SEGMENT17/>
               <tns:LOC_SEGMENT18/>
               <tns:LOC_SEGMENT19/>
               <tns:LOC_SEGMENT20/>
               <tns:TRANSACTION_QUANTITY>
                  <xsl:value-of select="ns0:TransactionQuantity"/>
               </tns:TRANSACTION_QUANTITY>
               <tns:TRANSACTION_UOM/>
               <tns:TRANSACTION_UNIT_OF_MEASURE>
                  <xsl:value-of select="ns0:TransactionUnitOfMeasure"/>
               </tns:TRANSACTION_UNIT_OF_MEASURE>
               <tns:RESERVATION_QUANTITY/>
               <tns:TRANSACTION_DATE>
                  <xsl:value-of select="concat (substring (ns0:TransactionDate, 1, 4 ), &quot;/&quot;, substring (ns0:TransactionDate, 6, 2 ), &quot;/&quot;, substring (ns0:TransactionDate, 9, 2 ), &quot; 00:00&quot; )"/>
               </tns:TRANSACTION_DATE>
               <tns:TRANSACTION_SOURCE_TYPE_NAME/>
               <tns:TRANSACTION_TYPE_NAME>
                  <xsl:value-of select="ns0:TransactionTypeName"/>
               </tns:TRANSACTION_TYPE_NAME>
               <tns:TRANSFER_ORGANIZATION_TYPE/>
               <tns:TRANSFER_ORGANIZATION_NAME/>
               <tns:TRANSFER_SUBINVENTORY/>
               <tns:XFER_LOC_SEGMENT1/>
               <tns:XFER_LOC_SEGMENT2/>
               <tns:XFER_LOC_SEGMENT3/>
               <tns:XFER_LOC_SEGMENT4/>
               <tns:XFER_LOC_SEGMENT5/>
               <tns:XFER_LOC_SEGMENT6/>
               <tns:XFER_LOC_SEGMENT7/>
               <tns:XFER_LOC_SEGMENT8/>
               <tns:XFER_LOC_SEGMENT9/>
               <tns:XFER_LOC_SEGMENT10/>
               <tns:XFER_LOC_SEGMENT11/>
               <tns:XFER_LOC_SEGMENT12/>
               <tns:XFER_LOC_SEGMENT13/>
               <tns:XFER_LOC_SEGMENT14/>
               <tns:XFER_LOC_SEGMENT15/>
               <tns:XFER_LOC_SEGMENT16/>
               <tns:XFER_LOC_SEGMENT17/>
               <tns:XFER_LOC_SEGMENT18/>
               <tns:XFER_LOC_SEGMENT19/>
               <tns:XFER_LOC_SEGMENT20/>
               <tns:PRIMARY_QUANTITY>
                  <xsl:value-of select="ns0:TransactionQuantity"/>
               </tns:PRIMARY_QUANTITY>
               <tns:SECONDARY_TRANSACTION_QUANTITY/>
               <tns:SECONDARY_UOM_CODE/>
               <tns:SECONDARY_UNIT_OF_MEASURE/>
               <tns:SOURCE_CODE>
                  <xsl:value-of select="ns0:SourceCode"/>
               </tns:SOURCE_CODE>
               <tns:SOURCE_HEADER_ID>
                  <xsl:value-of select="ns0:SourceHeaderId"/>
               </tns:SOURCE_HEADER_ID>
               <tns:SOURCE_LINE_ID>
                  <xsl:value-of select="ns0:SourceLineId"/>
               </tns:SOURCE_LINE_ID>
               <tns:TRANSACTION_SOURCE_NAME/>
               <tns:DSP_SEGMENT1>
                  <xsl:value-of select="ns0:DspSegment1"/>
               </tns:DSP_SEGMENT1>
               <tns:DSP_SEGMENT2>
                  <xsl:value-of select="ns0:DspSegment2"/>
               </tns:DSP_SEGMENT2>
               <tns:DSP_SEGMENT3>
                  <xsl:value-of select="ns0:DspSegment3"/>
               </tns:DSP_SEGMENT3>
               <tns:DSP_SEGMENT4>
                  <xsl:value-of select="ns0:DspSegment4"/>
               </tns:DSP_SEGMENT4>
               <tns:DSP_SEGMENT5>
                  <xsl:value-of select="ns0:DspSegment5"/>
               </tns:DSP_SEGMENT5>
               <tns:DSP_SEGMENT6>
                  <xsl:value-of select="ns0:DspSegment6"/>
               </tns:DSP_SEGMENT6>
               <tns:DSP_SEGMENT7>
                  <xsl:value-of select="ns0:DspSegment7"/>
               </tns:DSP_SEGMENT7>
               <tns:DSP_SEGMENT8>
                  <xsl:value-of select="ns0:DspSegment8"/>
               </tns:DSP_SEGMENT8>
               <tns:DSP_SEGMENT9/>
               <tns:DSP_SEGMENT10/>
               <tns:DSP_SEGMENT11/>
               <tns:DSP_SEGMENT12/>
               <tns:DSP_SEGMENT13/>
               <tns:DSP_SEGMENT14/>
               <tns:DSP_SEGMENT15/>
               <tns:DSP_SEGMENT16/>
               <tns:DSP_SEGMENT17/>
               <tns:DSP_SEGMENT18/>
               <tns:DSP_SEGMENT19/>
               <tns:DSP_SEGMENT20/>
               <tns:DSP_SEGMENT21/>
               <tns:DSP_SEGMENT22/>
               <tns:DSP_SEGMENT23/>
               <tns:DSP_SEGMENT24/>
               <tns:DSP_SEGMENT25/>
               <tns:DSP_SEGMENT26/>
               <tns:DSP_SEGMENT27/>
               <tns:DSP_SEGMENT28/>
               <tns:DSP_SEGMENT29/>
               <tns:DSP_SEGMENT30/>
               <tns:TRANSACTION_ACTION_NAME/>
               <tns:TRANSACTION_MODE>
                  <xsl:value-of select="ns0:TransactionMode"/>
               </tns:TRANSACTION_MODE>
               <tns:LOCK_FLAG/>
               <tns:TRANSACTION_REFERENCE>
                  <xsl:value-of select="ns0:Attribute1"/>
               </tns:TRANSACTION_REFERENCE>
               <tns:REASON_NAME/>
               <tns:CURRENCY_NAME/>
               <tns:CURRENCY_CODE/>
               <tns:CURRENCY_CONVERSION_TYPE/>
               <tns:CURRENCY_CONVERSION_RATE/>
               <tns:CURRENCY_CONVERSION_DATE/>
               <tns:TRANSACTION_COST/>
               <tns:TRANSFER_COST/>
               <tns:NEW_AVERAGE_COST/>
               <tns:VALUE_CHANGE/>
               <tns:PERCENTAGE_CHANGE/>
               <tns:DST_SEGMENT1/>
               <tns:DST_SEGMENT2/>
               <tns:DST_SEGMENT3/>
               <tns:DST_SEGMENT4/>
               <tns:DST_SEGMENT5/>
               <tns:DST_SEGMENT6/>
               <tns:DST_SEGMENT7/>
               <tns:DST_SEGMENT8/>
               <tns:DST_SEGMENT9/>
               <tns:DST_SEGMENT10/>
               <tns:DST_SEGMENT11/>
               <tns:DST_SEGMENT12/>
               <tns:DST_SEGMENT13/>
               <tns:DST_SEGMENT14/>
               <tns:DST_SEGMENT15/>
               <tns:DST_SEGMENT16/>
               <tns:DST_SEGMENT17/>
               <tns:DST_SEGMENT18/>
               <tns:DST_SEGMENT19/>
               <tns:DST_SEGMENT20/>
               <tns:DST_SEGMENT21/>
               <tns:DST_SEGMENT22/>
               <tns:DST_SEGMENT23/>
               <tns:DST_SEGMENT24/>
               <tns:DST_SEGMENT25/>
               <tns:DST_SEGMENT26/>
               <tns:DST_SEGMENT27/>
               <tns:DST_SEGMENT28/>
               <tns:DST_SEGMENT29/>
               <tns:DST_SEGMENT30/>
               <tns:LOCATION_TYPE/>
               <tns:EMPLOYEE_CODE/>
               <tns:RECEIVING_DOCUMENT/>
               <tns:LINE_ITEM_NUM/>
               <tns:SHIPMENT_NUMBER/>
               <tns:TRANSPORTATION_COST/>
               <tns:CONTAINERS/>
               <tns:WAYBILL_AIRBILL/>
               <tns:EXPECTED_ARRIVAL_DATE/>
               <tns:REQUIRED_FLAG/>
               <tns:SHIPPABLE_FLAG/>
               <tns:SHIPPED_QUANTITY/>
               <tns:VALIDATION_REQUIRED/>
               <tns:NEGATIVE_REQ_FLAG/>
               <tns:OWNING_TP_TYPE/>
               <tns:TRANSFER_OWNING_TP_TYPE/>
               <tns:OWNING_ORGANIZATION_NAME/>
               <tns:XFR_OWNING_ORGANIZATION_NAME/>
               <tns:TRANSFER_PERCENTAGE/>
               <tns:PLANNING_TP_TYPE/>
               <tns:TRANSFER_PLANNING_TP_TYPE/>
               <tns:ROUTING_REVISION/>
               <tns:ROUTING_REVISION_DATE/>
               <tns:ALTERNATE_BOM_DESIGNATOR/>
               <tns:ALTERNATE_ROUTING_DESIGNATOR/>
               <tns:ORGANIZATION_TYPE/>
               <tns:USSGL_TRANSACTION_CODE/>
               <tns:WIP_ENTITY_TYPE/>
               <tns:SCHEDULE_UPDATE_CODE/>
               <tns:SETUP_TEARDOWN_CODE/>
               <tns:PRIMARY_SWITCH/>
               <tns:MRP_CODE/>
               <tns:OPERATION_SEQ_NUM/>
               <tns:WIP_SUPPLY_TYPE/>
               <tns:RELIEVE_RESERVATIONS_FLAG/>
               <tns:RELIEVE_HIGH_LEVEL_RSV_FLAG/>
               <tns:TRANSFER_PRICE/>
               <tns:BUILD_BREAK_TO_UOM/>
               <tns:BUILD_BREAK_TO_UNIT_OF_MEASURE/>
               <tns:ATTRIBUTE_CATEGORY/>
               <tns:ATTRIBUTE1>
                  <xsl:value-of select="ns0:Attribute1"/>
               </tns:ATTRIBUTE1>
               <tns:ATTRIBUTE2>
                  <xsl:value-of select="ns0:Attribute2"/>
               </tns:ATTRIBUTE2>
               <tns:ATTRIBUTE3>
                  <xsl:value-of select="ns0:Attribute3"/>
               </tns:ATTRIBUTE3>
               <tns:ATTRIBUTE4>
                  <xsl:value-of select="ns0:Attribute4"/>
               </tns:ATTRIBUTE4>
               <tns:ATTRIBUTE5>
                  <xsl:value-of select="ns0:Attribute5"/>
               </tns:ATTRIBUTE5>
               <tns:ATTRIBUTE6>
                  <xsl:value-of select="ns0:Attribute6"/>
               </tns:ATTRIBUTE6>
               <tns:ATTRIBUTE7>
                  <xsl:value-of select="ns0:Attribute7"/>
               </tns:ATTRIBUTE7>
               <tns:ATTRIBUTE8>
                  <xsl:value-of select="ns0:Attribute8"/>
               </tns:ATTRIBUTE8>
               <tns:ATTRIBUTE9>
                  <xsl:value-of select="ns0:Attribute9"/>
               </tns:ATTRIBUTE9>
               <tns:ATTRIBUTE10>
                  <xsl:value-of select="ns0:Attribute10"/>
               </tns:ATTRIBUTE10>
               <tns:ATTRIBUTE11/>
               <tns:ATTRIBUTE12/>
               <tns:ATTRIBUTE13/>
               <tns:ATTRIBUTE14/>
               <tns:ATTRIBUTE15/>
               <tns:ATTRIBUTE16/>
               <tns:ATTRIBUTE17/>
               <tns:ATTRIBUTE18/>
               <tns:ATTRIBUTE19/>
               <tns:ATTRIBUTE20/>
               <tns:ATTRIBUTE_NUMBER1/>
               <tns:ATTRIBUTE_NUMBER2/>
               <tns:ATTRIBUTE_NUMBER3/>
               <tns:ATTRIBUTE_NUMBER4/>
               <tns:ATTRIBUTE_NUMBER5/>
               <tns:ATTRIBUTE_NUMBER6/>
               <tns:ATTRIBUTE_NUMBER7/>
               <tns:ATTRIBUTE_NUMBER8/>
               <tns:ATTRIBUTE_NUMBER9/>
               <tns:ATTRIBUTE_NUMBER10/>
               <tns:ATTRIBUTE_DATE1/>
               <tns:ATTRIBUTE_DATE2/>
               <tns:ATTRIBUTE_DATE3/>
               <tns:ATTRIBUTE_DATE4/>
               <tns:ATTRIBUTE_DATE5/>
               <tns:ATTRIBUTE_TIMESTAMP1/>
               <tns:ATTRIBUTE_TIMESTAMP2/>
               <tns:ATTRIBUTE_TIMESTAMP3/>
               <tns:ATTRIBUTE_TIMESTAMP4/>
               <tns:ATTRIBUTE_TIMESTAMP5/>
               <tns:TRANSACTION_COST_IDENTIFIER/>
               <tns:DEFAULT_TAXATION_COUNTRY/>
               <tns:DOCUMENT_SUB_TYPE/>
               <tns:TRX_BUSINESS_CATEGORY/>
               <tns:USER_DEFINED_FISC_CLASS/>
               <tns:TAX_INVOICE_NUMBER/>
               <tns:TAX_INVOICE_DATE/>
               <tns:PRODUCT_CATEGORY/>
               <tns:PRODUCT_TYPE/>
               <tns:ASSESSABLE_VALUE/>
               <tns:TAX_CLASSIFICATION_CODE/>
               <tns:EXEMPT_CERTIFICATE_NUMBER/>
               <tns:EXEMPT_REASON_CODE/>
               <tns:INTENDED_USE/>
               <tns:FIRST_PTY_NUMBER/>
               <tns:THIRD_PTY_NUMBER/>
               <tns:FINAL_DISCHARGE_LOC_CODE/>
               <tns:CATEGORY_NAME/>
               <tns:OWNING_ORGANIZATION_ID/>
               <tns:XFR_OWNING_ORGANIZATION_ID/>
               <tns:PRC_BU_NAME/>
               <tns:VENDOR_NAME/>
               <tns:VENDOR_NUMBER/>
               <tns:CONSIGNMENT_AGREEMENT_NUM/>
               <tns:END>
                  <xsl:value-of select="dvm:lookupValue (&quot;Dvms/InventoryBizProperties.dvm&quot;, &quot;CODE&quot;, &quot;Y&quot;, &quot;VALUE&quot;, Y )"/>
               </tns:END>
            </tns:nxsdTransactionInventoryType>
         </xsl:for-each>
      </tns:nxsdTransactionInventory>
   </xsl:template>
</xsl:stylesheet>
