<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://soa.estrellaroja.com.mx/CFDITec" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns4="http://soa.estrellaroja.com.mx/CFDI"
                xmlns:ns5="http://soa.estrellaroja.com.mx/Reports/XXER_AP_INVOICE_VALIDATION_AUTOMATICA"
                xmlns:ns6="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://soa.estrellaroja.com.mx/CFDITec/types"
                xmlns:ns3="http://soa.estrellaroja.com.mx/Reports/XXER_ValidationComplement"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns7="http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI"
                xmlns:ns8="http://www.sat.gob.mx/sitio_internet/cfd/catalogos"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns9="http://soa.estrellaroja.com.mx/AuditControlTec/types"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/CFDITec/CFDITec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetComplementCFDIRs" namespace="http://soa.estrellaroja.com.mx/CFDITec"/>
         </oracle-xsl-mapper:source>
                  <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/CFDITec/CFDITec.xsd"/>
            <oracle-xsl-mapper:rootElement name="MergeComplementsAPRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
            <oracle-xsl-mapper:param name="MergeComplementsAPRq.MergeComplementsAPRq"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/OSB/AuditControlTec/AuditControlTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="MergeComplementsAPRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED FEB 01 10:25:06 CST 2023].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
      <xsl:param name="MergeComplementsAPRq.MergeComplementsAPRq"/>
   <xsl:template match="/">
      <tns:MergeComplementsAPRq>
         <tns:Complements>
            <tns:Complement>
               <tns:paymentId>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:ID_PAGO"/>
               </tns:paymentId>
               <tns:paymentNumber>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:NUMERO_PAGO"/>
               </tns:paymentNumber>
               <tns:nombreEmisor>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:NOMBRE_PROVEEDOR"/>
               </tns:nombreEmisor>
               <tns:emisorRfc>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:RFC_PROVEEDOR"/>
               </tns:emisorRfc>
               <tns:nombrePreceptor>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:NOMBRE_EMPRESA"/>
               </tns:nombrePreceptor>
               <tns:receptorRfc>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:RFC_EMPRESA"/>
               </tns:receptorRfc>
               <tns:paymentAmount>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:MONTO_PAGO"/>
               </tns:paymentAmount>
               <tns:paymentCurrency>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:MONEDA_PAGO"/>
               </tns:paymentCurrency>
               <tns:paymentDate>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:FECHA_PAGO"/>
               </tns:paymentDate>
               <tns:statusDesc>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:STATUS"/>
               </tns:statusDesc>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Folio">
                  <tns:folioXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Folio"/>
                  </tns:folioXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Serie">
                  <tns:serieXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Serie"/>
                  </tns:serieXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Emisor/@Nombre">
                  <tns:nombreEmisorXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Emisor/@Nombre"/>
                  </tns:nombreEmisorXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Emisor/@Rfc">
                  <tns:emisorRfcXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Emisor/@Rfc"/>
                  </tns:emisorRfcXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Receptor/@Nombre">
                  <tns:nombreReceptorXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Receptor/@Nombre"/>
                  </tns:nombreReceptorXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Receptor/@Rfc">
                  <tns:receptorRfcXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Receptor/@Rfc"/>
                  </tns:receptorRfcXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Total">
                  <tns:totalXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Total"/>
                  </tns:totalXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@SubTotal">
                  <tns:subtotalXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@SubTotal"/>
                  </tns:subtotalXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@TipoCambio">
                  <tns:tipoCambioXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@TipoCambio"/>
                  </tns:tipoCambioXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Moneda">
                  <tns:monedaXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Moneda"/>
                  </tns:monedaXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Receptor/@UsoCFDI">
                  <tns:usoCfdiXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Receptor/@UsoCFDI"/>
                  </tns:usoCfdiXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@FormaPago">
                  <tns:formaPagoXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@FormaPago"/>
                  </tns:formaPagoXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@TipoDeComprobante">
                  <tns:tipoComprobanteXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@TipoDeComprobante"/>
                  </tns:tipoComprobanteXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Conceptos/ns4:Concepto[1]/@Descripcion">
                  <tns:descripcionXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Conceptos/ns4:Concepto[1]/@Descripcion"/>
                  </tns:descripcionXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Complemento/ns4:TimbreFiscalDigital/@UUID">
                  <tns:uuidXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Complemento/ns4:TimbreFiscalDigital/@UUID"/>
                  </tns:uuidXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Fecha">
                  <tns:fechaXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Fecha"/>
                  </tns:fechaXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Complemento/ns4:TimbreFiscalDigital/@FechaTimbrado">
                  <tns:fechaTimbradoXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Complemento/ns4:TimbreFiscalDigital/@FechaTimbrado"/>
                  </tns:fechaTimbradoXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Conceptos/ns4:Concepto[1]/@ObjetoImp">
                  <tns:objetoImpXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Conceptos/ns4:Concepto[1]/@ObjetoImp"/>
                  </tns:objetoImpXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Receptor/@RegimenFiscalReceptor">
                  <tns:receptorRegimenXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Receptor/@RegimenFiscalReceptor"/>
                  </tns:receptorRegimenXml>
               </xsl:if>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Emisor/@RegimenFiscal">
                  <tns:emisorRegimenXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/ns4:Emisor/@RegimenFiscal"/>
                  </tns:emisorRegimenXml>
               </xsl:if>
               <tns:receptorRegimen>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:REGIMEN_EMPRESA"/>
               </tns:receptorRegimen>
               <xsl:if test="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Version">
                  <tns:versionXml>
                     <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns0:Comprobante/@Version"/>
                  </tns:versionXml>
               </xsl:if>
               <tns:paymentStatus>
                  <xsl:value-of select="/ns0:GetComplementCFDIRs/ns0:COMPLEMENT/ns3:DATA_DS/ns3:G_1/ns3:PAYMENT_STATUS"/>
               </tns:paymentStatus>
               <tns:ComplementsLinesAp>
                  <xsl:for-each select="$MergeComplementsAPRq.MergeComplementsAPRq/tns:MergeComplementsAPRq/tns:Complements/tns:Complement/tns:ComplementsLinesAp/tns:XxerComplementsLinesApTbl">
                        <tns:XxerComplementsLinesApTbl>
                           <tns:drId>
                              <xsl:value-of select="tns:drId"/>
                           </tns:drId>
                           <xsl:if test="tns:invoiceId">
                              <tns:invoiceId>
                                 <xsl:if test="tns:invoiceId/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:invoiceId/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:invoiceId"/>
                              </tns:invoiceId>
                           </xsl:if>
                           <xsl:if test="tns:status">
                              <tns:status>
                                 <xsl:if test="tns:status/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:status/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:status"/>
                              </tns:status>
                           </xsl:if>
                           <xsl:if test="tns:statusDesc">
                              <tns:statusDesc>
                                 <xsl:if test="tns:statusDesc/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:statusDesc/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:statusDesc"/>
                              </tns:statusDesc>
                           </xsl:if>
                           <xsl:if test="tns:folioDrXml">
                              <tns:folioDrXml>
                                 <xsl:if test="tns:folioDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:folioDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:folioDrXml"/>
                              </tns:folioDrXml>
                           </xsl:if>
                           <xsl:if test="tns:serieDrXml">
                              <tns:serieDrXml>
                                 <xsl:if test="tns:serieDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:serieDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:serieDrXml"/>
                              </tns:serieDrXml>
                           </xsl:if>
                           <xsl:if test="tns:uuidDrXml">
                              <tns:uuidDrXml>
                                 <xsl:if test="tns:uuidDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:uuidDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:uuidDrXml"/>
                              </tns:uuidDrXml>
                           </xsl:if>
                           <xsl:if test="tns:impSaldoAntDrXml">
                              <tns:impSaldoAntDrXml>
                                 <xsl:if test="tns:impSaldoAntDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:impSaldoAntDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:impSaldoAntDrXml"/>
                              </tns:impSaldoAntDrXml>
                           </xsl:if>
                           <xsl:if test="tns:impPagoDrXml">
                              <tns:impPagoDrXml>
                                 <xsl:if test="tns:impPagoDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:impPagoDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:impPagoDrXml"/>
                              </tns:impPagoDrXml>
                           </xsl:if>
                           <xsl:if test="tns:impSaldoInsolutoDrXml">
                              <tns:impSaldoInsolutoDrXml>
                                 <xsl:if test="tns:impSaldoInsolutoDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:impSaldoInsolutoDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:impSaldoInsolutoDrXml"/>
                              </tns:impSaldoInsolutoDrXml>
                           </xsl:if>
                           <xsl:if test="tns:monedaDrXml">
                              <tns:monedaDrXml>
                                 <xsl:if test="tns:monedaDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:monedaDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:monedaDrXml"/>
                              </tns:monedaDrXml>
                           </xsl:if>
                           <xsl:if test="tns:metodoPagoDrXml">
                              <tns:metodoPagoDrXml>
                                 <xsl:if test="tns:metodoPagoDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:metodoPagoDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:metodoPagoDrXml"/>
                              </tns:metodoPagoDrXml>
                           </xsl:if>
                           <xsl:if test="tns:tipoCambioDrXml">
                              <tns:tipoCambioDrXml>
                                 <xsl:if test="tns:tipoCambioDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:tipoCambioDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:tipoCambioDrXml"/>
                              </tns:tipoCambioDrXml>
                           </xsl:if>
                           <xsl:if test="tns:formaPagoDrXml">
                              <tns:formaPagoDrXml>
                                 <xsl:if test="tns:formaPagoDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:formaPagoDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:formaPagoDrXml"/>
                              </tns:formaPagoDrXml>
                           </xsl:if>
                           <xsl:if test="tns:fechaDrXml">
                              <tns:fechaDrXml>
                                 <xsl:if test="tns:fechaDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:fechaDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:fechaDrXml"/>
                              </tns:fechaDrXml>
                           </xsl:if>
                           <xsl:if test="tns:attribute1">
                              <tns:attribute1>
                                 <xsl:if test="tns:attribute1/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:attribute1/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:attribute1"/>
                              </tns:attribute1>
                           </xsl:if>
                           <xsl:if test="tns:attribute2">
                              <tns:attribute2>
                                 <xsl:if test="tns:attribute2/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:attribute2/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:attribute2"/>
                              </tns:attribute2>
                           </xsl:if>
                           <xsl:if test="tns:attribute3">
                              <tns:attribute3>
                                 <xsl:if test="tns:attribute3/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:attribute3/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:attribute3"/>
                              </tns:attribute3>
                           </xsl:if>
                           <xsl:if test="tns:attribute4">
                              <tns:attribute4>
                                 <xsl:if test="tns:attribute4/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:attribute4/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:attribute4"/>
                              </tns:attribute4>
                           </xsl:if>
                           <xsl:if test="tns:attribute5">
                              <tns:attribute5>
                                 <xsl:if test="tns:attribute5/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:attribute5/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:attribute5"/>
                              </tns:attribute5>
                           </xsl:if>
                           <xsl:if test="tns:createdBy">
                              <tns:createdBy>
                                 <xsl:if test="tns:createdBy/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:createdBy/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:createdBy"/>
                              </tns:createdBy>
                           </xsl:if>
                           <xsl:if test="tns:creationDate">
                              <tns:creationDate>
                                 <xsl:if test="tns:creationDate/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:creationDate/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:creationDate"/>
                              </tns:creationDate>
                           </xsl:if>
                           <xsl:if test="tns:lastUpdatedBy">
                              <tns:lastUpdatedBy>
                                 <xsl:if test="tns:lastUpdatedBy/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:lastUpdatedBy/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:lastUpdatedBy"/>
                              </tns:lastUpdatedBy>
                           </xsl:if>
                           <xsl:if test="tns:lastUpdateDate">
                              <tns:lastUpdateDate>
                                 <xsl:if test="tns:lastUpdateDate/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:lastUpdateDate/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:lastUpdateDate"/>
                              </tns:lastUpdateDate>
                           </xsl:if>
                           <xsl:if test="tns:objectVersionNumber">
                              <tns:objectVersionNumber>
                                 <xsl:if test="tns:objectVersionNumber/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:objectVersionNumber/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:objectVersionNumber"/>
                              </tns:objectVersionNumber>
                           </xsl:if>
                           <xsl:if test="tns:objetoImpDrXml">
                              <tns:objetoImpDrXml>
                                 <xsl:if test="tns:objetoImpDrXml/@xsi:nil">
                                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                       <xsl:value-of select="tns:objetoImpDrXml/@xsi:nil"/>
                                    </xsl:attribute>
                                 </xsl:if>
                                 <xsl:value-of select="tns:objetoImpDrXml"/>
                              </tns:objetoImpDrXml>
                           </xsl:if>
                        </tns:XxerComplementsLinesApTbl>
                  </xsl:for-each>
               </tns:ComplementsLinesAp>
            </tns:Complement>
         </tns:Complements>
      </tns:MergeComplementsAPRq>
   </xsl:template>
</xsl:stylesheet>
