<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbStatusLoadInvoices" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/InvoicesBiz/InvoicesBiz/dbStatusLoadInvoices"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelStatusLoadInvoices"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension"
                xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns5="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/dbStatusLoadInvoices.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbStatusLoadInvoices"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelStatusLoadInvoices.wsdl"/>
            <oracle-xsl-mapper:rootElement name="StatusLoadInvoicesRs" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED JAN 17 11:41:22 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:StatusLoadInvoicesRs>
         <tns:Return>
            <tns:TotalSucceeded>
               <xsl:value-of select="/ns0:OutputParameters/ns0:P_TOTAL_SUCCESSFUL"/>
            </tns:TotalSucceeded>
            <tns:TotalErrors>
               <xsl:value-of select="/ns0:OutputParameters/ns0:P_TOTAL_ERRORS"/>
            </tns:TotalErrors>
            <tns:TotalProcessed>
               <xsl:value-of select="/ns0:OutputParameters/ns0:P_TOTAL_PROCESSED"/>
            </tns:TotalProcessed>
            <tns:ErrorsDetails>
               <xsl:for-each select="/ns0:OutputParameters/ns0:P_ERROR_MESSAGES_INV/ns0:P_ERROR_MESSAGES_INV_ITEM">
                  <tns:ErrorDetail>
                     <tns:DataValue>
                        <xsl:value-of select="ns0:DATA_VALUE"/>
                     </tns:DataValue>
                     <tns:ErrorMessage>
                        <xsl:value-of select="ns0:MESSAGE"/>
                     </tns:ErrorMessage>
                  </tns:ErrorDetail>
               </xsl:for-each>
            </tns:ErrorsDetails>
         </tns:Return>
      </tns:StatusLoadInvoicesRs>
   </xsl:template>
</xsl:stylesheet>
