<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="2.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz/StructursInvoicesBiz" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelBuildInvoicesZip"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns5="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns6="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesBiz"
                xmlns:ns4="http://soa.estrellaroja.com.mx/FinancialsTec"
                xmlns:fn="http://www.w3.org/2005/xpath-functions"
                xmlns:ns7="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelBuildInvoicesZip.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ListBUsAndOrgId" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz/StructursInvoicesBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelBuildInvoicesZip.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ListBUsAndOrgId" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz/StructursInvoicesBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE MAR 13 07:35:59 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:ListBUsAndOrgId>
         <xsl:for-each-group select="/ns0:ListBUsAndOrgId/ns0:return" group-by="ns0:OrgId">
            <ns0:return>
               <ns0:BuName>
                  <xsl:value-of select="current-group()[1]/ns0:BuName"/>
               </ns0:BuName>
               <ns0:OrgId>
                  <xsl:value-of select="current-grouping-key()"/>
               </ns0:OrgId>
            </ns0:return>
         </xsl:for-each-group>
      </ns0:ListBUsAndOrgId>
   </xsl:template>
</xsl:stylesheet>
