<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns1="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://www.sat.gob.mx/cfd/3" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns5="http://www.sat.gob.mx/Pagos" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:imp1="http://platform.integration.oracle/blocks/adapter/fw/metadata/umsReceiveEmail" xmlns:ns4="http://www.sat.gob.mx/TimbreFiscalDigital" xmlns:ns7="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns3="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:ns8="http://soa.estrellaroja.com.mx/SOAUtilitiesTec/types" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/ums/MessageBiz/MessageBiz/umsReceiveEmail" xmlns:ns6="http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns9="http://soa.estrellaroja.com.mx/AuditControlTec/types" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/umsReceiveEmail.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Comprobante" namespace="http://www.sat.gob.mx/cfd/3"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SOAUtilitiesTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DecodeRs" namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"/>
            <oracle-xsl-mapper:param name="decoderOutput.DecodeRs"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/AuditControlTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MergeIncPaymentComplementRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:substitutions>
         <oracle-xsl-mapper:sourceSubst substPath="/ns0:Comprobante/ns0:Complemento/any" substElem="ns5:Pagos"/>
         <oracle-xsl-mapper:sourceSubst substPath="/ns0:Comprobante/ns0:Complemento/any" substElem="ns4:TimbreFiscalDigital"/>
      </oracle-xsl-mapper:substitutions>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI DEC 15 11:22:26 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="decoderOutput.DecodeRs"/>
   <xsl:variable name="currentUser" select="dvm:lookupValue (&quot;DVM/Configuration.dvm&quot;, &quot;PropertyName&quot;, &quot;INTEGRATION_NAME&quot;, &quot;PropertyValue&quot;, &quot;&quot; )"/>
   <xsl:template match="/">
      <tns:MergeIncPaymentComplementRq>
         <tns:CreatedBy>
            <xsl:value-of select="$currentUser"/>
         </tns:CreatedBy>
         <tns:CreationDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
         </tns:CreationDate>
         <tns:LastUpdatedBy>
            <xsl:value-of select="$currentUser"/>
         </tns:LastUpdatedBy>
         <tns:LastUpdateDate>
            <xsl:value-of select="xp20:current-dateTime ( )"/>
         </tns:LastUpdateDate>
         <tns:ObjectVersionNumber>
            <xsl:value-of select="&quot;1&quot;"/>
         </tns:ObjectVersionNumber>
         <tns:RfcIssuer>
            <xsl:value-of select="/ns0:Comprobante/ns0:Emisor/@Rfc"/>
         </tns:RfcIssuer>
         <tns:RfcReceiver>
            <xsl:value-of select="/ns0:Comprobante/ns0:Receptor/@Rfc"/>
         </tns:RfcReceiver>
         <tns:TotalAmount>
            <xsl:value-of select="/ns0:Comprobante/ns0:Conceptos/ns0:Concepto[1]/@Importe"/>
         </tns:TotalAmount>
         <tns:Uuid>
            <xsl:value-of select="/ns0:Comprobante/ns0:Complemento/ns4:TimbreFiscalDigital/@UUID"/>
         </tns:Uuid>
         <tns:UuidDate>
            <xsl:value-of select="/ns0:Comprobante/ns0:Complemento/ns4:TimbreFiscalDigital/@FechaTimbrado"/>
         </tns:UuidDate>
         <tns:Status>
            <xsl:value-of select="&quot;PENDING&quot;"/>
         </tns:Status>
         <tns:Attatchment>
            <xsl:value-of select="normalize-space ($decoderOutput.DecodeRs/ns1:DecodeRs/ns1:Return/ns1:xmlOut )"/>
         </tns:Attatchment>
         <xsl:for-each select="/ns0:Comprobante/ns0:Complemento/ns5:Pagos/ns5:Pago"/>
         <xsl:for-each select="/ns0:Comprobante/ns0:Complemento/ns5:Pagos/ns5:Pago/ns5:DoctoRelacionado">
            <tns:Invoice>
               <tns:CreatedBy>
                  <xsl:value-of select="$currentUser"/>
               </tns:CreatedBy>
               <tns:CreationDate>
                  <xsl:value-of select="xp20:current-dateTime ( )"/>
               </tns:CreationDate>
               <tns:LastUpdatedBy>
                  <xsl:value-of select="$currentUser"/>
               </tns:LastUpdatedBy>
               <tns:LastUpdateDate>
                  <xsl:value-of select="xp20:current-dateTime ( )"/>
               </tns:LastUpdateDate>
               <tns:ObjectVersionNumber>
                  <xsl:value-of select="&quot;1&quot;"/>
               </tns:ObjectVersionNumber>
               <tns:Uuid>
                  <xsl:value-of select="@IdDocumento"/>
               </tns:Uuid>
               <tns:InstallmentNumber>
                  <xsl:value-of select="@NumParcialidad"/>
               </tns:InstallmentNumber>
            </tns:Invoice>
         </xsl:for-each>
      </tns:MergeIncPaymentComplementRq>
   </xsl:template>
</xsl:stylesheet>