<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StatementsBankBBVA" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/SFTPEstrellaRojaEnt/SFTPEstrellaRojaEnt/ftpReadFileStatementsBankBBVA"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"
                xmlns:ns3="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails"
                xmlns:client="http://xmlns.oracle.com/SFTPEstrellaRojaEnt/SFTPEstrellaRojaEnt/bpelManagementsStatmentsBankBBVA"
                xmlns:ns4="http://soa.estrellaroja.com.mx/MessageBiz"
                xmlns:ns6="http://soa.estrellaroja.com.mx/ERPManagementOfLoadImportBiz"
                xmlns:ns5="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelManagementsStatmentsBankBBVA.wsdl"/>
            <oracle-xsl-mapper:rootElement name="AccountStatements" namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StatementsBankBBVA"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelManagementsStatmentsBankBBVA.wsdl"/>
            <oracle-xsl-mapper:rootElement name="AccountStatements" namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StatementsBankBBVA"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON JAN 15 22:02:43 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:AccountStatements>
         <xsl:for-each select="/ns0:AccountStatements/ns0:Statements">
            <ns0:Statements>
               <ns0:Cuenta>
                  <xsl:value-of select="ns0:Cuenta"/>
               </ns0:Cuenta>
               <ns0:FechaValor>
                  <xsl:value-of select="xp20:format-dateTime (ns0:FechaValor, &quot;[M01]/[D01]/[Y0001]&quot; )"/>
               </ns0:FechaValor>
               <ns0:FolioBanco>
                  <xsl:value-of select="ns0:FolioBanco"/>
               </ns0:FolioBanco>
               <ns0:Transaccion>
                  <xsl:value-of select="ns0:Transaccion"/>
               </ns0:Transaccion>
               <ns0:TipoDeMovimiento>
                  <xsl:value-of select="ns0:TipoDeMovimiento"/>
               </ns0:TipoDeMovimiento>
               <ns0:Importe>
                  <xsl:value-of select="ns0:Importe"/>
               </ns0:Importe>
               <ns0:Moneda>
                  <xsl:value-of select="ns0:Moneda"/>
               </ns0:Moneda>
               <ns0:FolioAceptacion>
                  <xsl:value-of select="ns0:FolioAceptacion"/>
               </ns0:FolioAceptacion>
               <ns0:Referencia>
                  <xsl:value-of select="ns0:Referencia"/>
               </ns0:Referencia>
               <ns0:Contrato>
                  <xsl:value-of select="ns0:Contrato"/>
               </ns0:Contrato>
               <ns0:FechaOperacion>
                  <xsl:value-of select="ns0:FechaOperacion"/>
               </ns0:FechaOperacion>
               <ns0:NombreContratoCW>
                  <xsl:value-of select="ns0:NombreContratoCW"/>
               </ns0:NombreContratoCW>
               <ns0:CodigoTransaccion>
                  <xsl:value-of select="concat (&quot;V0&quot;, ns0:CodigoTransaccion )"/>
               </ns0:CodigoTransaccion>
               <ns0:TipoOperacion>
                  <xsl:value-of select="ns0:TipoOperacion"/>
               </ns0:TipoOperacion>
               <ns0:Plaza>
                  <xsl:value-of select="ns0:Plaza"/>
               </ns0:Plaza>
            </ns0:Statements>
         </xsl:for-each>
      </ns0:AccountStatements>
   </xsl:template>
</xsl:stylesheet>
