<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://soa.estrellaroja.com.mx/BankCodes" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/ftpServiceReaderFileSantander" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns4="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/ftpReadFileSant"
                xmlns:ns1="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://soa.estrellaroja.mx/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankSantander"
                xmlns:ns2="http://soa.estrellaroja.com.mx/StructureCodeBank"
                xmlns:ns5="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt"
                xmlns:ns6="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails"
                xmlns:ns8="http://soa.estrellaroja.com.mx/ERPManagementOfLoadImportBiz"
                xmlns:ns7="http://soa.estrellaroja.com.mx/MessageBiz">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelManagementsStatementsBankSantander.wsdl"/>
            <oracle-xsl-mapper:rootElement name="estadoCta" namespace="http://soa.estrellaroja.com.mx/ftpServiceReaderFileSantander"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelManagementsStatementsBankSantander.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CodigoList" namespace="http://soa.estrellaroja.com.mx/BankCodes"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI JAN 05 10:24:28 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CodigoList>
         <xsl:for-each select="/ns0:estadoCta/ns0:choice">
            <tns:Codigo>
               <xsl:value-of select="concat('S',substring (ns0:C1, 33, 4 ))"/>
            </tns:Codigo>
         </xsl:for-each>
      </tns:CodigoList>
   </xsl:template>
</xsl:stylesheet>
