<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/ftpServiceReaderFileSantander" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/ftpReadFileSant" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://soa.estrellaroja.mx/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankSantander"
                xmlns:ns2="http://soa.estrellaroja.com.mx/StructureCodeBank"
                xmlns:ns4="http://soa.estrellaroja.com.mx/BankCodes"
                xmlns:ns5="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt"
                xmlns:ns6="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"
                xmlns:ns7="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails"
                xmlns:ns8="http://soa.estrellaroja.com.mx/MessageBiz"
                xmlns:ns9="http://soa.estrellaroja.com.mx/ERPManagementOfLoadImportBiz">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelManagementsStatementsBankSantander.wsdl"/>
            <oracle-xsl-mapper:rootElement name="estadoCta" namespace="http://soa.estrellaroja.com.mx/ftpServiceReaderFileSantander"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelManagementsStatementsBankSantander.wsdl"/>
            <oracle-xsl-mapper:rootElement name="AccountStatementSantander" namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED JAN 03 13:21:15 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:AccountStatementSantander>
         <xsl:for-each select="/ns0:estadoCta/ns0:choice">
            <tns:Transactions>
               <tns:AccountNumber>
                  
                  <xsl:value-of select="oraext:right-trim (oraext:right-trim (substring (ns0:C1, 1, 16 ) ) )"/>
               </tns:AccountNumber>
               <tns:StatementDate>
                  <xsl:value-of select="concat (substring (substring (ns0:C1, 17, 8 ), 1, 2 ), &quot;/&quot;, substring (substring (ns0:C1, 17, 8 ), 3, 2 ), &quot;/&quot;, substring (substring (ns0:C1, 17, 8 ), 5, 4 ) )"/>
               </tns:StatementDate>
               <tns:HourTransaction>
                  <xsl:value-of select="substring (ns0:C1, 25, 4 )"/>
               </tns:HourTransaction>
               <tns:BranchNameBank>
                  <xsl:value-of select="substring (ns0:C1, 29, 4 )"/>
               </tns:BranchNameBank>
               <tns:BankCode>
                  <xsl:value-of select="concat (&quot;S&quot;, substring (ns0:C1, 33, 4 ) )"/>
               </tns:BankCode>
               <tns:Description>
                  <xsl:value-of select="substring (ns0:C1, 37, 40 )"/>
               </tns:Description>
               <tns:SignType>
                  <xsl:value-of select="substring (ns0:C1, 77, 1 )"/>
               </tns:SignType>
               <tns:Amount>
                  <xsl:value-of select="concat (substring (substring (ns0:C1, 78, 14 ), 1, 12 ), &quot;.&quot;, substring (substring (ns0:C1, 78, 14 ), 13, 14 ) )"/>
               </tns:Amount>
               <tns:Balance>
               <xsl:value-of select="concat (substring (substring (ns0:C1,  92, 14 ), 1, 12 ), &quot;.&quot;, substring (substring (ns0:C1,  92, 14 ), 13, 14 ) )"/>
               </tns:Balance>
               <tns:Reference>
                  <!--xsl:value-of select="substring (ns0:C1, 106, 8 )"/-->
                  <!--xsl:value-of select="substring(ns0:C1,114,15)"/-->
                  <xsl:value-of select="substring (ns0:C1, 114, 30 )"/>
               </tns:Reference>
               <tns:Concept>
                  <xsl:value-of select="substring (ns0:C1, 114, 40 )"/>
               </tns:Concept>
               <tns:Additional/>
            </tns:Transactions>
         </xsl:for-each>
      </tns:AccountStatementSantander>
   </xsl:template>
</xsl:stylesheet>
