<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StatementsBankBanamex"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/ftp/SFTPEstrellaRojaEnt/SFTPEstrellaRojaEnt/ftpReadFileStatementBankBanamex"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/SFTPEstrellaRojaEnt/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankBanamex"
                xmlns:ns5="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"
                xmlns:ns4="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails"
                xmlns:ns3="http://soa.estrellaroja.com.mx/StructureCodeBank"
                xmlns:ns6="http://soa.estrellaroja.com.mx/MessageBiz"
                xmlns:ns7="http://soa.estrellaroja.com.mx/ERPManagementOfLoadImportBiz">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
                   <oracle-xsl-mapper:schema location="../WSDLs/bpelManagementsStatementsBankBanamex.wsdl"/>
        <oracle-xsl-mapper:rootElement name="StatementsBankBanamex"
                                       namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StatementsBankBanamex"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../Schemas/SFTPEstrellaRojaEnt.xsd"/>
        <oracle-xsl-mapper:rootElement name="AccountStatementBanamexRq"
                                       namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU JAN 18 09:17:22 CST 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:AccountStatementBanamexRq>
      <tns:RequestDate>
        <xsl:value-of select="concat (substring (substring (/ns0:StatementsBankBanamex/ns0:StatementLine[1.0]/., 1, 6 ), 1, 2 ), &quot;/&quot;, substring (substring (/ns0:StatementsBankBanamex/ns0:StatementLine[1.0]/., 1, 6 ), 3, 2 ), &quot;/&quot;, substring (substring (/ns0:StatementsBankBanamex/ns0:StatementLine[1.0]/., 1, 6 ), 5, 4 ) )"/>
      </tns:RequestDate>
      <tns:RequestAccountNumber>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[2]/self::node(), 1, 4 )"/>
      </tns:RequestAccountNumber>
      <tns:TransactionsQuantity>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[3]/self::node(), 1, 4 )"/>
      </tns:TransactionsQuantity>
      <tns:BranchNumber>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[4]/self::node(), 1, 4 )"/>
      </tns:BranchNumber>
      <tns:BankAccountNumber>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[4]/self::node(), 5, string-length (/ns0:StatementsBankBanamex/ns0:StatementLine[4]/. ) )"/>
      </tns:BankAccountNumber>
      <tns:TypeSignFirst>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[5]/self::node(), 1, 1 )"/>
      </tns:TypeSignFirst>
      <tns:StartBalance>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[5]/self::node(), 2, 17 )"/>
      </tns:StartBalance>
      <tns:QuantityCashOutOfMoney>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[5], 19, 5 )"/>
      </tns:QuantityCashOutOfMoney>
      <tns:AmountCashOutOfMoney>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[5]/self::node(), 24, 17 )"/>
      </tns:AmountCashOutOfMoney>
      <tns:QuantityChargerOfMoney>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[5]/self::node(), 41, 5 )"/>
      </tns:QuantityChargerOfMoney>
      <tns:TotalAmount>
        <xsl:value-of select="concat(substring (substring (/ns0:StatementsBankBanamex/ns0:StatementLine[5]/self::node(), 46, 17 ),1,15),&quot;.&quot;,substring (substring (/ns0:StatementsBankBanamex/ns0:StatementLine[5]/self::node(), 46, 17 ),16,2))"/>
      </tns:TotalAmount>
      <tns:TypeSignSecond>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[5]/self::node(), 63, 1 )"/>
      </tns:TypeSignSecond>
      <tns:FinalBalance>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[5]/self::node(), 64, 79 )"/>
      </tns:FinalBalance>
      <tns:ConstantValueN>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[6]/self::node(), 1, 1 )"/>
      </tns:ConstantValueN>
      <tns:AccountName>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[6]/self::node(), 2, 40 )"/>
      </tns:AccountName>
      <tns:BranchName>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[6]/self::node(), 42, 4 )"/>
      </tns:BranchName>
      <tns:AccountNumber>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[6]/self::node(), 46, 61 )"/>
      </tns:AccountNumber>
      <tns:ConstantValueF>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[7]/self::node(), 1, 1 )"/>
      </tns:ConstantValueF>
      <tns:ConstantType>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[7]/self::node(), 2, 1 )"/>
      </tns:ConstantType>
      <tns:FinalBalanceAccount>
        <xsl:value-of select="substring (/ns0:StatementsBankBanamex/ns0:StatementLine[7]/self::node(), 3, 19 )"/>
      </tns:FinalBalanceAccount>
      <tns:Lines>
        <xsl:for-each select="/ns0:StatementsBankBanamex/ns0:StatementLine">
          <xsl:if test="position ( ) > 7">
            <tns:Line>
              <tns:TypeTransaction>
                <xsl:value-of select="substring (., 1, 1 )"/>
              </tns:TypeTransaction>
              <tns:AuthorizationNumber>
                <xsl:value-of select="substring (., 2, 8 )"/>
              </tns:AuthorizationNumber>
              <tns:BanamexCode>
                <xsl:value-of select="concat (&quot;B&quot;, substring (., 10, 2 ), substring (., 83, 84 ) )"/>
              </tns:BanamexCode>
              <tns:BranchNumber>
                <xsl:value-of select="substring (., 13, 3 )"/>
              </tns:BranchNumber>
              <tns:ReferenceNumber>
                <xsl:value-of select="substring (., 16, 10 )"/>
              </tns:ReferenceNumber>
              <tns:ReferenceAlphanumeric>
                <xsl:value-of select="substring (., 26, 40 )"/>
              </tns:ReferenceAlphanumeric>
              <tns:Amount>
                <xsl:value-of select="concat (substring (., 66, 15 ), &quot;.&quot;, substring (., 81, 2 ) )"/>
              </tns:Amount>
              <tns:OperationSubCode>
                <xsl:value-of select="substring (., 83, 84 )"/>
              </tns:OperationSubCode>
            </tns:Line>
          </xsl:if>
        </xsl:for-each>
      </tns:Lines>
    </tns:AccountStatementBanamexRq>
  </xsl:template>
</xsl:stylesheet>
