<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/StructureBankDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="DATA_DS" namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/StructureBankDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="DATA_DS" namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI JAN 12 13:46:20 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:DATA_DS>
         <ns0:P_BANK_ACCOUNT_NUM>
            <xsl:value-of select="/ns0:DATA_DS/P_BANK_ACCOUNT_NUM"/>
         </ns0:P_BANK_ACCOUNT_NUM>
         <xsl:for-each select="/ns0:DATA_DS/G_1">
            <ns0:G_1>
               <ns0:BANK_ACCOUNT_NAME>
                  <xsl:value-of select="BANK_ACCOUNT_NAME"/>
               </ns0:BANK_ACCOUNT_NAME>
               <ns0:BANK_ACCOUNT_NUM>
                  <xsl:value-of select="BANK_ACCOUNT_NUM"/>
               </ns0:BANK_ACCOUNT_NUM>
               <ns0:BANK_ACCOUNT_ID>
                  <xsl:value-of select="BANK_ACCOUNT_ID"/>
               </ns0:BANK_ACCOUNT_ID>
               <ns0:BANK_NAME_ALT>
                  <xsl:value-of select="BANK_NAME_ALT"/>
               </ns0:BANK_NAME_ALT>
               <ns0:CURRENCY_CODE>
               <xsl:value-of select="CURRENCY_CODE"/>
               </ns0:CURRENCY_CODE>
            </ns0:G_1>
         </xsl:for-each>
      </ns0:DATA_DS>
   </xsl:template>
</xsl:stylesheet>
