<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails"
                xmlns:tns="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaBiz"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StatementsBankBanregio"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns2="http://soa.estrellaroja.com.mx/StructureCodeBank"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns1 ns0 ns2 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:client="http://xmlns.oracle.com/GER_SOA_OCI/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankBanregio"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns3="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaBiz/types"
                xmlns:ns4="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/bpelManagementsStatementsBankBanregio"
                xmlns:strClass="http://www.oracle.com/XSL/Transform/java/java.lang.String">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/bpelManagementsStatementsBankBanregio.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Banregio"
                                       namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StatementsBankBanregio"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/StructureBankDetails.xsd"/>
        <oracle-xsl-mapper:rootElement name="GetBankDetailsRs"
                                       namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaEnt/StructureBankDetails"/>
        <oracle-xsl-mapper:param name="varGetBankDetailsRs"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/StructureBankCode.xsd"/>
        <oracle-xsl-mapper:rootElement name="DATA_DS" namespace="http://soa.estrellaroja.com.mx/StructureCodeBank"/>
        <oracle-xsl-mapper:param name="varDataCodeReport"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/SOA/SFTPEstrellaRojaBiz/SFTPEstrellaRojaBiz.wsdl"/>
        <oracle-xsl-mapper:rootElement name="GetBankStatementsRq"
                                       namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaBiz"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED DEC 14 20:35:35 CST 2022].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="varGetBankDetailsRs"/>
  <xsl:param name="varDataCodeReport"/>
  <xsl:param name="varFlowId"/>
  <xsl:variable name="varCodigoB"
                select="/ns0:Banregio/ns0:Extracto/ns0:transacciones/ns0:transaccion/ns0:referencia_operacion"/>
  <xsl:variable name="varCodigoR" select="$varDataCodeReport/ns2:DATA_DS/ns2:XXER_CE_CODIGO_BANCARIO/ns2:TRX_CODE"/>
  <xsl:variable name="varType" select="$varDataCodeReport/ns2:DATA_DS/ns2:XXER_CE_CODIGO_BANCARIO/ns2:TRX_TYPE"/>
  <xsl:template match="/">
    <tns:GetBankStatementsRq>
      <tns:BankName>
        <xsl:value-of select="$varGetBankDetailsRs/ns1:GetBankDetailsRs/ns1:Return/ns1:BankDetails/ns1:BankName"/>
      </tns:BankName>
      <tns:Sufix>BANREGIO</tns:Sufix>
      <tns:BankBranch>
        <xsl:value-of select="$varGetBankDetailsRs/ns1:GetBankDetailsRs/ns1:Return/ns1:BankDetails/ns1:BranchName"/>
      </tns:BankBranch>
      <tns:BanchId>
        <xsl:value-of select="$varFlowId"/>
      </tns:BanchId>
      <tns:Balances>
        <tns:Balance>
          <tns:AccountNumber>
            <xsl:value-of select="/ns0:Banregio/ns0:Extracto/ns0:numero_cuenta"/>
          </tns:AccountNumber>
          <tns:StatementCode>OPBD</tns:StatementCode>
          <tns:Balance>
            <xsl:value-of select="strClass:replaceAll(/ns0:Banregio/ns0:Extracto/ns0:apertura/ns0:saldo_cierre_ant,',','.')"/>
          </tns:Balance>
          <tns:CurrencyCode>
            <xsl:value-of select="$varGetBankDetailsRs/ns1:GetBankDetailsRs/ns1:Return/ns1:BankDetails/ns1:CurrencyCode"/>
          </tns:CurrencyCode>
          <tns:Indicator>CRFT</tns:Indicator>
          <tns:BalanceDate>
            <xsl:value-of select="concat(substring(/ns0:Banregio/ns0:Extracto/ns0:apertura/ns0:fecha_cierre_ant, 3, 2),'/',substring(/ns0:Banregio/ns0:Extracto/ns0:apertura/ns0:fecha_cierre_ant, 5, 2),'/','20',substring(/ns0:Banregio/ns0:Extracto/ns0:apertura/ns0:fecha_cierre_ant, 1, 2))"/>
          </tns:BalanceDate>
          <tns:OrigBalanceCode>10</tns:OrigBalanceCode>
        </tns:Balance>
        <tns:Balance>
          <tns:AccountNumber>
            <xsl:value-of select="/ns0:Banregio/ns0:Extracto/ns0:numero_cuenta"/>
          </tns:AccountNumber>
          <tns:StatementCode>CLBD</tns:StatementCode>
          <tns:Balance>
            <xsl:value-of select="strClass:replaceAll(/ns0:Banregio/ns0:Extracto/ns0:cierre/ns0:saldo_cierre,',','.')"/>
          </tns:Balance>
          <tns:CurrencyCode>
            <xsl:value-of select="$varGetBankDetailsRs/ns1:GetBankDetailsRs/ns1:Return/ns1:BankDetails/ns1:CurrencyCode"/>
          </tns:CurrencyCode>
          <tns:Indicator>CRDT</tns:Indicator>
          <tns:BalanceDate>
            <xsl:value-of select="concat(substring(/ns0:Banregio/ns0:Extracto/ns0:cierre/ns0:fecha_cierre, 3, 2),'/',substring(/ns0:Banregio/ns0:Extracto/ns0:cierre/ns0:fecha_cierre, 5, 2),'/','20',substring(/ns0:Banregio/ns0:Extracto/ns0:cierre/ns0:fecha_cierre, 1, 2))"/>
          </tns:BalanceDate>
          <tns:OrigBalanceCode>10</tns:OrigBalanceCode>
        </tns:Balance>
      </tns:Balances>
      <tns:BankLinesDetails>
        <xsl:for-each select="/ns0:Banregio/ns0:Extracto/ns0:transacciones/ns0:transaccion">
          <tns:AccountStatementsLists>
            <tns:AccountNumber>
              <xsl:value-of select="/ns0:Banregio/ns0:Extracto/ns0:numero_cuenta"/>
            </tns:AccountNumber>
            <tns:StatementDate>
              <xsl:value-of select="concat(substring(ns0:informacion/ns0:fecha_mov, 3, 2),'/',substring(ns0:informacion/ns0:fecha_mov, 5, 2),'/','20',substring(ns0:informacion/ns0:fecha_mov, 1, 2))"/>
            </tns:StatementDate>
            <tns:BankCode>
              <xsl:value-of select="ns0:referencia_operacion/ns0:codigo_transaccion"/>
            </tns:BankCode>
                          <xsl:variable name="varCodigoB"
                select="ns0:referencia_operacion/ns0:codigo_transaccion"/>
            
            <xsl:for-each select="$varDataCodeReport/ns2:DATA_DS/ns2:XXER_CE_CODIGO_BANCARIO">

  <xsl:variable name="varCodigoR" select="ns2:TRX_CODE"/>
  <xsl:variable name="varType" select="ns2:TRX_TYPE"/>
              <xsl:if test="$varCodigoR = $varCodigoB">
                <tns:TransactionType>
                  <xsl:value-of select="$varType"/>
                </tns:TransactionType>
              </xsl:if>
            </xsl:for-each>
            <xsl:choose>
              <xsl:when test="ns0:informacion/ns0:desc_t_f='C' or ns0:informacion/ns0:desc_t_f='RC'">
                <tns:TypeSign>-</tns:TypeSign>
              </xsl:when>
              <xsl:otherwise>
                <tns:TypeSign>+</tns:TypeSign>
              </xsl:otherwise>
            </xsl:choose>
            <tns:Amount>
              <xsl:value-of select="concat (ns0:informacion/ns0:monto_entero,'.', ns0:informacion/ns0:monto_decimal )"/>
            </tns:Amount>
            <tns:References>
              <xsl:value-of select="ns0:informacion/ns0:referencia"/>
            </tns:References>
          </tns:AccountStatementsLists>
        </xsl:for-each>
      </tns:BankLinesDetails>
    </tns:GetBankStatementsRq>
  </xsl:template>
</xsl:stylesheet>
