<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesAP" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesEnt/bpelValidateInvoicesAP"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesEnt"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns4="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelValidateInvoicesAP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DATA_DS" namespace="http://soa.estrellaroja.com.mx/InvoicesAP"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/InvoicesBiz/InvoicesBiz.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ValidateInvoicesAPRq" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 14 19:23:43 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ValidateInvoicesAPRq>
         <tns:InvoicesAP>
            <xsl:for-each select="/ns0:DATA_DS/ns0:G_INVOICES">
               <tns:InvoiceAP>
                  <tns:SupplierId>
                     <xsl:value-of select="ns0:SUPPLIER_ID"/>
                  </tns:SupplierId>
                  <tns:SupplierRFC>
                     <xsl:value-of select="ns0:SUPPLIER_RFC"/>
                  </tns:SupplierRFC>
                  <tns:Total>
                     <xsl:value-of select="ns0:TOTAL"/>
                  </tns:Total>
                  <xsl:if test="ns0:SUBTOTAL">
                     <tns:Subtotal>
                        <xsl:value-of select="ns0:SUBTOTAL"/>
                     </tns:Subtotal>
                  </xsl:if>
                  <tns:SupplierName>
                     <xsl:value-of select="ns0:SUPPLIERNAME"/>
                  </tns:SupplierName>
                  <tns:InvoiceDate>
                     <xsl:value-of select="ns0:INVOICEDATE"/>
                  </tns:InvoiceDate>
                  <tns:CreationDate>
                     <xsl:value-of select="ns0:CREATION_DATE"/>
                  </tns:CreationDate>
                  <tns:LastUpdateDate>
                     <xsl:value-of select="ns0:LAST_UPDATE_DATE"/>
                  </tns:LastUpdateDate>
                  <tns:Status>
                     <xsl:value-of select="ns0:STATUS"/>
                  </tns:Status>
                  <tns:Currency>
                     <xsl:value-of select="ns0:CURRENCY"/>
                  </tns:Currency>
                  <tns:ReceptorRFC>
                     <xsl:value-of select="ns0:RECEPTOR_RFC"/>
                  </tns:ReceptorRFC>
                  <tns:NameRFC>
                     <xsl:value-of select="ns0:NAME_RFC"/>
                  </tns:NameRFC>
                  <tns:InvoiceId>
                     <xsl:value-of select="ns0:INVOICE_ID"/>
                  </tns:InvoiceId>
                  <tns:SupplierNumber>
                     <xsl:value-of select="ns0:SUPPLIER_NUMBER"/>
                  </tns:SupplierNumber>
                  <tns:InvoiceNumber>
                     <xsl:value-of select="ns0:INVOICE_NUMBER"/>
                  </tns:InvoiceNumber>
                  <xsl:if test="ns0:TOTAL_TAX_AMOUNT">
                     <tns:TotalTaxAmount>
                        <xsl:value-of select="ns0:TOTAL_TAX_AMOUNT"/>
                     </tns:TotalTaxAmount>
                  </xsl:if>
                  <tns:BusinessUnit>
                     <xsl:value-of select="ns0:BUSINESS_UNIT"/>
                  </tns:BusinessUnit>
                  <tns:numeroPago>
                     <xsl:value-of select="ns0:NUMERO_PAGO"/>
                  </tns:numeroPago>
                  <tns:documentoPago>
                     <xsl:value-of select="ns0:DOCUMENTO_PAGO"/>
                  </tns:documentoPago>
                  <tns:estadoPago>
                     <xsl:value-of select="ns0:ESTADO_PAGO"/>
                  </tns:estadoPago>
                  <tns:tipoPago>
                     <xsl:value-of select="ns0:TIPO_PAGO"/>
                  </tns:tipoPago>
                  <tns:conciliadas>
                     <xsl:value-of select="ns0:CONCILIADAS"/>
                  </tns:conciliadas>
                  <tns:beneficio>
                     <xsl:value-of select="ns0:BENEFICIO"/>
                  </tns:beneficio>
                  <tns:sitioBeneficio>
                     <xsl:value-of select="ns0:SITIO_BENEFICIO"/>
                  </tns:sitioBeneficio>
                  <tns:fechaPago>
                     <xsl:value-of select="ns0:FECHA_PAGO"/>
                  </tns:fechaPago>
                  <tns:monedaPago>
                     <xsl:value-of select="ns0:MONEDA_PAGO"/>
                  </tns:monedaPago>
                  <tns:direccionPago>
                     <xsl:value-of select="ns0:DIRECCION_PAGO"/>
                  </tns:direccionPago>
                  <tns:noCuentaPago>
                     <xsl:value-of select="ns0:NO_CUENTA_PAGO"/>
                  </tns:noCuentaPago>
                  <tns:proveedorParte>
                     <xsl:value-of select="ns0:PROVEEDOR_PARTE"/>
                  </tns:proveedorParte>
                  <tns:sitioProveedor>
                     <xsl:value-of select="ns0:SITIO_PROVEEDOR"/>
                  </tns:sitioProveedor>
                  <tns:unidadNegocio>
                     <xsl:value-of select="ns0:UNIDAD_NEGOCIO"/>
                  </tns:unidadNegocio>
                  <tns:nomBancoPagador>
                     <xsl:value-of select="ns0:NOM_BANCO_PAGADOR"/>
                  </tns:nomBancoPagador>
                  <tns:fecPagoBanco>
                     <xsl:value-of select="ns0:FEC_PAGO_BANCO"/>
                  </tns:fecPagoBanco>
                  <tns:importePagadoBanco>
                     <xsl:value-of select="ns0:IMPORTE_PAGADO_BANCO"/>
                  </tns:importePagadoBanco>
                  <tns:cuentaBancariaPago>
                     <xsl:value-of select="ns0:CUENTA_BANCARIA_PAGO"/>
                  </tns:cuentaBancariaPago>
                  <tns:importPagoBanco>
                     <xsl:value-of select="ns0:IMPORT_PAGO_BANCO"/>
                  </tns:importPagoBanco>
                  <tns:nombreActual>
                     <xsl:value-of select="ns0:NOMBRE_ACTUAL"/>
                  </tns:nombreActual>
                  <tns:detalle>
                     <xsl:value-of select="ns0:DETALLES"/>
                  </tns:detalle>
                  <tns:tercerSegmContable>
                     <xsl:value-of select="ns0:TERCER_SEGM_COTABLE"/>
                  </tns:tercerSegmContable>
                  <tns:conceptoCuenCotble3>
                     <xsl:value-of select="ns0:CONCEPTO_CUEN_COTBLE3"/>
                  </tns:conceptoCuenCotble3>
                  <tns:quintoSegmContable>
                     <xsl:value-of select="ns0:QUINTO_SEGM_CONTABLE"/>
                  </tns:quintoSegmContable>
                  <tns:conceptoCuenContable5>
                     <xsl:value-of select="ns0:CONCEPTO_CUEN_CONTABLE5"/>
                  </tns:conceptoCuenContable5>
               </tns:InvoiceAP>
            </xsl:for-each>
         </tns:InvoicesAP>
      </tns:ValidateInvoicesAPRq>
   </xsl:template>
</xsl:stylesheet>
