<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesEnt/XxerApLocatePayment"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesEnt/bpelValidatePaymentComplements"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns4="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec"
                xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesEnt"
                xmlns:ns2="http://soa.estrellaroja.com.mx/InvoicesBiz">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../../WSDLs/bpelValidatePaymentComplements.wsdl"/>
        <oracle-xsl-mapper:rootElement name="DATA_DS"
                                       namespace="http://soa.estrellaroja.com.mx/InvoicesEnt/XxerApLocatePayment"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../../WSDLs/bpelValidatePaymentComplements.wsdl"/>
        <oracle-xsl-mapper:rootElement name="DATA_DS"
                                       namespace="http://soa.estrellaroja.com.mx/InvoicesEnt/XxerApLocatePayment"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU JAN 11 22:19:55 CST 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:DATA_DS>
      <ns0:P_INVOICE_NUMBER>
        <xsl:value-of select="/ns0:DATA_DS/P_INVOICE_NUMBER"/>
      </ns0:P_INVOICE_NUMBER>
      <ns0:P_INSTALLMENT_NUMBER>
        <xsl:value-of select="/ns0:DATA_DS/P_INSTALLMENT_NUMBER"/>
      </ns0:P_INSTALLMENT_NUMBER>
      <ns0:PAYMENT_INFO>
        <ns0:CHECKID>
          <xsl:value-of select="/ns0:DATA_DS/PAYMENT_INFO/CHECKID"/>
        </ns0:CHECKID>
        <ns0:CHECKNUMBER>
          <xsl:value-of select="/ns0:DATA_DS/PAYMENT_INFO/CHECKNUMBER"/>
        </ns0:CHECKNUMBER>
      </ns0:PAYMENT_INFO>
    </ns0:DATA_DS>
  </xsl:template>
</xsl:stylesheet>
