<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns1="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 ns1 mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelCreateCustomer" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec/types">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateCustomer.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreateCustomerRq" namespace="http://soa.estrellaroja.com.mx/CustomerBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/External/ERPIntegrationServiceTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreatePersonRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
            <oracle-xsl-mapper:param name="varCreatePersonRs.CreatePersonRs"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/External/ERPIntegrationServiceTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreateCustomerAccountRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED DEC 20 15:53:51 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varCreatePersonRs.CreatePersonRs"/>
   <xsl:template match="/">
      <ns1:CreateCustomerAccountRq>
         <ns1:PartyId>
            <xsl:value-of select="$varCreatePersonRs.CreatePersonRs/ns1:CreatePersonRs/ns1:Return/ns1:PartyId"/>
         </ns1:PartyId>
         <ns1:CustomerAccount>
            <ns1:Name>
               <xsl:value-of select="/ns0:CreateCustomerRq/ns0:CustomerData/ns0:AccountName"/>
            </ns1:Name>
            <ns1:Description>
               <xsl:value-of select="/ns0:CreateCustomerRq/ns0:CustomerData/ns0:AccountName"/>
            </ns1:Description>
            <ns1:CustomerType>
               <xsl:value-of select="dvm:lookupValue (&quot;Dvms/dvmCustomerBizProperties.dvm&quot;, &quot;CODE&quot;, &quot;CUSTOMER_TYPE&quot;, &quot;VALUE&quot;, &quot;&quot; )"/>
            </ns1:CustomerType>
            <ns1:CustomerClassCode>
               <xsl:value-of select="dvm:lookupValue (&quot;Dvms/dvmCustomerBizProperties.dvm&quot;, &quot;CODE&quot;, &quot;CUSTOMER_CLASS_CODE&quot;, &quot;VALUE&quot;, &quot;&quot; )"/>
            </ns1:CustomerClassCode>
         </ns1:CustomerAccount>
      </ns1:CreateCustomerAccountRq>
   </xsl:template>
</xsl:stylesheet>