<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelCreateSite" xmlns:ns4="http://soa.estrellaroja.com.mx/CoherenceTec">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateSite.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CustSiteData" namespace="http://soa.estrellaroja.com.mx/CustomerBiz"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateSite.wsdl"/>
        <oracle-xsl-mapper:rootElement name="FindCustomerAccountRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [SAT DEC 23 18:41:19 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:FindCustomerAccountRq>
      <tns:findCriteria>
        <tns:fetchStart>0</tns:fetchStart>
        <tns:fetchSize>-1</tns:fetchSize>
        <tns:filter>
          <tns:conjunction>And</tns:conjunction>
          <tns:group>
            <tns:conjunction>And</tns:conjunction>
            <tns:upperCaseCompare>false</tns:upperCaseCompare>
            <tns:item>
              <tns:upperCaseCompare>false</tns:upperCaseCompare>
              <tns:attribute>CustomerAccountSite</tns:attribute>
              <tns:operator>Exists</tns:operator>
              <tns:nested>
                <tns:group>
                  <tns:item>
                    <tns:conjunction>And</tns:conjunction>
                    <tns:upperCaseCompare>false</tns:upperCaseCompare>
                    <tns:attribute>CustomerAccountId</tns:attribute>
                    <tns:operator>IN</tns:operator>
                    <tns:value>
                      <xsl:value-of select="/ns0:CustSiteData/ns0:CustomerAccountId"/>
                    </tns:value>
                  </tns:item>
                  <tns:item>
                    <tns:conjunction>And</tns:conjunction>
                    <tns:upperCaseCompare>false</tns:upperCaseCompare>
                    <tns:attribute>PartySiteId</tns:attribute>
                    <tns:operator>IN</tns:operator>
                    <tns:value>
                      <xsl:value-of select="/ns0:CustSiteData/ns0:PartySiteId"/>
                    </tns:value>
                  </tns:item>
                  <tns:item>
                    <tns:conjunction>And</tns:conjunction>
                    <tns:upperCaseCompare>false</tns:upperCaseCompare>
                    <tns:attribute>SetId</tns:attribute>
                    <tns:operator>IN</tns:operator>
                    <tns:value>
                      <xsl:value-of select="/ns0:CustSiteData/ns0:SetId"/>
                    </tns:value>
                  </tns:item>
                </tns:group>
              </tns:nested>
            </tns:item>
          </tns:group>
        </tns:filter>
        <tns:findAttribute>CustomerAccountId</tns:findAttribute>
        <tns:findAttribute>CustomerAccountSite</tns:findAttribute>
        <tns:findAttribute>PartyId</tns:findAttribute>
        <tns:findAttribute>AccountNumber</tns:findAttribute>
        <tns:findAttribute>AccountName</tns:findAttribute>
        <tns:excludeAttribute>false</tns:excludeAttribute>
        <tns:childFindCriteria>
          <tns:fetchStart>0</tns:fetchStart>
          <tns:fetchSize>-1</tns:fetchSize>
          <tns:filter>
            <tns:group>
              <tns:upperCaseCompare>false</tns:upperCaseCompare>
              <tns:item>
                <tns:conjunction>And</tns:conjunction>
                <tns:upperCaseCompare>false</tns:upperCaseCompare>
                <tns:attribute>CustomerAccountId</tns:attribute>
                <tns:operator>IN</tns:operator>
                <tns:value>
                  <xsl:value-of select="/ns0:CustSiteData/ns0:CustomerAccountId"/>
                </tns:value>
              </tns:item>
              <tns:item>
                <tns:conjunction>And</tns:conjunction>
                <tns:upperCaseCompare>false</tns:upperCaseCompare>
                <tns:attribute>PartySiteId</tns:attribute>
                <tns:operator>IN</tns:operator>
                <tns:value>
                  <xsl:value-of select="/ns0:CustSiteData/ns0:PartySiteId"/>
                </tns:value>
              </tns:item>
              <tns:item>
                <tns:conjunction>And</tns:conjunction>
                <tns:upperCaseCompare>false</tns:upperCaseCompare>
                <tns:attribute>SetId</tns:attribute>
                <tns:operator>IN</tns:operator>
                <tns:value>
                  <xsl:value-of select="/ns0:CustSiteData/ns0:SetId"/>
                </tns:value>
              </tns:item>
              <tns:item>
                <tns:conjunction>And</tns:conjunction>
                <tns:upperCaseCompare>false</tns:upperCaseCompare>
                <tns:attribute>CustomerAccountSiteUse</tns:attribute>
                <tns:operator>EXISTS</tns:operator>
                <tns:nested>
                  <tns:group>
                    <tns:item>
                      <tns:conjunction>And</tns:conjunction>
                      <tns:upperCaseCompare>false</tns:upperCaseCompare>
                      <tns:attribute>SiteUseCode</tns:attribute>
                      <tns:operator>IN</tns:operator>
                      <xsl:choose>
                        <xsl:when test="contains (/ns0:CustSiteData/ns0:SiteUseCode, &quot;/&quot; )">
                          <tns:value>BILL_TO</tns:value>
                          <tns:value>SHIP_TO</tns:value>
                        </xsl:when>
                        <xsl:otherwise>
                          <tns:value>
                            <xsl:value-of select="/ns0:CustSiteData/ns0:SiteUseCode"/>
                          </tns:value>
                        </xsl:otherwise>
                      </xsl:choose>
                    </tns:item>
                  </tns:group>
                </tns:nested>
              </tns:item>
            </tns:group>
          </tns:filter>
          <tns:findAttribute>CustomerAccountSiteId</tns:findAttribute>
          <tns:findAttribute>PartySiteId</tns:findAttribute>
          <tns:findAttribute>CustomerAccountSiteUse</tns:findAttribute>
          <tns:childFindCriteria>
            <tns:fetchStart>0</tns:fetchStart>
            <tns:fetchSize>-1</tns:fetchSize>
            <tns:filter>
              <tns:group>
                <tns:upperCaseCompare>false</tns:upperCaseCompare>
                <tns:item>
                  <tns:conjunction>And</tns:conjunction>
                  <tns:upperCaseCompare>false</tns:upperCaseCompare>
                  <tns:attribute>SiteUseCode</tns:attribute>
                  <tns:operator>IN</tns:operator>
                  <xsl:choose>
                    <xsl:when test="contains (/ns0:CustSiteData/ns0:SiteUseCode, &quot;/&quot; )">
                      <tns:value>BILL_TO</tns:value>
                      <tns:value>SHIP_TO</tns:value>
                    </xsl:when>
                    <xsl:otherwise>
                      <tns:value>
                        <xsl:value-of select="/ns0:CustSiteData/ns0:SiteUseCode"/>
                      </tns:value>
                    </xsl:otherwise>
                  </xsl:choose>
                </tns:item>
              </tns:group>
            </tns:filter>
            <tns:findAttribute>SiteUseId</tns:findAttribute>
            <tns:findAttribute>SiteUseCode</tns:findAttribute>
            <tns:childAttrName>CustomerAccountSiteUse</tns:childAttrName>
          </tns:childFindCriteria>
          <tns:childAttrName>CustomerAccountSite</tns:childAttrName>
        </tns:childFindCriteria>
      </tns:findCriteria>
      <tns:findControl>
        <tns:retrieveAllTranslations>false</tns:retrieveAllTranslations>
      </tns:findControl>
    </tns:FindCustomerAccountRq>
  </xsl:template>
</xsl:stylesheet>