<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns1="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 ns1 mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelCreateSite" xmlns:ns4="http://soa.estrellaroja.com.mx/CoherenceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateSite.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CustSiteData" namespace="http://soa.estrellaroja.com.mx/CustomerBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateSite.wsdl"/>
            <oracle-xsl-mapper:rootElement name="AssignSiteToAccountRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
            <oracle-xsl-mapper:param name="varAssignSiteToAccountRs.AssignSiteToAccountRs"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateSite.wsdl"/>
            <oracle-xsl-mapper:rootElement name="AssignSiteToAccountRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [SAT DEC 23 19:38:06 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varAssignSiteToAccountRs.AssignSiteToAccountRs"/>
   <xsl:template match="/">
      <ns1:AssignSiteToAccountRq>
         <ns1:CustomerAccountSiteId>
            <xsl:value-of select="$varAssignSiteToAccountRs.AssignSiteToAccountRs/ns1:AssignSiteToAccountRs/ns1:Return/ns1:CustAccountSite/ns1:CustAccountSiteId"/>
         </ns1:CustomerAccountSiteId>
         <ns1:CustomerAccountId>
            <xsl:value-of select="/ns0:CustSiteData/ns0:CustomerAccountId"/>
         </ns1:CustomerAccountId>
         <ns1:PartyId>
            <xsl:value-of select="/ns0:CustSiteData/ns0:PartyId"/>
         </ns1:PartyId>
         <ns1:PartySiteId>
            <xsl:value-of select="/ns0:CustSiteData/ns0:PartySiteId"/>
         </ns1:PartySiteId>
         <ns1:SetId>
            <xsl:value-of select="/ns0:CustSiteData/ns0:SetId"/>
         </ns1:SetId>
         <ns1:SiteUseIdPrimaryBillTo>
            <xsl:value-of select="$varAssignSiteToAccountRs.AssignSiteToAccountRs/ns1:AssignSiteToAccountRs/ns1:Return/ns1:CustAccountSite[1]/ns1:SiteUse[ns1:UseCode='BILL_TO']/ns1:UseId"/>
         </ns1:SiteUseIdPrimaryBillTo>
         <ns1:AddressType>SHIP_TO</ns1:AddressType>
         <ns1:PartySiteUseId>
            <xsl:value-of select="$varAssignSiteToAccountRs.AssignSiteToAccountRs/ns1:AssignSiteToAccountRs/ns1:Return/ns1:CustAccountSite[1]/ns1:SiteUse[ns1:UseCode='SHIP_TO']/ns1:UseId"/>
         </ns1:PartySiteUseId>
      </ns1:AssignSiteToAccountRq>
   </xsl:template>
</xsl:stylesheet>