<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://soa.estrellaroja.com.mx/CoherenceTec" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://soa.estrellaroja.com.mx/CoherenceTec/types" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/External/CoherenceTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="TERRITORIES" namespace="http://soa.estrellaroja.com.mx/CoherenceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/External/CoherenceTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="TERRITORIES" namespace="http://soa.estrellaroja.com.mx/CoherenceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON DEC 18 17:51:40 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:TERRITORIES>
         <ns0:P_COUNTRYNAME>
            <xsl:value-of select="/ns0:TERRITORIES/P_COUNTRYNAME"/>
         </ns0:P_COUNTRYNAME>
         <xsl:for-each select="/ns0:TERRITORIES/TERRITORY">
            <ns0:TERRITORY>
               <ns0:ROWID>
                  <xsl:value-of select="ROWID"/>
               </ns0:ROWID>
               <ns0:TERRITORYCODE>
                  <xsl:value-of select="TERRITORYCODE"/>
               </ns0:TERRITORYCODE>
               <ns0:NLSTERRITORY>
                  <xsl:value-of select="NLSTERRITORY"/>
               </ns0:NLSTERRITORY>
               <ns0:ISOTERRITORYCODE>
                  <xsl:value-of select="ISOTERRITORYCODE"/>
               </ns0:ISOTERRITORYCODE>
               <ns0:TERRITORYSHORTNAME>
                  <xsl:value-of select="TERRITORYSHORTNAME"/>
               </ns0:TERRITORYSHORTNAME>
               <ns0:DESCRIPTION>
                  <xsl:value-of select="DESCRIPTION"/>
               </ns0:DESCRIPTION>
               <ns0:ALTERNATETERRITORYCODE>
                  <xsl:value-of select="ALTERNATETERRITORYCODE"/>
               </ns0:ALTERNATETERRITORYCODE>
            </ns0:TERRITORY>
         </xsl:for-each>
      </ns0:TERRITORIES>
   </xsl:template>
</xsl:stylesheet>