<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/FinancialsTec" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelCreateSites" xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateSites.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetCustomerSitesRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateSites.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreateSitesRq" namespace="http://soa.estrellaroja.com.mx/CustomerBiz"/>
            <oracle-xsl-mapper:param name="inputVariable.CreateSitesRq"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateSites.wsdl"/>
            <oracle-xsl-mapper:rootElement name="SiteCollection" namespace="http://soa.estrellaroja.com.mx/CustomerBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI DEC 22 19:23:59 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="inputVariable.CreateSitesRq"/>
   <xsl:template match="/">
      <ns1:SiteCollection>
         <xsl:for-each select="/ns0:GetCustomerSitesRs/ns0:Return/ns0:CustomerSite">
            <xsl:sort order="ascending" select="ns0:CreatedDate"/>
            <ns1:Site>
               <ns1:PartyId>
                  <xsl:value-of select="$inputVariable.CreateSitesRq/ns1:CreateSitesRq/ns1:PartyId"/>
               </ns1:PartyId>
               <ns1:CustomerAccountId>
                  <xsl:value-of select="$inputVariable.CreateSitesRq/ns1:CreateSitesRq/ns1:CustomerAccountId"/>
               </ns1:CustomerAccountId>
               <ns1:CustomerPartyType>
                  <xsl:value-of select="$inputVariable.CreateSitesRq/ns1:CreateSitesRq/ns1:CustomerType"/>
               </ns1:CustomerPartyType>
               <ns1:SiteName>
                  <xsl:if test="ns0:SiteName/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:SiteName/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:SiteName"/>
               </ns1:SiteName>
               <ns1:SiteDescription>
                  <xsl:if test="ns0:SiteDescription/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:SiteDescription/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:SiteDescription"/>
               </ns1:SiteDescription>
               <xsl:if test="ns0:AccountAddressSet">
                  <ns1:AccountAddressSet>
                     <xsl:if test="ns0:AccountAddressSet/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:AccountAddressSet/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:AccountAddressSet"/>
                  </ns1:AccountAddressSet>
               </xsl:if>
               <ns1:LegacyCustomerSiteId>
                  <xsl:value-of select="ns0:CustomerSiteId"/>
               </ns1:LegacyCustomerSiteId>
               <ns1:StreetName>
                  <xsl:value-of select="ns0:StreetName"/>
               </ns1:StreetName>
               <ns1:ExternalNumber>
                  <xsl:value-of select="ns0:ExternalNumber"/>
               </ns1:ExternalNumber>
               <ns1:InternalNumber>
                  <xsl:if test="ns0:InternalNumber/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:InternalNumber/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:InternalNumber"/>
               </ns1:InternalNumber>
               <ns1:PostalCode>
                  <xsl:value-of select="ns0:PostalCode"/>
               </ns1:PostalCode>
               <ns1:Province>
                  <xsl:value-of select="ns0:Province"/>
               </ns1:Province>
               <ns1:City>
                  <xsl:value-of select="ns0:City"/>
               </ns1:City>
               <ns1:State>
                  <xsl:value-of select="ns0:State"/>
               </ns1:State>
               <ns1:Country>
                  <xsl:value-of select="ns0:Country"/>
               </ns1:Country>
               <ns1:SiteUseCode>
                  <xsl:value-of select="ns0:SiteUse"/>
               </ns1:SiteUseCode>
               <ns1:CreatedDate>
                  <xsl:value-of select="ns0:CreatedDate"/>
               </ns1:CreatedDate>
            </ns1:Site>
         </xsl:for-each>
      </ns1:SiteCollection>
   </xsl:template>
</xsl:stylesheet>