<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/FinancialsTec" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelUpdateSites">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelUpdateSites.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetCustomerSitesRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelUpdateSites.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetCustomerSitesRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
            <oracle-xsl-mapper:param name="varGetCustomerBillSitesRs.GetCustomerSitesRs"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelUpdateSites.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetCustomerSitesRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
            <oracle-xsl-mapper:param name="varGetCustomerShipSitesRs.GetCustomerSitesRs"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelUpdateSites.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetCustomerSitesRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI DEC 15 23:16:17 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varGetCustomerBillSitesRs.GetCustomerSitesRs"/>
   <xsl:param name="varGetCustomerShipSitesRs.GetCustomerSitesRs"/>
   <xsl:template match="/">
      <ns0:GetCustomerSitesRs>
         <ns0:Return>
            <xsl:for-each select="/ns0:GetCustomerSitesRs/ns0:Return/ns0:CustomerSite">
                  <ns0:CustomerSite>
                  <ns0:CustomerSiteId>
                     <xsl:if test="ns0:CustomerSiteId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CustomerSiteId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CustomerSiteId"/>
                  </ns0:CustomerSiteId>
                  <ns0:CustomerId>
                     <xsl:if test="ns0:CustomerId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CustomerId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CustomerId"/>
                  </ns0:CustomerId>
                  <ns0:StreetName>
                     <xsl:if test="ns0:StreetName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:StreetName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:StreetName"/>
                  </ns0:StreetName>
                  <ns0:ExternalNumber>
                     <xsl:if test="ns0:ExternalNumber/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ExternalNumber/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ExternalNumber"/>
                  </ns0:ExternalNumber>
                  <ns0:InternalNumber>
                     <xsl:if test="ns0:InternalNumber/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:InternalNumber/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:InternalNumber"/>
                  </ns0:InternalNumber>
                  <ns0:PostalCode>
                     <xsl:if test="ns0:PostalCode/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:PostalCode/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:PostalCode"/>
                  </ns0:PostalCode>
                  <ns0:Province>
                     <xsl:if test="ns0:Province/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Province/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Province"/>
                  </ns0:Province>
                  <ns0:City>
                     <xsl:if test="ns0:City/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:City/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:City"/>
                  </ns0:City>
                  <ns0:State>
                     <xsl:if test="ns0:State/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:State/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:State"/>
                  </ns0:State>
                  <ns0:Country>
                     <xsl:if test="ns0:Country/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Country/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Country"/>
                  </ns0:Country>
                  <ns0:SiteName>
                     <xsl:if test="ns0:SiteName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SiteName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SiteName"/>
                  </ns0:SiteName>
                  <ns0:SiteDescription>
                     <xsl:if test="ns0:SiteDescription/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SiteDescription/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SiteDescription"/>
                  </ns0:SiteDescription>
                  <ns0:SiteUse>
                     <xsl:if test="ns0:SiteUse/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SiteUse/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SiteUse"/>
                  </ns0:SiteUse>
                  <ns0:CreatedDate>
                     <xsl:if test="ns0:CreatedDate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CreatedDate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CreatedDate"/>
                  </ns0:CreatedDate>
                  <ns0:SourceTable>
                     <xsl:if test="ns0:SourceTable/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SourceTable/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SourceTable"/>
                  </ns0:SourceTable>
                  <xsl:if test="ns0:siteId">
                     <ns0:siteId>
                        <xsl:if test="ns0:siteId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:siteId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:siteId"/>
                     </ns0:siteId>
                  </xsl:if>
                  <xsl:if test="ns0:replicationInd">
                     <ns0:replicationInd>
                        <xsl:if test="ns0:replicationInd/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:replicationInd/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:replicationInd"/>
                     </ns0:replicationInd>
                  </xsl:if>
                  <xsl:if test="ns0:replicationMsg">
                     <ns0:replicationMsg>
                        <xsl:if test="ns0:replicationMsg/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:replicationMsg/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:replicationMsg"/>
                     </ns0:replicationMsg>
                  </xsl:if>
               </ns0:CustomerSite>
            </xsl:for-each>
            <xsl:for-each select="$varGetCustomerBillSitesRs.GetCustomerSitesRs/ns0:GetCustomerSitesRs/ns0:Return/ns0:CustomerSite">
               <ns0:CustomerSite>
                  <ns0:CustomerSiteId>
                     <xsl:if test="ns0:CustomerSiteId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CustomerSiteId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CustomerSiteId"/>
                  </ns0:CustomerSiteId>
                  <ns0:CustomerId>
                     <xsl:if test="ns0:CustomerId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CustomerId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CustomerId"/>
                  </ns0:CustomerId>
                  <ns0:StreetName>
                     <xsl:if test="ns0:StreetName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:StreetName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:StreetName"/>
                  </ns0:StreetName>
                  <ns0:ExternalNumber>
                     <xsl:if test="ns0:ExternalNumber/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ExternalNumber/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ExternalNumber"/>
                  </ns0:ExternalNumber>
                  <ns0:InternalNumber>
                     <xsl:if test="ns0:InternalNumber/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:InternalNumber/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:InternalNumber"/>
                  </ns0:InternalNumber>
                  <ns0:PostalCode>
                     <xsl:if test="ns0:PostalCode/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:PostalCode/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:PostalCode"/>
                  </ns0:PostalCode>
                  <ns0:Province>
                     <xsl:if test="ns0:Province/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Province/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Province"/>
                  </ns0:Province>
                  <ns0:City>
                     <xsl:if test="ns0:City/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:City/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:City"/>
                  </ns0:City>
                  <ns0:State>
                     <xsl:if test="ns0:State/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:State/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:State"/>
                  </ns0:State>
                  <ns0:Country>
                     <xsl:if test="ns0:Country/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Country/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Country"/>
                  </ns0:Country>
                  <ns0:SiteName>
                     <xsl:if test="ns0:SiteName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SiteName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SiteName"/>
                  </ns0:SiteName>
                  <ns0:SiteDescription>
                     <xsl:if test="ns0:SiteDescription/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SiteDescription/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SiteDescription"/>
                  </ns0:SiteDescription>
                  <ns0:SiteUse>
                     <xsl:if test="ns0:SiteUse/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SiteUse/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SiteUse"/>
                  </ns0:SiteUse>
                  <ns0:CreatedDate>
                     <xsl:if test="ns0:CreatedDate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CreatedDate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CreatedDate"/>
                  </ns0:CreatedDate>
                  <ns0:SourceTable>
                     <xsl:if test="ns0:SourceTable/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SourceTable/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SourceTable"/>
                  </ns0:SourceTable>
                  <xsl:if test="ns0:siteId">
                     <ns0:siteId>
                        <xsl:if test="ns0:siteId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:siteId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:siteId"/>
                     </ns0:siteId>
                  </xsl:if>
                  <xsl:if test="ns0:replicationInd">
                     <ns0:replicationInd>
                        <xsl:if test="ns0:replicationInd/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:replicationInd/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:replicationInd"/>
                     </ns0:replicationInd>
                  </xsl:if>
                  <xsl:if test="ns0:replicationMsg">
                     <ns0:replicationMsg>
                        <xsl:if test="ns0:replicationMsg/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:replicationMsg/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:replicationMsg"/>
                     </ns0:replicationMsg>
                  </xsl:if>
               </ns0:CustomerSite>
            </xsl:for-each>
            <xsl:for-each select="$varGetCustomerShipSitesRs.GetCustomerSitesRs/ns0:GetCustomerSitesRs/ns0:Return/ns0:CustomerSite">
               <ns0:CustomerSite>
                  <ns0:CustomerSiteId>
                     <xsl:if test="ns0:CustomerSiteId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CustomerSiteId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CustomerSiteId"/>
                  </ns0:CustomerSiteId>
                  <ns0:CustomerId>
                     <xsl:if test="ns0:CustomerId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CustomerId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CustomerId"/>
                  </ns0:CustomerId>
                  <ns0:StreetName>
                     <xsl:if test="ns0:StreetName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:StreetName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:StreetName"/>
                  </ns0:StreetName>
                  <ns0:ExternalNumber>
                     <xsl:if test="ns0:ExternalNumber/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ExternalNumber/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ExternalNumber"/>
                  </ns0:ExternalNumber>
                  <ns0:InternalNumber>
                     <xsl:if test="ns0:InternalNumber/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:InternalNumber/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:InternalNumber"/>
                  </ns0:InternalNumber>
                  <ns0:PostalCode>
                     <xsl:if test="ns0:PostalCode/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:PostalCode/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:PostalCode"/>
                  </ns0:PostalCode>
                  <ns0:Province>
                     <xsl:if test="ns0:Province/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Province/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Province"/>
                  </ns0:Province>
                  <ns0:City>
                     <xsl:if test="ns0:City/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:City/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:City"/>
                  </ns0:City>
                  <ns0:State>
                     <xsl:if test="ns0:State/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:State/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:State"/>
                  </ns0:State>
                  <ns0:Country>
                     <xsl:if test="ns0:Country/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Country/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Country"/>
                  </ns0:Country>
                  <ns0:SiteName>
                     <xsl:if test="ns0:SiteName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SiteName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SiteName"/>
                  </ns0:SiteName>
                  <ns0:SiteDescription>
                     <xsl:if test="ns0:SiteDescription/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SiteDescription/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SiteDescription"/>
                  </ns0:SiteDescription>
                  <ns0:SiteUse>
                     <xsl:if test="ns0:SiteUse/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SiteUse/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SiteUse"/>
                  </ns0:SiteUse>
                  <ns0:CreatedDate>
                     <xsl:if test="ns0:CreatedDate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CreatedDate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CreatedDate"/>
                  </ns0:CreatedDate>
                  <ns0:SourceTable>
                     <xsl:if test="ns0:SourceTable/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SourceTable/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SourceTable"/>
                  </ns0:SourceTable>
                  <xsl:if test="ns0:siteId">
                     <ns0:siteId>
                        <xsl:if test="ns0:siteId/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:siteId/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:siteId"/>
                     </ns0:siteId>
                  </xsl:if>
                  <xsl:if test="ns0:replicationInd">
                     <ns0:replicationInd>
                        <xsl:if test="ns0:replicationInd/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:replicationInd/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:replicationInd"/>
                     </ns0:replicationInd>
                  </xsl:if>
                  <xsl:if test="ns0:replicationMsg">
                     <ns0:replicationMsg>
                        <xsl:if test="ns0:replicationMsg/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="ns0:replicationMsg/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:replicationMsg"/>
                     </ns0:replicationMsg>
                  </xsl:if>
               </ns0:CustomerSite>
            </xsl:for-each>
         </ns0:Return>
      </ns0:GetCustomerSitesRs>
   </xsl:template>
</xsl:stylesheet>