<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://soa.estrellaroja.com.mx/CoherenceTec" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns4="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:ns3="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelCreateSite">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateSite.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetOrgListRs" namespace="http://soa.estrellaroja.com.mx/CoherenceTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateSite.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OrgCollection" namespace="http://soa.estrellaroja.com.mx/CoherenceTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON DEC 25 18:15:26 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:OrgCollection>
         <xsl:for-each select="/ns0:GetOrgListRs/ns0:Return/ns0:OrgCollection/ns0:ORGS">
            <ns0:ORGS>
               <ns0:SET_ID>
                  <xsl:value-of select="ns0:SET_ID"/>
               </ns0:SET_ID>
               <ns0:SET_CODE>
                  <xsl:value-of select="ns0:SET_CODE"/>
               </ns0:SET_CODE>
               <ns0:SET_NAME>
                  <xsl:value-of select="ns0:SET_NAME"/>
               </ns0:SET_NAME>
               <ns0:DESCRIPTION>
                  <xsl:value-of select="ns0:DESCRIPTION"/>
               </ns0:DESCRIPTION>
            </ns0:ORGS>
         </xsl:for-each>
      </ns0:OrgCollection>
   </xsl:template>
</xsl:stylesheet>