<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="bpelValidateInvoicesAP" targetNamespace="http://soa.estrellaroja.com.mx/InvoicesEnt/bpelValidateInvoicesAP" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/InvoicesEnt/bpelValidateInvoicesAP" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesEnt" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://schemas.oracle.com/bpel/extension" xmlns:ns2="http://soa.estrellaroja.com.mx/InvoicesAP">
   <plnk:partnerLinkType name="bpelValidateInvoicesAP">
      <plnk:role name="bpelValidateInvoicesAPProvider" portType="client:bpelValidateInvoicesAP"/>
   </plnk:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://soa.estrellaroja.com.mx/InvoicesEnt" schemaLocation="oramds:/apps/SOA/INER_InvoicesEnt/InvoicesEnt.xsd"/>
      </schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://soa.estrellaroja.com.mx/InvoicesAP" schemaLocation="../Schemas/InvoicesAP.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="ValidateInvoicesAPRq">
      <wsdl:part name="ValidateInvoicesAPRq" element="ns0:ValidateInvoicesAPRq"/>
   </wsdl:message>
   <wsdl:message name="ValidateInvoicesAPRs">
      <wsdl:part name="ValidateInvoicesAPRs" element="ns0:ValidateInvoicesAPRs"/>
   </wsdl:message>
   <wsdl:portType name="bpelValidateInvoicesAP">
      <wsdl:operation name="ValidateInvoicesAP">
         <wsdl:input message="client:ValidateInvoicesAPRq"/>
         <wsdl:output message="client:ValidateInvoicesAPRs"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
