<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="LetterPorteBiz" targetNamespace="http://soa.estrellaroja.com.mx/LetterPorteBiz" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://soa.estrellaroja.com.mx/LetterPorteBiz" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="wsLetterPorteBiz">
      <plnk:role name="LetterPorteBizPort" portType="tns:LetterPorteBizPort"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/LetterPorteBiz" location="oramds:/apps/SOA/LetterPorteBiz/LetterPorteBiz.wsdl"/>
</wsdl:definitions>
