<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="bpelUpdateUuid" targetNamespace="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelUpdateUuid" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelUpdateUuid" xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesBiz" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:ns4="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:ns5="http://soa.estrellaroja.com.mx/MessageTec">
   <plnk:partnerLinkType name="bpelUpdateUuid">
      <plnk:role name="bpelUpdateUuidProvider" portType="client:bpelUpdateUuid"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" location="ERPIntegrationServiceTecWrapper.wsdl"/>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" location="SOAUtilitiesTecWrapper.wsdl"/>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/MessageTec" location="MessageTecWrapper.wsdl"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelUpdateUuid" xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesBiz" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" xmlns:ns4="http://soa.estrellaroja.com.mx/SOAUtilitiesTec">
         <import namespace="http://soa.estrellaroja.com.mx/InvoicesBiz" schemaLocation="oramds:/apps/SOA/INER_InvoicesBiz/InvoicesBiz.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="UpdateUuidRq">
      <wsdl:part name="UpdateUuidRq" element="ns1:UpdateUuidRq"/>
   </wsdl:message>
   <wsdl:message name="UpdateUuidRs">
      <wsdl:part name="UpdateUuidRs" element="ns1:UpdateUuidRs"/>
   </wsdl:message>
   <wsdl:portType name="bpelUpdateUuid">
      <wsdl:operation name="UpdateUuid">
         <wsdl:input message="client:UpdateUuidRq"/>
         <wsdl:output message="client:UpdateUuidRs"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
