<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="bpelUpdateStatusInvoices" targetNamespace="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelUpdateStatusInvoices" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelUpdateStatusInvoices" xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesBiz" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://soa.estrellaroja.com.mx/FinancialsTec">
   <plnk:partnerLinkType name="bpelUpdateStatusInvoices">
      <plnk:role name="bpelUpdateStatusInvoicesProvider" portType="client:bpelUpdateStatusInvoices"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/FinancialsTec" location="FinancialsTecWrapper.wsdl"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://soa.estrellaroja.com.mx/InvoicesBiz" schemaLocation="oramds:/apps/SOA/INER_InvoicesBiz/InvoicesBiz.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="UpdateStatusInvoicesRq">
      <wsdl:part name="UpdateStatusInvoicesRq" element="ns1:UpdateStatusInvoicesRq"/>
   </wsdl:message>
   <wsdl:message name="UpdateStatusInvoicesRs">
      <wsdl:part name="UpdateStatusInvoicesRs" element="ns1:UpdateStatusInvoicesRs"/>
   </wsdl:message>
   <wsdl:portType name="bpelUpdateStatusInvoices">
      <wsdl:operation name="UpdateStatusInvoices">
         <wsdl:input message="client:UpdateStatusInvoicesRq"/>
         <wsdl:output message="client:UpdateStatusInvoicesRs"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
