<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="FinancialsTec"
     targetNamespace="http://soa.estrellaroja.com.mx/FinancialsTec"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://soa.estrellaroja.com.mx/FinancialsTec"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="wsFinancialsTec">
        <plnk:role name="FinancialsTecPortType" portType="tns:FinancialsTecPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soa.estrellaroja.com.mx/FinancialsTec" location="oramds:/apps/OSB/INER_FinancialsTec/FinancialsTec.wsdl"/>
</wsdl:definitions>
