<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://impl.utilities.cloud.estrellaroja.com.mx/" xmlns:tns="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns1="http://impl.utilities.cloud.estrellaroja.com.mx/types"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension"
                xmlns:client="http://soa.estrellaroja.com.mx/SOAUtilitiesTec/bpelbpelGenerateZipFile">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SOAUtilitiesImpl.wsdl"/>
            <oracle-xsl-mapper:rootElement name="createZipFileResponse" namespace="http://impl.utilities.cloud.estrellaroja.com.mx/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelGenerateZipFile.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GenerateZipFileRs" namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [SAT OCT 14 20:42:23 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GenerateZipFileRs>
         <xsl:if test="/ns0:createZipFileResponse/return/succcess">
            <ns3:Success/>
         </xsl:if>
         <xsl:if test="not (/ns0:createZipFileResponse/return/succcess )">
            <ns3:Errors>
               <xsl:if test="/ns0:createZipFileResponse/return/error">
                  <ns3:Error>
                     <ns3:ErrorCode>
                        <xsl:value-of select="/ns0:createZipFileResponse/return/error/errorCode"/>
                     </ns3:ErrorCode>
                     <ns3:ShortDescription>
                        <xsl:value-of select="/ns0:createZipFileResponse/return/error/shortDescription"/>
                     </ns3:ShortDescription>
                     <ns3:Description>
                        <xsl:value-of select="/ns0:createZipFileResponse/return/error/description"/>
                     </ns3:Description>
                     <ns3:BusinessProcess>
                        <xsl:value-of select="/ns0:createZipFileResponse/return/error/businessProcess"/>
                     </ns3:BusinessProcess>
                     <ns3:FailedService>
                        <xsl:value-of select="/ns0:createZipFileResponse/return/error/failedService"/>
                     </ns3:FailedService>
                     <ns3:TimeStamp>
                        <xsl:value-of select="xp20:current-dateTime ( )"/>
                     </ns3:TimeStamp>
                  </ns3:Error>
               </xsl:if>
            </ns3:Errors>
         </xsl:if>
         <xsl:if test="/ns0:createZipFileResponse/return/succcess">
            <tns:Return>
               <tns:ContentBase64>
                  <xsl:value-of select="/ns0:createZipFileResponse/return/returnType/encodeBase64"/>
               </tns:ContentBase64>
            </tns:Return>
         </xsl:if>
      </tns:GenerateZipFileRs>
   </xsl:template>
</xsl:stylesheet>
