<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://impl.utilities.cloud.estrellaroja.com.mx/" xmlns:tns="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns1="http://impl.utilities.cloud.estrellaroja.com.mx/types"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:client="http://xmlns.oracle.com/SOAUtilitiesTec/SOAUtilitiesTec/bpelGetHtmlControl">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SOAUtilitiesImpl.wsdl"/>
            <oracle-xsl-mapper:rootElement name="getHtmlControlResponse" namespace="http://impl.utilities.cloud.estrellaroja.com.mx/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelGetHtmlControl.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetHtmlControlRs" namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED DEC 27 11:26:21 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetHtmlControlRs>
         <xsl:if test="/ns0:getHtmlControlResponse/return/success = &quot;true&quot;">
            <ns2:Success/>
         </xsl:if>
         <xsl:if test="/ns0:getHtmlControlResponse/return/success = &quot;false&quot;">
            <ns2:Errors>
               <ns2:Error>
                  <ns2:ErrorCode>
                     <xsl:value-of select="/ns0:getHtmlControlResponse/return/error/errorCode"/>
                  </ns2:ErrorCode>
                  <ns2:ShortDescription>
                     <xsl:value-of select="/ns0:getHtmlControlResponse/return/error/shortDescription"/>
                  </ns2:ShortDescription>
                  <ns2:Description>
                     <xsl:value-of select="/ns0:getHtmlControlResponse/return/error/description"/>
                  </ns2:Description>
                  <ns2:BusinessProcess>
                     <xsl:value-of select="/ns0:getHtmlControlResponse/return/error/businessProcess"/>
                  </ns2:BusinessProcess>
                  <ns2:FailedService>
                     <xsl:value-of select="/ns0:getHtmlControlResponse/return/error/failedService"/>
                  </ns2:FailedService>
                  <ns2:TimeStamp>
                     <xsl:value-of select="xp20:current-dateTime ( )"/>
                  </ns2:TimeStamp>
               </ns2:Error>
            </ns2:Errors>
         </xsl:if>
         <xsl:if test="/ns0:getHtmlControlResponse/return/returnType/htmlControl">
            <tns:Return>
               <tns:HtmlControl>
                  <xsl:value-of select="/ns0:getHtmlControlResponse/return/returnType/htmlControl"/>
               </tns:HtmlControl>
            </tns:Return>
         </xsl:if>
      </tns:GetHtmlControlRs>
   </xsl:template>
</xsl:stylesheet>
