<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://soa.estrellaroja.com.mx/DigitalStampTec" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/cfd/3"
                xmlns:ns4="http://soa.estrellaroja.com.mx/DigitalStampTec/types"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelDigitalStamp"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns5="http://soa.estrellaroja.com.mx/sitio_internet/cfd/tipoDatos/tdCFDI"
                xmlns:ns7="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns6="http://soa.estrellaroja.com.mx/TimbreFiscalDigital"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns8="http://soa.estrellaroja.com.mx/AuditControlTec/types"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns9="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns10="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DigitalStampTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="createTrxCFDIRs" namespace="http://soa.estrellaroja.com.mx/DigitalStampTec"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelDigitalStamp.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DATA_DS" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
            <oracle-xsl-mapper:param name="varInvoice"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/AuditControlTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InsertArElecInvoiceErrorsRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU JAN 04 19:06:03 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varInvoice"/>
   <xsl:template match="/">
      <tns:InsertArElecInvoiceErrorsRq>
         <tns:ElecInvoiceErrors>
            <tns:customerTrxId>
               <xsl:value-of select="$varInvoice/ns1:DATA_DS/ns1:invoice/ns1:CUSTOMER_TRX_ID"/>
            </tns:customerTrxId>
            <tns:numeroFactura>
               <xsl:value-of select="$varInvoice/ns1:DATA_DS/ns1:invoice/ns1:TRX_NUMBER"/>
            </tns:numeroFactura>
            <tns:tipocfd>
               <xsl:value-of select="$varInvoice/ns1:DATA_DS/ns1:invoice/ns1:document_type"/>
            </tns:tipocfd>
            <tns:payload/>
            <tns:errorCode>
               <xsl:value-of select="/ns0:createTrxCFDIRs/ns1:Errors/ns1:Error/ns1:ErrorCode"/>
            </tns:errorCode>
            <tns:errorDescription>
               <xsl:value-of select="substring (/ns0:createTrxCFDIRs/ns2:Errors/ns2:Error/ns2:Description, 0, 2400 )"/>
            </tns:errorDescription>
            <tns:creationDate>
               <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:creationDate>
            <tns:lastUpdateDate>
               <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:lastUpdateDate>
            <tns:createdBy>InvoicesBiz</tns:createdBy>
            <tns:lastUpdatedBy>InvoicesBiz</tns:lastUpdatedBy>
         </tns:ElecInvoiceErrors>
      </tns:InsertArElecInvoiceErrorsRq>
   </xsl:template>
</xsl:stylesheet>
