<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns4="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns5="http://soa.estrellaroja.com.mx/cfd/3"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ElectronicInvoiceAP"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelValidateInvoicesAP"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns6="http://soa.estrellaroja.com.mx/sitio_internet/cfd/tipoDatos/tdCFDI"
                xmlns:ns1="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns7="http://soa.estrellaroja.com.mx/TimbreFiscalDigital"
                xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0"
                xmlns:ns8="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/"
                xmlns:ns10="http://xmlns.oracle.com/adf/svc/types/" xmlns:ns11="commonj.sdo/xml"
                xmlns:ns12="commonj.sdo/java"
                xmlns:ns9="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns13="commonj.sdo"
                xmlns:ns18="http://www.sat.gob.mx/ConsumoDeCombustibles11"
                xmlns:ns19="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos"
                xmlns:ns21="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/ComExt"
                xmlns:ns27="http://www.sat.gob.mx/sitio_internet/cfd/catalogos"
                xmlns:ns15="http://www.sat.gob.mx/TimbreFiscalDigital"
                xmlns:ns16="http://www.sat.gob.mx/EstadoDeCuentaCombustible12"
                xmlns:ns17="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina"
                xmlns:ns14="http://www.sat.gob.mx/cfd/4"
                xmlns:ns20="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte"
                xmlns:ns22="http://www.sat.gob.mx/CartaPorte20"
                xmlns:ns23="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Combustible"
                xmlns:ns24="http://www.sat.gob.mx/nomina12"
                xmlns:ns25="http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI"
                xmlns:ns26="http://www.sat.gob.mx/Pagos20"
                xmlns:ns28="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelValidateInvoicesAP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InvoiceAP" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ServiceERP/ErpIntegrationService.xsd"/>
            <oracle-xsl-mapper:rootElement name="submitESSJobRequest" namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 10 10:57:54 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
            <tns:submitESSJobRequest>
         <tns:jobPackageName>
            <xsl:value-of select="&quot;oracle/apps/ess/financials/payables/invoices/transactions&quot;"/>
         </tns:jobPackageName>
         <tns:jobDefinitionName>
            <xsl:value-of select='"APXAPRVL"'/>
         </tns:jobDefinitionName>
         <tns:paramList>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:OrganizationId"/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"ALL"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"#NULL"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"#NULL"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"#NULL"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"#NULL"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceId"/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"#NULL"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"#NULL"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"300000002834552"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select="&quot;#NULL&quot;"/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select="&quot;1&quot;"/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"#NULL"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"#NULL"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"#NULL"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"1"'/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select='"#NULL"'/>
         </tns:paramList>
      </tns:submitESSJobRequest>
   </xsl:template>
</xsl:stylesheet>
