<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:tns="http://soa.estrellaroja.com.mx/InvoicesBiz/StructursInvoicesBiz" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelBuildInvoicesZip"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns5="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns4="http://soa.estrellaroja.com.mx/FinancialsTec"
                xmlns:ns6="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelBuildInvoicesZip.wsdl"/>
            <oracle-xsl-mapper:rootElement name="invoicesToCsv" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelBuildInvoicesZip.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ListStructureInvoicesCSV" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz/StructursInvoicesBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE MAR 13 21:02:55 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ListStructureInvoicesCSV>
         <tns:List>
            <tns:InvoicesCSV>
               <xsl:for-each select="/ns0:invoicesToCsv/ns0:InvoicesList">
                  <tns:ReturnList>
                     <tns:Notes_from_Source>
                        <xsl:value-of select="ns0:Notes_from_Source"/>
                     </tns:Notes_from_Source>
                     <tns:Transaction_Batch_Source_Name>
                        <xsl:value-of select="ns0:Transaction_Batch_Source_Name"/>
                     </tns:Transaction_Batch_Source_Name>
                     <tns:Transaction_Type_Name>
                        <xsl:value-of select="ns0:Transaction_Type_Name"/>
                     </tns:Transaction_Type_Name>
                     <tns:Payment_Terms>
                        <xsl:value-of select="ns0:Payment_Terms"/>
                     </tns:Payment_Terms>
                     <tns:Transaction_Date>
                        <xsl:value-of select="ns0:Transaction_Date"/>
                     </tns:Transaction_Date>
                     <tns:Accounting_Date>
                        <xsl:value-of select="ns0:Accounting_Date"/>
                     </tns:Accounting_Date>
                     <tns:Transaction_Number>
                        <xsl:value-of select="ns0:Transaction_Number"/>
                     </tns:Transaction_Number>
                     <tns:Original_System_Bill_to_Customer_Reference>
                        <xsl:value-of select="ns0:Original_System_Bill_to_Customer_Reference"/>
                     </tns:Original_System_Bill_to_Customer_Reference>
                     <tns:Original_System_Bill_to_Customer_Address_Reference>
                        <xsl:value-of select="ns0:Original_System_Bill_to_Customer_Address_Reference"/>
                     </tns:Original_System_Bill_to_Customer_Address_Reference>
                     <tns:Original_System_Bill_to_Customer_Contact_Reference>
                        <xsl:value-of select="ns0:Original_System_Bill_to_Customer_Contact_Reference"/>
                     </tns:Original_System_Bill_to_Customer_Contact_Reference>
                     <tns:Original_System_Ship_to_Customer_Reference>
                        <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Reference"/>
                     </tns:Original_System_Ship_to_Customer_Reference>
                     <tns:Original_System_Ship_to_Customer_Address_Reference>
                        <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Address_Reference"/>
                     </tns:Original_System_Ship_to_Customer_Address_Reference>
                     <tns:Original_System_Ship_to_Customer_Contact_Reference>
                        <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Contact_Reference"/>
                     </tns:Original_System_Ship_to_Customer_Contact_Reference>
                     <tns:Original_System_Ship_to_Customer_Account_Reference>
                        <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Account_Reference"/>
                     </tns:Original_System_Ship_to_Customer_Account_Reference>
                     <tns:Original_System_Ship_to_Customer_Account_Address_Reference>
                        <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Account_Address_Reference"/>
                     </tns:Original_System_Ship_to_Customer_Account_Address_Reference>
                     <tns:Original_System_Ship_to_Customer_Account_Contact_Reference>
                        <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Account_Contact_Reference"/>
                     </tns:Original_System_Ship_to_Customer_Account_Contact_Reference>
                     <tns:Original_System_Sold_to_Customer_Reference>
                        <xsl:value-of select="ns0:Original_System_Sold_to_Customer_Reference"/>
                     </tns:Original_System_Sold_to_Customer_Reference>
                     <tns:Original_System_Sold_to_Customer_Account_Reference>
                        <xsl:value-of select="ns0:Original_System_Sold_to_Customer_Account_Reference"/>
                     </tns:Original_System_Sold_to_Customer_Account_Reference>
                     <tns:Bill_to_Customer_Account_Number>
                        <xsl:value-of select="ns0:Bill_to_Customer_Account_Number"/>
                     </tns:Bill_to_Customer_Account_Number>
                     <tns:Bill_to_Customer_Site_Number>
                        <xsl:value-of select="ns0:Bill_to_Customer_Site_Number"/>
                     </tns:Bill_to_Customer_Site_Number>
                     <tns:Bill_to_Contact_Party_Number>
                        <xsl:value-of select="ns0:Bill_to_Contact_Party_Number"/>
                     </tns:Bill_to_Contact_Party_Number>
                     <tns:Ship_to_Customer_Account_Number>
                        <xsl:value-of select="ns0:Ship_to_Customer_Account_Number"/>
                     </tns:Ship_to_Customer_Account_Number>
                     <tns:Ship_to_Customer_Site_Number>
                        <xsl:value-of select="ns0:Ship_to_Customer_Site_Number"/>
                     </tns:Ship_to_Customer_Site_Number>
                     <tns:Ship_to_Contact_Party_Number>
                        <xsl:value-of select="ns0:Ship_to_Contact_Party_Number"/>
                     </tns:Ship_to_Contact_Party_Number>
                     <tns:Sold_to_Customer_Account_Number>
                        <xsl:value-of select="ns0:Sold_to_Customer_Account_Number"/>
                     </tns:Sold_to_Customer_Account_Number>
                     <tns:Transaction_Line_Type>
                        <xsl:value-of select="ns0:Transaction_Line_Type"/>
                     </tns:Transaction_Line_Type>
                     <tns:Transaction_Line_Description>
                        <xsl:value-of select="ns0:Transaction_Line_Description"/>
                     </tns:Transaction_Line_Description>
                     <tns:Currency_Code>
                        <xsl:value-of select="ns0:Currency_Code"/>
                     </tns:Currency_Code>
                     <tns:Currency_Conversion_Type>
                        <xsl:value-of select="ns0:Currency_Conversion_Type"/>
                     </tns:Currency_Conversion_Type>
                     <tns:Currency_Conversion_Date>
                        <xsl:value-of select="ns0:Currency_Conversion_Date"/>
                     </tns:Currency_Conversion_Date>
                     <tns:Currency_Conversion_Rate>
                        <xsl:value-of select="ns0:Currency_Conversion_Rate"/>
                     </tns:Currency_Conversion_Rate>
                     <tns:Transaction_Line_Amount>
                        <xsl:value-of select="ns0:Transaction_Line_Amount"/>
                     </tns:Transaction_Line_Amount>
                     <tns:Transaction_Line_Quantity>
                        <xsl:value-of select="ns0:Transaction_Line_Quantity"/>
                     </tns:Transaction_Line_Quantity>
                     <tns:Customer_Ordered_Quantity>
                        <xsl:value-of select="ns0:Customer_Ordered_Quantity"/>
                     </tns:Customer_Ordered_Quantity>
                     <tns:Unit_Selling_Price>
                        <xsl:value-of select="ns0:Unit_Selling_Price"/>
                     </tns:Unit_Selling_Price>
                     <tns:Unit_Standard_Price>
                        <xsl:value-of select="ns0:Unit_Standard_Price"/>
                     </tns:Unit_Standard_Price>
                     <tns:Line_Transactions_Flexfield_Context>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Context"/>
                     </tns:Line_Transactions_Flexfield_Context>
                     <tns:Line_Transactions_Flexfield_Segment_1>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_1"/>
                     </tns:Line_Transactions_Flexfield_Segment_1>
                     <tns:Line_Transactions_Flexfield_Segment_2>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_2"/>
                     </tns:Line_Transactions_Flexfield_Segment_2>
                     <tns:Line_Transactions_Flexfield_Segment_3>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_3"/>
                     </tns:Line_Transactions_Flexfield_Segment_3>
                     <tns:Line_Transactions_Flexfield_Segment_4>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_4"/>
                     </tns:Line_Transactions_Flexfield_Segment_4>
                     <tns:Line_Transactions_Flexfield_Segment_5>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_5"/>
                     </tns:Line_Transactions_Flexfield_Segment_5>
                     <tns:Line_Transactions_Flexfield_Segment_6>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_6"/>
                     </tns:Line_Transactions_Flexfield_Segment_6>
                     <tns:Line_Transactions_Flexfield_Segment_7>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_7"/>
                     </tns:Line_Transactions_Flexfield_Segment_7>
                     <tns:Line_Transactions_Flexfield_Segment_8>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_8"/>
                     </tns:Line_Transactions_Flexfield_Segment_8>
                     <tns:Line_Transactions_Flexfield_Segment_9>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_9"/>
                     </tns:Line_Transactions_Flexfield_Segment_9>
                     <tns:Line_Transactions_Flexfield_Segment_10>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_10"/>
                     </tns:Line_Transactions_Flexfield_Segment_10>
                     <tns:Line_Transactions_Flexfield_Segment_11>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_11"/>
                     </tns:Line_Transactions_Flexfield_Segment_11>
                     <tns:Line_Transactions_Flexfield_Segment_12>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_12"/>
                     </tns:Line_Transactions_Flexfield_Segment_12>
                     <tns:Line_Transactions_Flexfield_Segment_13>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_13"/>
                     </tns:Line_Transactions_Flexfield_Segment_13>
                     <tns:Line_Transactions_Flexfield_Segment_14>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_14"/>
                     </tns:Line_Transactions_Flexfield_Segment_14>
                     <tns:Line_Transactions_Flexfield_Segment_15>
                        <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_15"/>
                     </tns:Line_Transactions_Flexfield_Segment_15>
                     <tns:Primary_Salesperson_Number>
                        <xsl:value-of select="ns0:Primary_Salesperson_Number"/>
                     </tns:Primary_Salesperson_Number>
                     <tns:Tax_Classification_Code>
                        <xsl:value-of select="ns0:Tax_Classification_Code"/>
                     </tns:Tax_Classification_Code>
                     <tns:Legal_Entity_Identifier>
                        <xsl:value-of select="ns0:Legal_Entity_Identifier"/>
                     </tns:Legal_Entity_Identifier>
                     <tns:Accounted_Amount_in_Ledger_Currency>
                        <xsl:value-of select="ns0:Accounted_Amount_in_Ledger_Currency"/>
                     </tns:Accounted_Amount_in_Ledger_Currency>
                     <tns:Sales_Order_Number>
                        <xsl:value-of select="ns0:Sales_Order_Number"/>
                     </tns:Sales_Order_Number>
                     <tns:Sales_Order_Date>
                        <xsl:value-of select="ns0:Sales_Order_Date"/>
                     </tns:Sales_Order_Date>
                     <tns:Actual_Ship_Date>
                        <xsl:value-of select="ns0:Actual_Ship_Date"/>
                     </tns:Actual_Ship_Date>
                     <tns:Warehouse_Code>
                        <xsl:value-of select="ns0:Warehouse_Code"/>
                     </tns:Warehouse_Code>
                     <tns:Unit_of_Measure_Code>
                        <xsl:value-of select="ns0:Unit_of_Measure_Code"/>
                     </tns:Unit_of_Measure_Code>
                     <tns:Unit_of_Measure_Name>
                        <xsl:value-of select="ns0:Unit_of_Measure_Name"/>
                     </tns:Unit_of_Measure_Name>
                     <tns:Invoicing_Rule_Name>
                        <xsl:value-of select="ns0:Invoicing_Rule_Name"/>
                     </tns:Invoicing_Rule_Name>
                     <tns:Revenue_Scheduling_Rule_Name>
                        <xsl:value-of select="ns0:Revenue_Scheduling_Rule_Name"/>
                     </tns:Revenue_Scheduling_Rule_Name>
                     <tns:Number_of_Revenue_Periods>
                        <xsl:value-of select="ns0:Number_of_Revenue_Periods"/>
                     </tns:Number_of_Revenue_Periods>
                     <tns:Revenue_Scheduling_Rule_Start_Date>
                        <xsl:value-of select="ns0:Revenue_Scheduling_Rule_Start_Date"/>
                     </tns:Revenue_Scheduling_Rule_Start_Date>
                     <tns:Revenue_Scheduling_Rule_End_Date>
                        <xsl:value-of select="ns0:Revenue_Scheduling_Rule_End_Date"/>
                     </tns:Revenue_Scheduling_Rule_End_Date>
                     <tns:Reason_Code_Meaning>
                        <xsl:value-of select="ns0:Reason_Code_Meaning"/>
                     </tns:Reason_Code_Meaning>
                     <tns:Last_Period_to_Credit>
                        <xsl:value-of select="ns0:Last_Period_to_Credit"/>
                     </tns:Last_Period_to_Credit>
                     <tns:Transaction_Business_Category_Code>
                        <xsl:value-of select="ns0:Transaction_Business_Category_Code"/>
                     </tns:Transaction_Business_Category_Code>
                     <tns:Product_Fiscal_Classification_Code>
                        <xsl:value-of select="ns0:Product_Fiscal_Classification_Code"/>
                     </tns:Product_Fiscal_Classification_Code>
                     <tns:Product_Category_Code>
                        <xsl:value-of select="ns0:Product_Category_Code"/>
                     </tns:Product_Category_Code>
                     <tns:Product_Type>
                        <xsl:value-of select="ns0:Product_Type"/>
                     </tns:Product_Type>
                     <tns:Line_Intended_Use_Code>
                        <xsl:value-of select="ns0:Line_Intended_Use_Code"/>
                     </tns:Line_Intended_Use_Code>
                     <tns:Assessable_Value>
                        <xsl:value-of select="ns0:Assessable_Value"/>
                     </tns:Assessable_Value>
                     <tns:Document_Sub_Type>
                        <xsl:value-of select="ns0:Document_Sub_Type"/>
                     </tns:Document_Sub_Type>
                     <tns:Default_Taxation_Country>
                        <xsl:value-of select="ns0:Default_Taxation_Country"/>
                     </tns:Default_Taxation_Country>
                     <tns:User_Defined_Fiscal_Classification>
                        <xsl:value-of select="ns0:User_Defined_Fiscal_Classification"/>
                     </tns:User_Defined_Fiscal_Classification>
                     <tns:Tax_Invoice_Number>
                        <xsl:value-of select="ns0:Tax_Invoice_Number"/>
                     </tns:Tax_Invoice_Number>
                     <tns:Tax_Invoice_Date>
                        <xsl:value-of select="ns0:Tax_Invoice_Date"/>
                     </tns:Tax_Invoice_Date>
                     <tns:Tax_Regime_Code>
                        <xsl:value-of select="ns0:Tax_Regime_Code"/>
                     </tns:Tax_Regime_Code>
                     <tns:Tax>
                        <xsl:value-of select="ns0:Tax"/>
                     </tns:Tax>
                     <tns:Tax_Status_Code>
                        <xsl:value-of select="ns0:Tax_Status_Code"/>
                     </tns:Tax_Status_Code>
                     <tns:Tax_Rate_Code>
                        <xsl:value-of select="ns0:Tax_Rate_Code"/>
                     </tns:Tax_Rate_Code>
                     <tns:Tax_Jurisdiction_Code>
                        <xsl:value-of select="ns0:Tax_Jurisdiction_Code"/>
                     </tns:Tax_Jurisdiction_Code>
                     <tns:First_Party_Registration_Number>
                        <xsl:value-of select="ns0:First_Party_Registration_Number"/>
                     </tns:First_Party_Registration_Number>
                     <tns:Third_Party_Registration_Number>
                        <xsl:value-of select="ns0:Third_Party_Registration_Number"/>
                     </tns:Third_Party_Registration_Number>
                     <tns:Final_Discharge_Location>
                        <xsl:value-of select="ns0:Final_Discharge_Location"/>
                     </tns:Final_Discharge_Location>
                     <tns:Taxable_Amount>
                        <xsl:value-of select="ns0:Taxable_Amount"/>
                     </tns:Taxable_Amount>
                     <tns:Taxable_Flag>
                        <xsl:value-of select="ns0:Taxable_Flag"/>
                     </tns:Taxable_Flag>
                     <tns:Tax_Exemption_Flag>
                        <xsl:value-of select="ns0:Tax_Exemption_Flag"/>
                     </tns:Tax_Exemption_Flag>
                     <tns:TTax_Exemption_Reason_Code>
                        <xsl:value-of select="ns0:TTax_Exemption_Reason_Code"/>
                     </tns:TTax_Exemption_Reason_Code>
                     <tns:Tax_Exemption_Reason_Code_Meaning>
                        <xsl:value-of select="ns0:Tax_Exemption_Reason_Code_Meaning"/>
                     </tns:Tax_Exemption_Reason_Code_Meaning>
                     <tns:Tax_Exemption_Certificate_Number>
                        <xsl:value-of select="ns0:Tax_Exemption_Certificate_Number"/>
                     </tns:Tax_Exemption_Certificate_Number>
                     <tns:Line_Amount_Includes_Tax_Flag>
                        <xsl:value-of select="ns0:Line_Amount_Includes_Tax_Flag"/>
                     </tns:Line_Amount_Includes_Tax_Flag>
                     <tns:Tax_Precedence>
                        <xsl:value-of select="ns0:Tax_Precedence"/>
                     </tns:Tax_Precedence>
                     <tns:Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules>
                        <xsl:value-of select="ns0:Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules"/>
                     </tns:Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules>
                     <tns:Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms>
                        <xsl:value-of select="ns0:Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms"/>
                     </tns:Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms>
                     <tns:Reason_Code>
                        <xsl:value-of select="ns0:Reason_Code"/>
                     </tns:Reason_Code>
                     <tns:Tax_Rate>
                        <xsl:value-of select="ns0:Tax_Rate"/>
                     </tns:Tax_Rate>
                     <tns:FOB_Point>
                        <xsl:value-of select="ns0:FOB_Point"/>
                     </tns:FOB_Point>
                     <tns:Carrier>
                        <xsl:value-of select="ns0:Carrier"/>
                     </tns:Carrier>
                     <tns:Shipping_Reference>
                        <xsl:value-of select="ns0:Shipping_Reference"/>
                     </tns:Shipping_Reference>
                     <tns:Sales_Order_Line_Number>
                        <xsl:value-of select="ns0:Sales_Order_Line_Number"/>
                     </tns:Sales_Order_Line_Number>
                     <tns:Sales_Order_Source>
                        <xsl:value-of select="ns0:Sales_Order_Source"/>
                     </tns:Sales_Order_Source>
                     <tns:Sales_Order_Revision_Number>
                        <xsl:value-of select="ns0:Sales_Order_Revision_Number"/>
                     </tns:Sales_Order_Revision_Number>
                     <tns:Purchase_Order_Number>
                        <xsl:value-of select="ns0:Purchase_Order_Number"/>
                     </tns:Purchase_Order_Number>
                     <tns:Purchase_Order_Revision_Number>
                        <xsl:value-of select="ns0:Purchase_Order_Revision_Number"/>
                     </tns:Purchase_Order_Revision_Number>
                     <tns:Purchase_Order_Date>
                        <xsl:value-of select="ns0:Purchase_Order_Date"/>
                     </tns:Purchase_Order_Date>
                     <tns:Agreement_Name>
                        <xsl:value-of select="ns0:Agreement_Name"/>
                     </tns:Agreement_Name>
                     <tns:Memo_Line_Name>
                        <xsl:value-of select="ns0:Memo_Line_Name"/>
                     </tns:Memo_Line_Name>
                     <tns:Document_Number>
                        <xsl:value-of select="ns0:Document_Number"/>
                     </tns:Document_Number>
                     <tns:Original_System_Batch_Name>
                        <xsl:value-of select="ns0:Original_System_Batch_Name"/>
                     </tns:Original_System_Batch_Name>
                     <tns:Link_to_Transactions_Flexfield_Context>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Context"/>
                     </tns:Link_to_Transactions_Flexfield_Context>
                     <tns:Link_to_Transactions_Flexfield_Segment_1>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_1"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_1>
                     <tns:Link_to_Transactions_Flexfield_Segment_2>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_2"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_2>
                     <tns:Link_to_Transactions_Flexfield_Segment_3>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_3"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_3>
                     <tns:Link_to_Transactions_Flexfield_Segment_4>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_4"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_4>
                     <tns:Link_to_Transactions_Flexfield_Segment_5>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_5"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_5>
                     <tns:Link_to_Transactions_Flexfield_Segment_6>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_6"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_6>
                     <tns:Link_to_Transactions_Flexfield_Segment_7>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_7"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_7>
                     <tns:Link_to_Transactions_Flexfield_Segment_8>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_8"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_8>
                     <tns:Link_to_Transactions_Flexfield_Segment_9>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_9"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_9>
                     <tns:Link_to_Transactions_Flexfield_Segment_10>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_10"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_10>
                     <tns:Link_to_Transactions_Flexfield_Segment_11>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_11"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_11>
                     <tns:Link_to_Transactions_Flexfield_Segment_12>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_12"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_12>
                     <tns:Link_to_Transactions_Flexfield_Segment_13>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_13"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_13>
                     <tns:Link_to_Transactions_Flexfield_Segment_14>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_14"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_14>
                     <tns:Link_to_Transactions_Flexfield_Segment_15>
                        <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_15"/>
                     </tns:Link_to_Transactions_Flexfield_Segment_15>
                     <tns:Reference_Transactions_Flexfield_Context>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Context"/>
                     </tns:Reference_Transactions_Flexfield_Context>
                     <tns:Reference_Transactions_Flexfield_Segment_1>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_1"/>
                     </tns:Reference_Transactions_Flexfield_Segment_1>
                     <tns:Reference_Transactions_Flexfield_Segment_2>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_2"/>
                     </tns:Reference_Transactions_Flexfield_Segment_2>
                     <tns:Reference_Transactions_Flexfield_Segment_3>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_3"/>
                     </tns:Reference_Transactions_Flexfield_Segment_3>
                     <tns:Reference_Transactions_Flexfield_Segment_4>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_4"/>
                     </tns:Reference_Transactions_Flexfield_Segment_4>
                     <tns:Reference_Transactions_Flexfield_Segment_5>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_5"/>
                     </tns:Reference_Transactions_Flexfield_Segment_5>
                     <tns:Reference_Transactions_Flexfield_Segment_6>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_6"/>
                     </tns:Reference_Transactions_Flexfield_Segment_6>
                     <tns:Reference_Transactions_Flexfield_Segment_7>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_7"/>
                     </tns:Reference_Transactions_Flexfield_Segment_7>
                     <tns:Reference_Transactions_Flexfield_Segment_8>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_8"/>
                     </tns:Reference_Transactions_Flexfield_Segment_8>
                     <tns:Reference_Transactions_Flexfield_Segment_9>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_9"/>
                     </tns:Reference_Transactions_Flexfield_Segment_9>
                     <tns:Reference_Transactions_Flexfield_Segment_10>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_10"/>
                     </tns:Reference_Transactions_Flexfield_Segment_10>
                     <tns:Reference_Transactions_Flexfield_Segment_11>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_11"/>
                     </tns:Reference_Transactions_Flexfield_Segment_11>
                     <tns:Reference_Transactions_Flexfield_Segment_12>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_12"/>
                     </tns:Reference_Transactions_Flexfield_Segment_12>
                     <tns:Reference_Transactions_Flexfield_Segment_13>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_13"/>
                     </tns:Reference_Transactions_Flexfield_Segment_13>
                     <tns:Reference_Transactions_Flexfield_Segment_14>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_14"/>
                     </tns:Reference_Transactions_Flexfield_Segment_14>
                     <tns:Reference_Transactions_Flexfield_Segment_15>
                        <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_15"/>
                     </tns:Reference_Transactions_Flexfield_Segment_15>
                     <tns:Link_To_Parent_Line_Context>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Context"/>
                     </tns:Link_To_Parent_Line_Context>
                     <tns:Link_To_Parent_Line_Segment_1>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_1"/>
                     </tns:Link_To_Parent_Line_Segment_1>
                     <tns:Link_To_Parent_Line_Segment_2>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_2"/>
                     </tns:Link_To_Parent_Line_Segment_2>
                     <tns:Link_To_Parent_Line_Segment_3>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_3"/>
                     </tns:Link_To_Parent_Line_Segment_3>
                     <tns:Link_To_Parent_Line_Segment_4>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_4"/>
                     </tns:Link_To_Parent_Line_Segment_4>
                     <tns:Link_To_Parent_Line_Segment_5>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_5"/>
                     </tns:Link_To_Parent_Line_Segment_5>
                     <tns:Link_To_Parent_Line_Segment_6>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_6"/>
                     </tns:Link_To_Parent_Line_Segment_6>
                     <tns:Link_To_Parent_Line_Segment_7>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_7"/>
                     </tns:Link_To_Parent_Line_Segment_7>
                     <tns:Link_To_Parent_Line_Segment_8>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_8"/>
                     </tns:Link_To_Parent_Line_Segment_8>
                     <tns:Link_To_Parent_Line_Segment_9>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_9"/>
                     </tns:Link_To_Parent_Line_Segment_9>
                     <tns:Link_To_Parent_Line_Segment_10>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_10"/>
                     </tns:Link_To_Parent_Line_Segment_10>
                     <tns:Link_To_Parent_Line_Segment_11>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_11"/>
                     </tns:Link_To_Parent_Line_Segment_11>
                     <tns:Link_To_Parent_Line_Segment_12>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_12"/>
                     </tns:Link_To_Parent_Line_Segment_12>
                     <tns:Link_To_Parent_Line_Segment_13>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_13"/>
                     </tns:Link_To_Parent_Line_Segment_13>
                     <tns:Link_To_Parent_Line_Segment_14>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_14"/>
                     </tns:Link_To_Parent_Line_Segment_14>
                     <tns:Link_To_Parent_Line_Segment_15>
                        <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_15"/>
                     </tns:Link_To_Parent_Line_Segment_15>
                     <tns:Receipt_Method_Name>
                        <xsl:value-of select="ns0:Receipt_Method_Name"/>
                     </tns:Receipt_Method_Name>
                     <tns:Printing_Option>
                        <xsl:value-of select="ns0:Printing_Option"/>
                     </tns:Printing_Option>
                     <tns:Related_Batch_Source_Name>
                        <xsl:value-of select="ns0:Related_Batch_Source_Name"/>
                     </tns:Related_Batch_Source_Name>
                     <tns:Related_Transaction_Number>
                        <xsl:value-of select="ns0:Related_Transaction_Number"/>
                     </tns:Related_Transaction_Number>
                     <tns:Inventory_Item_Number>
                        <xsl:value-of select="ns0:Inventory_Item_Number"/>
                     </tns:Inventory_Item_Number>
                     <tns:Inventory_Item_Segment_2>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_2"/>
                     </tns:Inventory_Item_Segment_2>
                     <tns:Inventory_Item_Segment_3>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_3"/>
                     </tns:Inventory_Item_Segment_3>
                     <tns:Inventory_Item_Segment_4>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_4"/>
                     </tns:Inventory_Item_Segment_4>
                     <tns:Inventory_Item_Segment_5>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_5"/>
                     </tns:Inventory_Item_Segment_5>
                     <tns:Inventory_Item_Segment_6>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_6"/>
                     </tns:Inventory_Item_Segment_6>
                     <tns:Inventory_Item_Segment_7>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_7"/>
                     </tns:Inventory_Item_Segment_7>
                     <tns:Inventory_Item_Segment_8>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_8"/>
                     </tns:Inventory_Item_Segment_8>
                     <tns:Inventory_Item_Segment_9>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_9"/>
                     </tns:Inventory_Item_Segment_9>
                     <tns:Inventory_Item_Segment_10>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_10"/>
                     </tns:Inventory_Item_Segment_10>
                     <tns:Inventory_Item_Segment_11>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_11"/>
                     </tns:Inventory_Item_Segment_11>
                     <tns:Inventory_Item_Segment_12>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_12"/>
                     </tns:Inventory_Item_Segment_12>
                     <tns:Inventory_Item_Segment_13>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_13"/>
                     </tns:Inventory_Item_Segment_13>
                     <tns:Inventory_Item_Segment_14>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_14"/>
                     </tns:Inventory_Item_Segment_14>
                     <tns:Inventory_Item_Segment_15>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_15"/>
                     </tns:Inventory_Item_Segment_15>
                     <tns:Inventory_Item_Segment_16>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_16"/>
                     </tns:Inventory_Item_Segment_16>
                     <tns:Inventory_Item_Segment_17>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_17"/>
                     </tns:Inventory_Item_Segment_17>
                     <tns:Inventory_Item_Segment_18>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_18"/>
                     </tns:Inventory_Item_Segment_18>
                     <tns:Inventory_Item_Segment_19>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_19"/>
                     </tns:Inventory_Item_Segment_19>
                     <tns:Inventory_Item_Segment_20>
                        <xsl:value-of select="ns0:Inventory_Item_Segment_20"/>
                     </tns:Inventory_Item_Segment_20>
                     <tns:Bill_To_Customer_Bank_Account_Name>
                        <xsl:value-of select="ns0:Bill_To_Customer_Bank_Account_Name"/>
                     </tns:Bill_To_Customer_Bank_Account_Name>
                     <tns:Reset_Transaction_Date_Flag>
                        <xsl:value-of select="ns0:Reset_Transaction_Date_Flag"/>
                     </tns:Reset_Transaction_Date_Flag>
                     <tns:Payment_Server_Order_Number>
                        <xsl:value-of select="ns0:Payment_Server_Order_Number"/>
                     </tns:Payment_Server_Order_Number>
                     <tns:Last_Transaction_on_Debit_Authorization>
                        <xsl:value-of select="ns0:Last_Transaction_on_Debit_Authorization"/>
                     </tns:Last_Transaction_on_Debit_Authorization>
                     <tns:Approval_Code>
                        <xsl:value-of select="ns0:Approval_Code"/>
                     </tns:Approval_Code>
                     <tns:Address_Verification_Code>
                        <xsl:value-of select="ns0:Address_Verification_Code"/>
                     </tns:Address_Verification_Code>
                     <tns:Transaction_Line_Translated_Description>
                        <xsl:value-of select="ns0:Transaction_Line_Translated_Description"/>
                     </tns:Transaction_Line_Translated_Description>
                     <tns:Consolidated_Billing_Number>
                        <xsl:value-of select="ns0:Consolidated_Billing_Number"/>
                     </tns:Consolidated_Billing_Number>
                     <tns:Promised_Commitment_Amount>
                        <xsl:value-of select="ns0:Promised_Commitment_Amount"/>
                     </tns:Promised_Commitment_Amount>
                     <tns:Payment_Set_Identifier>
                        <xsl:value-of select="ns0:Payment_Set_Identifier"/>
                     </tns:Payment_Set_Identifier>
                     <tns:Original_Accounting_Date>
                        <xsl:value-of select="ns0:Original_Accounting_Date"/>
                     </tns:Original_Accounting_Date>
                     <tns:Invoiced_Line_Accounting_Level>
                        <xsl:value-of select="ns0:Invoiced_Line_Accounting_Level"/>
                     </tns:Invoiced_Line_Accounting_Level>
                     <tns:Override_AutoAccounting_Flag>
                        <xsl:value-of select="ns0:Override_AutoAccounting_Flag"/>
                     </tns:Override_AutoAccounting_Flag>
                     <tns:Historical_Flag>
                        <xsl:value-of select="ns0:Historical_Flag"/>
                     </tns:Historical_Flag>
                     <tns:Deferral_Exclusion_Flag>
                        <xsl:value-of select="ns0:Deferral_Exclusion_Flag"/>
                     </tns:Deferral_Exclusion_Flag>
                     <tns:Payment_Attributes>
                        <xsl:value-of select="ns0:Payment_Attributes"/>
                     </tns:Payment_Attributes>
                     <tns:Invoice_Billing_Date>
                        <xsl:value-of select="ns0:Invoice_Billing_Date"/>
                     </tns:Invoice_Billing_Date>
                     <tns:Invoice_Lines_Flexfield_Context>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Context"/>
                     </tns:Invoice_Lines_Flexfield_Context>
                     <tns:Invoice_Lines_Flexfield_Segment_1>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_1"/>
                     </tns:Invoice_Lines_Flexfield_Segment_1>
                     <tns:Invoice_Lines_Flexfield_Segment_2>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_2"/>
                     </tns:Invoice_Lines_Flexfield_Segment_2>
                     <tns:Invoice_Lines_Flexfield_Segment_3>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_3"/>
                     </tns:Invoice_Lines_Flexfield_Segment_3>
                     <tns:Invoice_Lines_Flexfield_Segment_4>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_4"/>
                     </tns:Invoice_Lines_Flexfield_Segment_4>
                     <tns:Invoice_Lines_Flexfield_Segment_5>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_5"/>
                     </tns:Invoice_Lines_Flexfield_Segment_5>
                     <tns:Invoice_Lines_Flexfield_Segment_6>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_6"/>
                     </tns:Invoice_Lines_Flexfield_Segment_6>
                     <tns:Invoice_Lines_Flexfield_Segment_7>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_7"/>
                     </tns:Invoice_Lines_Flexfield_Segment_7>
                     <tns:Invoice_Lines_Flexfield_Segment_8>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_8"/>
                     </tns:Invoice_Lines_Flexfield_Segment_8>
                     <tns:Invoice_Lines_Flexfield_Segment_9>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_9"/>
                     </tns:Invoice_Lines_Flexfield_Segment_9>
                     <tns:Invoice_Lines_Flexfield_Segment_10>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_10"/>
                     </tns:Invoice_Lines_Flexfield_Segment_10>
                     <tns:Invoice_Lines_Flexfield_Segment_11>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_11"/>
                     </tns:Invoice_Lines_Flexfield_Segment_11>
                     <tns:Invoice_Lines_Flexfield_Segment_12>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_12"/>
                     </tns:Invoice_Lines_Flexfield_Segment_12>
                     <tns:Invoice_Lines_Flexfield_Segment_13>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_13"/>
                     </tns:Invoice_Lines_Flexfield_Segment_13>
                     <tns:Invoice_Lines_Flexfield_Segment_14>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_14"/>
                     </tns:Invoice_Lines_Flexfield_Segment_14>
                     <tns:Invoice_Lines_Flexfield_Segment_15>
                        <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_15"/>
                     </tns:Invoice_Lines_Flexfield_Segment_15>
                     <tns:Invoice_Transactions_Flexfield_Context>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Context"/>
                     </tns:Invoice_Transactions_Flexfield_Context>
                     <tns:Invoice_Transactions_Flexfield_Segment_1>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_1"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_1>
                     <tns:Invoice_Transactions_Flexfield_Segment_2>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_2"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_2>
                     <tns:Invoice_Transactions_Flexfield_Segment_3>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_3"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_3>
                     <tns:Invoice_Transactions_Flexfield_Segment_4>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_4"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_4>
                     <tns:Invoice_Transactions_Flexfield_Segment_5>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_5"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_5>
                     <tns:Invoice_Transactions_Flexfield_Segment_6>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_6"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_6>
                     <tns:Invoice_Transactions_Flexfield_Segment_7>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_7"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_7>
                     <tns:Invoice_Transactions_Flexfield_Segment_8>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_8"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_8>
                     <tns:Invoice_Transactions_Flexfield_Segment_9>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_9"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_9>
                     <tns:Invoice_Transactions_Flexfield_Segment_10>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_10"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_10>
                     <tns:Invoice_Transactions_Flexfield_Segment_11>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_11"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_11>
                     <tns:Invoice_Transactions_Flexfield_Segment_12>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_12"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_12>
                     <tns:Invoice_Transactions_Flexfield_Segment_13>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_13"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_13>
                     <tns:Invoice_Transactions_Flexfield_Segment_14>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_14"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_14>
                     <tns:Invoice_Transactions_Flexfield_Segment_15>
                        <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_15"/>
                     </tns:Invoice_Transactions_Flexfield_Segment_15>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Context>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Context"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Context>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_1>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_1"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_1>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_2>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_2"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_2>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_3>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_3"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_3>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_4>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_4"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_4>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_5>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_5"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_5>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_6>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_6"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_6>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_7>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_7"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_7>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_8>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_8"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_8>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_9>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_9"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_9>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_10>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_10"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_10>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_11>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_11"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_11>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_12>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_12"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_12>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_13>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_13"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_13>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_14>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_14"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_14>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_15>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_15"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_15>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_16>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_16"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_16>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_17>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_17"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_17>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_18>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_18"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_18>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_19>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_19"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_19>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_20>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_20"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_20>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_21>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_21"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_21>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_22>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_22"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_22>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_23>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_23"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_23>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_24>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_24"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_24>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_25>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_25"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_25>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_26>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_26"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_26>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_27>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_27"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_27>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_28>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_28"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_28>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_29>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_29"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_29>
                     <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_30>
                        <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_30"/>
                     </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_30>
                     <tns:Line_Global_Descriptive_Flexfield_Attribute_Category>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Attribute_Category"/>
                     </tns:Line_Global_Descriptive_Flexfield_Attribute_Category>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_1>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_1"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_1>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_2>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_2"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_2>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_3>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_3"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_3>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_4>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_4"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_4>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_5>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_5"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_5>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_6>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_6"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_6>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_7>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_7"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_7>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_8>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_8"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_8>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_9>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_9"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_9>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_10>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_10"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_10>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_11>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_11"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_11>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_12>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_12"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_12>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_13>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_13"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_13>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_14>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_14"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_14>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_15>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_15"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_15>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_16>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_16"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_16>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_17>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_17"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_17>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_18>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_18"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_18>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_19>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_19"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_19>
                     <tns:Line_Global_Descriptive_Flexfield_Segment_20>
                        <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_20"/>
                     </tns:Line_Global_Descriptive_Flexfield_Segment_20>
                     <tns:Business_Unit_Name>
                        <xsl:value-of select="ns0:Business_Unit_Name"/>
                     </tns:Business_Unit_Name>
                     <tns:Comments>
                        <xsl:value-of select="ns0:Comments"/>
                     </tns:Comments>
                     <tns:Enforce_Chronological_Document_Sequencing>
                        <xsl:value-of select="ns0:Enforce_Chronological_Document_Sequencing"/>
                     </tns:Enforce_Chronological_Document_Sequencing>
                     <tns:Aux>
                        <xsl:value-of select="ns0:Aux"/>
                     </tns:Aux>
                     <tns:C291>
                        <xsl:value-of select="ns0:C291"/>
                     </tns:C291>
                  </tns:ReturnList>
               </xsl:for-each>
            </tns:InvoicesCSV>
         </tns:List>
      </tns:ListStructureInvoicesCSV>
   </xsl:template>
</xsl:stylesheet>
