<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesBiz/StructursInvoicesBiz" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelBuildInvoicesZip"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns5="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns6="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns4="http://soa.estrellaroja.com.mx/FinancialsTec"
                xmlns:ns7="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelBuildInvoicesZip.wsdl"/>
            <oracle-xsl-mapper:rootElement name="invoicesToCsv" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelBuildInvoicesZip.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ListStrings" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz/StructursInvoicesBiz"/>
            <oracle-xsl-mapper:param name="varCurrentBu"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelBuildInvoicesZip.wsdl"/>
            <oracle-xsl-mapper:rootElement name="invoicesToCsv" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON MAR 12 19:32:45 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varCurrentBu"/>
   <xsl:template match="/">
      <ns0:invoicesToCsv>
         <xsl:for-each select="/ns0:invoicesToCsv/ns0:InvoicesList">
            <xsl:if test="$varCurrentBu/ns1:ListStrings/ns1:ReturnList/ns1:StringValue = ns0:Business_Unit_Name">
               <ns0:InvoicesList>
                  <ns0:Notes_from_Source>
                     <xsl:value-of select="ns0:Notes_from_Source"/>
                  </ns0:Notes_from_Source>
                  <ns0:Transaction_Batch_Source_Name>
                     <xsl:value-of select="ns0:Transaction_Batch_Source_Name"/>
                  </ns0:Transaction_Batch_Source_Name>
                  <ns0:Transaction_Type_Name>
                     <xsl:value-of select="ns0:Transaction_Type_Name"/>
                  </ns0:Transaction_Type_Name>
                  <ns0:Payment_Terms>
                     <xsl:value-of select="ns0:Payment_Terms"/>
                  </ns0:Payment_Terms>
                  <ns0:Transaction_Date>
                     <xsl:value-of select="ns0:Transaction_Date"/>
                  </ns0:Transaction_Date>
                  <ns0:Accounting_Date>
                     <xsl:value-of select="ns0:Accounting_Date"/>
                  </ns0:Accounting_Date>
                  <ns0:Transaction_Number>
                     <xsl:value-of select="ns0:Transaction_Number"/>
                  </ns0:Transaction_Number>
                  <ns0:Original_System_Bill_to_Customer_Reference>
                     <xsl:value-of select="ns0:Original_System_Bill_to_Customer_Reference"/>
                  </ns0:Original_System_Bill_to_Customer_Reference>
                  <ns0:Original_System_Bill_to_Customer_Address_Reference>
                     <xsl:value-of select="ns0:Original_System_Bill_to_Customer_Address_Reference"/>
                  </ns0:Original_System_Bill_to_Customer_Address_Reference>
                  <ns0:Original_System_Bill_to_Customer_Contact_Reference>
                     <xsl:value-of select="ns0:Original_System_Bill_to_Customer_Contact_Reference"/>
                  </ns0:Original_System_Bill_to_Customer_Contact_Reference>
                  <ns0:Original_System_Ship_to_Customer_Reference>
                     <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Reference"/>
                  </ns0:Original_System_Ship_to_Customer_Reference>
                  <ns0:Original_System_Ship_to_Customer_Address_Reference>
                     <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Address_Reference"/>
                  </ns0:Original_System_Ship_to_Customer_Address_Reference>
                  <ns0:Original_System_Ship_to_Customer_Contact_Reference>
                     <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Contact_Reference"/>
                  </ns0:Original_System_Ship_to_Customer_Contact_Reference>
                  <ns0:Original_System_Ship_to_Customer_Account_Reference>
                     <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Account_Reference"/>
                  </ns0:Original_System_Ship_to_Customer_Account_Reference>
                  <ns0:Original_System_Ship_to_Customer_Account_Address_Reference>
                     <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Account_Address_Reference"/>
                  </ns0:Original_System_Ship_to_Customer_Account_Address_Reference>
                  <ns0:Original_System_Ship_to_Customer_Account_Contact_Reference>
                     <xsl:value-of select="ns0:Original_System_Ship_to_Customer_Account_Contact_Reference"/>
                  </ns0:Original_System_Ship_to_Customer_Account_Contact_Reference>
                  <ns0:Original_System_Sold_to_Customer_Reference>
                     <xsl:value-of select="ns0:Original_System_Sold_to_Customer_Reference"/>
                  </ns0:Original_System_Sold_to_Customer_Reference>
                  <ns0:Original_System_Sold_to_Customer_Account_Reference>
                     <xsl:value-of select="ns0:Original_System_Sold_to_Customer_Account_Reference"/>
                  </ns0:Original_System_Sold_to_Customer_Account_Reference>
                  <ns0:Bill_to_Customer_Account_Number>
                     <xsl:value-of select="ns0:Bill_to_Customer_Account_Number"/>
                  </ns0:Bill_to_Customer_Account_Number>
                  <ns0:Bill_to_Customer_Site_Number>
                     <xsl:value-of select="ns0:Bill_to_Customer_Site_Number"/>
                  </ns0:Bill_to_Customer_Site_Number>
                  <ns0:Bill_to_Contact_Party_Number>
                     <xsl:value-of select="ns0:Bill_to_Contact_Party_Number"/>
                  </ns0:Bill_to_Contact_Party_Number>
                  <ns0:Ship_to_Customer_Account_Number>
                     <xsl:value-of select="ns0:Ship_to_Customer_Account_Number"/>
                  </ns0:Ship_to_Customer_Account_Number>
                  <ns0:Ship_to_Customer_Site_Number>
                     <xsl:value-of select="ns0:Ship_to_Customer_Site_Number"/>
                  </ns0:Ship_to_Customer_Site_Number>
                  <ns0:Ship_to_Contact_Party_Number>
                     <xsl:value-of select="ns0:Ship_to_Contact_Party_Number"/>
                  </ns0:Ship_to_Contact_Party_Number>
                  <ns0:Sold_to_Customer_Account_Number>
                     <xsl:value-of select="ns0:Sold_to_Customer_Account_Number"/>
                  </ns0:Sold_to_Customer_Account_Number>
                  <ns0:Transaction_Line_Type>
                     <xsl:value-of select="ns0:Transaction_Line_Type"/>
                  </ns0:Transaction_Line_Type>
                  <ns0:Transaction_Line_Description>
                     <xsl:value-of select="ns0:Transaction_Line_Description"/>
                  </ns0:Transaction_Line_Description>
                  <ns0:Currency_Code>
                     <xsl:value-of select="ns0:Currency_Code"/>
                  </ns0:Currency_Code>
                  <ns0:Currency_Conversion_Type>
                     <xsl:value-of select="ns0:Currency_Conversion_Type"/>
                  </ns0:Currency_Conversion_Type>
                  <ns0:Currency_Conversion_Date>
                     <xsl:value-of select="ns0:Currency_Conversion_Date"/>
                  </ns0:Currency_Conversion_Date>
                  <ns0:Currency_Conversion_Rate>
                     <xsl:value-of select="ns0:Currency_Conversion_Rate"/>
                  </ns0:Currency_Conversion_Rate>
                  <ns0:Transaction_Line_Amount>
                     <xsl:value-of select="ns0:Transaction_Line_Amount"/>
                  </ns0:Transaction_Line_Amount>
                  <ns0:Transaction_Line_Quantity>
                     <xsl:value-of select="ns0:Transaction_Line_Quantity"/>
                  </ns0:Transaction_Line_Quantity>
                  <ns0:Customer_Ordered_Quantity>
                     <xsl:value-of select="ns0:Customer_Ordered_Quantity"/>
                  </ns0:Customer_Ordered_Quantity>
                  <ns0:Unit_Selling_Price>
                     <xsl:value-of select="ns0:Unit_Selling_Price"/>
                  </ns0:Unit_Selling_Price>
                  <ns0:Unit_Standard_Price>
                     <xsl:value-of select="ns0:Unit_Standard_Price"/>
                  </ns0:Unit_Standard_Price>
                  <ns0:Line_Transactions_Flexfield_Context>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Context"/>
                  </ns0:Line_Transactions_Flexfield_Context>
                  <ns0:Line_Transactions_Flexfield_Segment_1>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_1"/>
                  </ns0:Line_Transactions_Flexfield_Segment_1>
                  <ns0:Line_Transactions_Flexfield_Segment_2>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_2"/>
                  </ns0:Line_Transactions_Flexfield_Segment_2>
                  <ns0:Line_Transactions_Flexfield_Segment_3>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_3"/>
                  </ns0:Line_Transactions_Flexfield_Segment_3>
                  <ns0:Line_Transactions_Flexfield_Segment_4>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_4"/>
                  </ns0:Line_Transactions_Flexfield_Segment_4>
                  <ns0:Line_Transactions_Flexfield_Segment_5>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_5"/>
                  </ns0:Line_Transactions_Flexfield_Segment_5>
                  <ns0:Line_Transactions_Flexfield_Segment_6>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_6"/>
                  </ns0:Line_Transactions_Flexfield_Segment_6>
                  <ns0:Line_Transactions_Flexfield_Segment_7>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_7"/>
                  </ns0:Line_Transactions_Flexfield_Segment_7>
                  <ns0:Line_Transactions_Flexfield_Segment_8>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_8"/>
                  </ns0:Line_Transactions_Flexfield_Segment_8>
                  <ns0:Line_Transactions_Flexfield_Segment_9>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_9"/>
                  </ns0:Line_Transactions_Flexfield_Segment_9>
                  <ns0:Line_Transactions_Flexfield_Segment_10>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_10"/>
                  </ns0:Line_Transactions_Flexfield_Segment_10>
                  <ns0:Line_Transactions_Flexfield_Segment_11>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_11"/>
                  </ns0:Line_Transactions_Flexfield_Segment_11>
                  <ns0:Line_Transactions_Flexfield_Segment_12>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_12"/>
                  </ns0:Line_Transactions_Flexfield_Segment_12>
                  <ns0:Line_Transactions_Flexfield_Segment_13>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_13"/>
                  </ns0:Line_Transactions_Flexfield_Segment_13>
                  <ns0:Line_Transactions_Flexfield_Segment_14>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_14"/>
                  </ns0:Line_Transactions_Flexfield_Segment_14>
                  <ns0:Line_Transactions_Flexfield_Segment_15>
                     <xsl:value-of select="ns0:Line_Transactions_Flexfield_Segment_15"/>
                  </ns0:Line_Transactions_Flexfield_Segment_15>
                  <ns0:Primary_Salesperson_Number>
                     <xsl:value-of select="ns0:Primary_Salesperson_Number"/>
                  </ns0:Primary_Salesperson_Number>
                  <ns0:Tax_Classification_Code>
                     <xsl:value-of select="ns0:Tax_Classification_Code"/>
                  </ns0:Tax_Classification_Code>
                  <ns0:Legal_Entity_Identifier>
                     <xsl:value-of select="ns0:Legal_Entity_Identifier"/>
                  </ns0:Legal_Entity_Identifier>
                  <ns0:Accounted_Amount_in_Ledger_Currency>
                     <xsl:value-of select="ns0:Accounted_Amount_in_Ledger_Currency"/>
                  </ns0:Accounted_Amount_in_Ledger_Currency>
                  <ns0:Sales_Order_Number>
                     <xsl:value-of select="ns0:Sales_Order_Number"/>
                  </ns0:Sales_Order_Number>
                  <ns0:Sales_Order_Date>
                     <xsl:value-of select="ns0:Sales_Order_Date"/>
                  </ns0:Sales_Order_Date>
                  <ns0:Actual_Ship_Date>
                     <xsl:value-of select="ns0:Actual_Ship_Date"/>
                  </ns0:Actual_Ship_Date>
                  <ns0:Warehouse_Code>
                     <xsl:value-of select="ns0:Warehouse_Code"/>
                  </ns0:Warehouse_Code>
                  <ns0:Unit_of_Measure_Code>
                     <xsl:value-of select="ns0:Unit_of_Measure_Code"/>
                  </ns0:Unit_of_Measure_Code>
                  <ns0:Unit_of_Measure_Name>
                     <xsl:value-of select="ns0:Unit_of_Measure_Name"/>
                  </ns0:Unit_of_Measure_Name>
                  <ns0:Invoicing_Rule_Name>
                     <xsl:value-of select="ns0:Invoicing_Rule_Name"/>
                  </ns0:Invoicing_Rule_Name>
                  <ns0:Revenue_Scheduling_Rule_Name>
                     <xsl:value-of select="ns0:Revenue_Scheduling_Rule_Name"/>
                  </ns0:Revenue_Scheduling_Rule_Name>
                  <ns0:Number_of_Revenue_Periods>
                     <xsl:value-of select="ns0:Number_of_Revenue_Periods"/>
                  </ns0:Number_of_Revenue_Periods>
                  <ns0:Revenue_Scheduling_Rule_Start_Date>
                     <xsl:value-of select="ns0:Revenue_Scheduling_Rule_Start_Date"/>
                  </ns0:Revenue_Scheduling_Rule_Start_Date>
                  <ns0:Revenue_Scheduling_Rule_End_Date>
                     <xsl:value-of select="ns0:Revenue_Scheduling_Rule_End_Date"/>
                  </ns0:Revenue_Scheduling_Rule_End_Date>
                  <ns0:Reason_Code_Meaning>
                     <xsl:value-of select="ns0:Reason_Code_Meaning"/>
                  </ns0:Reason_Code_Meaning>
                  <ns0:Last_Period_to_Credit>
                     <xsl:value-of select="ns0:Last_Period_to_Credit"/>
                  </ns0:Last_Period_to_Credit>
                  <ns0:Transaction_Business_Category_Code>
                     <xsl:value-of select="ns0:Transaction_Business_Category_Code"/>
                  </ns0:Transaction_Business_Category_Code>
                  <ns0:Product_Fiscal_Classification_Code>
                     <xsl:value-of select="ns0:Product_Fiscal_Classification_Code"/>
                  </ns0:Product_Fiscal_Classification_Code>
                  <ns0:Product_Category_Code>
                     <xsl:value-of select="ns0:Product_Category_Code"/>
                  </ns0:Product_Category_Code>
                  <ns0:Product_Type>
                     <xsl:value-of select="ns0:Product_Type"/>
                  </ns0:Product_Type>
                  <ns0:Line_Intended_Use_Code>
                     <xsl:value-of select="ns0:Line_Intended_Use_Code"/>
                  </ns0:Line_Intended_Use_Code>
                  <ns0:Assessable_Value>
                     <xsl:value-of select="ns0:Assessable_Value"/>
                  </ns0:Assessable_Value>
                  <ns0:Document_Sub_Type>
                     <xsl:value-of select="ns0:Document_Sub_Type"/>
                  </ns0:Document_Sub_Type>
                  <ns0:Default_Taxation_Country>
                     <xsl:value-of select="ns0:Default_Taxation_Country"/>
                  </ns0:Default_Taxation_Country>
                  <ns0:User_Defined_Fiscal_Classification>
                     <xsl:value-of select="ns0:User_Defined_Fiscal_Classification"/>
                  </ns0:User_Defined_Fiscal_Classification>
                  <ns0:Tax_Invoice_Number>
                     <xsl:value-of select="ns0:Tax_Invoice_Number"/>
                  </ns0:Tax_Invoice_Number>
                  <ns0:Tax_Invoice_Date>
                     <xsl:value-of select="ns0:Tax_Invoice_Date"/>
                  </ns0:Tax_Invoice_Date>
                  <ns0:Tax_Regime_Code>
                     <xsl:value-of select="ns0:Tax_Regime_Code"/>
                  </ns0:Tax_Regime_Code>
                  <ns0:Tax>
                     <xsl:value-of select="ns0:Tax"/>
                  </ns0:Tax>
                  <ns0:Tax_Status_Code>
                     <xsl:value-of select="ns0:Tax_Status_Code"/>
                  </ns0:Tax_Status_Code>
                  <ns0:Tax_Rate_Code>
                     <xsl:value-of select="ns0:Tax_Rate_Code"/>
                  </ns0:Tax_Rate_Code>
                  <ns0:Tax_Jurisdiction_Code>
                     <xsl:value-of select="ns0:Tax_Jurisdiction_Code"/>
                  </ns0:Tax_Jurisdiction_Code>
                  <ns0:First_Party_Registration_Number>
                     <xsl:value-of select="ns0:First_Party_Registration_Number"/>
                  </ns0:First_Party_Registration_Number>
                  <ns0:Third_Party_Registration_Number>
                     <xsl:value-of select="ns0:Third_Party_Registration_Number"/>
                  </ns0:Third_Party_Registration_Number>
                  <ns0:Final_Discharge_Location>
                     <xsl:value-of select="ns0:Final_Discharge_Location"/>
                  </ns0:Final_Discharge_Location>
                  <ns0:Taxable_Amount>
                     <xsl:value-of select="ns0:Taxable_Amount"/>
                  </ns0:Taxable_Amount>
                  <ns0:Taxable_Flag>
                     <xsl:value-of select="ns0:Taxable_Flag"/>
                  </ns0:Taxable_Flag>
                  <ns0:Tax_Exemption_Flag>
                     <xsl:value-of select="ns0:Tax_Exemption_Flag"/>
                  </ns0:Tax_Exemption_Flag>
                  <ns0:TTax_Exemption_Reason_Code>
                     <xsl:value-of select="ns0:TTax_Exemption_Reason_Code"/>
                  </ns0:TTax_Exemption_Reason_Code>
                  <ns0:Tax_Exemption_Reason_Code_Meaning>
                     <xsl:value-of select="ns0:Tax_Exemption_Reason_Code_Meaning"/>
                  </ns0:Tax_Exemption_Reason_Code_Meaning>
                  <ns0:Tax_Exemption_Certificate_Number>
                     <xsl:value-of select="ns0:Tax_Exemption_Certificate_Number"/>
                  </ns0:Tax_Exemption_Certificate_Number>
                  <ns0:Line_Amount_Includes_Tax_Flag>
                     <xsl:value-of select="ns0:Line_Amount_Includes_Tax_Flag"/>
                  </ns0:Line_Amount_Includes_Tax_Flag>
                  <ns0:Tax_Precedence>
                     <xsl:value-of select="ns0:Tax_Precedence"/>
                  </ns0:Tax_Precedence>
                  <ns0:Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules>
                     <xsl:value-of select="ns0:Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules"/>
                  </ns0:Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules>
                  <ns0:Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms>
                     <xsl:value-of select="ns0:Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms"/>
                  </ns0:Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms>
                  <ns0:Reason_Code>
                     <xsl:value-of select="ns0:Reason_Code"/>
                  </ns0:Reason_Code>
                  <ns0:Tax_Rate>
                     <xsl:value-of select="ns0:Tax_Rate"/>
                  </ns0:Tax_Rate>
                  <ns0:FOB_Point>
                     <xsl:value-of select="ns0:FOB_Point"/>
                  </ns0:FOB_Point>
                  <ns0:Carrier>
                     <xsl:value-of select="ns0:Carrier"/>
                  </ns0:Carrier>
                  <ns0:Shipping_Reference>
                     <xsl:value-of select="ns0:Shipping_Reference"/>
                  </ns0:Shipping_Reference>
                  <ns0:Sales_Order_Line_Number>
                     <xsl:value-of select="ns0:Sales_Order_Line_Number"/>
                  </ns0:Sales_Order_Line_Number>
                  <ns0:Sales_Order_Source>
                     <xsl:value-of select="ns0:Sales_Order_Source"/>
                  </ns0:Sales_Order_Source>
                  <ns0:Sales_Order_Revision_Number>
                     <xsl:value-of select="ns0:Sales_Order_Revision_Number"/>
                  </ns0:Sales_Order_Revision_Number>
                  <ns0:Purchase_Order_Number>
                     <xsl:value-of select="ns0:Purchase_Order_Number"/>
                  </ns0:Purchase_Order_Number>
                  <ns0:Purchase_Order_Revision_Number>
                     <xsl:value-of select="ns0:Purchase_Order_Revision_Number"/>
                  </ns0:Purchase_Order_Revision_Number>
                  <ns0:Purchase_Order_Date>
                     <xsl:value-of select="ns0:Purchase_Order_Date"/>
                  </ns0:Purchase_Order_Date>
                  <ns0:Agreement_Name>
                     <xsl:value-of select="ns0:Agreement_Name"/>
                  </ns0:Agreement_Name>
                  <ns0:Memo_Line_Name>
                     <xsl:value-of select="ns0:Memo_Line_Name"/>
                  </ns0:Memo_Line_Name>
                  <ns0:Document_Number>
                     <xsl:value-of select="ns0:Document_Number"/>
                  </ns0:Document_Number>
                  <ns0:Original_System_Batch_Name>
                     <xsl:value-of select="ns0:Original_System_Batch_Name"/>
                  </ns0:Original_System_Batch_Name>
                  <ns0:Link_to_Transactions_Flexfield_Context>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Context"/>
                  </ns0:Link_to_Transactions_Flexfield_Context>
                  <ns0:Link_to_Transactions_Flexfield_Segment_1>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_1"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_1>
                  <ns0:Link_to_Transactions_Flexfield_Segment_2>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_2"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_2>
                  <ns0:Link_to_Transactions_Flexfield_Segment_3>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_3"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_3>
                  <ns0:Link_to_Transactions_Flexfield_Segment_4>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_4"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_4>
                  <ns0:Link_to_Transactions_Flexfield_Segment_5>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_5"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_5>
                  <ns0:Link_to_Transactions_Flexfield_Segment_6>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_6"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_6>
                  <ns0:Link_to_Transactions_Flexfield_Segment_7>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_7"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_7>
                  <ns0:Link_to_Transactions_Flexfield_Segment_8>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_8"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_8>
                  <ns0:Link_to_Transactions_Flexfield_Segment_9>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_9"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_9>
                  <ns0:Link_to_Transactions_Flexfield_Segment_10>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_10"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_10>
                  <ns0:Link_to_Transactions_Flexfield_Segment_11>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_11"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_11>
                  <ns0:Link_to_Transactions_Flexfield_Segment_12>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_12"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_12>
                  <ns0:Link_to_Transactions_Flexfield_Segment_13>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_13"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_13>
                  <ns0:Link_to_Transactions_Flexfield_Segment_14>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_14"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_14>
                  <ns0:Link_to_Transactions_Flexfield_Segment_15>
                     <xsl:value-of select="ns0:Link_to_Transactions_Flexfield_Segment_15"/>
                  </ns0:Link_to_Transactions_Flexfield_Segment_15>
                  <ns0:Reference_Transactions_Flexfield_Context>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Context"/>
                  </ns0:Reference_Transactions_Flexfield_Context>
                  <ns0:Reference_Transactions_Flexfield_Segment_1>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_1"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_1>
                  <ns0:Reference_Transactions_Flexfield_Segment_2>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_2"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_2>
                  <ns0:Reference_Transactions_Flexfield_Segment_3>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_3"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_3>
                  <ns0:Reference_Transactions_Flexfield_Segment_4>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_4"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_4>
                  <ns0:Reference_Transactions_Flexfield_Segment_5>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_5"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_5>
                  <ns0:Reference_Transactions_Flexfield_Segment_6>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_6"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_6>
                  <ns0:Reference_Transactions_Flexfield_Segment_7>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_7"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_7>
                  <ns0:Reference_Transactions_Flexfield_Segment_8>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_8"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_8>
                  <ns0:Reference_Transactions_Flexfield_Segment_9>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_9"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_9>
                  <ns0:Reference_Transactions_Flexfield_Segment_10>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_10"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_10>
                  <ns0:Reference_Transactions_Flexfield_Segment_11>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_11"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_11>
                  <ns0:Reference_Transactions_Flexfield_Segment_12>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_12"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_12>
                  <ns0:Reference_Transactions_Flexfield_Segment_13>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_13"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_13>
                  <ns0:Reference_Transactions_Flexfield_Segment_14>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_14"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_14>
                  <ns0:Reference_Transactions_Flexfield_Segment_15>
                     <xsl:value-of select="ns0:Reference_Transactions_Flexfield_Segment_15"/>
                  </ns0:Reference_Transactions_Flexfield_Segment_15>
                  <ns0:Link_To_Parent_Line_Context>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Context"/>
                  </ns0:Link_To_Parent_Line_Context>
                  <ns0:Link_To_Parent_Line_Segment_1>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_1"/>
                  </ns0:Link_To_Parent_Line_Segment_1>
                  <ns0:Link_To_Parent_Line_Segment_2>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_2"/>
                  </ns0:Link_To_Parent_Line_Segment_2>
                  <ns0:Link_To_Parent_Line_Segment_3>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_3"/>
                  </ns0:Link_To_Parent_Line_Segment_3>
                  <ns0:Link_To_Parent_Line_Segment_4>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_4"/>
                  </ns0:Link_To_Parent_Line_Segment_4>
                  <ns0:Link_To_Parent_Line_Segment_5>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_5"/>
                  </ns0:Link_To_Parent_Line_Segment_5>
                  <ns0:Link_To_Parent_Line_Segment_6>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_6"/>
                  </ns0:Link_To_Parent_Line_Segment_6>
                  <ns0:Link_To_Parent_Line_Segment_7>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_7"/>
                  </ns0:Link_To_Parent_Line_Segment_7>
                  <ns0:Link_To_Parent_Line_Segment_8>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_8"/>
                  </ns0:Link_To_Parent_Line_Segment_8>
                  <ns0:Link_To_Parent_Line_Segment_9>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_9"/>
                  </ns0:Link_To_Parent_Line_Segment_9>
                  <ns0:Link_To_Parent_Line_Segment_10>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_10"/>
                  </ns0:Link_To_Parent_Line_Segment_10>
                  <ns0:Link_To_Parent_Line_Segment_11>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_11"/>
                  </ns0:Link_To_Parent_Line_Segment_11>
                  <ns0:Link_To_Parent_Line_Segment_12>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_12"/>
                  </ns0:Link_To_Parent_Line_Segment_12>
                  <ns0:Link_To_Parent_Line_Segment_13>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_13"/>
                  </ns0:Link_To_Parent_Line_Segment_13>
                  <ns0:Link_To_Parent_Line_Segment_14>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_14"/>
                  </ns0:Link_To_Parent_Line_Segment_14>
                  <ns0:Link_To_Parent_Line_Segment_15>
                     <xsl:value-of select="ns0:Link_To_Parent_Line_Segment_15"/>
                  </ns0:Link_To_Parent_Line_Segment_15>
                  <ns0:Receipt_Method_Name>
                     <xsl:value-of select="ns0:Receipt_Method_Name"/>
                  </ns0:Receipt_Method_Name>
                  <ns0:Printing_Option>
                     <xsl:value-of select="ns0:Printing_Option"/>
                  </ns0:Printing_Option>
                  <ns0:Related_Batch_Source_Name>
                     <xsl:value-of select="ns0:Related_Batch_Source_Name"/>
                  </ns0:Related_Batch_Source_Name>
                  <ns0:Related_Transaction_Number>
                     <xsl:value-of select="ns0:Related_Transaction_Number"/>
                  </ns0:Related_Transaction_Number>
                  <ns0:Inventory_Item_Number>
                     <xsl:value-of select="ns0:Inventory_Item_Number"/>
                  </ns0:Inventory_Item_Number>
                  <ns0:Inventory_Item_Segment_2>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_2"/>
                  </ns0:Inventory_Item_Segment_2>
                  <ns0:Inventory_Item_Segment_3>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_3"/>
                  </ns0:Inventory_Item_Segment_3>
                  <ns0:Inventory_Item_Segment_4>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_4"/>
                  </ns0:Inventory_Item_Segment_4>
                  <ns0:Inventory_Item_Segment_5>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_5"/>
                  </ns0:Inventory_Item_Segment_5>
                  <ns0:Inventory_Item_Segment_6>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_6"/>
                  </ns0:Inventory_Item_Segment_6>
                  <ns0:Inventory_Item_Segment_7>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_7"/>
                  </ns0:Inventory_Item_Segment_7>
                  <ns0:Inventory_Item_Segment_8>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_8"/>
                  </ns0:Inventory_Item_Segment_8>
                  <ns0:Inventory_Item_Segment_9>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_9"/>
                  </ns0:Inventory_Item_Segment_9>
                  <ns0:Inventory_Item_Segment_10>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_10"/>
                  </ns0:Inventory_Item_Segment_10>
                  <ns0:Inventory_Item_Segment_11>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_11"/>
                  </ns0:Inventory_Item_Segment_11>
                  <ns0:Inventory_Item_Segment_12>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_12"/>
                  </ns0:Inventory_Item_Segment_12>
                  <ns0:Inventory_Item_Segment_13>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_13"/>
                  </ns0:Inventory_Item_Segment_13>
                  <ns0:Inventory_Item_Segment_14>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_14"/>
                  </ns0:Inventory_Item_Segment_14>
                  <ns0:Inventory_Item_Segment_15>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_15"/>
                  </ns0:Inventory_Item_Segment_15>
                  <ns0:Inventory_Item_Segment_16>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_16"/>
                  </ns0:Inventory_Item_Segment_16>
                  <ns0:Inventory_Item_Segment_17>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_17"/>
                  </ns0:Inventory_Item_Segment_17>
                  <ns0:Inventory_Item_Segment_18>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_18"/>
                  </ns0:Inventory_Item_Segment_18>
                  <ns0:Inventory_Item_Segment_19>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_19"/>
                  </ns0:Inventory_Item_Segment_19>
                  <ns0:Inventory_Item_Segment_20>
                     <xsl:value-of select="ns0:Inventory_Item_Segment_20"/>
                  </ns0:Inventory_Item_Segment_20>
                  <ns0:Bill_To_Customer_Bank_Account_Name>
                     <xsl:value-of select="ns0:Bill_To_Customer_Bank_Account_Name"/>
                  </ns0:Bill_To_Customer_Bank_Account_Name>
                  <ns0:Reset_Transaction_Date_Flag>
                     <xsl:value-of select="ns0:Reset_Transaction_Date_Flag"/>
                  </ns0:Reset_Transaction_Date_Flag>
                  <ns0:Payment_Server_Order_Number>
                     <xsl:value-of select="ns0:Payment_Server_Order_Number"/>
                  </ns0:Payment_Server_Order_Number>
                  <ns0:Last_Transaction_on_Debit_Authorization>
                     <xsl:value-of select="ns0:Last_Transaction_on_Debit_Authorization"/>
                  </ns0:Last_Transaction_on_Debit_Authorization>
                  <ns0:Approval_Code>
                     <xsl:value-of select="ns0:Approval_Code"/>
                  </ns0:Approval_Code>
                  <ns0:Address_Verification_Code>
                     <xsl:value-of select="ns0:Address_Verification_Code"/>
                  </ns0:Address_Verification_Code>
                  <ns0:Transaction_Line_Translated_Description>
                     <xsl:value-of select="ns0:Transaction_Line_Translated_Description"/>
                  </ns0:Transaction_Line_Translated_Description>
                  <ns0:Consolidated_Billing_Number>
                     <xsl:value-of select="ns0:Consolidated_Billing_Number"/>
                  </ns0:Consolidated_Billing_Number>
                  <ns0:Promised_Commitment_Amount>
                     <xsl:value-of select="ns0:Promised_Commitment_Amount"/>
                  </ns0:Promised_Commitment_Amount>
                  <ns0:Payment_Set_Identifier>
                     <xsl:value-of select="ns0:Payment_Set_Identifier"/>
                  </ns0:Payment_Set_Identifier>
                  <ns0:Original_Accounting_Date>
                     <xsl:value-of select="ns0:Original_Accounting_Date"/>
                  </ns0:Original_Accounting_Date>
                  <ns0:Invoiced_Line_Accounting_Level>
                     <xsl:value-of select="ns0:Invoiced_Line_Accounting_Level"/>
                  </ns0:Invoiced_Line_Accounting_Level>
                  <ns0:Override_AutoAccounting_Flag>
                     <xsl:value-of select="ns0:Override_AutoAccounting_Flag"/>
                  </ns0:Override_AutoAccounting_Flag>
                  <ns0:Historical_Flag>
                     <xsl:value-of select="ns0:Historical_Flag"/>
                  </ns0:Historical_Flag>
                  <ns0:Deferral_Exclusion_Flag>
                     <xsl:value-of select="ns0:Deferral_Exclusion_Flag"/>
                  </ns0:Deferral_Exclusion_Flag>
                  <ns0:Payment_Attributes>
                     <xsl:value-of select="ns0:Payment_Attributes"/>
                  </ns0:Payment_Attributes>
                  <ns0:Invoice_Billing_Date>
                     <xsl:value-of select="ns0:Invoice_Billing_Date"/>
                  </ns0:Invoice_Billing_Date>
                  <ns0:Invoice_Lines_Flexfield_Context>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Context"/>
                  </ns0:Invoice_Lines_Flexfield_Context>
                  <ns0:Invoice_Lines_Flexfield_Segment_1>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_1"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_1>
                  <ns0:Invoice_Lines_Flexfield_Segment_2>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_2"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_2>
                  <ns0:Invoice_Lines_Flexfield_Segment_3>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_3"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_3>
                  <ns0:Invoice_Lines_Flexfield_Segment_4>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_4"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_4>
                  <ns0:Invoice_Lines_Flexfield_Segment_5>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_5"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_5>
                  <ns0:Invoice_Lines_Flexfield_Segment_6>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_6"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_6>
                  <ns0:Invoice_Lines_Flexfield_Segment_7>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_7"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_7>
                  <ns0:Invoice_Lines_Flexfield_Segment_8>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_8"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_8>
                  <ns0:Invoice_Lines_Flexfield_Segment_9>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_9"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_9>
                  <ns0:Invoice_Lines_Flexfield_Segment_10>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_10"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_10>
                  <ns0:Invoice_Lines_Flexfield_Segment_11>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_11"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_11>
                  <ns0:Invoice_Lines_Flexfield_Segment_12>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_12"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_12>
                  <ns0:Invoice_Lines_Flexfield_Segment_13>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_13"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_13>
                  <ns0:Invoice_Lines_Flexfield_Segment_14>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_14"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_14>
                  <ns0:Invoice_Lines_Flexfield_Segment_15>
                     <xsl:value-of select="ns0:Invoice_Lines_Flexfield_Segment_15"/>
                  </ns0:Invoice_Lines_Flexfield_Segment_15>
                  <ns0:Invoice_Transactions_Flexfield_Context>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Context"/>
                  </ns0:Invoice_Transactions_Flexfield_Context>
                  <ns0:Invoice_Transactions_Flexfield_Segment_1>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_1"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_1>
                  <ns0:Invoice_Transactions_Flexfield_Segment_2>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_2"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_2>
                  <ns0:Invoice_Transactions_Flexfield_Segment_3>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_3"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_3>
                  <ns0:Invoice_Transactions_Flexfield_Segment_4>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_4"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_4>
                  <ns0:Invoice_Transactions_Flexfield_Segment_5>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_5"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_5>
                  <ns0:Invoice_Transactions_Flexfield_Segment_6>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_6"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_6>
                  <ns0:Invoice_Transactions_Flexfield_Segment_7>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_7"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_7>
                  <ns0:Invoice_Transactions_Flexfield_Segment_8>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_8"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_8>
                  <ns0:Invoice_Transactions_Flexfield_Segment_9>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_9"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_9>
                  <ns0:Invoice_Transactions_Flexfield_Segment_10>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_10"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_10>
                  <ns0:Invoice_Transactions_Flexfield_Segment_11>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_11"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_11>
                  <ns0:Invoice_Transactions_Flexfield_Segment_12>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_12"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_12>
                  <ns0:Invoice_Transactions_Flexfield_Segment_13>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_13"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_13>
                  <ns0:Invoice_Transactions_Flexfield_Segment_14>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_14"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_14>
                  <ns0:Invoice_Transactions_Flexfield_Segment_15>
                     <xsl:value-of select="ns0:Invoice_Transactions_Flexfield_Segment_15"/>
                  </ns0:Invoice_Transactions_Flexfield_Segment_15>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Context>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Context"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Context>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_1>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_1"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_1>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_2>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_2"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_2>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_3>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_3"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_3>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_4>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_4"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_4>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_5>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_5"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_5>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_6>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_6"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_6>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_7>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_7"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_7>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_8>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_8"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_8>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_9>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_9"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_9>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_10>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_10"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_10>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_11>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_11"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_11>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_12>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_12"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_12>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_13>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_13"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_13>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_14>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_14"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_14>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_15>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_15"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_15>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_16>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_16"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_16>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_17>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_17"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_17>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_18>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_18"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_18>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_19>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_19"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_19>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_20>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_20"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_20>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_21>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_21"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_21>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_22>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_22"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_22>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_23>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_23"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_23>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_24>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_24"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_24>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_25>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_25"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_25>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_26>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_26"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_26>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_27>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_27"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_27>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_28>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_28"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_28>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_29>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_29"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_29>
                  <ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_30>
                     <xsl:value-of select="ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_30"/>
                  </ns0:Receivables_Transaction_Region_Information_Flexfield_Segment_30>
                  <ns0:Line_Global_Descriptive_Flexfield_Attribute_Category>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Attribute_Category"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Attribute_Category>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_1>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_1"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_1>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_2>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_2"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_2>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_3>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_3"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_3>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_4>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_4"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_4>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_5>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_5"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_5>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_6>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_6"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_6>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_7>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_7"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_7>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_8>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_8"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_8>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_9>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_9"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_9>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_10>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_10"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_10>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_11>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_11"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_11>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_12>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_12"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_12>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_13>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_13"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_13>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_14>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_14"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_14>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_15>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_15"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_15>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_16>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_16"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_16>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_17>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_17"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_17>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_18>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_18"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_18>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_19>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_19"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_19>
                  <ns0:Line_Global_Descriptive_Flexfield_Segment_20>
                     <xsl:value-of select="ns0:Line_Global_Descriptive_Flexfield_Segment_20"/>
                  </ns0:Line_Global_Descriptive_Flexfield_Segment_20>
                  <ns0:Business_Unit_Name>
                     <xsl:value-of select="ns0:Business_Unit_Name"/>
                  </ns0:Business_Unit_Name>
                  <ns0:Comments>
                     <xsl:value-of select="ns0:Comments"/>
                  </ns0:Comments>
                  <ns0:Enforce_Chronological_Document_Sequencing>
                     <xsl:value-of select="ns0:Enforce_Chronological_Document_Sequencing"/>
                  </ns0:Enforce_Chronological_Document_Sequencing>
                  <ns0:Aux>
                     <xsl:value-of select="ns0:Aux"/>
                  </ns0:Aux>
                  <ns0:C291>
                     <xsl:value-of select="&quot;END&quot;"/>
                  </ns0:C291>
               </ns0:InvoicesList>
            </xsl:if>
         </xsl:for-each>
      </ns0:invoicesToCsv>
   </xsl:template>
</xsl:stylesheet>
