<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns1="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://soa.estrellaroja.com.mx/ValidacionAutomaticTec" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns5="http://soa.estrellaroja.com.mx/cfd/3"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ElectronicInvoiceAP"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelValidateInvoicesAP"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns6="http://soa.estrellaroja.com.mx/sitio_internet/cfd/tipoDatos/tdCFDI"
                xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns7="http://soa.estrellaroja.com.mx/TimbreFiscalDigital"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns8="http://soa.estrellaroja.com.mx/ValidacionAutomaticTec"
                xmlns:ns9="http://soa.estrellaroja.com.mx/ValidacionAutomaticTec"
                xmlns:ns11="http://www.sat.gob.mx/ConsumoDeCombustibles11"
                xmlns:ns12="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos"
                xmlns:ns13="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/ComExt"
                xmlns:ns14="http://www.sat.gob.mx/sitio_internet/cfd/catalogos"
                xmlns:ns15="http://www.sat.gob.mx/TimbreFiscalDigital"
                xmlns:ns16="http://www.sat.gob.mx/EstadoDeCuentaCombustible12"
                xmlns:ns17="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns10="http://www.sat.gob.mx/cfd/4"
                xmlns:ns18="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte"
                xmlns:ns19="http://www.sat.gob.mx/CartaPorte20"
                xmlns:ns20="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Combustible"
                xmlns:ns21="http://www.sat.gob.mx/nomina12"
                xmlns:ns22="http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI"
                xmlns:ns23="http://www.sat.gob.mx/Pagos20">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelValidateInvoicesAP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InvoiceAP" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelValidateInvoicesAP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DecodeRq" namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"/>
            <oracle-xsl-mapper:param name="invokeWsSOAUtilitiesTecDecodeRq.DecodeRq"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelValidateInvoicesAP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ValidationOracleXmlRequest" namespace="http://soa.estrellaroja.com.mx/ValidacionAutomaticTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 10 01:21:42 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="invokeWsSOAUtilitiesTecDecodeRq.DecodeRq"/>
   <xsl:template match="/">
      <tns:ValidationOracleXmlRequest>
         <tns:businessUnit>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:BusinessUnit"/>
         </tns:businessUnit>
         <tns:creationDate>
            <xsl:value-of select="substring (/ns0:InvoiceAP/ns0:CreationDate, 1, 10 )"/>
         </tns:creationDate>
         <tns:currencyCode>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:Currency"/>
         </tns:currencyCode>
         <xsl:for-each select="/ns0:InvoiceAP/ns0:details">
            <tns:details>
               <tns:amount>
                  <xsl:value-of select="ns0:idAmount"/>
               </tns:amount>
               <tns:baseAmount>
                  <xsl:value-of select="ns0:idBaseAmount"/>
               </tns:baseAmount>
               <tns:description>
                  <xsl:value-of select="ns0:idDescription"/>
               </tns:description>
               <tns:itemDescription>
                  <xsl:value-of select="ns0:idItemDescription"/>
               </tns:itemDescription>
               <tns:itemId>
                  <xsl:value-of select="ns0:idItemId"/>
               </tns:itemId>
               <tns:lineNumber>
                  <xsl:value-of select="ns0:IdLineNumber"/>
               </tns:lineNumber>
               <tns:lineSource>
                  <xsl:value-of select="ns0:idLineSource"/>
               </tns:lineSource>
               <tns:lineType>
                  <xsl:value-of select="ns0:idLineType "/>
               </tns:lineType>
               <tns:orderDetail>
                  <tns:amount>
                     <xsl:value-of select="ns0:odAmount"/>
                  </tns:amount>
                  <tns:codeCombination>
                     <tns:id>
                        <xsl:value-of select="ns0:odCodeCombinationId"/>
                     </tns:id>
                     <tns:segment1>
                        <xsl:value-of select="ns0:gccSegment1"/>
                     </tns:segment1>
                     <tns:segment2>
                        <xsl:value-of select="ns0:gccSegment2"/>
                     </tns:segment2>
                     <tns:segment3>
                        <xsl:value-of select="ns0:gccSegment3"/>
                     </tns:segment3>
                     <tns:segment4>
                        <xsl:value-of select="ns0:gccSegment4"/>
                     </tns:segment4>
                     <tns:segment5>
                        <xsl:value-of select="ns0:gccSegment5"/>
                     </tns:segment5>
                     <tns:type>
                        <xsl:value-of select="ns0:gccAccountType"/>
                     </tns:type>
                  </tns:codeCombination>
                  <tns:destOrganizationId>
                     <xsl:value-of select="ns0:odDestOrganizationId"/>
                  </tns:destOrganizationId>
                  <tns:discount>
                     <xsl:value-of select="ns0:odDiscount"/>
                  </tns:discount>
                  <tns:id>
                     <xsl:value-of select="ns0:orderDetailId"/>
                  </tns:id>
                  <tns:itemDescription>
                     <xsl:value-of select="ns0:odItemDescription"/>
                  </tns:itemDescription>
                  <tns:itemId>
                     <xsl:value-of select="ns0:odItemId"/>
                  </tns:itemId>
                  <tns:lineTypeId>
                     <xsl:value-of select="ns0:odLineTypeId"/>
                  </tns:lineTypeId>
                  <tns:listPrice>
                     <xsl:value-of select="ns0:odListPrice"/>
                  </tns:listPrice>
                  <tns:orderId>
                     <xsl:value-of select="ns0:orderId"/>
                  </tns:orderId>
                  <tns:quantity>
                     <xsl:value-of select="ns0:odQuantity"/>
                  </tns:quantity>
                  <tns:unitCode>
                     <xsl:value-of select="ns0:odUnitCode"/>
                  </tns:unitCode>
                  <tns:unitPrice>
                     <xsl:value-of select="ns0:odUnitPrice"/>
                  </tns:unitPrice>
               </tns:orderDetail>
               <tns:organizationId>
                  <xsl:value-of select="ns0:idOrganizationId"/>
               </tns:organizationId>
               <tns:quantity>
                  <xsl:value-of select="ns0:idQuantity"/>
               </tns:quantity>
               <tns:tax>
                  <xsl:value-of select="ns0:idTax"/>
               </tns:tax>
               <tns:taxClassCode>
                  <xsl:value-of select="ns0:idTaxClassCode"/>
               </tns:taxClassCode>
               <tns:taxJurisdictionCode>
                  <xsl:value-of select="ns0:idTaxJurisdictionCode"/>
               </tns:taxJurisdictionCode>
               <tns:taxLineId>
                  <xsl:value-of select="ns0:idTaxRateId"/>
               </tns:taxLineId>
               <tns:taxRate>
                  <xsl:value-of select="ns0:idTaxRate"/>
               </tns:taxRate>
               <tns:taxRateCode>
                  <xsl:value-of select="ns0:idTaxRateCode"/>
               </tns:taxRateCode>
               <tns:taxRateId>
                  <xsl:value-of select="ns0:idTaxLineId"/>
               </tns:taxRateId>
               <tns:taxRegimeCode>
                  <xsl:value-of select="ns0:idTaxRegimeCode"/>
               </tns:taxRegimeCode>
               <tns:taxStatusCode>
                  <xsl:value-of select="ns0:idTaxStatusCode"/>
               </tns:taxStatusCode>
               <tns:unitCode>
                  <xsl:value-of select="ns0:idUnitCode"/>
               </tns:unitCode>
               <tns:unitPrice>
                  <xsl:value-of select="ns0:idUnitPrice"/>
               </tns:unitPrice>
               <tns:awtGroupId>
                  <xsl:value-of select="ns0:idAwtGroupId"/>
               </tns:awtGroupId>
               <tns:awtGroupCode>
                  <xsl:value-of select="ns0:idAwtGroupCode"/>
               </tns:awtGroupCode>
               <tns:awtPercentageRate>
                  <xsl:value-of select="ns0:awtPercentageRate"/>
               </tns:awtPercentageRate>
            </tns:details>
         </xsl:for-each>
         <tns:folio/>
         <tns:id>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceId"/>
         </tns:id>
         <tns:invoiceDate>
            <xsl:value-of select="substring (/ns0:InvoiceAP/ns0:CreationDate, 1, 10 )"/>
         </tns:invoiceDate>
         <tns:lastUpdateDate>
            <xsl:value-of select="substring (/ns0:InvoiceAP/ns0:LastUpdateDate, 1, 10 )"/>
         </tns:lastUpdateDate>
         <tns:legalEntityId>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:LegalentityId"/>
         </tns:legalEntityId>
         <tns:legalEntityName>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:NameRFC"/>
         </tns:legalEntityName>
         <tns:legalEntityRfc>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:ReceptorRFC"/>
         </tns:legalEntityRfc>
         <tns:legalEntitySegment>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:LegalEntitySegment"/>
         </tns:legalEntitySegment>
         <tns:number>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceNumber"/>
         </tns:number>
         <tns:order>
            <tns:billBuId>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:OrderBillbuId"/>
            </tns:billBuId>
            <tns:email>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:OrdereMail"/>
            </tns:email>
            <tns:id>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:OrderId"/>
            </tns:id>
            <tns:number>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:OrderNumber"/>
            </tns:number>
            <tns:supplierId>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:OrderSupplierId"/>
            </tns:supplierId>
            <tns:termsId>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:OrderTermsId"/>
            </tns:termsId>
         </tns:order>
         <tns:organizationId>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:OrganizationId"/>
         </tns:organizationId>
         <tns:pdfCount>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:PdfRegistrados"/>
         </tns:pdfCount>
         <tns:pdfFileName>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:Pdf"/>
         </tns:pdfFileName>
         <tns:serie>
            <xsl:value-of select='""'/>
         </tns:serie>
         <tns:subtotal>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:Subtotal"/>
         </tns:subtotal>
         <tns:supplier>
            <tns:address>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:Address"/>
            </tns:address>
            <tns:city>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:City"/>
            </tns:city>
            <tns:id>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierId"/>
            </tns:id>
            <tns:name>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierName"/>
            </tns:name>
            <tns:number>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierNumber"/>
            </tns:number>
            <tns:partyId>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierPartyId"/>
            </tns:partyId>
            <tns:rfc>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierRFC"/>
            </tns:rfc>
            <tns:state>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:State"/>
            </tns:state>
            <tns:type>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierType"/>
            </tns:type>
            <tns:zipCode>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:ZipCode"/>
            </tns:zipCode>
            <tns:siteId>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierSiteId"/>
            </tns:siteId>
            <tns:siteCode>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierSiteCode"/>
            </tns:siteCode>
            <tns:siteBusinessUnitId>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierSiteBusinessUnitId"/>
            </tns:siteBusinessUnitId>
            <tns:siteAwtGroupId>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierSiteAwtGroupId"/>
            </tns:siteAwtGroupId>
            <tns:siteAwtGroupCode>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierSiteAwtGroupCode"/>
            </tns:siteAwtGroupCode>
            <tns:siteAwtPercentageRate>
               <xsl:value-of select="/ns0:InvoiceAP/ns0:SupplierSiteAwtPercentageRate"/>
            </tns:siteAwtPercentageRate>
            <tns:sendMailAfterValidation>
               <xsl:value-of select='"true"'/>
            </tns:sendMailAfterValidation>
         </tns:supplier>
         <tns:tax>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:TotalTaxAmount"/>
         </tns:tax>
         <tns:termsDescription>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceTermsDesc"/>
         </tns:termsDescription>
         <tns:termsId>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceTermsId"/>
         </tns:termsId>
         <tns:termsName>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceTermsName"/>
         </tns:termsName>
         <tns:total>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:Total"/>
         </tns:total>
         <tns:type>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceType"/>
         </tns:type>
         <tns:validationStatus>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:Status"/>
         </tns:validationStatus>
         <tns:xmlCount>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:XmlRegistrados"/>
         </tns:xmlCount>
         <tns:xmlFileName>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:Xml"/>
         </tns:xmlFileName>
         <tns:invoiceSource>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceSource"/>
         </tns:invoiceSource>
         <tns:invoiceAwtGroupId>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceAwtGroupId"/>
         </tns:invoiceAwtGroupId>
         <tns:invoiceAwtGroupCode>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceAwtGroupCode"/>
         </tns:invoiceAwtGroupCode>
         <tns:invoiceAwtPercentageRate>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceAwtPercentageRate"/>
         </tns:invoiceAwtPercentageRate>
         <tns:approvalStatus>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:ApprovalStatus"/>
         </tns:approvalStatus>
         <tns:xmlBase64>
            <xsl:value-of select="$invokeWsSOAUtilitiesTecDecodeRq.DecodeRq/ns1:DecodeRq/ns1:charChain"/>
         </tns:xmlBase64>
      </tns:ValidationOracleXmlRequest>
   </xsl:template>
</xsl:stylesheet>
