<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:tns="http://soa.estrellaroja.com.mx/DigitalStampTec"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz"
                exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns2="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelDigitalStamp"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns4="http://soa.estrellaroja.com.mx/cfd/3"
                xmlns:ns5="http://soa.estrellaroja.com.mx/DigitalStampTec/types"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns6="http://soa.estrellaroja.com.mx/sitio_internet/cfd/tipoDatos/tdCFDI"
                xmlns:ns7="http://soa.estrellaroja.com.mx/TimbreFiscalDigital"
                xmlns:ns8="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelDigitalStamp.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DATA_DS" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DigitalStampTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="createTrxCFDIRq"
                                           namespace="http://soa.estrellaroja.com.mx/DigitalStampTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE JAN 30 15:37:29 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:createTrxCFDIRq>
         <tns:invoice>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:id_rfc/text()">
               <tns:id_rfc>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:id_rfc"/>
               </tns:id_rfc>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:certificate_number/text()">
               <tns:certificate_number>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:certificate_number"/>
               </tns:certificate_number>
            </xsl:if>
            <tns:issuer_rfc>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_rfc"/>
            </tns:issuer_rfc>
            <tns:issuer_name>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_name"/>
            </tns:issuer_name>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:issuer_street/text()">
               <tns:issuer_street>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_street"/>
               </tns:issuer_street>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:issuer_ext_number/text()">
               <tns:issuer_ext_number>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_ext_number"/>
               </tns:issuer_ext_number>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:issuer_int_number/text()">
               <tns:issuer_int_number>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_int_number"/>
               </tns:issuer_int_number>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:issuer_colony/text()">
               <tns:issuer_colony>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_colony"/>
               </tns:issuer_colony>
            </xsl:if>
            <tns:issuer_zip_code>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_zip_code"/>
            </tns:issuer_zip_code>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:issuer_municipality/text()">
               <tns:issuer_municipality>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_municipality"/>
               </tns:issuer_municipality>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:issuer_state/text()">
               <tns:issuer_state>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_state"/>
               </tns:issuer_state>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:issuer_phone/text()">
               <tns:issuer_phone>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_phone"/>
               </tns:issuer_phone>
            </xsl:if>
            <tns:issuer_country>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_country"/>
            </tns:issuer_country>
            <tns:invoice_date>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:invoice_date"/>
            </tns:invoice_date>
            <tns:document_type>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:document_type"/>
            </tns:document_type>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:additional_information/text()">
               <tns:additional_information>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:additional_information"/>
               </tns:additional_information>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:cancellation_date/text()">
               <tns:cancellation_date>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:cancellation_date"/>
               </tns:cancellation_date>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:total_words/text()">
               <tns:total_words>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:total_words"/>
               </tns:total_words>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:total_items/text()">
               <tns:total_items>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:total_items"/>
               </tns:total_items>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:local_retention_name/text()">
               <tns:local_retention_name>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:local_retention_name"/>
               </tns:local_retention_name>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:local_retention_percentage/text()">
               <tns:local_retention_percentage>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:local_retention_percentage"/>
               </tns:local_retention_percentage>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:local_retencion_amount/text()">
               <tns:local_retencion_amount>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:local_retencion_amount"/>
               </tns:local_retencion_amount>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:total_vat/text()">
               <tns:total_vat>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:total_vat"/>
               </tns:total_vat>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:total_stps/text()">
               <tns:total_stps>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:total_stps"/>
               </tns:total_stps>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:total_st/text()">
               <tns:total_st>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:total_st"/>
               </tns:total_st>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:total_tips/text()">
               <tns:total_tip>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:total_tips"/>
               </tns:total_tip>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:retention_vat/text()">
               <tns:retention_vat>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:retention_vat"/>
               </tns:retention_vat>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:retention_rt/text()">
               <tns:retention_rt>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:retention_rt"/>
               </tns:retention_rt>
            </xsl:if>
            <tns:subtotal>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:subtotal"/>
            </tns:subtotal>
            <tns:total>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:total"/>
            </tns:total>
            <tns:serie>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:serie"/>
            </tns:serie>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_id/text()">
               <tns:branch_id>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_id"/>
               </tns:branch_id>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_number/text()">
               <tns:branch_number>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_number"/>
               </tns:branch_number>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_name/text()">
               <tns:branch_name>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_name"/>
               </tns:branch_name>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_street/text()">
               <tns:branch_street>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_street"/>
               </tns:branch_street>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_ext_number/text()">
               <tns:branch_ext_number>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_ext_number"/>
               </tns:branch_ext_number>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_int_number/text()">
               <tns:branch_int_number>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_int_number"/>
               </tns:branch_int_number>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_colony/text()">
               <tns:branch_colony>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_colony"/>
               </tns:branch_colony>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_zip_code/text()">
               <tns:branch_zip_code>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_zip_code"/>
               </tns:branch_zip_code>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_municipality/text()">
               <tns:branch_municipality>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_municipality"/>
               </tns:branch_municipality>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_state/text()">
               <tns:branch_state>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_state"/>
               </tns:branch_state>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_reference/text()">
               <tns:branch_reference>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_reference"/>
               </tns:branch_reference>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_phone/text()">
               <tns:branch_phone>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_phone"/>
               </tns:branch_phone>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:branch_country/text()">
               <tns:branch_country>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:branch_country"/>
               </tns:branch_country>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_name/text()">
               <tns:receiver_name>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_name"/>
               </tns:receiver_name>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_email/text()">
               <tns:receiver_email>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_email"/>
               </tns:receiver_email>
            </xsl:if>
            <tns:receiver_rfc>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_rfc"/>
            </tns:receiver_rfc>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_phone/text()">
               <tns:receiver_phone>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_phone"/>
               </tns:receiver_phone>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_street/text()">
               <tns:receiver_street>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_street"/>
               </tns:receiver_street>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_ext_number/text()">
               <tns:receiver_ext_number>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_ext_number"/>
               </tns:receiver_ext_number>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_int_number/text()">
               <tns:receiver_int_number>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_int_number"/>
               </tns:receiver_int_number>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_colony/text()">
               <tns:receiver_colony>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_colony"/>
               </tns:receiver_colony>
            </xsl:if>
            <tns:receiver_zip_code>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_zip_code"/>
            </tns:receiver_zip_code>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_municipality/text()">
               <tns:receiver_municipality>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_municipality"/>
               </tns:receiver_municipality>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_state/text()">
               <tns:receiver_state>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_state"/>
               </tns:receiver_state>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_country/text()">
               <tns:receiver_country>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_country"/>
               </tns:receiver_country>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:receiver_passport/text()">
               <tns:receiver_passport>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_passport"/>
               </tns:receiver_passport>
            </xsl:if>
            <tns:receiver_cfdi_use>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:receiver_cfdi_use"/>
            </tns:receiver_cfdi_use>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:payment_method/text()">
               <tns:payment_method>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:payment_method"/>
               </tns:payment_method>
            </xsl:if>
            <tns:currency>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:currency"/>
            </tns:currency>
            <tns:issuer_tax_regime>
               <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:issuer_tax_regime"/>
            </tns:issuer_tax_regime>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:currency_exchange_rate/text()">
               <tns:currency_exchange_rate>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:currency_exchange_rate"/>
               </tns:currency_exchange_rate>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:payment_method_select/text()">
               <tns:payment_method_select>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:payment_method_select"/>
               </tns:payment_method_select>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:added_payment_methods/text()">
               <tns:added_payment_methods>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:added_payment_methods"/>
               </tns:added_payment_methods>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:payment_form/text()">
               <tns:payment_form>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:payment_form"/>
               </tns:payment_form>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:payment_condition/text()">
               <tns:payment_condition>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:payment_condition"/>
               </tns:payment_condition>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:payment_status/text()">
               <tns:payment_status>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:payment_status"/>
               </tns:payment_status>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:payment_account_number/text()">
               <tns:payment_account_number>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:payment_account_number"/>
               </tns:payment_account_number>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:discount/text()">
               <tns:discount>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:discount"/>
               </tns:discount>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:comments/text()">
               <tns:comments>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:comments"/>
               </tns:comments>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:service/text()">
               <tns:service>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:service"/>
               </tns:service>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:relationship_type/text()">
               <tns:relationship_type>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:relationship_type"/>
               </tns:relationship_type>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:related_cfdi/text()">
               <tns:related_cfdi>
                  <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:related_cfdi"/>
               </tns:related_cfdi>
            </xsl:if>
            <tns:invoice_items>
               <xsl:for-each select="/ns0:DATA_DS/ns0:invoice/ns0:item">
                  <tns:Item>
                     <tns:description>
                        <xsl:value-of select="ns0:description"/>
                     </tns:description>
                     <xsl:if test="ns0:prod_serv_key/text()">
                        <tns:prod_serv_key>
                           <xsl:value-of select="ns0:prod_serv_key"/>
                        </tns:prod_serv_key>
                     </xsl:if>
                     <xsl:if test="ns0:quantity/text()">
                        <tns:quantity>
                           <xsl:value-of select="ns0:quantity"/>
                        </tns:quantity>
                     </xsl:if>
                     <xsl:if test="ns0:discount/text()">
                        <tns:discount>
                           <xsl:value-of select="ns0:discount"/>
                        </tns:discount>
                     </xsl:if>
                     <xsl:if test="ns0:vat_percentage/text()">
                        <tns:vat_percentage>
                           <xsl:value-of select="ns0:vat_percentage"/>
                        </tns:vat_percentage>
                     </xsl:if>
                     <xsl:if test="ns0:unit/text()">
                        <tns:unit>
                           <xsl:value-of select="ns0:unit"/>
                        </tns:unit>
                     </xsl:if>
                     <xsl:if test="ns0:unit_key/text()">
                        <tns:unit_key>
                           <xsl:value-of select="ns0:unit_key"/>
                        </tns:unit_key>
                     </xsl:if>
                     <xsl:if test="ns0:unit_price/text()">
                        <tns:unit_price>
                           <xsl:value-of select="ns0:unit_price"/>
                        </tns:unit_price>
                     </xsl:if>
                     <xsl:if test="ns0:tax_base/text()">
                        <tns:tax_base>
                           <xsl:value-of select="ns0:tax_base"/>
                        </tns:tax_base>
                     </xsl:if>
                     <xsl:if test="ns0:tax/text()">
                        <tns:tax>
                           <xsl:value-of select="ns0:tax"/>
                        </tns:tax>
                     </xsl:if>
                     <xsl:if test="ns0:factor_type/text()">
                        <tns:factor_type>
                           <xsl:value-of select="ns0:factor_type"/>
                        </tns:factor_type>
                     </xsl:if>
                     <xsl:if test="ns0:rate_fee/text()">
                        <tns:rate_fee>
                           <xsl:value-of select="ns0:rate_fee"/>
                        </tns:rate_fee>
                     </xsl:if>
                     <xsl:if test="ns0:stps_percentage/text()">
                        <tns:stps_percentage>
                           <xsl:value-of select="ns0:stps_percentage"/>
                        </tns:stps_percentage>
                     </xsl:if>
                     <xsl:if test="ns0:imp_percentage/text()">
                        <tns:imp_percentage>
                           <xsl:value-of select="ns0:imp_percentage"/>
                        </tns:imp_percentage>
                     </xsl:if>
                     <xsl:if test="ns0:retention_vat_percentage/text()">
                        <tns:retention_vat_percentage>
                           <xsl:value-of select="ns0:retention_vat_percentage"/>
                        </tns:retention_vat_percentage>
                     </xsl:if>
                     <xsl:if test="ns0:retention_rt_percentage/text()">
                        <tns:retention_rt_percentage>
                           <xsl:value-of select="ns0:retention_rt_percentage"/>
                        </tns:retention_rt_percentage>
                     </xsl:if>
                     <tns:amount>
                        <xsl:value-of select="ns0:amount"/>
                     </tns:amount>
                     <tns:subtotal>
                        <xsl:value-of select="ns0:subtotal"/>
                     </tns:subtotal>
                     <xsl:if test="ns0:vat/text()">
                        <tns:vat>
                           <xsl:value-of select="ns0:vat"/>
                        </tns:vat>
                     </xsl:if>
                     <xsl:if test="ns0:stps/text()">
                        <tns:stps>
                           <xsl:value-of select="ns0:stps"/>
                        </tns:stps>
                     </xsl:if>
                     <xsl:if test="ns0:imp/text()">
                        <tns:imp>
                           <xsl:value-of select="ns0:imp"/>
                        </tns:imp>
                     </xsl:if>
                     <xsl:if test="ns0:retention_vat/text()">
                        <tns:retention_vat>
                           <xsl:value-of select="ns0:retention_vat"/>
                        </tns:retention_vat>
                     </xsl:if>
                     <xsl:if test="ns0:retention_rt/text()">
                        <tns:retention_rt>
                           <xsl:value-of select="ns0:retention_rt"/>
                        </tns:retention_rt>
                     </xsl:if>
                     <tns:total>
                        <xsl:value-of select="ns0:total"/>
                     </tns:total>
                     <xsl:if test="ns0:st/text()">
                        <tns:st>
                           <xsl:value-of select="ns0:st"/>
                        </tns:st>
                     </xsl:if>
                     <xsl:if test="ns0:addendum_interface_apply/text()">
                        <tns:addendum_interface_apply>
                           <xsl:value-of select="ns0:addendum_interface_apply"/>
                        </tns:addendum_interface_apply>
                     </xsl:if>
                     <xsl:if test="ns0:addendum_interface_type/text()">
                        <tns:addendum_interface_type>
                           <xsl:value-of select="ns0:addendum_interface_type"/>
                        </tns:addendum_interface_type>
                     </xsl:if>
                     <xsl:if test="ns0:addendum_interface_concept/text()">
                        <tns:addendum_interface_concept>
                           <xsl:value-of select="ns0:addendum_interface_concept"/>
                        </tns:addendum_interface_concept>
                     </xsl:if>
                  </tns:Item>
               </xsl:for-each>
            </tns:invoice_items>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:grupo_ado">
              <tns:addendaAdo>
                 <tns:grupo_ado>
                    <tns:tipoAddenda>
                       <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:grupo_ado/ns0:tipoAddenda"/>
                    </tns:tipoAddenda>
                    <tns:valor>
                       <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:grupo_ado/ns0:addendaValor"/>
                    </tns:valor>
                 </tns:grupo_ado>
              </tns:addendaAdo>
            </xsl:if>
            <xsl:if test="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw">
               <tns:addendaVW>
                  <tns:psv_vw>
                     <tns:moneda>
                        <tns:tipoMoneda>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:moneda/ns0:tipoMoneda"/>
                        </tns:tipoMoneda>
                        <tns:tipoCambio>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:moneda/ns0:tipoCambio"/>
                        </tns:tipoCambio>
                        <tns:codigoImpuesto>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:moneda/ns0:codigoImpuesto"/>
                        </tns:codigoImpuesto>
                     </tns:moneda>
                     <tns:proveedor>
                        <tns:codigo>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:proveedor/ns0:codigo"/>
                        </tns:codigo>
                        <tns:nombre>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:proveedor/ns0:nombre"/>
                        </tns:nombre>
                        <tns:correoContacto>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:proveedor/ns0:correoContacto"/>
                        </tns:correoContacto>
                     </tns:proveedor>
                     <tns:destino>
                        <tns:codigo>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:destino/ns0:codigo"/>
                        </tns:codigo>
                     </tns:destino>
                     <tns:referencias>
                        <tns:referenciaProveedor>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:referencias/ns0:referenciaProveedor"/>
                        </tns:referenciaProveedor>
                        <tns:numeroASN>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:referencias/ns0:numeroASN"/>
                        </tns:numeroASN>
                     </tns:referencias>
                     <tns:solicitante>
                        <tns:nombre>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:solicitante/ns0:nombre"/>
                        </tns:nombre>
                        <tns:correo>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:solicitante/ns0:correo"/>
                        </tns:correo>
                     </tns:solicitante>
                     <tns:partes>
                        <tns:referencias>
                           <tns:ordenCompra>
                              <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:ordenCompra"/>
                           </tns:ordenCompra>
                        </tns:referencias>
                        <tns:posicion>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:parte/ns0:posicion"/>
                        </tns:posicion>
                        <tns:numeroMaterial>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:parte/ns0:numeroMaterial"/>
                        </tns:numeroMaterial>
                        <tns:descripcionMaterial>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:parte/ns0:descripcionMaterial"/>
                        </tns:descripcionMaterial>
                        <tns:cantidadMaterial>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:parte/ns0:cantidadMaterial"/>
                        </tns:cantidadMaterial>
                        <tns:unidadMedida>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:parte/ns0:unidadMedida"/>
                        </tns:unidadMedida>
                        <tns:precioUnitario>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:parte/ns0:precioUnitario"/>
                        </tns:precioUnitario>
                        <tns:montoLinea>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:parte/ns0:montoLinea"/>
                        </tns:montoLinea>
                        <tns:pesoBruto>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:parte/ns0:pesoBruto"/>
                        </tns:pesoBruto>
                        <tns:pesoNeto>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:parte/ns0:pesoNeto"/>
                        </tns:pesoNeto>
                        <tns:codigoImpuesto>
                           <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:partes/ns0:referencia/ns0:parte/ns0:codigoImpuesto"/>
                        </tns:codigoImpuesto>
                     </tns:partes>
                     <tns:version>
                        <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:version"/>
                     </tns:version>
                     <tns:tipoDocumentoFiscal>
                        <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:tipoDocumentoFiscal"/>
                     </tns:tipoDocumentoFiscal>
                     <tns:tipoDocumentoVWM>
                        <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:tipoDocumentoVWM"/>
                     </tns:tipoDocumentoVWM>
                     <tns:division>
                        <xsl:value-of select="/ns0:DATA_DS/ns0:invoice/ns0:psv_vw/ns0:division"/>
                     </tns:division>
                  </tns:psv_vw>
               </tns:addendaVW>
            </xsl:if>
         </tns:invoice>
      </tns:createTrxCFDIRq>
   </xsl:template>
</xsl:stylesheet>
