<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://soa.estrellaroja.com.mx/StructureTrxInterface" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesEnt"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesEnt/bpelLoadInvoices"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns4="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelLoadInvoices.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ParamsToUpdateUuid" namespace="http://soa.estrellaroja.com.mx/StructureTrxInterface"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/InvoicesBizWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="UpdateUuidRq" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI JAN 26 09:47:37 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:UpdateUuidRq>
         <xsl:for-each select="/ns0:ParamsToUpdateUuid/ns0:Params">
            <tns:ListUpdateUuidRq>
               <tns:OperationMode>
                  <xsl:value-of select='"single"'/>
               </tns:OperationMode>
               <tns:Object>
                  <ns4:EntityName>
                     <xsl:value-of select='"Receivables Invoice"'/>
                  </ns4:EntityName>
                  <ns4:ContextValue>
                     <xsl:value-of select='"Contabilidad Electronica (MX)"'/>
                  </ns4:ContextValue>
                  <ns4:UserKeyA>
                     <xsl:value-of select="ns0:TrxNumber"/>
                  </ns4:UserKeyA>
                  <ns4:UserKeyB>
                     <xsl:value-of select='"#NULL"'/>
                  </ns4:UserKeyB>
                  <ns4:UserKeyC>
                     <xsl:value-of select='"#NULL"'/>
                  </ns4:UserKeyC>
                  <ns4:UserKeyD>
                     <xsl:value-of select="ns0:CUSTOMER_TRX_ID"/>
                  </ns4:UserKeyD>
                  <ns4:UserKeyE>
                     <xsl:value-of select='"#NULL"'/>
                  </ns4:UserKeyE>
                  <ns4:DFFAttributes>
                     <xsl:value-of select="concat('{','&quot;ATTRIBUTE3&quot;:','&quot;', ns0:UUID, '&quot;,', '&quot;ATTRIBUTE5&quot;:','&quot;',substring-after (ns0:TrxNumber, '-' ),'&quot;','}')"/>
                  </ns4:DFFAttributes>
               </tns:Object>
               <tns:NotificationCode>
                  <xsl:value-of select='"10"'/>
               </tns:NotificationCode>

            </tns:ListUpdateUuidRq>
            <tns:ListUpdateUuidRq>
               <tns:OperationMode>single</tns:OperationMode>
               <tns:Object>
                  <ns4:EntityName>Receivables Invoice</ns4:EntityName>
                  <ns4:ContextValue>JLxMXReceivablesInformation</ns4:ContextValue>
                  <ns4:UserKeyA>
                     <xsl:value-of select="ns0:TrxNumber"/>
                  </ns4:UserKeyA>
                  <ns4:UserKeyB>#NULL</ns4:UserKeyB>
                  <ns4:UserKeyC>#NULL</ns4:UserKeyC>
                  <ns4:UserKeyD>
                     <xsl:value-of select="ns0:CUSTOMER_TRX_ID"/>
                  </ns4:UserKeyD>
                  <ns4:UserKeyE>#NULL</ns4:UserKeyE>
                  <ns4:DFFAttributes>
                     <xsl:value-of select="concat (concat (concat (concat (concat (concat (concat (concat (&quot;{&quot;, '&quot;' ), &quot;GLOBAL_ATTRIBUTE1&quot; ), '&quot;' ), &quot;:&quot; ), '&quot;' ), ns0:UUID ), '&quot;' ), &quot;}&quot; )"/>
                  </ns4:DFFAttributes>
               </tns:Object>
               <tns:NotificationCode>10</tns:NotificationCode>
            </tns:ListUpdateUuidRq>
         </xsl:for-each>
      </tns:UpdateUuidRq>
   </xsl:template>
</xsl:stylesheet>
