<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesAP" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesEnt/bpelValidateInvoicesAP"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesEnt"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns5="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelValidateInvoicesAP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DATA_DS" namespace="http://soa.estrellaroja.com.mx/InvoicesAP"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/InvoicesBizWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ValidateInvoicesAPRq" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 14 19:23:43 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ValidateInvoicesAPRq>
         <tns:InvoicesAP>
            <xsl:for-each select="/ns0:DATA_DS/ns0:G_INVOICES">
               <tns:InvoiceAP>
                  <tns:SupplierId>
                     <xsl:value-of select="ns0:SUPPLIER_ID"/>
                  </tns:SupplierId>
                  <tns:SupplierRFC>
                     <xsl:value-of select="ns0:SUPPLIER_RFC"/>
                  </tns:SupplierRFC>
                  <tns:Total>
                     <xsl:value-of select="ns0:TOTAL"/>
                  </tns:Total>
                  <xsl:if test="ns0:SUBTOTAL">
                     <tns:Subtotal>
                        <xsl:value-of select="ns0:SUBTOTAL"/>
                     </tns:Subtotal>
                  </xsl:if>
                  <tns:SupplierName>
                     <xsl:value-of select="ns0:SUPPLIERNAME"/>
                  </tns:SupplierName>
                  <tns:InvoiceDate>
                     <xsl:value-of select="ns0:INVOICEDATE"/>
                  </tns:InvoiceDate>
                  <tns:CreationDate>
                     <xsl:value-of select="ns0:CREATION_DATE"/>
                  </tns:CreationDate>
                  <tns:LastUpdateDate>
                     <xsl:value-of select="ns0:LAST_UPDATE_DATE"/>
                  </tns:LastUpdateDate>
                  <tns:Status>
                     <xsl:value-of select="ns0:APPROVAL_STATUS"/>
                  </tns:Status>
                  <tns:Currency>
                     <xsl:value-of select="ns0:CURRENCY"/>
                  </tns:Currency>
                  <tns:ReceptorRFC>
                     <xsl:value-of select="ns0:RECEPTOR_RFC"/>
                  </tns:ReceptorRFC>
                  <tns:NameRFC>
                     <xsl:value-of select="ns0:NAME_RFC"/>
                  </tns:NameRFC>
                  <tns:InvoiceId>
                     <xsl:value-of select="ns0:INVOICE_ID"/>
                  </tns:InvoiceId>
                  <tns:SupplierNumber>
                     <xsl:value-of select="ns0:SUPPLIER_NUMBER"/>
                  </tns:SupplierNumber>
                  <tns:InvoiceNumber>
                     <xsl:value-of select="ns0:INVOICE_NUMBER"/>
                  </tns:InvoiceNumber>
                  <xsl:if test="ns0:TOTAL_TAX_AMOUNT">
                     <tns:TotalTaxAmount>
                        <xsl:value-of select="ns0:TOTAL_TAX_AMOUNT"/>
                     </tns:TotalTaxAmount>
                  </xsl:if>
                  <tns:BusinessUnit>
                     <xsl:value-of select="ns0:BUSINESS_UNIT"/>
                  </tns:BusinessUnit>
                  <tns:InvoiceSource>
                     <xsl:value-of select="ns0:INVOICESOURCE"/>
                  </tns:InvoiceSource>
                  <tns:InvoiceType>
                     <xsl:value-of select="ns0:INVOICETYPE"/>
                  </tns:InvoiceType>
                  <tns:InvoiceAwtGroupId>
                     <xsl:value-of select="ns0:INVOICEAWTGROUPID"/>
                  </tns:InvoiceAwtGroupId>
                  <tns:InvoiceAwtGroupCode>
                     <xsl:value-of select="ns0:INVOICEAWTGROUPCODE"/>
                  </tns:InvoiceAwtGroupCode>
                  <tns:InvoiceAwtPercentageRate>
                     <xsl:value-of select="ns0:INVOICE_PERCENTAGE_RATE"/>
                  </tns:InvoiceAwtPercentageRate>
                  <tns:InvoiceTermsId>
                     <xsl:value-of select="ns0:INVOICETERMSID"/>
                  </tns:InvoiceTermsId>
                  <tns:InvoiceTermsName>
                     <xsl:value-of select="ns0:INVOICETERMSNAME"/>
                  </tns:InvoiceTermsName>
                  <tns:InvoiceTermsDesc>
                     <xsl:value-of select="ns0:INVOICETERMSDESC"/>
                  </tns:InvoiceTermsDesc>
                  <tns:ApprovalStatus>
                     <xsl:value-of select="ns0:APPROVALSTATUS"/>
                  </tns:ApprovalStatus>
                  <tns:SupplierPartyId>
                     <xsl:value-of select="ns0:SUPPLIERPARTYID"/>
                  </tns:SupplierPartyId>
                  <tns:SupplierSiteId>
                     <xsl:value-of select="ns0:SUPPLIERSITEID"/>
                  </tns:SupplierSiteId>
                  <tns:SupplierSiteCode>
                     <xsl:value-of select="ns0:SUPPLIERSITECODE"/>
                  </tns:SupplierSiteCode>
                  <tns:SupplierSiteBusinessUnitId>
                     <xsl:value-of select="ns0:SUPPLIERSITEBUSINESSUNITID"/>
                  </tns:SupplierSiteBusinessUnitId>
                  <tns:SupplierSiteAwtGroupId>
                     <xsl:value-of select="ns0:SUPPLIERSITEAWTGROUPID"/>
                  </tns:SupplierSiteAwtGroupId>
                  <tns:SupplierSiteAwtGroupCode>
                     <xsl:value-of select="ns0:SUPPLIERSITEAWTGROUPCODE"/>
                  </tns:SupplierSiteAwtGroupCode>
                  <tns:SupplierSiteAwtPercentageRate>
                     <xsl:value-of select="ns0:SUPPLIER_PERCENTAGE_RATE"/>
                  </tns:SupplierSiteAwtPercentageRate>
                  <tns:SupplierType>
                     <xsl:value-of select="ns0:SUPPLIERTYPE"/>
                  </tns:SupplierType>
                  <tns:State>
                     <xsl:value-of select="ns0:STATE"/>
                  </tns:State>
                  <tns:City>
                     <xsl:value-of select="ns0:CITY"/>
                  </tns:City>
                  <tns:Address>
                     <xsl:value-of select="ns0:ADDRESS"/>
                  </tns:Address>
                  <tns:ZipCode>
                     <xsl:value-of select="ns0:ZIPCODE"/>
                  </tns:ZipCode>
                  <tns:OrderId>
                     <xsl:value-of select="ns0:ORDERID"/>
                  </tns:OrderId>
                  <tns:OrderNumber>
                     <xsl:value-of select="ns0:ORDERNUMBER"/>
                  </tns:OrderNumber>
                  <tns:OrderBillbuId>
                     <xsl:value-of select="ns0:ORDERBILLBUID"/>
                  </tns:OrderBillbuId>
                  <tns:OrderSupplierId>
                     <xsl:value-of select="ns0:ORDERSUPPLIERID"/>
                  </tns:OrderSupplierId>
                  <tns:OrdereMail>
                     <xsl:value-of select="ns0:ORDEREMAIL"/>
                  </tns:OrdereMail>
                  <tns:OrderTermsId>
                     <xsl:value-of select="ns0:ORDERTERMSID"/>
                  </tns:OrderTermsId>
                  <tns:OrganizationId>
                     <xsl:value-of select="ns0:ORGANIZATIONID"/>
                  </tns:OrganizationId>
                  <tns:LegalentityId>
                     <xsl:value-of select="ns0:LEGALENTITYID"/>
                  </tns:LegalentityId>
                  <tns:LegalEntitySegment>
                     <xsl:value-of select="ns0:LEGALENTITYSEGMENT"/>
                  </tns:LegalEntitySegment>
                  <tns:Xml>
                     <xsl:value-of select="ns0:XML"/>
                  </tns:Xml>
                  <tns:XmlRegistrados>
                     <xsl:value-of select="ns0:XML_REGISTRADOS"/>
                  </tns:XmlRegistrados>
                  <tns:Pdf>
                     <xsl:value-of select="ns0:PDF"/>
                  </tns:Pdf>
                  <tns:PdfRegistrados>
                     <xsl:value-of select="ns0:PDF_REGISTRADOS"/>
                  </tns:PdfRegistrados>
                  <xsl:for-each select="ns0:G_INVOICES1">
                     <tns:details>
                        <tns:IdLineNumber>
                           <xsl:value-of select="ns0:IDLINENUMBER"/>
                        </tns:IdLineNumber>
                        <tns:idLineType>
                           <xsl:value-of select="ns0:IDLINETYPE"/>
                        </tns:idLineType>
                        <tns:idDescription>
                           <xsl:value-of select="ns0:IDDESCRIPTION"/>
                        </tns:idDescription>
                        <tns:idLineSource>
                           <xsl:value-of select="ns0:IDLINESOURCE"/>
                        </tns:idLineSource>
                        <tns:idOrganizationId>
                           <xsl:value-of select="ns0:IDORGANIZATIONID"/>
                        </tns:idOrganizationId>
                        <tns:idItemId>
                           <xsl:value-of select="ns0:IDITEMID"/>
                        </tns:idItemId>
                        <tns:idItemDescription>
                           <xsl:value-of select="ns0:IDITEMDESCRIPTION"/>
                        </tns:idItemDescription>
                        <tns:idUnitCode>
                           <xsl:value-of select="ns0:IDUNITCODE"/>
                        </tns:idUnitCode>
                        <tns:idUnitPrice>
                           <xsl:value-of select="ns0:IDUNITPRICE"/>
                        </tns:idUnitPrice>
                        <tns:idQuantity>
                           <xsl:value-of select="ns0:IDQUANTITY"/>
                        </tns:idQuantity>
                        <tns:idAmount>
                           <xsl:value-of select="ns0:IDAMOUNT"/>
                        </tns:idAmount>
                        <tns:idBaseAmount>
                           <xsl:value-of select="ns0:IDBASEAMOUNT"/>
                        </tns:idBaseAmount>
                        <tns:idTaxLineId>
                           <xsl:value-of select="ns0:IDTAXLINEID"/>
                        </tns:idTaxLineId>
                        <tns:idTaxRegimeCode>
                           <xsl:value-of select="ns0:IDTAXREGIMECODE"/>
                        </tns:idTaxRegimeCode>
                        <tns:idTax>
                           <xsl:value-of select="ns0:IDTAX"/>
                        </tns:idTax>
                        <tns:idTaxJurisdictionCode>
                           <xsl:value-of select="ns0:IDTAXJURISDICTIONCODE"/>
                        </tns:idTaxJurisdictionCode>
                        <tns:idTaxStatusCode>
                           <xsl:value-of select="ns0:IDTAXSTATUSCODE"/>
                        </tns:idTaxStatusCode>
                        <tns:idTaxRateId>
                           <xsl:value-of select="ns0:IDTAXRATEID"/>
                        </tns:idTaxRateId>
                        <tns:idTaxRateCode>
                           <xsl:value-of select="ns0:IDTAXRATECODE"/>
                        </tns:idTaxRateCode>
                        <tns:idTaxRate>
                           <xsl:value-of select="ns0:IDTAXRATE"/>
                        </tns:idTaxRate>
                        <tns:idTaxClassCode>
                           <xsl:value-of select="ns0:IDTAXCLASSCODE"/>
                        </tns:idTaxClassCode>
                        <tns:idAwtGroupId>
                           <xsl:value-of select="ns0:IDAWTGROUPID"/>
                        </tns:idAwtGroupId>
                        <tns:idAwtGroupCode>
                           <xsl:value-of select="ns0:IDAWTGROUPCODE"/>
                        </tns:idAwtGroupCode>
                        <tns:awtPercentageRate>
                           <xsl:value-of select="ns0:PERCENTAGE_RATE"/>
                        </tns:awtPercentageRate>
                        <tns:orderId>
                           <xsl:value-of select="ns0:ORDERID"/>
                        </tns:orderId>
                        <tns:orderDetailId>
                           <xsl:value-of select="ns0:ORDERDETAILID"/>
                        </tns:orderDetailId>
                        <tns:odDiscount>
                           <xsl:value-of select="ns0:ODDISCOUNT"/>
                        </tns:odDiscount>
                        <tns:odListPrice>
                           <xsl:value-of select="ns0:ODLISTPRICE"/>
                        </tns:odListPrice>
                        <tns:odLineTypeId>
                           <xsl:value-of select="ns0:ODLINETYPEID"/>
                        </tns:odLineTypeId>
                        <tns:odItemId>
                           <xsl:value-of select="ns0:ODITEMID"/>
                        </tns:odItemId>
                        <tns:odItemDescription>
                           <xsl:value-of select="ns0:ODITEMDESCRIPTION"/>
                        </tns:odItemDescription>
                        <tns:odUnitCode>
                           <xsl:value-of select="ns0:ODUNITCODE"/>
                        </tns:odUnitCode>
                        <tns:odUnitPrice>
                           <xsl:value-of select="ns0:ODUNITPRICE"/>
                        </tns:odUnitPrice>
                        <tns:odQuantity>
                           <xsl:value-of select="ns0:ODQUANTITY"/>
                        </tns:odQuantity>
                        <tns:odAmount>
                           <xsl:value-of select="ns0:ODAMOUNT"/>
                        </tns:odAmount>
                        <tns:odCodeCombinationId>
                           <xsl:value-of select="ns0:ODCODECOMBINATIONID"/>
                        </tns:odCodeCombinationId>
                        <tns:odDestOrganizationId>
                           <xsl:value-of select="ns0:ODDESTORGANIZATIONID"/>
                        </tns:odDestOrganizationId>
                        <tns:gccAccountType>
                           <xsl:value-of select="ns0:GCCACCOUNTTYPE"/>
                        </tns:gccAccountType>
                        <tns:gccSegment1>
                           <xsl:value-of select="ns0:GCCSEGMENT1"/>
                        </tns:gccSegment1>
                        <tns:gccSegment2>
                           <xsl:value-of select="ns0:GCCSEGMENT2"/>
                        </tns:gccSegment2>
                        <tns:gccSegment3>
                           <xsl:value-of select="ns0:GCCSEGMENT3"/>
                        </tns:gccSegment3>
                        <tns:gccSegment4>
                           <xsl:value-of select="ns0:GCCSEGMENT4"/>
                        </tns:gccSegment4>
                        <tns:gccSegment5>
                           <xsl:value-of select="ns0:GCCSEGMENT5"/>
                        </tns:gccSegment5>
                     </tns:details>
                  </xsl:for-each>
               </tns:InvoiceAP>
            </xsl:for-each>
         </tns:InvoicesAP>
      </tns:ValidateInvoicesAPRq>
   </xsl:template>
</xsl:stylesheet>
