<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://soa.estrellaroja.com.mx/CFDITec" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://soa.estrellaroja.com.mx/AuditControlTec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/CFDI"
                xmlns:ns4="http://soa.estrellaroja.com.mx/Reports/XXER_AP_INVOICE_VALIDATION_AUTOMATICA"
                xmlns:ns5="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:client="http://soa.estrellaroja.com.mx/CFDITec/BpelGetInvoiceCFDIFromERP"
                xmlns:ns6="http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI"
                xmlns:ns7="http://www.sat.gob.mx/sitio_internet/cfd/catalogos"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns8="http://soa.estrellaroja.com.mx/AuditControlTec/types"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns9="http://soa.estrellaroja.com.mx/Reports/XXER_ValidationComplement">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BpelGetInvoiceCFDIFromERP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetInvoiceCFDIFromERPRs" namespace="http://soa.estrellaroja.com.mx/CFDITec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/OSB/AuditControlTec/AuditControlTec.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MergeInvoicesAPRq" namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED JAN 25 12:34:13 CST 2023].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:MergeInvoicesAPRq>
         <tns:Invoices>
            <tns:Invoice>
               <tns:CreatedBy>CFDITec</tns:CreatedBy>
               <tns:CreationDate>
                  <xsl:value-of select="xp20:current-dateTime ( )"/>
               </tns:CreationDate>
               <tns:invoiceId>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:INVOICE_ID"/>
               </tns:invoiceId>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Emisor/@Rfc">
                  <tns:emisorRfc>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Emisor/@Rfc"/>
                  </tns:emisorRfc>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Receptor/@Rfc">
                  <tns:receptorRfc>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Receptor/@Rfc"/>
                  </tns:receptorRfc>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Total">
                  <tns:amount>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Total"/>
                  </tns:amount>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Complemento/ns3:TimbreFiscalDigital/@UUID">
                  <tns:uuid>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Complemento/ns3:TimbreFiscalDigital/@UUID"/>
                  </tns:uuid>
               </xsl:if>
               <tns:businessUnit>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:BUSINESS_UNIT"/>
               </tns:businessUnit>
               <tns:invoiceNumber>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:INVOICE_NUMBER"/>
               </tns:invoiceNumber>
               <tns:supplierNumber>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:SUPPLIER_NUMBER"/>
               </tns:supplierNumber>
               <tns:sitioProveedor>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:SUPPLIER_SITE_ID"/>
               </tns:sitioProveedor>
               <tns:unidadNegocio>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:BUSINESS_UNIT"/>
               </tns:unidadNegocio>
               <tns:tercerSegmCotable>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:G_INVOICES1[ns4:ID_LINE_TYPE='ITEM' and string-length(ns4:GCC_SEGMENT3) > 0][1]/ns4:GCC_SEGMENT3"/>
               </tns:tercerSegmCotable>
               <tns:quintoSegmContable>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:G_INVOICES1[ns4:ID_LINE_TYPE='ITEM' and string-length(ns4:GCC_SEGMENT5) > 0][1]/ns4:GCC_SEGMENT5"/>
               </tns:quintoSegmContable>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@TipoDeComprobante">
                  <tns:tipoComprobante>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@TipoDeComprobante"/>
                  </tns:tipoComprobante>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Complemento/ns3:TimbreFiscalDigital/@FechaTimbrado">
                  <tns:fechaTimbrado>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Complemento/ns3:TimbreFiscalDigital/@FechaTimbrado"/>
                  </tns:fechaTimbrado>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:CfdiRelacionados/@TipoRelacion">
                  <tns:tipoRelacion>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:CfdiRelacionados[1]/@TipoRelacion"/>
                  </tns:tipoRelacion>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:CfdiRelacionados/ns3:CfdiRelacionado/@UUID">
                  <tns:uuidRelacion>
                  <xsl:for-each select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:CfdiRelacionados">
                     <xsl:for-each select="ns3:CfdiRelacionado">
                    <xsl:value-of select="concat (@UUID, &quot;,&quot; )"/>
                     </xsl:for-each>
                  </xsl:for-each>
                  
                           
                        </tns:uuidRelacion>
               </xsl:if>
               <tns:nombreEmisor>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:SUPPLIER_NAME"/>
               </tns:nombreEmisor>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Receptor/@UsoCFDI">
                  <tns:usoCfdi>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Receptor/@UsoCFDI"/>
                  </tns:usoCfdi>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@SubTotal">
                  <tns:subtotal>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@SubTotal"/>
                  </tns:subtotal>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Descuento">
                  <tns:descuento>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Descuento"/>
                  </tns:descuento>
               </xsl:if>
               <xsl:if test="sum(/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Traslados/ns3:Traslado[@Impuesto = &quot;003&quot;]/@Importe)>0">
                  <tns:totalIeps>
                     <xsl:value-of select="sum(/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Traslados/ns3:Traslado[@Impuesto = &quot;003&quot;]/@Importe)"/>
                  </tns:totalIeps>
               </xsl:if>
               <xsl:if test="sum(/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Traslados/ns3:Traslado[((@Impuesto = &quot;002&quot;) and (@TasaOCuota = &quot;0.160000&quot;))]/@Importe)>0">
                  <tns:iva16>
                     <xsl:value-of select="sum (/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Traslados/ns3:Traslado[((@Impuesto = &quot;002&quot;) and (@TasaOCuota = &quot;0.160000&quot;))]/@Importe )"/>
                  </tns:iva16>
               </xsl:if>
               <xsl:if test="sum (/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Retenciones/ns3:Retencion[(@Impuesto = &quot;002&quot;)]/@Importe ) > 0">
                  <tns:retenidoIva>
                     <xsl:value-of select="sum (/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Retenciones/ns3:Retencion[(@Impuesto = &quot;002&quot;)]/@Importe )"/>
                  </tns:retenidoIva>
               </xsl:if>
               <xsl:if test="sum (/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Retenciones/ns3:Retencion[(@Impuesto = &quot;001&quot;)]/@Importe ) > 0">
                  <tns:retenidoIsr>
                     <xsl:value-of select='sum (/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Retenciones/ns3:Retencion[(@Impuesto = "001")]/@Importe )'/>
                  </tns:retenidoIsr>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Total">
                  <tns:total>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Total"/>
                  </tns:total>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Moneda">
                  <tns:moneda>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Moneda"/>
                  </tns:moneda>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@TipoCambio">
                  <tns:tipoCambio>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@TipoCambio"/>
                  </tns:tipoCambio>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@FormaPago">
                  <tns:formaPago>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@FormaPago"/>
                  </tns:formaPago>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@MetodoPago">
                  <tns:metodoPago>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@MetodoPago"/>
                  </tns:metodoPago>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Conceptos/ns3:Concepto/@Descripcion">
                  <tns:conceptos>
                     <xsl:value-of select="substring (/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE[1]/ns0:Comprobante[1]/ns3:Conceptos/ns3:Concepto[1]/@Descripcion, 0, 2998 )"/>
                  </tns:conceptos>
               </xsl:if>
               <xsl:if test="sum(/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Traslados/ns3:Traslado[@Impuesto = &quot;003&quot;]/@Importe)>0">
                  <tns:combustible>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Traslados/ns3:Traslado[@Impuesto = &quot;003&quot;][1]/@Impuesto"/></tns:combustible>
               </xsl:if>
               <xsl:if test="sum(/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Traslados/ns3:Traslado[((@Impuesto = &quot;002&quot;) and (@TasaOCuota = &quot;0.160000&quot;))]/@Importe)>0">
                  <tns:iva8>
                     <xsl:value-of select="sum (/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Impuestos/ns3:Traslados/ns3:Traslado[((@Impuesto = &quot;002&quot;) and (@TasaOCuota = &quot;0.080000&quot;))]/@Importe )"/>
                  </tns:iva8>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Conceptos/ns3:Concepto[1]/@ObjetoImp">
                  <tns:objetoImpXml>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Conceptos/ns3:Concepto[1]/@ObjetoImp"/>
                  </tns:objetoImpXml>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Receptor/@RegimenFiscalReceptor">
                  <tns:receptorRegimenXml>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Receptor/@RegimenFiscalReceptor"/>
                  </tns:receptorRegimenXml>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Emisor/@RegimenFiscal">
                  <tns:emisorRegimenXml>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Emisor/@RegimenFiscal"/>
                  </tns:emisorRegimenXml>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:LEGAL_ENTITY_REGIMEN">
                  <tns:receptorRegimen>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:LEGAL_ENTITY_REGIMEN"/>
                  </tns:receptorRegimen>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Version">
                  <tns:versionXml>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Version"/>
                  </tns:versionXml>
               </xsl:if>
               <tns:tipoFactura>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:INVOICE_TYPE"/>
               </tns:tipoFactura>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Folio">
                  <tns:folioFiscal>
                     <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/@Folio"/>
                  </tns:folioFiscal>
               </xsl:if>
               <tns:totalOracle>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:TOTAL"/>
               </tns:totalOracle>
               <tns:supplierName>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:SUPPLIER_NAME"/>
               </tns:supplierName>
               <tns:creationDateOracle>
                  <xsl:value-of select="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:CREATION_DATE"/>
               </tns:creationDateOracle>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Conceptos/ns3:Concepto/ns3:Parte/ns3:InformacionAduanera/@NumeroPedimento">
                  <tns:numeroPedimentoXml>
                     <xsl:value-of select="oraext:create-delimited-string (/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Conceptos/ns3:Concepto/ns3:Parte/ns3:InformacionAduanera/@NumeroPedimento, ',' )"/>
                  </tns:numeroPedimentoXml>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Conceptos/ns3:Concepto/ns3:CuentaPredial/@Numero">
                  <tns:cuentaPredialXml>
                     <xsl:value-of select="oraext:create-delimited-string (/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns0:Comprobante/ns3:Conceptos/ns3:Concepto/ns3:CuentaPredial/@Numero, &quot;,&quot; )"/>
                  </tns:cuentaPredialXml>
               </xsl:if>
               <xsl:if test="/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:SUPPLIER_SITE_AWT_GROUP_CODE">
                  <tns:supplierSiteAwtGroupCode>
                     <xsl:value-of select="concat (/ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:SUPPLIER_SITE_AWT_GROUP_CODE, &quot;- ISR: &quot;, /ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:SUPPLIER_RET_ISR, &quot; IVA: &quot;, /ns0:GetInvoiceCFDIFromERPRs/ns0:INVOICE/ns4:DATA_DS/ns4:G_INVOICES/ns4:SUPPLIER_RET_IVA )"/>
                  </tns:supplierSiteAwtGroupCode>
               </xsl:if>
            </tns:Invoice>
         </tns:Invoices>
      </tns:MergeInvoicesAPRq>
   </xsl:template>
</xsl:stylesheet>
