<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="bpelGetComplementToUpdInvoices" targetNamespace="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelGetComplementToUpdInvoices" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelGetComplementToUpdInvoices" xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesBiz" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://soa.estrellaroja.com.mx/FinancialsTec">
   <plnk:partnerLinkType name="bpelGetComplementToUpdInvoices">
      <plnk:role name="bpelGetComplementToUpdInvoicesProvider" portType="client:bpelGetComplementToUpdInvoices"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/FinancialsTec" location="oramds:/apps/OSB/FinancialsTec/FinancialsTec.wsdl"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://soa.estrellaroja.com.mx/InvoicesBiz" schemaLocation="oramds:/apps/SOA/InvoicesBiz/InvoicesBiz.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="GetComplementToUpdInvoicesRq">
      <wsdl:part name="GetComplementToUpdInvoicesRq" element="ns1:GetComplementToUpdInvoicesRq"/>
   </wsdl:message>
   <wsdl:message name="GetComplementToUpdInvoicesRs">
      <wsdl:part name="GetComplementToUpdInvoicesRs" element="ns1:GetComplementToUpdInvoicesRs"/>
   </wsdl:message>
   <wsdl:portType name="bpelGetComplementToUpdInvoices">
      <wsdl:operation name="GetComplementToUpdInvoices">
         <wsdl:input message="client:GetComplementToUpdInvoicesRq"/>
         <wsdl:output message="client:GetComplementToUpdInvoicesRs"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
