<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="DigitalStampGERTec" targetNamespace="http://soa.estrellaroja.com.mx/DigitalStampGERTec" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://soa.estrellaroja.com.mx/DigitalStampGERTec" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="wsDigitalStmapGERTec">
      <plnk:role name="DigitalStampGERTecPortType" portType="tns:DigitalStampGERTecPortType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://soa.estrellaroja.com.mx/DigitalStampGERTec" location="oramds:/apps/OSB/DigitalStampGERTec/DigitalStampGERTec.wsdl"/>
</wsdl:definitions>
