<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns1="http://www.sat.gob.mx/cfd/3"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns0="http://www.sat.gob.mx/cfd/4" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns1 ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:consumodecombustibles11="http://www.sat.gob.mx/ConsumoDeCombustibles11"
                xmlns:pago10="http://www.sat.gob.mx/Pagos"
                xmlns:ns3="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos"
                xmlns:ns5="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/ComExt"
                xmlns:catCFDI="http://www.sat.gob.mx/sitio_internet/cfd/catalogos"
                xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital"
                xmlns:ecc12="http://www.sat.gob.mx/EstadoDeCuentaCombustible12"
                xmlns:ns2="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina"
                xmlns:ns4="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte"
                xmlns:cartaporte20="http://www.sat.gob.mx/CartaPorte20" xmlns:nomina12="http://www.sat.gob.mx/nomina12"
                xmlns:ns6="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Combustible"
                xmlns:tdCFDI="http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI"
                xmlns:pago20="http://www.sat.gob.mx/Pagos20"
                xmlns:ns10="http://soa.estrellaroja.com.mx/ValidationInvoicesAPEnt"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns7="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns9="http://soa.estrellaroja.com.mx/Reports/XXER_AP_INVOICE_VALIDATION_AUTOMATICA"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns8="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz/types">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ValidationInvoicesAPBiz/ValidationInvoicesAPBiz.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InvoiceXML"
                                       namespace="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Common/XSD/CFDI40/cfdv40.xsd"/>
        <oracle-xsl-mapper:rootElement name="Comprobante" namespace="http://www.sat.gob.mx/cfd/4"/>
        <oracle-xsl-mapper:param name="v_comprobante40"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Common/XSD/CFDI/cfdv33.xsd"/>
        <oracle-xsl-mapper:rootElement name="Comprobante" namespace="http://www.sat.gob.mx/cfd/3"/>
        <oracle-xsl-mapper:param name="v_comprobante33"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ValidationInvoicesAPBiz/ValidationInvoicesAPBiz.wsdl"/>
        <oracle-xsl-mapper:rootElement name="InvoiceXML"
                                       namespace="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE OCT 18 10:15:26 CDT 2022].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="v_comprobante33"/>
  <xsl:param name="v_comprobante40"/>
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="string-length ($v_comprobante40/ns0:Comprobante/@Version ) > 0 or string-length ($v_comprobante33/ns1:Comprobante/@Version ) > 0">
        <xsl:choose>
          <xsl:when test="$v_comprobante40/ns0:Comprobante/@Version='4.0'">
            <tns:InvoiceXML>
              <tns:Version>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@Version"/>
              </tns:Version>
              <tns:Serie>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@Serie"/>
              </tns:Serie>
              <tns:Folio>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@Folio"/>
              </tns:Folio>
              <tns:Fecha>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@Fecha"/>
              </tns:Fecha>
              <tns:FormaPago>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@FormaPago"/>
              </tns:FormaPago>
              <tns:CondicionesDePago>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@CondicionesDePago"/>
              </tns:CondicionesDePago>
              <tns:SubTotal>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@SubTotal"/>
              </tns:SubTotal>
              <xsl:if test="string-length ($v_comprobante40/ns0:Comprobante/@Descuento )>0">
                <tns:Descuento>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@Descuento"/>
                </tns:Descuento>
              </xsl:if>
              <tns:Moneda>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@Moneda"/>
              </tns:Moneda>
              <tns:TipoCambio>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@TipoCambio"/>
              </tns:TipoCambio>
              <tns:Total>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@Total"/>
              </tns:Total>
              <tns:TipoDeComprobante>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@TipoDeComprobante"/>
              </tns:TipoDeComprobante>
              <tns:Exportacion>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@Exportacion"/>
              </tns:Exportacion>
              <tns:MetodoPago>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@MetodoPago"/>
              </tns:MetodoPago>
              <tns:Confirmacion>
                <xsl:value-of select="$v_comprobante40/ns0:Comprobante/@Confirmacion"/>
              </tns:Confirmacion>
              <xsl:if test="$v_comprobante40/ns0:Comprobante/ns0:CfdiRelacionados">
                <xsl:for-each select="$v_comprobante40/ns0:Comprobante/ns0:CfdiRelacionados">
                  <tns:CfdiRelacionados>
                    <tns:TipoRelacion>
                      <xsl:value-of select="@TipoRelacion"/>
                    </tns:TipoRelacion>
                    <xsl:for-each select="ns0:CfdiRelacionado">
                      <tns:UUID>
                        <xsl:value-of select="@UUID"/>
                      </tns:UUID>
                    </xsl:for-each>
                  </tns:CfdiRelacionados>
                </xsl:for-each>
              </xsl:if>
              <tns:Emisor>
                <tns:Rfc>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Emisor/@Rfc"/>
                </tns:Rfc>
                <tns:Nombre>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Emisor/@Nombre"/>
                </tns:Nombre>
                <tns:RegimenFiscal>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Emisor/@RegimenFiscal"/>
                </tns:RegimenFiscal>
                <tns:FacAtrAdquirente>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Emisor/@FacAtrAdquirente"/>
                </tns:FacAtrAdquirente>
              </tns:Emisor>
              <tns:Receptor>
                <tns:Rfc>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Receptor/@Rfc"/>
                </tns:Rfc>
                <tns:Nombre>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Receptor/@Nombre"/>
                </tns:Nombre>
                <tns:RegimenFiscalReceptor>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Receptor/@RegimenFiscalReceptor"/>
                </tns:RegimenFiscalReceptor>
                <tns:DomicilioFiscalReceptor>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Receptor/@DomicilioFiscalReceptor"/>
                </tns:DomicilioFiscalReceptor>
                <tns:ResidenciaFiscal>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Receptor/@ResidenciaFiscal"/>
                </tns:ResidenciaFiscal>
                <tns:NumRegIdTrib>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Receptor/@NumRegIdTrib"/>
                </tns:NumRegIdTrib>
                <tns:UsoCFDI>
                  <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Receptor/@UsoCFDI"/>
                </tns:UsoCFDI>
              </tns:Receptor>
              <xsl:if test="$v_comprobante40/ns0:Comprobante/ns0:Conceptos">
                <xsl:for-each select="$v_comprobante40/ns0:Comprobante/ns0:Conceptos/ns0:Concepto">
                  <tns:Concepto>
                    <tns:ClaveProdServ>
                      <xsl:value-of select="@ClaveProdServ"/>
                    </tns:ClaveProdServ>
                    <tns:NoIdentificacion>
                      <xsl:value-of select="@NoIdentificacion"/>
                    </tns:NoIdentificacion>
                    <tns:Cantidad>
                      <xsl:value-of select="@Cantidad"/>
                    </tns:Cantidad>
                    <tns:ClaveUnidad>
                      <xsl:value-of select="@ClaveUnidad"/>
                    </tns:ClaveUnidad>
                    <tns:Unidad>
                      <xsl:value-of select="@Unidad"/>
                    </tns:Unidad>
                    <tns:Importe>
                      <xsl:value-of select="@Importe"/>
                    </tns:Importe>
                    <tns:Descuento>
                      <xsl:value-of select="@Descuento"/>
                    </tns:Descuento>
                    <tns:ObjetoImp>
                      <xsl:value-of select="@ObjetoImp"/>
                    </tns:ObjetoImp>
                    <tns:Descripcion>
                      <xsl:value-of select="@Descripcion"/>
                    </tns:Descripcion>
                    <tns:ValorUnitario>
                      <xsl:value-of select="@ValorUnitario"/>
                    </tns:ValorUnitario>
                    <tns:Impuestos>
                      <xsl:if test="ns0:Impuestos/ns0:Traslados/ns0:Traslado">
                        <xsl:for-each select="ns0:Impuestos/ns0:Traslados/ns0:Traslado">
                          <tns:Traslado>
                            <tns:Base>
                              <xsl:value-of select="@Base"/>
                            </tns:Base>
                            <tns:Impuesto>
                              <xsl:value-of select="@Impuesto"/>
                            </tns:Impuesto>
                            <tns:TipoFactor>
                              <xsl:value-of select="@TipoFactor"/>
                            </tns:TipoFactor>
                            <tns:TasaOCuota>
                              <xsl:value-of select="@TasaOCuota"/>
                            </tns:TasaOCuota>
                            <tns:Importe>
                              <xsl:value-of select="@Importe"/>
                            </tns:Importe>
                          </tns:Traslado>
                        </xsl:for-each>
                      </xsl:if>
                      <xsl:if test="ns0:Impuestos/ns0:Retenciones/ns0:Retencion">
                        <xsl:for-each select="ns0:Impuestos/ns0:Retenciones/ns0:Retencion">
                          <tns:Retencion>
                            <tns:Base>
                              <xsl:value-of select="@Base"/>
                            </tns:Base>
                            <tns:Impuesto>
                              <xsl:value-of select="@Impuesto"/>
                            </tns:Impuesto>
                            <tns:TipoFactor>
                              <xsl:value-of select="@TipoFactor"/>
                            </tns:TipoFactor>
                            <tns:TasaOCuota>
                              <xsl:value-of select="@TasaOCuota"/>
                            </tns:TasaOCuota>
                            <tns:Importe>
                              <xsl:value-of select="@Importe"/>
                            </tns:Importe>
                          </tns:Retencion>
                        </xsl:for-each>
                      </xsl:if>
                    </tns:Impuestos>
                    <tns:ACuentaTerceros>
                      <tns:RfcACuentaTerceros>
                        <xsl:value-of select="ns0:ACuentaTerceros/@RfcACuentaTerceros"/>
                      </tns:RfcACuentaTerceros>
                      <tns:NombreACuentaTerceros>
                        <xsl:value-of select="ns0:ACuentaTerceros/@NombreACuentaTerceros"/>
                      </tns:NombreACuentaTerceros>
                      <tns:RegimenFiscalACuentaTerceros>
                        <xsl:value-of select="ns0:ACuentaTerceros/@RegimenFiscalACuentaTerceros"/>
                      </tns:RegimenFiscalACuentaTerceros>
                      <tns:DomicilioFiscalACuentaTerceros>
                        <xsl:value-of select="ns0:ACuentaTerceros/@DomicilioFiscalACuentaTerceros"/>
                      </tns:DomicilioFiscalACuentaTerceros>
                    </tns:ACuentaTerceros>
                    <xsl:if test="ns0:Parte">
                      <xsl:for-each select="ns0:Parte">
                        <tns:Parte>
                          <tns:ClaveProdServ>
                            <xsl:value-of select="@ClaveProdServ"/>
                          </tns:ClaveProdServ>
                          <tns:NoIdentificacion>
                            <xsl:value-of select="@NoIdentificacion"/>
                          </tns:NoIdentificacion>
                          <tns:Cantidad>
                            <xsl:value-of select="@Cantidad"/>
                          </tns:Cantidad>
                          <tns:Unidad>
                            <xsl:value-of select="@Unidad"/>
                          </tns:Unidad>
                          <tns:Descripcion>
                            <xsl:value-of select="@Descripcion"/>
                          </tns:Descripcion>
                          <tns:ValorUnitario>
                            <xsl:value-of select="@ValorUnitario"/>
                          </tns:ValorUnitario>
                          <tns:Importe>
                            <xsl:value-of select="@Importe"/>
                          </tns:Importe>
                          <xsl:if test="ns0:InformacionAduanera">
                            <xsl:for-each select="ns0:InformacionAduanera">
                              <tns:NumeroPedimento>
                                <xsl:value-of select="@NumeroPedimento"/>
                              </tns:NumeroPedimento>
                            </xsl:for-each>
                          </xsl:if>
                        </tns:Parte>
                      </xsl:for-each>
                    </xsl:if>
                    <xsl:if test="ns0:CuentaPredial">
                      <xsl:for-each select="ns0:CuentaPredial">
                        <tns:CuentaPredial>
                          <xsl:value-of select="."/>
                        </tns:CuentaPredial>
                      </xsl:for-each>
                    </xsl:if>
                    <xsl:if test="ns0:InformacionAduanera">
                      <xsl:for-each select="ns0:InformacionAduanera">
                        <tns:NumeroPedimento>
                          <xsl:value-of select="@NumeroPedimento"/>
                        </tns:NumeroPedimento>
                      </xsl:for-each>
                    </xsl:if>
                  </tns:Concepto>
                </xsl:for-each>
              </xsl:if>
              <tns:Complemento>
                <tns:TimbreFiscalDigital>
                  <tns:Version>
                    <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@Version"/>
                  </tns:Version>
                  <tns:UUID>
                    <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@UUID"/>
                  </tns:UUID>
                  <tns:FechaTimbrado>
                    <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@FechaTimbrado"/>
                  </tns:FechaTimbrado>
                  <tns:RfcProvCertif>
                    <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@RfcProvCertif"/>
                  </tns:RfcProvCertif>
                  <tns:Leyenda>
                    <xsl:value-of select="$v_comprobante40/ns0:Comprobante/ns0:Complemento/tfd:TimbreFiscalDigital/@Leyenda"/>
                  </tns:Leyenda>
                </tns:TimbreFiscalDigital>
              </tns:Complemento>
            </tns:InvoiceXML>
          </xsl:when>
          <xsl:when test="$v_comprobante33/ns1:Comprobante/@Version='3.3'">
            <tns:InvoiceXML>
              <tns:Version>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@Version"/>
              </tns:Version>
              <tns:Serie>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@Serie"/>
              </tns:Serie>
              <tns:Folio>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@Folio"/>
              </tns:Folio>
              <tns:Fecha>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@Fecha"/>
              </tns:Fecha>
              <tns:FormaPago>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@FormaPago"/>
              </tns:FormaPago>
              <tns:CondicionesDePago>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@CondicionesDePago"/>
              </tns:CondicionesDePago>
              <tns:SubTotal>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@SubTotal"/>
              </tns:SubTotal>
              <xsl:if test="string-length ($v_comprobante33/ns1:Comprobante/@Descuento )>0">
                <tns:Descuento>
                  <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@Descuento"/>
                </tns:Descuento>
              </xsl:if>
              <tns:Moneda>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@Moneda"/>
              </tns:Moneda>
              <tns:TipoCambio>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@TipoCambio"/>
              </tns:TipoCambio>
              <tns:Total>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@Total"/>
              </tns:Total>
              <tns:TipoDeComprobante>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@TipoDeComprobante"/>
              </tns:TipoDeComprobante>
              <tns:MetodoPago>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@MetodoPago"/>
              </tns:MetodoPago>
              <tns:Confirmacion>
                <xsl:value-of select="$v_comprobante33/ns1:Comprobante/@Confirmacion"/>
              </tns:Confirmacion>
              <tns:CfdiRelacionados>
                <tns:TipoRelacion>
                  <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:CfdiRelacionados/@TipoRelacion"/>
                </tns:TipoRelacion>
                <xsl:for-each select="$v_comprobante33/ns1:Comprobante/ns1:CfdiRelacionados/ns1:CfdiRelacionado">
                  <tns:UUID>
                    <xsl:value-of select="@UUID"/>
                  </tns:UUID>
                </xsl:for-each>
              </tns:CfdiRelacionados>
              <tns:Emisor>
                <tns:Rfc>
                  <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Emisor/@Rfc"/>
                </tns:Rfc>
                <tns:Nombre>
                  <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Emisor/@Nombre"/>
                </tns:Nombre>
                <tns:RegimenFiscal>
                  <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Emisor/@RegimenFiscal"/>
                </tns:RegimenFiscal>
              </tns:Emisor>
              <tns:Receptor>
                <tns:Rfc>
                  <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Receptor/@Rfc"/>
                </tns:Rfc>
                <tns:Nombre>
                  <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Receptor/@Nombre"/>
                </tns:Nombre>
                <tns:ResidenciaFiscal>
                  <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Receptor/@ResidenciaFiscal"/>
                </tns:ResidenciaFiscal>
                <tns:NumRegIdTrib>
                  <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Receptor/@NumRegIdTrib"/>
                </tns:NumRegIdTrib>
                <tns:UsoCFDI>
                  <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Receptor/@UsoCFDI"/>
                </tns:UsoCFDI>
              </tns:Receptor>
              <xsl:if test="$v_comprobante33/ns1:Comprobante/ns1:Conceptos/ns1:Concepto">
                <xsl:for-each select="$v_comprobante33/ns1:Comprobante/ns1:Conceptos/ns1:Concepto">
                  <tns:Concepto>
                    <tns:ClaveProdServ>
                      <xsl:value-of select="@ClaveProdServ"/>
                    </tns:ClaveProdServ>
                    <tns:NoIdentificacion>
                      <xsl:value-of select="@NoIdentificacion"/>
                    </tns:NoIdentificacion>
                    <tns:Cantidad>
                      <xsl:value-of select="@Cantidad"/>
                    </tns:Cantidad>
                    <tns:ClaveUnidad>
                      <xsl:value-of select="@ClaveUnidad"/>
                    </tns:ClaveUnidad>
                    <tns:Unidad>
                      <xsl:value-of select="@Unidad"/>
                    </tns:Unidad>
                    <tns:Importe>
                      <xsl:value-of select="@Importe"/>
                    </tns:Importe>
                    <tns:Descuento>
                      <xsl:value-of select="@Descuento"/>
                    </tns:Descuento>
                    <tns:Descripcion>
                      <xsl:value-of select="@Descripcion"/>
                    </tns:Descripcion>
                    <tns:ValorUnitario>
                      <xsl:value-of select="@ValorUnitario"/>
                    </tns:ValorUnitario>
                    <tns:Impuestos>
                      <xsl:if test="ns1:Impuestos/ns1:Traslados/ns1:Traslado">
                        <xsl:for-each select="ns1:Impuestos/ns1:Traslados/ns1:Traslado">
                          <tns:Traslado>
                            <tns:Base>
                              <xsl:value-of select="@Base"/>
                            </tns:Base>
                            <tns:Impuesto>
                              <xsl:value-of select="@Impuesto"/>
                            </tns:Impuesto>
                            <tns:TipoFactor>
                              <xsl:value-of select="@TipoFactor"/>
                            </tns:TipoFactor>
                            <tns:TasaOCuota>
                              <xsl:value-of select="@TasaOCuota"/>
                            </tns:TasaOCuota>
                            <tns:Importe>
                              <xsl:value-of select="@Importe"/>
                            </tns:Importe>
                          </tns:Traslado>
                        </xsl:for-each>
                      </xsl:if>
                      <xsl:if test="ns1:Impuestos/ns1:Retenciones/ns1:Retencion">
                        <xsl:for-each select="ns1:Impuestos/ns1:Retenciones/ns1:Retencion">
                          <tns:Retencion>
                            <tns:Base>
                              <xsl:value-of select="@Base"/>
                            </tns:Base>
                            <tns:Impuesto>
                              <xsl:value-of select="@Impuesto"/>
                            </tns:Impuesto>
                            <tns:TipoFactor>
                              <xsl:value-of select="@TipoFactor"/>
                            </tns:TipoFactor>
                            <tns:TasaOCuota>
                              <xsl:value-of select="@TasaOCuota"/>
                            </tns:TasaOCuota>
                            <tns:Importe>
                              <xsl:value-of select="@Importe"/>
                            </tns:Importe>
                          </tns:Retencion>
                        </xsl:for-each>
                      </xsl:if>
                    </tns:Impuestos>
                    <xsl:if test="ns1:Parte">
                      <xsl:for-each select="ns1:Parte">
                        <tns:Parte>
                          <tns:ClaveProdServ>
                            <xsl:value-of select="@ClaveProdServ"/>
                          </tns:ClaveProdServ>
                          <tns:NoIdentificacion>
                            <xsl:value-of select="@NoIdentificacion"/>
                          </tns:NoIdentificacion>
                          <tns:Cantidad>
                            <xsl:value-of select="@Cantidad"/>
                          </tns:Cantidad>
                          <tns:Unidad>
                            <xsl:value-of select="@Unidad"/>
                          </tns:Unidad>
                          <tns:Descripcion>
                            <xsl:value-of select="@Descripcion"/>
                          </tns:Descripcion>
                          <tns:ValorUnitario>
                            <xsl:value-of select="@ValorUnitario"/>
                          </tns:ValorUnitario>
                          <tns:Importe>
                            <xsl:value-of select="@Importe"/>
                          </tns:Importe>
                          <xsl:if test="ns1:InformacionAduanera">
                            <xsl:for-each select="ns1:InformacionAduanera">
                              <tns:NumeroPedimento>
                                <xsl:value-of select="@NumeroPedimento"/>
                              </tns:NumeroPedimento>
                            </xsl:for-each>
                          </xsl:if>
                        </tns:Parte>
                      </xsl:for-each>
                    </xsl:if>
                    <tns:CuentaPredial>
                      <xsl:value-of select="ns1:CuentaPredial/@Numero"/>
                    </tns:CuentaPredial>
                    <xsl:if test="ns1:InformacionAduanera">
                      <xsl:for-each select="ns1:InformacionAduanera">
                        <tns:NumeroPedimento>
                          <xsl:value-of select="@NumeroPedimento"/>
                        </tns:NumeroPedimento>
                      </xsl:for-each>
                    </xsl:if>
                  </tns:Concepto>
                </xsl:for-each>
              </xsl:if>
              <tns:Complemento>
                <tns:TimbreFiscalDigital>
                  <tns:Version>
                    <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Complemento/tfd:TimbreFiscalDigital/@Version"/>
                  </tns:Version>
                  <tns:UUID>
                    <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Complemento/tfd:TimbreFiscalDigital/@UUID"/>
                  </tns:UUID>
                  <tns:FechaTimbrado>
                    <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Complemento/tfd:TimbreFiscalDigital/@FechaTimbrado"/>
                  </tns:FechaTimbrado>
                  <tns:RfcProvCertif>
                    <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Complemento/tfd:TimbreFiscalDigital/@RfcProvCertif"/>
                  </tns:RfcProvCertif>
                  <tns:Leyenda>
                    <xsl:value-of select="$v_comprobante33/ns1:Comprobante/ns1:Complemento/tfd:TimbreFiscalDigital/@Leyenda"/>
                  </tns:Leyenda>
                </tns:TimbreFiscalDigital>
              </tns:Complemento>
            </tns:InvoiceXML>
          </xsl:when>
        </xsl:choose>
      </xsl:when>
      <xsl:otherwise>
        <tns:InvoiceXML>
          <tns:Version>
            <xsl:value-of select="0"/>
          </tns:Version>
        </tns:InvoiceXML>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>
