<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns1="http://platform.integration.oracle/blocks/adapter/fw/metadata/umsSendEmail"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://soa.estrellaroja.com.mx/MessageTec"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns1 ns0 mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://soa.estrellaroja.com.mx/MessageTec/bpelSendEmail"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ums/MessageTec/MessageTec/umsSendEmail"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:strClass="http://www.oracle.com/XSL/Transform/java/java.lang.String">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/bpelSendEmail.wsdl"/>
        <oracle-xsl-mapper:rootElement name="MessageRq" namespace="http://soa.estrellaroja.com.mx/MessageTec"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/umsSendEmail.wsdl"/>
        <oracle-xsl-mapper:rootElement name="message"
                                       namespace="http://platform.integration.oracle/blocks/adapter/fw/metadata/umsSendEmail"/>
        <oracle-xsl-mapper:param name="varInvokeWSUmsNotificationEmailRq.body"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/umsSendEmail.wsdl"/>
        <oracle-xsl-mapper:rootElement name="message"
                                       namespace="http://platform.integration.oracle/blocks/adapter/fw/metadata/umsSendEmail"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI SEP 15 11:26:49 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="varInvokeWSUmsNotificationEmailRq.body"/>
  <xsl:param name="varFlowId"/>
  <xsl:template match="/">
    <ns1:message>
      <ns1:payload>
        <xsl:value-of select="strClass:replaceAll(
        strClass:replaceAll(
        strClass:replaceAll($varInvokeWSUmsNotificationEmailRq.body/ns1:message/ns1:payload,
        '@MessagePayload@',/ns0:MessageRq/ns0:Message/ns0:Message),
        '@SubjectMail@',/ns0:MessageRq/ns0:Message/ns0:Subject),
        '@InstanceID@', $varFlowId)"/>
      </ns1:payload>
    </ns1:message>
  </xsl:template>
</xsl:stylesheet>