<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://soa.estrellaroja.com.mx/SOAUtilitiesTec/types"
                xmlns:ns3="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaBiz"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns7="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaBiz/CeStatementHeaderInt"
                xmlns:ns5="http://soa.estrellaroja.com.mx/CeStatementBalanceInt"
                xmlns:ns4="http://schemas.oracle.com/bpel/extension"
                xmlns:client="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaBiz/bpelGetBankStatements"
                xmlns:ns6="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaBiz/CeStatementLinesInt"
                xmlns:ns8="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaBiz/types">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/SOAUtilitiesTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EncodeRs" namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelGetBankStatements.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CompositeInstanceId"
                                           namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaBiz"/>
            <oracle-xsl-mapper:param name="varCompositeInstanceId"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelGetBankStatements.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Path" namespace="http://soa.estrellaroja.com.mx/SFTPEstrellaRojaBiz"/>
            <oracle-xsl-mapper:param name="varFilePAth"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/SOAUtilitiesTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GenerateZipFileRq" namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON JAN 15 17:43:59 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varCompositeInstanceId"/>
   <xsl:param name="varFilePAth"/>
   <xsl:template match="/">
      <ns0:GenerateZipFileRq>
         <ns0:FileNameToZip>
            <xsl:value-of select="concat (&quot;CeBankStatements_&quot;, $varCompositeInstanceId/ns3:CompositeInstanceId, xp20:format-dateTime (xp20:current-date ( ), &quot;[D01][M01][Y0001]&quot; ) )"/>
         </ns0:FileNameToZip>
         <ns0:PathFileToZip>
            <xsl:value-of select="$varFilePAth/ns3:Path/ns3:filtePath"/>
         </ns0:PathFileToZip>
         <ns0:FilesCompress>
            <xsl:for-each select="/ns0:EncodeRs/ns0:Return/ns0:CodedReturn">
               <ns0:FileToCompress>
                  <ns0:ContentFile>
                     <xsl:value-of select="ns0:DataBase64"/>
                  </ns0:ContentFile>
                  <ns0:PathFile>
                     <xsl:value-of select="$varFilePAth/ns3:Path/ns3:filtePath"/>
                  </ns0:PathFile>
                  <ns0:FileName>
                     <xsl:value-of select="ns0:ContentDataName"/>
                  </ns0:FileName>
               </ns0:FileToCompress>
            </xsl:for-each>
         </ns0:FilesCompress>
      </ns0:GenerateZipFileRq>
   </xsl:template>
</xsl:stylesheet>
