<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://soa.estrellaroja.com.mx/LetterPorteBiz/NXSD/RelationCFDIs"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="http://soa.estrellaroja.com.mx/LetterPorteTec/Types"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns1="http://soa.estrellaroja.com.mx/LetterPorteTec" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/LetterPorteBiz"
                xmlns:client="http://soa.estrellaroja.com.mx/LetterPorteBiz/BPELRelationCFDIs"
                xmlns:ns4="http://soa.estrellaroja.com.mx/LetterPorteBiz">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/OSB/LetterPorteTec/LetterPorteTec.wsdl"/>
        <oracle-xsl-mapper:rootElement name="GetRelationsCFDIsRs"
                                       namespace="http://soa.estrellaroja.com.mx/LetterPorteTec/Types"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/BPELRelationCFDIs.wsdl"/>
        <oracle-xsl-mapper:rootElement name="RelationsCFDIs"
                                       namespace="http://soa.estrellaroja.com.mx/LetterPorteBiz/NXSD/RelationCFDIs"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON NOV 29 16:12:49 CST 2021].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:RelationsCFDIs>
      <xsl:for-each select="/ns0:GetRelationsCFDIsRs/ns0:RelationCFDIs">
        <tns:RelationCFDIs>
          <tns:Transaccion>
            <xsl:value-of select="ns0:NumeroDocumento"/>
          </tns:Transaccion>
          <tns:NumeroGuia>
            <xsl:value-of select="ns0:NumeroProducto"/>
          </tns:NumeroGuia>
          <tns:MontoTotal>
            <xsl:value-of select="ns0:TotalFactura"/>
          </tns:MontoTotal>
          <tns:UUID_Ingreso>
            <xsl:value-of select="ns0:UuidIngreso"/>
          </tns:UUID_Ingreso>
          <tns:Estatus>
            <xsl:value-of select="ns0:Estatus"/>
          </tns:Estatus>
          <tns:URL_XML_Ingreso>
            <xsl:value-of select="ns0:UrlXmlIngreso"/>
          </tns:URL_XML_Ingreso>
          <tns:URL_PDF_Ingreso>
            <xsl:value-of select="ns0:UrlPdfIngreso"/>
          </tns:URL_PDF_Ingreso>
          <tns:Fecha_Ingreso>
            <xsl:value-of select="ns0:DateIngreso"/>
          </tns:Fecha_Ingreso>
          <tns:UUID_CP>
            <xsl:value-of select="ns0:UuidCp"/>
          </tns:UUID_CP>
          <tns:Estatus_CP>
            <xsl:value-of select="ns0:EstatusCp"/>
          </tns:Estatus_CP>
          <tns:URL_XML_CP>
            <xsl:value-of select="ns0:UrlXmlCp"/>
          </tns:URL_XML_CP>
          <tns:URL_PDF_CP>
            <xsl:value-of select="ns0:UrlPdfCp"/>
          </tns:URL_PDF_CP>
          <tns:Fecha_CP>
            <xsl:value-of select="ns0:DateCp"/>
          </tns:Fecha_CP>
        </tns:RelationCFDIs>
      </xsl:for-each>
    </tns:RelationsCFDIs>
  </xsl:template>
</xsl:stylesheet>
