<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://TargetNamespace.com/ServiceName" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/FinancialsTec" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://soa.estrellaroja.com.mx/FinancialsTec/types" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns3="http://soa.estrellaroja.com.mx/JournalBiz" xmlns:ns4="http://schemas.oracle.com/bpel/extension" xmlns:client="http://soa.estrellaroja.com.mx/JournalBiz/bpelGetJournal">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/FinancialsTecWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetJournalRs" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpelGetJournal.wsdl"/>
            <oracle-xsl-mapper:rootElement name="FileJournal" namespace="http://TargetNamespace.com/ServiceName"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE DEC 19 14:50:44 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:FileJournal>
         <xsl:for-each select="/ns0:GetJournalRs/ns0:Return/ns0:Journals">
            <tns:Journals>
               <tns:Status>
                  <xsl:value-of select="ns0:StatusCode"/>
               </tns:Status>
               <tns:LedgerID>
                  <xsl:value-of select="dvm:lookupValue (&quot;Dvms/Journals.dvm&quot;, &quot;Code&quot;, &quot;Ledger1&quot;, &quot;Value&quot;, &quot;&quot; )"/>
               </tns:LedgerID>
               <tns:EffectiveDateOfTransaction>
                  <xsl:value-of select="ns0:EffectiveDateOfTransaction"/>
               </tns:EffectiveDateOfTransaction>
               <tns:JournalSource>
                  <xsl:value-of select="ns0:JournalSource"/>
               </tns:JournalSource>
               <tns:JournalCategory>
                  <xsl:value-of select="ns0:JournalCategory"/>
               </tns:JournalCategory>
               <tns:CurrencyCode>
                  <xsl:value-of select="ns0:CurrencyCode"/>
               </tns:CurrencyCode>
               <tns:JournalEntryCreationDate>
                  <xsl:value-of select="ns0:JournalEntryCreationDate"/>
               </tns:JournalEntryCreationDate>
               <tns:ActualFlag>
                  <xsl:value-of select="ns0:ActualFlag"/>
               </tns:ActualFlag>
               <tns:Segment1>
                  <xsl:value-of select="ns0:Segment1"/>
               </tns:Segment1>
               <tns:Segment2>
                  <xsl:value-of select="ns0:Segment2"/>
               </tns:Segment2>
               <tns:Segment3>
                  <xsl:value-of select="ns0:Segment3"/>
               </tns:Segment3>
               <tns:Segment4>
                  <xsl:value-of select="ns0:Segment4"/>
               </tns:Segment4>
               <tns:Segment5>
                  <xsl:value-of select="ns0:Segment5"/>
               </tns:Segment5>
               <tns:Segment6>
                  <xsl:value-of select="ns0:Segment6"/>
               </tns:Segment6>
               <tns:Segment7>
                  <xsl:value-of select="ns0:Segment7"/>
               </tns:Segment7>
               <tns:Segment8>
                  <xsl:value-of select="ns0:Segment8"/>
               </tns:Segment8>
               <tns:Segment9>
                  <xsl:value-of select="ns0:Segment9"/>
               </tns:Segment9>
               <tns:Segment10>
                  <xsl:value-of select="ns0:Segment10"/>
               </tns:Segment10>
               <tns:Segment11>
                  <xsl:value-of select="ns0:Segment11"/>
               </tns:Segment11>
               <tns:Segment12>
                  <xsl:value-of select="ns0:Segment12"/>
               </tns:Segment12>
               <tns:Segment13>
                  <xsl:value-of select="ns0:Segment13"/>
               </tns:Segment13>
               <tns:Segment14>
                  <xsl:value-of select="ns0:Segment14"/>
               </tns:Segment14>
               <tns:Segment15>
                  <xsl:value-of select="ns0:Segment15"/>
               </tns:Segment15>
               <tns:Segment16>
                  <xsl:value-of select="ns0:Segment16"/>
               </tns:Segment16>
               <tns:Segment17>
                  <xsl:value-of select="ns0:Segment17"/>
               </tns:Segment17>
               <tns:Segment18>
                  <xsl:value-of select="ns0:Segment18"/>
               </tns:Segment18>
               <tns:Segment19>
                  <xsl:value-of select="ns0:Segment19"/>
               </tns:Segment19>
               <tns:Segment20>
                  <xsl:value-of select="ns0:Segment20"/>
               </tns:Segment20>
               <tns:Segment21>
                  <xsl:value-of select="ns0:Segment21"/>
               </tns:Segment21>
               <tns:Segment22>
                  <xsl:value-of select="ns0:Segment22"/>
               </tns:Segment22>
               <tns:Segment23>
                  <xsl:value-of select="ns0:Segment23"/>
               </tns:Segment23>
               <tns:Segment24>
                  <xsl:value-of select="ns0:Segment24"/>
               </tns:Segment24>
               <tns:Segment25>
                  <xsl:value-of select="ns0:Segment25"/>
               </tns:Segment25>
               <tns:Segment26>
                  <xsl:value-of select="ns0:Segment26"/>
               </tns:Segment26>
               <tns:Segment27>
                  <xsl:value-of select="ns0:Segment27"/>
               </tns:Segment27>
               <tns:Segment28>
                  <xsl:value-of select="ns0:Segment28"/>
               </tns:Segment28>
               <tns:Segment29>
                  <xsl:value-of select="ns0:Segment29"/>
               </tns:Segment29>
               <tns:Segment30>
                  <xsl:value-of select="ns0:Segment30"/>
               </tns:Segment30>
               <tns:EnteredDebitAmount>
                  <xsl:value-of select="ns0:EnteredDebitAmount"/>
               </tns:EnteredDebitAmount>
               <tns:EnteredCreditAmount>
                  <xsl:value-of select="ns0:EnteredCreditAmount"/>
               </tns:EnteredCreditAmount>
               <tns:ConvertedDebitAmount>
                  <xsl:value-of select="ns0:ConvertedDebitAmount"/>
               </tns:ConvertedDebitAmount>
               <tns:ConvertedCreditAmount>
                  <xsl:value-of select="ns0:ConvertedCreditAmount"/>
               </tns:ConvertedCreditAmount>
               <tns:REFERENCE1BatchName>
                  <xsl:value-of select="dvm:lookupValue (&quot;Dvms/Journals.dvm&quot;, &quot;Code&quot;, ns0:JournalSource, &quot;Value&quot;, &quot;&quot; )"/>
               </tns:REFERENCE1BatchName>
               <tns:REFERENCE2BatchDescription>
                  <xsl:value-of select="ns0:REFERENCE2BatchDescription"/>
               </tns:REFERENCE2BatchDescription>
               <tns:REFERENCE3>
                  <xsl:value-of select="ns0:REFERENCE3"/>
               </tns:REFERENCE3>
               <tns:REFERENCE4JournalEntryName>
                  <xsl:value-of select="ns0:REFERENCE4JournalEntryName"/>
               </tns:REFERENCE4JournalEntryName>
               <tns:REFERENCE5JournalEntryDescription>
                  <xsl:value-of select="ns0:REFERENCE5JournalEntryDescription"/>
               </tns:REFERENCE5JournalEntryDescription>
               <tns:REFERENCE6JournalEntryReference>
                  <xsl:value-of select="ns0:REFERENCE6JournalEntryReference"/>
               </tns:REFERENCE6JournalEntryReference>
               <tns:REFERENCE7JournalEntryReversalflag>
                  <xsl:value-of select="ns0:REFERENCE7JournalEntryReversalflag"/>
               </tns:REFERENCE7JournalEntryReversalflag>
               <tns:REFERENCE8JournalEntryReversalPeriod>
                  <xsl:value-of select="ns0:REFERENCE8JournalEntryReversalPeriod"/>
               </tns:REFERENCE8JournalEntryReversalPeriod>
               <tns:REFERENCE9JournalReversalMethod>
                  <xsl:value-of select="ns0:REFERENCE9JournalReversalMethod"/>
               </tns:REFERENCE9JournalReversalMethod>
               <tns:REFERENCE10JournalEntryLineDescription>
                  <xsl:value-of select="ns0:REFERENCE10JournalEntryLineDescription"/>
               </tns:REFERENCE10JournalEntryLineDescription>
               <tns:ReferenceColumn1>
                  <xsl:value-of select="ns0:ReferenceColumn1"/>
               </tns:ReferenceColumn1>
               <tns:ReferenceColumn2>
                  <xsl:value-of select="ns0:ReferenceColumn2"/>
               </tns:ReferenceColumn2>
               <tns:ReferenceColumn3>
                  <xsl:value-of select="ns0:ReferenceColumn3"/>
               </tns:ReferenceColumn3>
               <tns:ReferenceColumn4>
                  <xsl:value-of select="ns0:ReferenceColumn4"/>
               </tns:ReferenceColumn4>
               <tns:ReferenceColumn5>
                  <xsl:value-of select="ns0:ReferenceColumn5"/>
               </tns:ReferenceColumn5>
               <tns:ReferenceColumn6>
                  <xsl:value-of select="ns0:ReferenceColumn6"/>
               </tns:ReferenceColumn6>
               <tns:ReferenceColumn7>
                  <xsl:value-of select="ns0:ReferenceColumn7"/>
               </tns:ReferenceColumn7>
               <tns:ReferenceColumn8>
                  <xsl:value-of select="ns0:ReferenceColumn8"/>
               </tns:ReferenceColumn8>
               <tns:ReferenceColumn9>
                  <xsl:value-of select="ns0:ReferenceColumn9"/>
               </tns:ReferenceColumn9>
               <tns:ReferenceColumn10>
                  <xsl:value-of select="ns0:ReferenceColumn10"/>
               </tns:ReferenceColumn10>
               <tns:StatisticalAmount>
                  <xsl:value-of select="ns0:StatisticalAmount"/>
               </tns:StatisticalAmount>
               <tns:CurrencyConversionType>
                  <xsl:value-of select="ns0:CurrencyConversionType"/>
               </tns:CurrencyConversionType>
               <tns:CurrencyConversionDate>
                  <xsl:value-of select="ns0:CurrencyConversionDate"/>
               </tns:CurrencyConversionDate>
               <tns:CurrencyConversionRate>
                  <xsl:value-of select="ns0:CurrencyConversionRate"/>
               </tns:CurrencyConversionRate>
               <tns:InterfaceGroupIdentifier>
                  <xsl:value-of select="ns0:InterfaceGroupIdentifier"/>
               </tns:InterfaceGroupIdentifier>
               <tns:ContextFieldForJournalEntryLineDFF>
                  <xsl:value-of select="ns0:ContextFieldForJournalEntryLineDFF"/>
               </tns:ContextFieldForJournalEntryLineDFF>
               <tns:ATTRIBUTE1>
                  <xsl:value-of select="ns0:ATTRIBUTE1"/>
               </tns:ATTRIBUTE1>
               <tns:ATTRIBUTE2>
                  <xsl:value-of select="ns0:ATTRIBUTE2"/>
               </tns:ATTRIBUTE2>
               <tns:Attribute3>
                  <xsl:value-of select="ns0:Attribute3"/>
               </tns:Attribute3>
               <tns:Attribute4>
                  <xsl:value-of select="ns0:Attribute4"/>
               </tns:Attribute4>
               <tns:Attribute5>
                  <xsl:value-of select="ns0:Attribute5"/>
               </tns:Attribute5>
               <tns:Attribute6>
                  <xsl:value-of select="ns0:Attribute6"/>
               </tns:Attribute6>
               <tns:Attribute7>
                  <xsl:value-of select="ns0:Attribute7"/>
               </tns:Attribute7>
               <tns:Attribute8>
                  <xsl:value-of select="ns0:Attribute8"/>
               </tns:Attribute8>
               <tns:Attribute9>
                  <xsl:value-of select="ns0:Attribute9"/>
               </tns:Attribute9>
               <tns:Attribute10>
                  <xsl:value-of select="ns0:Attribute10"/>
               </tns:Attribute10>
               <tns:Attribute11>
                  <xsl:value-of select="ns0:Attribute11"/>
               </tns:Attribute11>
               <tns:Attribute12>
                  <xsl:value-of select="ns0:Attribute12"/>
               </tns:Attribute12>
               <tns:Attribute13>
                  <xsl:value-of select="ns0:Attribute13"/>
               </tns:Attribute13>
               <tns:Attribute14>
                  <xsl:value-of select="ns0:Attribute14"/>
               </tns:Attribute14>
               <tns:Attribute15>
                  <xsl:value-of select="ns0:Attribute15"/>
               </tns:Attribute15>
               <tns:Attribute16>
                  <xsl:value-of select="ns0:Attribute16"/>
               </tns:Attribute16>
               <tns:Attribute17>
                  <xsl:value-of select="ns0:Attribute17"/>
               </tns:Attribute17>
               <tns:Attribute18>
                  <xsl:value-of select="ns0:Attribute18"/>
               </tns:Attribute18>
               <tns:Attribute19>
                  <xsl:value-of select="ns0:Attribute19"/>
               </tns:Attribute19>
               <tns:Attribute20>
                  <xsl:value-of select="ns0:Attribute20"/>
               </tns:Attribute20>
               <tns:ContextFieldForCapturedInformationDFF>
                  <xsl:value-of select="ns0:ContextFieldForCapturedInformationDFF"/>
               </tns:ContextFieldForCapturedInformationDFF>
               <tns:AverageJournalFlag>
                  <xsl:value-of select="ns0:AverageJournalFlag"/>
               </tns:AverageJournalFlag>
               <tns:ClearingCompany>
                  <xsl:value-of select="ns0:ClearingCompany"/>
               </tns:ClearingCompany>
               <tns:LedgerName>
                  <xsl:value-of select="ns0:LedgerName"/>
               </tns:LedgerName>
               <tns:EncumbranceTypeID>
                  <xsl:value-of select="ns0:EncumbranceTypeID"/>
               </tns:EncumbranceTypeID>
               <tns:ReconciliationReference>
                  <xsl:value-of select="ns0:ReconciliationReference"/>
               </tns:ReconciliationReference>
               <tns:EndLine>
                  <xsl:value-of select="&quot;END&quot;"/>
               </tns:EndLine>
            </tns:Journals>
         </xsl:for-each>
      </tns:FileJournal>
   </xsl:template>
</xsl:stylesheet>