<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="bruleImportToERPCloudDS" targetNamespace="http://xmlns.oracle.com/bruleImportToERPCloud/bruleImportToERPCloudDS" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://xmlns.oracle.com/bruleImportToERPCloud/bruleImportToERPCloudDS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="bruleImportToERPCloud.bruleImportToERPCloudDS">
      <plnk:role name="IDecisionService" portType="tns:IDecisionService"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://xmlns.oracle.com/bruleImportToERPCloud/bruleImportToERPCloudDS" location="bruleImportToERPCloudDS.wsdl"/>
</wsdl:definitions>
