<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="bpelDecode" targetNamespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec/bpelDecode" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/SOAUtilitiesTec/bpelDecode" xmlns:ns1="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/bpel/extension">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" schemaLocation="oramds:/apps/SOA/DEV_SOAUtilitiesTec/SOAUtilitiesTec.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="DecodeRq">
      <wsdl:part name="DecodeRq" element="ns1:DecodeRq"/>
   </wsdl:message>
   <wsdl:message name="DecodeRs">
      <wsdl:part name="DecodeRs" element="ns1:DecodeRs"/>
   </wsdl:message>
   <wsdl:portType name="bpelDecode">
      <wsdl:operation name="Decode">
         <wsdl:input message="client:DecodeRq"/>
         <wsdl:output message="client:DecodeRs"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="bpelDecode">
      <plnk:role name="bpelDecodeProvider" portType="client:bpelDecode"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
