<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://soa.estrellaroja.com.mx/PaymentComplementBiz" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://soa.estrellaroja.com.mx/PaymentComplementEnt" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns1="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://soa.estrellaroja.com.mx/PaymentComplementEnt/bpelStampPaymentComplement"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns3="http://soa.estrellaroja.com.mx/PaymentComplementBiz/types"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelStampPaymentComplement.wsdl"/>
            <oracle-xsl-mapper:rootElement name="PAYMENTS_DS" namespace="http://soa.estrellaroja.com.mx/PaymentComplementEnt"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/PaymentComplementBizWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="StampPaymentComplementRq" namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 14 00:28:02 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:StampPaymentComplementRq>
         <xsl:for-each select="/ns0:PAYMENTS_DS/ns0:HEADER">
            <tns:Header>
               <tns:CashReceiptId>
                  <xsl:value-of select="ns0:CASH_RECEIPT_ID"/>
               </tns:CashReceiptId>
               <tns:ReceiptNumber>
                  <xsl:value-of select="ns0:RECEIPT_NUMBER"/>
               </tns:ReceiptNumber>
               <tns:IssuerRfc>
                  <xsl:value-of select="ns0:ISSUER_RFC"/>
               </tns:IssuerRfc>
               <tns:IssuerName>
                  <xsl:value-of select="ns0:ISSUER_NAME"/>
               </tns:IssuerName>
               <tns:IssuerZipCode>
                  <xsl:value-of select="ns0:ISSUER_ZIP_CODE"/>
               </tns:IssuerZipCode>
               <tns:IssuerStreet>
                  <xsl:value-of select="ns0:ISSUER_STREET"/>
               </tns:IssuerStreet>
               <tns:IssuerColony>
                  <xsl:value-of select="ns0:ISSUER_COLONY"/>
               </tns:IssuerColony>
               <tns:IssuerMunicipality>
                  <xsl:value-of select="ns0:ISSUER_MUNICIPALITY"/>
               </tns:IssuerMunicipality>
               <tns:IssuerState>
                  <xsl:value-of select="ns0:ISSUER_STATE"/>
               </tns:IssuerState>
               <tns:IssuerCountry>
                  <xsl:value-of select="ns0:ISSUER_COUNTRY"/>
               </tns:IssuerCountry>
               <tns:InvoiceDate>
                  <xsl:value-of select="ns0:INVOICE_DATE"/>
               </tns:InvoiceDate>
               <tns:DocumentType>
                  <xsl:value-of select="ns0:DOCUMENT_TYPE"/>
               </tns:DocumentType>
               <tns:AdditionalInformation>
                  <xsl:value-of select="ns0:ADDITIONAL_INFORMATION"/>
               </tns:AdditionalInformation>
               <tns:TotalWords>
                  <xsl:value-of select="ns0:TOTAL_WORDS"/>
               </tns:TotalWords>
               <tns:DescriptionItm>
                  <xsl:value-of select="ns0:DESCRIPTION_ITM"/>
               </tns:DescriptionItm>
               <tns:ProdservkeyItm>
                  <xsl:value-of select="ns0:PROD_SERV_KEY_ITM"/>
               </tns:ProdservkeyItm>
               <tns:QuantityItm>
                  <xsl:value-of select="ns0:QUANTITY_ITM"/>
               </tns:QuantityItm>
               <tns:VatPercentageItm>
                  <xsl:value-of select="ns0:VAT_PERCENTAGE_ITM"/>
               </tns:VatPercentageItm>
               <tns:UnitKeyItm>
                  <xsl:value-of select="ns0:UNIT_KEY_ITM"/>
               </tns:UnitKeyItm>
               <tns:AmountItm>
                  <xsl:value-of select="ns0:AMOUNT_ITM"/>
               </tns:AmountItm>
               <tns:SubtotalItm>
                  <xsl:value-of select="ns0:SUBTOTAL_ITM"/>
               </tns:SubtotalItm>
               <tns:VatItm>
                  <xsl:value-of select="ns0:VAT_ITM"/>
               </tns:VatItm>
               <tns:TotalItm>
                  <xsl:value-of select="ns0:TOTAL_ITM"/>
               </tns:TotalItm>
               <tns:TaxObjectItm>
                  <xsl:value-of select="ns0:TAX_OBJECT_ITM"/>
               </tns:TaxObjectItm>
               <tns:TotalVat>
                  <xsl:value-of select="ns0:TOTAL_VAT"/>
               </tns:TotalVat>
               <tns:Subtotal>
                  <xsl:value-of select="ns0:SUBTOTAL"/>
               </tns:Subtotal>
               <tns:Total>
                  <xsl:value-of select="ns0:TOTAL"/>
               </tns:Total>
               <tns:Serie>
                  <xsl:value-of select="ns0:SERIE"/>
               </tns:Serie>
               <tns:BranchName>
                  <xsl:value-of select="ns0:BRANCH_NAME"/>
               </tns:BranchName>
               <tns:BranchZipCode>
                  <xsl:value-of select="ns0:BRANCH_ZIP_CODE"/>
               </tns:BranchZipCode>
               <tns:ReceiverName>
                  <xsl:value-of select="ns0:RECEIVER_NAME"/>
               </tns:ReceiverName>
               <tns:ReceiverRfc>
                  <xsl:value-of select="ns0:RECEIVER_RFC"/>
               </tns:ReceiverRfc>
               <tns:ReceiverPhone>
                  <xsl:value-of select="ns0:RECEIVER_PHONE"/>
               </tns:ReceiverPhone>
               <tns:ReceiverAddress>
                  <xsl:value-of select="ns0:RECEIVER_ADDRESS"/>
               </tns:ReceiverAddress>
               <tns:ReceiverCounty>
                  <xsl:value-of select="ns0:RECEIVER_COUNTY"/>
               </tns:ReceiverCounty>
               <tns:ReceiverExtNumber>
                  <xsl:value-of select="ns0:RECEIVER_EXT_NUMBER"/>
               </tns:ReceiverExtNumber>
               <tns:ReceiverIntNumber>
                  <xsl:value-of select="ns0:RECEIVER_INT_NUMBER"/>
               </tns:ReceiverIntNumber>
               <tns:ReceiverStreet>
                  <xsl:value-of select="ns0:RECEIVER_STREET"/>
               </tns:ReceiverStreet>
               <tns:ReceiverMunicipality>
                  <xsl:value-of select="ns0:RECEIVER_MUNICIPALITY"/>
               </tns:ReceiverMunicipality>
               <tns:ReceiverState>
                  <xsl:value-of select="ns0:RECEIVER_STATE"/>
               </tns:ReceiverState>
               <tns:ReceiverCountry>
                  <xsl:value-of select="ns0:RECEIVER_COUNTRY"/>
               </tns:ReceiverCountry>
               <tns:ReceiverColony>
                  <xsl:value-of select="ns0:RECEIVER_COLONY"/>
               </tns:ReceiverColony>
               <tns:ReceiverCfdiUse>
                  <xsl:value-of select="ns0:RECEIVER_CFDI_USE"/>
               </tns:ReceiverCfdiUse>
               <tns:ReceiverTaxRegime>
                  <xsl:value-of select="ns0:RECEIVER_TAX_REGIME"/>
               </tns:ReceiverTaxRegime>
               <tns:ReceiverZipCode>
                  <xsl:value-of select="ns0:RECEIVER_ZIP_CODE"/>
               </tns:ReceiverZipCode>
               <tns:Currency>
                  <xsl:value-of select="ns0:CURRENCY"/>
               </tns:Currency>
               <tns:IssuerTaxRegime>
                  <xsl:value-of select="ns0:ISSUER_TAX_REGIME"/>
               </tns:IssuerTaxRegime>
               <tns:Comments>
                  <xsl:value-of select="ns0:COMMENTS"/>
               </tns:Comments>
               <tns:Service>
                  <xsl:value-of select="ns0:SERVICE"/>
               </tns:Service>
               <tns:PaymentDatePc>
                  <xsl:value-of select="ns0:PAYMENT_DATE_PC"/>
               </tns:PaymentDatePc>
               <tns:PaymentWayPc>
                  <xsl:value-of select="ns0:PAYMENT_WAY_PC"/>
               </tns:PaymentWayPc>
               <tns:CurrencyPc>
                  <xsl:value-of select="ns0:CURRENCY_PC"/>
               </tns:CurrencyPc>
               <tns:CurrencyExchangePc>
                  <xsl:value-of select="ns0:CURRENCY_EXCHANGE_PC"/>
               </tns:CurrencyExchangePc>
               <tns:AmountPc>
                  <xsl:value-of select="ns0:AMOUNT_PC"/>
               </tns:AmountPc>
               <tns:OperationNumberPc>
                  <xsl:value-of select="ns0:OPERATION_NUMBER_PC"/>
               </tns:OperationNumberPc>
               <tns:BankNamePc>
                  <xsl:value-of select="ns0:BANK_NAME_PC"/>
               </tns:BankNamePc>
               <tns:PayerAccountPc>
                  <xsl:value-of select="ns0:PAYER_ACCOUNT_PC"/>
               </tns:PayerAccountPc>
               <tns:BenAccIssuerRfcPc>
                  <xsl:value-of select="ns0:BEN_ACC_ISSUER_RFC_PC"/>
               </tns:BenAccIssuerRfcPc>
               <tns:BeneficiaryAccountPc>
                  <xsl:value-of select="ns0:BENEFICIARY_ACCOUNT_PC"/>
               </tns:BeneficiaryAccountPc>
               <tns:PaymentStringTypePc>
                  <xsl:value-of select="ns0:PAYMENT_STRING_TYPE_PC"/>
               </tns:PaymentStringTypePc>
               <tns:PaymentCertPc>
                  <xsl:value-of select="ns0:PAYMENT_CERT_PC"/>
               </tns:PaymentCertPc>
               <tns:PaymentStringPc>
                  <xsl:value-of select="ns0:PAYMENT_STRING_PC"/>
               </tns:PaymentStringPc>
               <tns:PaymentSealPc>
                  <xsl:value-of select="ns0:PAYMENT_SEAL_PC"/>
               </tns:PaymentSealPc>
               <tns:VersionPc>
                  <xsl:value-of select="ns0:VERSION_PC"/>
               </tns:VersionPc>
               <tns:CustomerNumber>
                  <xsl:value-of select="ns0:CUSTOMER_NUMBER"/>
               </tns:CustomerNumber>
               <tns:AccountNumber>
                  <xsl:value-of select="ns0:ACCOUNT_NUMBER"/>
               </tns:AccountNumber>
               <tns:SiteNumber>
                  <xsl:value-of select="ns0:SITE_NUMBER"/>
               </tns:SiteNumber>
               <tns:LastUpdateDate>
                  <xsl:value-of select="ns0:LAST_UPDATE_DATE"/>
               </tns:LastUpdateDate>
               <tns:LastUpatedby>
                  <xsl:value-of select="ns0:LAST_UPDATED_BY"/>
               </tns:LastUpatedby>
               <tns:BusinessUnit>
                  <xsl:value-of select="ns0:BUSINESS_UNIT"/>
               </tns:BusinessUnit>
               <tns:EstatusCFDI>
                  <xsl:value-of select="ns0:ESTATUS_CFDI"/>
               </tns:EstatusCFDI>
               <tns:Exportacion>
                  <xsl:value-of select="ns0:EXPORTACION"/>
               </tns:Exportacion>
               <tns:ReceiptMethod>
                  <xsl:value-of select="ns0:RECEIPT_METHOD"/>
               </tns:ReceiptMethod>
               <xsl:for-each select="ns0:LINES">
                  <tns:Lines>
                     <tns:CashReceiptId>
                        <xsl:value-of select="ns0:CASH_RECEIPT_ID"/>
                     </tns:CashReceiptId>
                     <tns:InvoiceNumber>
                        <xsl:value-of select="ns0:INVOICE_NUMBER"/>
                     </tns:InvoiceNumber>
                     <tns:DocumentId>
                        <xsl:value-of select="ns0:DOCUMENT_ID"/>
                     </tns:DocumentId>
                     <tns:Serie>
                        <xsl:value-of select="ns0:SERIE"/>
                     </tns:Serie>
                     <tns:Folio>
                        <xsl:value-of select="ns0:FOLIO"/>
                     </tns:Folio>
                     <tns:Currency>
                        <xsl:value-of select="ns0:CURRENCY"/>
                     </tns:Currency>
                     <tns:CurrencyExchange>
                        <xsl:value-of select="ns0:CURRENCY_EXCHANGE"/>
                     </tns:CurrencyExchange>
                     <tns:PaymentMethod>
                        <xsl:value-of select="ns0:PAYMENT_METHOD"/>
                     </tns:PaymentMethod>
                     <tns:PartialityNumber>
                        <xsl:value-of select="ns0:PARTIALITY_NUMBER"/>
                     </tns:PartialityNumber>
                     <tns:PreviousBalance>
                        <xsl:value-of select="ns0:PREVIOUS_BALANCE"/>
                     </tns:PreviousBalance>
                     <tns:PaidAmount>
                        <xsl:value-of select="ns0:PAID_AMOUNT"/>
                     </tns:PaidAmount>
                     <tns:OutStandingBalance>
                        <xsl:value-of select="ns0:OUTSTANDING_BALANCE"/>
                     </tns:OutStandingBalance>
                     <tns:CustomerTrxLineId>
                        <xsl:value-of select="ns0:CUSTOMER_TRX_LINE_ID"/>
                     </tns:CustomerTrxLineId>
                     <tns:ReceiptNumber>
                        <xsl:value-of select="ns0:RECEIPT_NUMBER"/>
                     </tns:ReceiptNumber>
                     <tns:InstallmentNumber>
                        <xsl:value-of select="ns0:INSTALLMENT_NUMBER"/>
                     </tns:InstallmentNumber>
                     <tns:ReceivableApplicationId>
                        <xsl:value-of select="ns0:RECEIVABLE_APPLICATION_ID"/>
                     </tns:ReceivableApplicationId>
                     <tns:TrxNumber>
                        <xsl:value-of select="ns0:TRX_NUMBER"/>
                     </tns:TrxNumber>
                     <tns:Exportacion>
                        <xsl:value-of select="ns0:EXPORTACION"/>
                     </tns:Exportacion>
                     <tns:TaxObject>
                        <xsl:value-of select="ns0:TAX_OBJECT"/>
                     </tns:TaxObject>
                     <tns:RetainedTaxBase>
                        <xsl:value-of select="ns0:RETAINED_TAX_BASE"/>
                     </tns:RetainedTaxBase>
                     <tns:RetainedTax>
                        <xsl:value-of select="ns0:RETAINED_TAX"/>
                     </tns:RetainedTax>
                     <tns:RetainedRateFee>
                        <xsl:value-of select="ns0:RETAINED_RATE_FEE"/>
                     </tns:RetainedRateFee>
                     <tns:RetainedFactorType>
                        <xsl:value-of select="ns0:RETAINED_FACTOR_TYPE"/>
                     </tns:RetainedFactorType>
                     <tns:RetainedAmount>
                        <xsl:value-of select="ns0:RETAINED_AMOUNT"/>
                     </tns:RetainedAmount>
                     <tns:TransferredsTaxBase>
                        <xsl:value-of select="ns0:TRANSFERREDS_TAX_BASE"/>
                     </tns:TransferredsTaxBase>
                     <tns:TransferredsTax>
                        <xsl:value-of select="ns0:TRANSFERREDS_TAX"/>
                     </tns:TransferredsTax>
                     <tns:TransferredsRateFee>
                        <xsl:value-of select="ns0:TRANSFERREDS_RATE_FEE"/>
                     </tns:TransferredsRateFee>
                     <tns:TransferredsFactorType>
                        <xsl:value-of select="ns0:TRANSFERREDS_FACTOR_TYPE"/>
                     </tns:TransferredsFactorType>
                     <tns:TransferredsAmount>
                        <xsl:value-of select="ns0:TRANSFERREDS_AMOUNT"/>
                     </tns:TransferredsAmount>
                  </tns:Lines>
               </xsl:for-each>
            </tns:Header>
         </xsl:for-each>
      </tns:StampPaymentComplementRq>
   </xsl:template>
</xsl:stylesheet>
