<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://soa.estrellaroja.com.mx/JournalEnt" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationBiz" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationBiz/types"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://soa.estrellaroja.com.mx/JournalEnt/bpelSendFileJournal"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://schemas.oracle.com/bpel/extension" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/ERPIntegrationBizWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ImportToERPCloudRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/ERPIntegrationBizWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ImportToERPCloudRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"/>
            <oracle-xsl-mapper:param name="varInvokeWsERPIntegrationBizImportToERPCloudL2Rs.ImportToERPCloudRs"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelSendFileJournal.wsdl"/>
            <oracle-xsl-mapper:rootElement name="SendFileJournalRs" namespace="http://soa.estrellaroja.com.mx/JournalEnt"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE DEC 19 15:45:11 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varInvokeWsERPIntegrationBizImportToERPCloudL2Rs.ImportToERPCloudRs"/>
   <xsl:template match="/">
      <tns:SendFileJournalRs>
         <xsl:if test="string-length (/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process/ns0:Id ) > 0 and string-length ($varInvokeWsERPIntegrationBizImportToERPCloudL2Rs.ImportToERPCloudRs/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process/ns0:Id ) > 0">
            <ns1:Success>
               <xsl:value-of select="&quot;Success&quot;"/>
            </ns1:Success>
         </xsl:if>
         <xsl:if test="$varInvokeWsERPIntegrationBizImportToERPCloudL2Rs.ImportToERPCloudRs/ns0:ImportToERPCloudRs/ns1:Errors and /ns0:ImportToERPCloudRs/ns1:Errors">
            <ns1:Errors>
               <xsl:choose>
                  <xsl:when test="/ns0:ImportToERPCloudRs/ns1:Errors/ns1:Error">
                     <xsl:for-each select="/ns0:ImportToERPCloudRs/ns1:Errors/ns1:Error">
                        <ns1:Error>
                           <ns1:ErrorCode>
                              <xsl:value-of select="ns1:ErrorCode"/>
                           </ns1:ErrorCode>
                           <ns1:ShortDescription>
                              <xsl:value-of select="ns1:ShortDescription"/>
                           </ns1:ShortDescription>
                           <ns1:Description>
                              <xsl:value-of select="ns1:Description"/>
                           </ns1:Description>
                           <ns1:BusinessProcess>
                              <xsl:value-of select="ns1:BusinessProcess"/>
                           </ns1:BusinessProcess>
                           <ns1:FailedService>
                              <xsl:value-of select="ns1:FailedService"/>
                           </ns1:FailedService>
                           <ns1:TimeStamp>
                              <xsl:value-of select="ns1:TimeStamp"/>
                           </ns1:TimeStamp>
                        </ns1:Error>
                     </xsl:for-each>
                  </xsl:when>
                  <xsl:when test="$varInvokeWsERPIntegrationBizImportToERPCloudL2Rs.ImportToERPCloudRs/ns0:ImportToERPCloudRs/ns1:Errors/ns1:Error">
                     <xsl:for-each select="$varInvokeWsERPIntegrationBizImportToERPCloudL2Rs.ImportToERPCloudRs/ns0:ImportToERPCloudRs/ns1:Errors/ns1:Error">
                        <ns1:Error>
                           <ns1:ErrorCode>
                              <xsl:value-of select="ns1:ErrorCode"/>
                           </ns1:ErrorCode>
                           <ns1:ShortDescription>
                              <xsl:value-of select="ns1:ShortDescription"/>
                           </ns1:ShortDescription>
                           <ns1:Description>
                              <xsl:value-of select="ns1:Description"/>
                           </ns1:Description>
                           <ns1:BusinessProcess>
                              <xsl:value-of select="ns1:BusinessProcess"/>
                           </ns1:BusinessProcess>
                           <ns1:FailedService>
                              <xsl:value-of select="ns1:FailedService"/>
                           </ns1:FailedService>
                           <ns1:TimeStamp>
                              <xsl:value-of select="ns1:TimeStamp"/>
                           </ns1:TimeStamp>
                        </ns1:Error>
                     </xsl:for-each>
                  </xsl:when>
               </xsl:choose>
            </ns1:Errors>
         </xsl:if>
         <xsl:if test="/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process">
            <xsl:choose>
               <xsl:when test="/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process">
                  <tns:Return>
                     <tns:Process>
                        <tns:FileLedgerName>
                           <xsl:value-of select="&quot;LIBRO ER&quot;"/>
                        </tns:FileLedgerName>
                        <tns:Id>
                           <xsl:value-of select="/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process/ns0:Id"/>
                        </tns:Id>
                        <tns:ProcessName>
                           <xsl:value-of select="/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process/ns0:ProcessName"/>
                        </tns:ProcessName>
                        <tns:Status>
                           <xsl:value-of select="/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process/ns0:Status"/>
                        </tns:Status>
                     </tns:Process>
                  </tns:Return>
               </xsl:when>
            </xsl:choose>
            <xsl:choose>
               <xsl:when test="/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process">
                  <tns:Return>
                     <tns:Process>
                        <tns:FileLedgerName>
                           <xsl:value-of select="&quot;LIBRO SECUNDARIO ER&quot;"/>
                        </tns:FileLedgerName>
                        <tns:Id>
                           <xsl:value-of select="$varInvokeWsERPIntegrationBizImportToERPCloudL2Rs.ImportToERPCloudRs/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process/ns0:Id"/>
                        </tns:Id>
                        <tns:ProcessName>
                           <xsl:value-of select="$varInvokeWsERPIntegrationBizImportToERPCloudL2Rs.ImportToERPCloudRs/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process/ns0:ProcessName"/>
                        </tns:ProcessName>
                        <tns:Status>
                           <xsl:value-of select="$varInvokeWsERPIntegrationBizImportToERPCloudL2Rs.ImportToERPCloudRs/ns0:ImportToERPCloudRs/ns0:Return/ns0:Processes/ns0:Process/ns0:Status"/>
                        </tns:Status>
                     </tns:Process>
                  </tns:Return>
               </xsl:when>
            </xsl:choose>
         </xsl:if>
      </tns:SendFileJournalRs>
   </xsl:template>
</xsl:stylesheet>
