<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="bpelCreateSites" targetNamespace="http://soa.estrellaroja.com.mx/CustomerBiz/bpelCreateSites" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelCreateSites" xmlns:ns1="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://soa.estrellaroja.com.mx/FinancialsTec" xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec">
   <plnk:partnerLinkType name="bpelCreateSites">
      <plnk:role name="bpelCreateSitesProvider" portType="client:bpelCreateSites"/>
   </plnk:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelCreateSites" xmlns:ns1="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://soa.estrellaroja.com.mx/FinancialsTec" xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec">
         <import namespace="http://soa.estrellaroja.com.mx/CustomerBiz" schemaLocation="oramds:/apps/SOA/CustomerBiz/CustomerBiz.xsd"/>
      </schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelCreateSites" xmlns:ns1="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://soa.estrellaroja.com.mx/FinancialsTec" xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec">
         <xsd:import namespace="http://soa.estrellaroja.com.mx/FinancialsTec" schemaLocation="oramds:/apps/OSB/FinancialsTec/FinancialsTec.xsd"/>
      </xsd:schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelCreateSites" xmlns:ns1="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://soa.estrellaroja.com.mx/FinancialsTec" xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec">
         <xsd:import namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" schemaLocation="oramds:/apps/OSB/ERPIntegrationServiceTec/ERPIntegrationServiceTec.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="CreateSitesRq">
      <wsdl:part name="CreateSitesRq" element="ns1:CreateSitesRq"/>
   </wsdl:message>
   <wsdl:message name="CreateSitesRs">
      <wsdl:part name="CreateSitesRs" element="ns1:CreateSitesRs"/>
   </wsdl:message>
   <wsdl:portType name="bpelCreateSites">
      <wsdl:operation name="CreateSites">
         <wsdl:input message="client:CreateSitesRq"/>
         <wsdl:output message="client:CreateSitesRs"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
