<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="bpelUpdateCustomer" targetNamespace="http://soa.estrellaroja.com.mx/CustomerBiz/bpelUpdateCustomer" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/CustomerBiz/bpelUpdateCustomer" xmlns:ns1="http://soa.estrellaroja.com.mx/CustomerBiz" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons">
   <plnk:partnerLinkType name="bpelUpdateCustomer">
      <plnk:role name="bpelUpdateCustomerProvider" portType="client:bpelUpdateCustomer"/>
   </plnk:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://soa.estrellaroja.com.mx/CustomerBiz" schemaLocation="oramds:/apps/SOA/CustomerBiz/CustomerBiz.xsd"/>
      </schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" schemaLocation="oramds:/apps/Common/XSD/EstrellaRojaCommons.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="UpdateCustomerRq">
      <wsdl:part name="UpdateCustomerRq" element="ns1:UpdateCustomerRq"/>
   </wsdl:message>
   <wsdl:message name="UpdateCustomerRs">
      <wsdl:part name="UpdateCustomerRs" element="ns1:UpdateCustomerRs"/>
   </wsdl:message>
   <wsdl:portType name="bpelUpdateCustomer">
      <wsdl:operation name="UpdateCustomer">
         <wsdl:input message="client:UpdateCustomerRq"/>
         <wsdl:output message="client:UpdateCustomerRs"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
