<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/StructureTrxCust" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://soa.estrellaroja.com.mx/ReceiptEnt/bpelCreateReceipts" xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://soa.estrellaroja.com.mx/ReceiptEnt">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateReceipts.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DATA_DS" namespace="http://soa.estrellaroja.com.mx/StructureTrxCust"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelCreateReceipts.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DATA_DS" namespace="http://soa.estrellaroja.com.mx/StructureTrxCust"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE JAN 09 15:24:42 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:DATA_DS>
         <ns0:TRXNUMBER>
            <xsl:value-of select="/ns0:DATA_DS/TRXNUMBER"/>
         </ns0:TRXNUMBER>
         <ns0:ORGID>
            <xsl:value-of select="/ns0:DATA_DS/ORGID"/>
         </ns0:ORGID>
         <ns0:CUSTOMERID>
            <xsl:value-of select="/ns0:DATA_DS/CUSTOMERID"/>
         </ns0:CUSTOMERID>
         <ns0:CUSTOMER_TRX>
            <ns0:CUSTOMER_TRX_ID>
               <xsl:value-of select="/ns0:DATA_DS/ns0:CUSTOMER_TRX/ns0:CUSTOMER_TRX_ID"/>
            </ns0:CUSTOMER_TRX_ID>
            <ns0:UUID>
               <xsl:value-of select="/ns0:DATA_DS/ns0:CUSTOMER_TRX/ns0:UUID"/>
            </ns0:UUID>
         </ns0:CUSTOMER_TRX>
         <ns0:ORG_UNIT>
            <ns0:BUSINESS_UNIT>
               <xsl:value-of select="/ns0:DATA_DS/ns0:ORG_UNIT/ns0:BUSINESS_UNIT"/>
            </ns0:BUSINESS_UNIT>
         </ns0:ORG_UNIT>
      </ns0:DATA_DS>
   </xsl:template>
</xsl:stylesheet>