<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="PaymentComplementBiz"
     targetNamespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://soa.estrellaroja.com.mx/PaymentComplementBiz"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="wsPaymentComplementBiz">
        <plnk:role name="PaymentComplementBizPortType" portType="tns:PaymentComplementBizPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz" location="oramds:/apps/SOA/PaymentComplementBiz/PaymentComplementBiz.wsdl"/>
</wsdl:definitions>
