<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ERPIntegrationBiz"
     targetNamespace="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationBiz"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="wsERPIntegrationBiz">
        <plnk:role name="ERPIntegrationBizPortType" portType="tns:ERPIntegrationBizPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soa.estrellaroja.com.mx/ERPIntegrationBiz" location="oramds:/apps/SOA/ERPIntegrationBiz/ERPIntegrationBiz.wsdl"/>
</wsdl:definitions>
