<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="umsSendEmail" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ums/MessageTec/MessageTec/umsSendEmail" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ums/MessageTec/MessageTec/umsSendEmail" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:imp1="http://platform.integration.oracle/blocks/adapter/fw/metadata/umsSendEmail" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="SendNotification_plt">
      <plt:role name="SendNotification_role">
         <plt:portType name="tns:SendNotification_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://platform.integration.oracle/blocks/adapter/fw/metadata/umsSendEmail" schemaLocation="../Schemas/umsSendEmail.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="SendNotification_msg">
      <wsdl:part name="body" element="imp1:message"/>
   </wsdl:message>
   <wsdl:message name="SendNotification_msg_reply">
      <wsdl:part name="body" element="imp1:response"/>
   </wsdl:message>
   <wsdl:portType name="SendNotification_ptt">
      <wsdl:operation name="SendNotification">
         <wsdl:input message="tns:SendNotification_msg"/>
         <wsdl:output message="tns:SendNotification_msg_reply"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
