<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://soa.estrellaroja.com.mx/InvoicesBiz/DoctosRelacionados" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/ElectronicInvoiceAP"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelUploadPaymentComplements"
                xmlns:ns6="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelUploadPaymentComplements.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ExtPaymentComplement" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelUploadPaymentComplements.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RelatedDocs" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz/DoctosRelacionados"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI DEC 29 12:49:54 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:RelatedDocs>
         <xsl:for-each select="/ns0:ExtPaymentComplement/ns0:Invoice">
            <tns:RelatedDoc>
               <tns:InvoiceNumber>
                  <xsl:value-of select="ns0:InvoiceNumber"/>
               </tns:InvoiceNumber>
               <tns:Uuid>
                  <xsl:value-of select="ns0:Uuid"/>
               </tns:Uuid>
            </tns:RelatedDoc>
         </xsl:for-each>
      </tns:RelatedDocs>
   </xsl:template>
</xsl:stylesheet>
