<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns1="http://soa.estrellaroja.com.mx/cfd/3" 
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" 
                xmlns:tns="http://soa.estrellaroja.com.mx/ElectronicInvoiceAP" 
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" 
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" 
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" 
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" 
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" 
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" 
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
                xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz" 
                exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns4="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelValidateInvoicesAP"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns5="http://soa.estrellaroja.com.mx/sitio_internet/cfd/tipoDatos/tdCFDI"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns6="http://soa.estrellaroja.com.mx/TimbreFiscalDigital"
                xmlns:cfdi="http://www.sat.gob.mx/cfd/3"
                xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital"
                xmlns:ns7="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelValidateInvoicesAP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InvoiceAP" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelValidateInvoicesAP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Comprobante" namespace="http://soa.estrellaroja.com.mx/cfd/3"/>
            <oracle-xsl-mapper:param name="varXMLInvoice"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelValidateInvoicesAP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Payment" namespace="http://soa.estrellaroja.com.mx/ElectronicInvoiceAP"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED JAN 31 11:15:47 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varXMLInvoice"/>
   <xsl:template match="/">
      <tns:Payment>
         <tns:InvoiceNumber>
            <xsl:value-of select="/ns0:InvoiceAP/ns0:InvoiceNumber"/>
         </tns:InvoiceNumber>
         <tns:RfcIssuer>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Emisor/@Rfc"/>
         </tns:RfcIssuer>
         <tns:RfcReceiver>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Receptor/@Rfc"/>
         </tns:RfcReceiver>
         <tns:TotalAmount>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/@Total"/>
         </tns:TotalAmount>
         <tns:Uuid>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Complemento/tfd:TimbreFiscalDigital/@UUID"/>
         </tns:Uuid>
         <tns:CuentaPredial>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Conceptos/cfdi:Concepto/cfdi:CuentaPredial/@Numero"/>
         </tns:CuentaPredial>
         <tns:UsoCFDI>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Receptor/@UsoCFDI"/>
         </tns:UsoCFDI>
         <tns:Moneda>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/@Moneda"/>
         </tns:Moneda>
         <tns:InformacionAduanera>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Conceptos/cfdi:Concepto/cfdi:Parte/cfdi:InformacionAduanera/@NumeroPedimento"/>
         </tns:InformacionAduanera>
         <tns:FormaPago>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/@FormaPago"/>
         </tns:FormaPago>
         <tns:MetodoPago>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/@MetodoPago"/>
         </tns:MetodoPago>
         <tns:ClaveProdServ>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Conceptos/cfdi:Concepto/@ClaveProdServ"/>
         </tns:ClaveProdServ>
         <tns:FechaTimbrado>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Complemento/tfd:TimbreFiscalDigital/@FechaTimbrado"/>
         </tns:FechaTimbrado>
         <tns:TipoDeComprobante>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/@TipoDeComprobante"/>
         </tns:TipoDeComprobante>
         <tns:SubTotal>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/@SubTotal"/>
         </tns:SubTotal>
         <tns:TipoRelacion>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:CfdiRelacionados/@TipoRelacion"/>
         </tns:TipoRelacion>
         <tns:UUIDRelacion>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:CfdiRelacionados/cfdi:CfdiRelacionado/@UUID"/>
         </tns:UUIDRelacion>
         <tns:RFCEmisor>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/ns1:Emisor/@Rfc"/>
         </tns:RFCEmisor>
         <tns:NomEmisor>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Emisor/@Nombre"/>
         </tns:NomEmisor>
         <tns:Descuento>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/@Descuento"/>
         </tns:Descuento>
         <tns:TipoCambio>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/@TipoCambio"/>
         </tns:TipoCambio>
         <tns:DescripcionL>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Conceptos/cfdi:Concepto/@Descripcion"/>
         </tns:DescripcionL>
         <tns:RetenidoIVA>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Impuestos/cfdi:Retenciones/cfdi:Retencion/@Importe"/>
         </tns:RetenidoIVA>
         <tns:RetenidoISR/>
         <tns:Impuesto>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Conceptos/cfdi:Concepto/cfdi:Impuestos/cfdi:Traslados/cfdi:Traslado/@TasaOCuota"/>
         </tns:Impuesto>
         <tns:Importe>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Impuestos/cfdi:Traslados/cfdi:Traslado/@Importe"/>
         </tns:Importe>
         <tns:Impuestoieps>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Conceptos/cfdi:Concepto/cfdi:Impuestos/cfdi:Traslados/cfdi:Traslado/@Impuesto"/>
         </tns:Impuestoieps>
         <tns:Importeieps>
            <xsl:value-of select="$varXMLInvoice/ns1:Comprobante/cfdi:Conceptos/cfdi:Concepto/cfdi:Impuestos/cfdi:Traslados/cfdi:Traslado/@Importe"/>
         </tns:Importeieps>
      </tns:Payment>
   </xsl:template>
</xsl:stylesheet>
