<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbaGetInvoices" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://soa.estrellaroja.com.mx/InvoicesBiz" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/InvoicesBiz/InvoicesBiz/dbaGetInvoices"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelBuildInvoicesZip"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns4="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension"
                xmlns:ns5="http://soa.estrellaroja.com.mx/FinancialsTec"
                xmlns:ns6="http://soa.estrellaroja.com.mx/InvoicesBiz/StructursInvoicesBiz"
                xmlns:ns7="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns8="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/dbaGetInvoices.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbaGetInvoices"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelBuildInvoicesZip.wsdl"/>
            <oracle-xsl-mapper:rootElement name="invoicesToCsv" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED DEC 27 20:20:23 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:invoicesToCsv>
         <xsl:for-each select="/ns0:OutputParameters/ns0:P_INVOICE/ns0:P_INVOICE_ITEM">
            <tns:InvoicesList>
               <tns:Notes_from_Source>
                  <xsl:value-of select="ns0:NOTES_FROM_SOURCE"/>
               </tns:Notes_from_Source>
               <tns:Transaction_Batch_Source_Name>
                  <xsl:value-of select="ns0:TRANSACTION_BATCH_SOURCE_NAME"/>
               </tns:Transaction_Batch_Source_Name>
               <tns:Transaction_Type_Name>
                  <xsl:value-of select="ns0:TRANSACTION_TYPE_NAME"/>
               </tns:Transaction_Type_Name>
               <tns:Payment_Terms>
                  <xsl:value-of select="ns0:PAYMENT_TERMS"/>
               </tns:Payment_Terms>
               <tns:Transaction_Date>
                  <xsl:value-of select="concat (substring (ns0:TRANSACTION_DATE, 1, 4 ), &quot;/&quot;, substring (ns0:TRANSACTION_DATE, 6, 2 ), &quot;/&quot;, substring (ns0:TRANSACTION_DATE, 9, 2 ) )"/>
               </tns:Transaction_Date>
               <tns:Accounting_Date>
                  <xsl:value-of select="concat (substring (ns0:ACCOUNTING_DATE, 1, 4 ), &quot;/&quot;, substring (ns0:ACCOUNTING_DATE, 6, 2 ), &quot;/&quot;, substring (ns0:ACCOUNTING_DATE, 9, 2 ) )"/>
               </tns:Accounting_Date>
               <tns:Transaction_Number>
                  <xsl:value-of select="ns0:TRANSACTION_NUMBER"/>
               </tns:Transaction_Number>
               <tns:Original_System_Bill_to_Customer_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_BILL_TO_CUSTOMER_REFERENCE"/>
               </tns:Original_System_Bill_to_Customer_Reference>
               <tns:Original_System_Bill_to_Customer_Address_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_BILL_TO_CUSTOMER_ADDRESS_REFERENCE"/>
               </tns:Original_System_Bill_to_Customer_Address_Reference>
               <tns:Original_System_Bill_to_Customer_Contact_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_BILL_TO_CUSTOMER_CONTACT_REFERENCE"/>
               </tns:Original_System_Bill_to_Customer_Contact_Reference>
               <tns:Original_System_Ship_to_Customer_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_SHIP_TO_CUSTOMER_REFERENCE"/>
               </tns:Original_System_Ship_to_Customer_Reference>
               <tns:Original_System_Ship_to_Customer_Address_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_SHIP_TO_CUSTOMER_ADDRESS_REFERENCE"/>
               </tns:Original_System_Ship_to_Customer_Address_Reference>
               <tns:Original_System_Ship_to_Customer_Contact_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_SHIP_TO_CUSTOMER_CONTACT_REFERENCE"/>
               </tns:Original_System_Ship_to_Customer_Contact_Reference>
               <tns:Original_System_Ship_to_Customer_Account_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_SHIP_TO_CUSTOMER_ACCOUNT_REFERENCE"/>
               </tns:Original_System_Ship_to_Customer_Account_Reference>
               <tns:Original_System_Ship_to_Customer_Account_Address_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_SHIP_TO_CUSTOMER_ACCOUNT_ADDRESS_REFERENCE"/>
               </tns:Original_System_Ship_to_Customer_Account_Address_Reference>
               <tns:Original_System_Ship_to_Customer_Account_Contact_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_SHIP_TO_CUSTOMER_ACCOUNT_CONTACT_REFERENCE"/>
               </tns:Original_System_Ship_to_Customer_Account_Contact_Reference>
               <tns:Original_System_Sold_to_Customer_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_SOLD_TO_CUSTOMER_REFERENCE"/>
               </tns:Original_System_Sold_to_Customer_Reference>
               <tns:Original_System_Sold_to_Customer_Account_Reference>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_SOLD_TO_CUSTOMER_ACCOUNT_REFERENCE"/>
               </tns:Original_System_Sold_to_Customer_Account_Reference>
               <tns:Bill_to_Customer_Account_Number>
                  <xsl:value-of select="ns0:BILL_TO_CUSTOMER_ACCOUNT_NUMBER"/>
               </tns:Bill_to_Customer_Account_Number>
               <tns:Bill_to_Customer_Site_Number>
                  <xsl:value-of select="ns0:BILL_TO_CUSTOMER_SITE_NUMBER"/>
               </tns:Bill_to_Customer_Site_Number>
               <tns:Bill_to_Contact_Party_Number>
                  <xsl:value-of select="ns0:BILL_TO_CONTACT_PARTY_NUMBER"/>
               </tns:Bill_to_Contact_Party_Number>
               <tns:Ship_to_Customer_Account_Number>
                  <xsl:value-of select="ns0:SHIP_TO_CUSTOMER_ACCOUNT_NUMBER"/>
               </tns:Ship_to_Customer_Account_Number>
               <tns:Ship_to_Customer_Site_Number>
                  <xsl:value-of select="ns0:SHIP_TO_CUSTOMER_SITE_NUMBER"/>
               </tns:Ship_to_Customer_Site_Number>
               <tns:Ship_to_Contact_Party_Number>
                  <xsl:value-of select="ns0:SHIP_TO_CONTACT_PARTY_NUMBER"/>
               </tns:Ship_to_Contact_Party_Number>
               <tns:Sold_to_Customer_Account_Number>
                  <xsl:value-of select="ns0:SOLD_TO_CUSTOMER_ACCOUNT_NUMBER"/>
               </tns:Sold_to_Customer_Account_Number>
               <tns:Transaction_Line_Type>
                  <xsl:value-of select="ns0:TRANSACTION_LINE_TYPE"/>
               </tns:Transaction_Line_Type>
               <tns:Transaction_Line_Description>
                  <xsl:value-of select="ns0:TRANSACTION_LINE_DESCRIPTION"/>
               </tns:Transaction_Line_Description>
               <tns:Currency_Code>
                  <xsl:value-of select="ns0:CURRENCY_CODE"/>
               </tns:Currency_Code>
               <tns:Currency_Conversion_Type>
                  <xsl:value-of select="ns0:CURRENCY_CONVERSION_TYPE"/>
               </tns:Currency_Conversion_Type>
               <tns:Currency_Conversion_Date>
                  <xsl:value-of select="concat (substring (ns0:CURRENCY_CONVERSION_DATE, 1, 4 ), &quot;/&quot;, substring (ns0:CURRENCY_CONVERSION_DATE, 6, 2 ), &quot;/&quot;, substring (ns0:CURRENCY_CONVERSION_DATE, 9, 2 ) )"/>
               </tns:Currency_Conversion_Date>
               <tns:Currency_Conversion_Rate>
                  <xsl:value-of select="ns0:CURRENCY_CONVERSION_RATE"/>
               </tns:Currency_Conversion_Rate>
               <tns:Transaction_Line_Amount>
                  <xsl:value-of select="ns0:TRANSACTION_LINE_AMOUNT"/>
               </tns:Transaction_Line_Amount>
               <tns:Transaction_Line_Quantity>
                  <xsl:value-of select="ns0:TRANSACTION_LINE_QUANTITY"/>
               </tns:Transaction_Line_Quantity>
               <tns:Customer_Ordered_Quantity>
                  <xsl:value-of select="ns0:CUSTOMER_ORDERED_QUANTITY"/>
               </tns:Customer_Ordered_Quantity>
               <tns:Unit_Selling_Price>
                  <xsl:value-of select="ns0:UNIT_SELLING_PRICE"/>
               </tns:Unit_Selling_Price>
               <tns:Unit_Standard_Price>
                  <xsl:value-of select="ns0:UNIT_STANDARD_PRICE"/>
               </tns:Unit_Standard_Price>
               <tns:Line_Transactions_Flexfield_Context>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_CONTEXT"/>
               </tns:Line_Transactions_Flexfield_Context>
               <tns:Line_Transactions_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_1"/>
               </tns:Line_Transactions_Flexfield_Segment_1>
               <tns:Line_Transactions_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_2"/>
               </tns:Line_Transactions_Flexfield_Segment_2>
               <tns:Line_Transactions_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_3"/>
               </tns:Line_Transactions_Flexfield_Segment_3>
               <tns:Line_Transactions_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_4"/>
               </tns:Line_Transactions_Flexfield_Segment_4>
               <tns:Line_Transactions_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_5"/>
               </tns:Line_Transactions_Flexfield_Segment_5>
               <tns:Line_Transactions_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_6"/>
               </tns:Line_Transactions_Flexfield_Segment_6>
               <tns:Line_Transactions_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_7"/>
               </tns:Line_Transactions_Flexfield_Segment_7>
               <tns:Line_Transactions_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_8"/>
               </tns:Line_Transactions_Flexfield_Segment_8>
               <tns:Line_Transactions_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_9"/>
               </tns:Line_Transactions_Flexfield_Segment_9>
               <tns:Line_Transactions_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_10"/>
               </tns:Line_Transactions_Flexfield_Segment_10>
               <tns:Line_Transactions_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_11"/>
               </tns:Line_Transactions_Flexfield_Segment_11>
               <tns:Line_Transactions_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_12"/>
               </tns:Line_Transactions_Flexfield_Segment_12>
               <tns:Line_Transactions_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_13"/>
               </tns:Line_Transactions_Flexfield_Segment_13>
               <tns:Line_Transactions_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_14"/>
               </tns:Line_Transactions_Flexfield_Segment_14>
               <tns:Line_Transactions_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:LINE_TRANSACTIONS_FLEXFIELD_SEGMENT_15"/>
               </tns:Line_Transactions_Flexfield_Segment_15>
               <tns:Primary_Salesperson_Number>
                  <xsl:value-of select="ns0:PRIMARY_SALESPERSON_NUMBER"/>
               </tns:Primary_Salesperson_Number>
               <tns:Tax_Classification_Code>
                  <xsl:value-of select="ns0:TAX_CLASSIFICATION_CODE"/>
               </tns:Tax_Classification_Code>
               <tns:Legal_Entity_Identifier>
                  <xsl:value-of select="ns0:LEGAL_ENTITY_IDENTIFIER"/>
               </tns:Legal_Entity_Identifier>
               <tns:Accounted_Amount_in_Ledger_Currency>
                  <xsl:value-of select="ns0:ACCOUNTED_AMOUNT_IN_LEDGER_CURRENCY"/>
               </tns:Accounted_Amount_in_Ledger_Currency>
               <tns:Sales_Order_Number>
                  <xsl:value-of select="ns0:SALES_ORDER_NUMBER"/>
               </tns:Sales_Order_Number>
               <tns:Sales_Order_Date>
                  <xsl:value-of select="ns0:SALES_ORDER_DATE"/>
               </tns:Sales_Order_Date>
               <tns:Actual_Ship_Date>
                  <xsl:value-of select="ns0:ACTUAL_SHIP_DATE"/>
               </tns:Actual_Ship_Date>
               <tns:Warehouse_Code>
                  <xsl:value-of select="ns0:WAREHOUSE_CODE"/>
               </tns:Warehouse_Code>
               <tns:Unit_of_Measure_Code>
                  <xsl:value-of select="ns0:UNIT_OF_MEASURE_CODE"/>
               </tns:Unit_of_Measure_Code>
               <tns:Unit_of_Measure_Name>
                  <xsl:value-of select="ns0:UNIT_OF_MEASURE_NAME"/>
               </tns:Unit_of_Measure_Name>
               <tns:Invoicing_Rule_Name>
                  <xsl:value-of select="ns0:INVOICING_RULE_NAME"/>
               </tns:Invoicing_Rule_Name>
               <tns:Revenue_Scheduling_Rule_Name>
                  <xsl:value-of select="ns0:REVENUE_SCHEDULING_RULE_NAME"/>
               </tns:Revenue_Scheduling_Rule_Name>
               <tns:Number_of_Revenue_Periods>
                  <xsl:value-of select="ns0:NUMBER_OF_REVENUE_PERIODS"/>
               </tns:Number_of_Revenue_Periods>
               <tns:Revenue_Scheduling_Rule_Start_Date>
                  <xsl:value-of select="ns0:REVENUE_SCHEDULING_RULE_START_DATE"/>
               </tns:Revenue_Scheduling_Rule_Start_Date>
               <tns:Revenue_Scheduling_Rule_End_Date>
                  <xsl:value-of select="ns0:REVENUE_SCHEDULING_RULE_END_DATE"/>
               </tns:Revenue_Scheduling_Rule_End_Date>
               <tns:Reason_Code_Meaning>
                  <xsl:value-of select="ns0:REASON_CODE_MEANING"/>
               </tns:Reason_Code_Meaning>
               <tns:Last_Period_to_Credit>
                  <xsl:value-of select="ns0:LAST_PERIOD_TO_CREDIT"/>
               </tns:Last_Period_to_Credit>
               <tns:Transaction_Business_Category_Code>
                  <xsl:value-of select="ns0:TRANSACTION_BUSINESS_CATEGORY_CODE"/>
               </tns:Transaction_Business_Category_Code>
               <tns:Product_Fiscal_Classification_Code>
                  <xsl:value-of select="ns0:PRODUCT_FISCAL_CLASSIFICATION_CODE"/>
               </tns:Product_Fiscal_Classification_Code>
               <tns:Product_Category_Code>
                  <xsl:value-of select="ns0:PRODUCT_CATEGORY_CODE"/>
               </tns:Product_Category_Code>
               <tns:Product_Type>
                  <xsl:value-of select="ns0:PRODUCT_TYPE"/>
               </tns:Product_Type>
               <tns:Line_Intended_Use_Code>
                  <xsl:value-of select="ns0:LINE_INTENDED_USE_CODE"/>
               </tns:Line_Intended_Use_Code>
               <tns:Assessable_Value>
                  <xsl:value-of select="ns0:ASSESSABLE_VALUE"/>
               </tns:Assessable_Value>
               <tns:Document_Sub_Type>
                  <xsl:value-of select="ns0:DOCUMENT_SUB_TYPE"/>
               </tns:Document_Sub_Type>
               <tns:Default_Taxation_Country>
                  <xsl:value-of select="ns0:DEFAULT_TAXATION_COUNTRY"/>
               </tns:Default_Taxation_Country>
               <tns:User_Defined_Fiscal_Classification>
                  <xsl:value-of select="ns0:USER_DEFINED_FISCAL_CLASSIFICATION"/>
               </tns:User_Defined_Fiscal_Classification>
               <tns:Tax_Invoice_Number>
                  <xsl:value-of select="ns0:TAX_INVOICE_NUMBER"/>
               </tns:Tax_Invoice_Number>
               <tns:Tax_Invoice_Date>
                  <xsl:value-of select="ns0:TAX_INVOICE_DATE"/>
               </tns:Tax_Invoice_Date>
               <tns:Tax_Regime_Code>
                  <xsl:value-of select="ns0:TAX_REGIME_CODE"/>
               </tns:Tax_Regime_Code>
               <tns:Tax>
                  <xsl:value-of select="ns0:TAX"/>
               </tns:Tax>
               <tns:Tax_Status_Code>
                  <xsl:value-of select="ns0:TAX_STATUS_CODE"/>
               </tns:Tax_Status_Code>
               <tns:Tax_Rate_Code>
                  <xsl:value-of select="ns0:TAX_RATE_CODE"/>
               </tns:Tax_Rate_Code>
               <tns:Tax_Jurisdiction_Code>
                  <xsl:value-of select="ns0:TAX_JURISDICTION_CODE"/>
               </tns:Tax_Jurisdiction_Code>
               <tns:First_Party_Registration_Number>
                  <xsl:value-of select="ns0:FIRST_PARTY_REGISTRATION_NUMBER"/>
               </tns:First_Party_Registration_Number>
               <tns:Third_Party_Registration_Number>
                  <xsl:value-of select="ns0:THIRD_PARTY_REGISTRATION_NUMBER"/>
               </tns:Third_Party_Registration_Number>
               <tns:Final_Discharge_Location>
                  <xsl:value-of select="ns0:FINAL_DISCHARGE_LOCATION"/>
               </tns:Final_Discharge_Location>
               <tns:Taxable_Amount>
                  <xsl:value-of select="ns0:TAXABLE_AMOUNT"/>
               </tns:Taxable_Amount>
               <tns:Taxable_Flag>
                  <xsl:value-of select="ns0:TAXABLE_FLAG"/>
               </tns:Taxable_Flag>
               <tns:Tax_Exemption_Flag>
                  <xsl:value-of select="ns0:TAX_EXEMPTION_FLAG"/>
               </tns:Tax_Exemption_Flag>
               <tns:TTax_Exemption_Reason_Code>
                  <xsl:value-of select="ns0:TAX_EXEMPTION_REASON_CODE"/>
               </tns:TTax_Exemption_Reason_Code>
               <tns:Tax_Exemption_Reason_Code_Meaning>
                  <xsl:value-of select="ns0:TAX_EXEMPTION_REASON_CODE_MEANING"/>
               </tns:Tax_Exemption_Reason_Code_Meaning>
               <tns:Tax_Exemption_Certificate_Number>
                  <xsl:value-of select="ns0:TAX_EXEMPTION_CERTIFICATE_NUMBER"/>
               </tns:Tax_Exemption_Certificate_Number>
               <tns:Line_Amount_Includes_Tax_Flag>
                  <xsl:value-of select="ns0:LINE_AMOUNT_INCLUDES_TAX_FLAG"/>
               </tns:Line_Amount_Includes_Tax_Flag>
               <tns:Tax_Precedence>
                  <xsl:value-of select="ns0:TAX_PRECEDENCE"/>
               </tns:Tax_Precedence>
               <tns:Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules>
                  <xsl:value-of select="ns0:CREDIT_METHOD_TO_BE_USED_FOR_LINES_WITH_REVENUE_SCHEDULING_RULES"/>
               </tns:Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules>
               <tns:Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms>
                  <xsl:value-of select="ns0:CREDIT_METHOD_TO_BE_USED_FOR_TRANSACTIONS_WITH_SPLIT_PAYMENT_TERMS"/>
               </tns:Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms>
               <tns:Reason_Code>
                  <xsl:value-of select="ns0:REASON_CODE"/>
               </tns:Reason_Code>
               <tns:Tax_Rate>
                  <xsl:value-of select="ns0:TAX_RATE"/>
               </tns:Tax_Rate>
               <tns:FOB_Point>
                  <xsl:value-of select="ns0:FOB_POINT"/>
               </tns:FOB_Point>
               <tns:Carrier>
                  <xsl:value-of select="ns0:CARRIER"/>
               </tns:Carrier>
               <tns:Shipping_Reference>
                  <xsl:value-of select="ns0:SHIPPING_REFERENCE"/>
               </tns:Shipping_Reference>
               <tns:Sales_Order_Line_Number>
                  <xsl:value-of select="ns0:SALES_ORDER_LINE_NUMBER"/>
               </tns:Sales_Order_Line_Number>
               <tns:Sales_Order_Source>
                  <xsl:value-of select="ns0:SALES_ORDER_SOURCE"/>
               </tns:Sales_Order_Source>
               <tns:Sales_Order_Revision_Number>
                  <xsl:value-of select="ns0:SALES_ORDER_REVISION_NUMBER"/>
               </tns:Sales_Order_Revision_Number>
               <tns:Purchase_Order_Number>
                  <xsl:value-of select="ns0:PURCHASE_ORDER_NUMBER"/>
               </tns:Purchase_Order_Number>
               <tns:Purchase_Order_Revision_Number>
                  <xsl:value-of select="ns0:PURCHASE_ORDER_REVISION_NUMBER"/>
               </tns:Purchase_Order_Revision_Number>
               <tns:Purchase_Order_Date>
                  <xsl:value-of select="ns0:PURCHASE_ORDER_DATE"/>
               </tns:Purchase_Order_Date>
               <tns:Agreement_Name>
                  <xsl:value-of select="ns0:AGREEMENT_NAME"/>
               </tns:Agreement_Name>
               <tns:Memo_Line_Name>
                  <xsl:value-of select="ns0:MEMO_LINE_NAME"/>
               </tns:Memo_Line_Name>
               <tns:Document_Number>
                  <xsl:value-of select="ns0:DOCUMENT_NUMBER"/>
               </tns:Document_Number>
               <tns:Original_System_Batch_Name>
                  <xsl:value-of select="ns0:ORIGINAL_SYSTEM_BATCH_NAME"/>
               </tns:Original_System_Batch_Name>
               <tns:Link_to_Transactions_Flexfield_Context>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_CONTEXT"/>
               </tns:Link_to_Transactions_Flexfield_Context>
               <tns:Link_to_Transactions_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_1"/>
               </tns:Link_to_Transactions_Flexfield_Segment_1>
               <tns:Link_to_Transactions_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_2"/>
               </tns:Link_to_Transactions_Flexfield_Segment_2>
               <tns:Link_to_Transactions_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_3"/>
               </tns:Link_to_Transactions_Flexfield_Segment_3>
               <tns:Link_to_Transactions_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_4"/>
               </tns:Link_to_Transactions_Flexfield_Segment_4>
               <tns:Link_to_Transactions_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_5"/>
               </tns:Link_to_Transactions_Flexfield_Segment_5>
               <tns:Link_to_Transactions_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_6"/>
               </tns:Link_to_Transactions_Flexfield_Segment_6>
               <tns:Link_to_Transactions_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_7"/>
               </tns:Link_to_Transactions_Flexfield_Segment_7>
               <tns:Link_to_Transactions_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_8"/>
               </tns:Link_to_Transactions_Flexfield_Segment_8>
               <tns:Link_to_Transactions_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_9"/>
               </tns:Link_to_Transactions_Flexfield_Segment_9>
               <tns:Link_to_Transactions_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_10"/>
               </tns:Link_to_Transactions_Flexfield_Segment_10>
               <tns:Link_to_Transactions_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_11"/>
               </tns:Link_to_Transactions_Flexfield_Segment_11>
               <tns:Link_to_Transactions_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_12"/>
               </tns:Link_to_Transactions_Flexfield_Segment_12>
               <tns:Link_to_Transactions_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_13"/>
               </tns:Link_to_Transactions_Flexfield_Segment_13>
               <tns:Link_to_Transactions_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_14"/>
               </tns:Link_to_Transactions_Flexfield_Segment_14>
               <tns:Link_to_Transactions_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:LINK_TO_TRANSACTIONS_FLEXFIELD_SEGMENT_15"/>
               </tns:Link_to_Transactions_Flexfield_Segment_15>
               <tns:Reference_Transactions_Flexfield_Context>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_CONTEXT"/>
               </tns:Reference_Transactions_Flexfield_Context>
               <tns:Reference_Transactions_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_1"/>
               </tns:Reference_Transactions_Flexfield_Segment_1>
               <tns:Reference_Transactions_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_2"/>
               </tns:Reference_Transactions_Flexfield_Segment_2>
               <tns:Reference_Transactions_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_3"/>
               </tns:Reference_Transactions_Flexfield_Segment_3>
               <tns:Reference_Transactions_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_4"/>
               </tns:Reference_Transactions_Flexfield_Segment_4>
               <tns:Reference_Transactions_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_5"/>
               </tns:Reference_Transactions_Flexfield_Segment_5>
               <tns:Reference_Transactions_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_6"/>
               </tns:Reference_Transactions_Flexfield_Segment_6>
               <tns:Reference_Transactions_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_7"/>
               </tns:Reference_Transactions_Flexfield_Segment_7>
               <tns:Reference_Transactions_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_8"/>
               </tns:Reference_Transactions_Flexfield_Segment_8>
               <tns:Reference_Transactions_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_9"/>
               </tns:Reference_Transactions_Flexfield_Segment_9>
               <tns:Reference_Transactions_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_10"/>
               </tns:Reference_Transactions_Flexfield_Segment_10>
               <tns:Reference_Transactions_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_11"/>
               </tns:Reference_Transactions_Flexfield_Segment_11>
               <tns:Reference_Transactions_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_12"/>
               </tns:Reference_Transactions_Flexfield_Segment_12>
               <tns:Reference_Transactions_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_13"/>
               </tns:Reference_Transactions_Flexfield_Segment_13>
               <tns:Reference_Transactions_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_14"/>
               </tns:Reference_Transactions_Flexfield_Segment_14>
               <tns:Reference_Transactions_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:REFERENCE_TRANSACTIONS_FLEXFIELD_SEGMENT_15"/>
               </tns:Reference_Transactions_Flexfield_Segment_15>
               <tns:Link_To_Parent_Line_Context>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_CONTEXT"/>
               </tns:Link_To_Parent_Line_Context>
               <tns:Link_To_Parent_Line_Segment_1>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_1"/>
               </tns:Link_To_Parent_Line_Segment_1>
               <tns:Link_To_Parent_Line_Segment_2>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_2"/>
               </tns:Link_To_Parent_Line_Segment_2>
               <tns:Link_To_Parent_Line_Segment_3>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_3"/>
               </tns:Link_To_Parent_Line_Segment_3>
               <tns:Link_To_Parent_Line_Segment_4>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_4"/>
               </tns:Link_To_Parent_Line_Segment_4>
               <tns:Link_To_Parent_Line_Segment_5>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_5"/>
               </tns:Link_To_Parent_Line_Segment_5>
               <tns:Link_To_Parent_Line_Segment_6>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_6"/>
               </tns:Link_To_Parent_Line_Segment_6>
               <tns:Link_To_Parent_Line_Segment_7>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_7"/>
               </tns:Link_To_Parent_Line_Segment_7>
               <tns:Link_To_Parent_Line_Segment_8>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_8"/>
               </tns:Link_To_Parent_Line_Segment_8>
               <tns:Link_To_Parent_Line_Segment_9>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_9"/>
               </tns:Link_To_Parent_Line_Segment_9>
               <tns:Link_To_Parent_Line_Segment_10>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_10"/>
               </tns:Link_To_Parent_Line_Segment_10>
               <tns:Link_To_Parent_Line_Segment_11>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_11"/>
               </tns:Link_To_Parent_Line_Segment_11>
               <tns:Link_To_Parent_Line_Segment_12>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_12"/>
               </tns:Link_To_Parent_Line_Segment_12>
               <tns:Link_To_Parent_Line_Segment_13>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_13"/>
               </tns:Link_To_Parent_Line_Segment_13>
               <tns:Link_To_Parent_Line_Segment_14>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_14"/>
               </tns:Link_To_Parent_Line_Segment_14>
               <tns:Link_To_Parent_Line_Segment_15>
                  <xsl:value-of select="ns0:LINK_TO_PARENT_LINE_SEGMENT_15"/>
               </tns:Link_To_Parent_Line_Segment_15>
               <tns:Receipt_Method_Name>
                  <xsl:value-of select="ns0:RECEIPT_METHOD_NAME"/>
               </tns:Receipt_Method_Name>
               <tns:Printing_Option>
                  <xsl:value-of select="ns0:PRINTING_OPTION"/>
               </tns:Printing_Option>
               <tns:Related_Batch_Source_Name>
                  <xsl:value-of select="ns0:RELATED_BATCH_SOURCE_NAME"/>
               </tns:Related_Batch_Source_Name>
               <tns:Related_Transaction_Number>
                  <xsl:value-of select="ns0:RELATED_TRANSACTION_NUMBER"/>
               </tns:Related_Transaction_Number>
               <tns:Inventory_Item_Number>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_NUMBER"/>
               </tns:Inventory_Item_Number>
               <tns:Inventory_Item_Segment_2>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_2"/>
               </tns:Inventory_Item_Segment_2>
               <tns:Inventory_Item_Segment_3>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_3"/>
               </tns:Inventory_Item_Segment_3>
               <tns:Inventory_Item_Segment_4>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_4"/>
               </tns:Inventory_Item_Segment_4>
               <tns:Inventory_Item_Segment_5>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_5"/>
               </tns:Inventory_Item_Segment_5>
               <tns:Inventory_Item_Segment_6>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_6"/>
               </tns:Inventory_Item_Segment_6>
               <tns:Inventory_Item_Segment_7>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_7"/>
               </tns:Inventory_Item_Segment_7>
               <tns:Inventory_Item_Segment_8>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_8"/>
               </tns:Inventory_Item_Segment_8>
               <tns:Inventory_Item_Segment_9>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_9"/>
               </tns:Inventory_Item_Segment_9>
               <tns:Inventory_Item_Segment_10>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_10"/>
               </tns:Inventory_Item_Segment_10>
               <tns:Inventory_Item_Segment_11>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_11"/>
               </tns:Inventory_Item_Segment_11>
               <tns:Inventory_Item_Segment_12>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_12"/>
               </tns:Inventory_Item_Segment_12>
               <tns:Inventory_Item_Segment_13>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_13"/>
               </tns:Inventory_Item_Segment_13>
               <tns:Inventory_Item_Segment_14>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_14"/>
               </tns:Inventory_Item_Segment_14>
               <tns:Inventory_Item_Segment_15>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_15"/>
               </tns:Inventory_Item_Segment_15>
               <tns:Inventory_Item_Segment_16>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_16"/>
               </tns:Inventory_Item_Segment_16>
               <tns:Inventory_Item_Segment_17>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_17"/>
               </tns:Inventory_Item_Segment_17>
               <tns:Inventory_Item_Segment_18>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_18"/>
               </tns:Inventory_Item_Segment_18>
               <tns:Inventory_Item_Segment_19>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_19"/>
               </tns:Inventory_Item_Segment_19>
               <tns:Inventory_Item_Segment_20>
                  <xsl:value-of select="ns0:INVENTORY_ITEM_SEGMENT_20"/>
               </tns:Inventory_Item_Segment_20>
               <tns:Bill_To_Customer_Bank_Account_Name>
                  <xsl:value-of select="ns0:BILL_TO_CUSTOMER_BANK_ACCOUNT_NAME"/>
               </tns:Bill_To_Customer_Bank_Account_Name>
               <tns:Reset_Transaction_Date_Flag>
                  <xsl:value-of select="ns0:RESET_TRANSACTION_DATE_FLAG"/>
               </tns:Reset_Transaction_Date_Flag>
               <tns:Payment_Server_Order_Number>
                  <xsl:value-of select="ns0:PAYMENT_SERVER_ORDER_NUMBER"/>
               </tns:Payment_Server_Order_Number>
               <tns:Last_Transaction_on_Debit_Authorization>
                  <xsl:value-of select="ns0:LAST_TRANSACTION_ON_DEBIT_AUTHORIZATION"/>
               </tns:Last_Transaction_on_Debit_Authorization>
               <tns:Approval_Code>
                  <xsl:value-of select="ns0:APPROVAL_CODE"/>
               </tns:Approval_Code>
               <tns:Address_Verification_Code>
                  <xsl:value-of select="ns0:ADDRESS_VERIFICATION_CODE"/>
               </tns:Address_Verification_Code>
               <tns:Transaction_Line_Translated_Description>
                  <xsl:value-of select="ns0:TRANSACTION_LINE_TRANSLATED_DESCRIPTION"/>
               </tns:Transaction_Line_Translated_Description>
               <tns:Consolidated_Billing_Number>
                  <xsl:value-of select="ns0:CONSOLIDATED_BILLING_NUMBER"/>
               </tns:Consolidated_Billing_Number>
               <tns:Promised_Commitment_Amount>
                  <xsl:value-of select="ns0:PROMISED_COMMITMENT_AMOUNT"/>
               </tns:Promised_Commitment_Amount>
               <tns:Payment_Set_Identifier>
                  <xsl:value-of select="ns0:PAYMENT_SET_IDENTIFIER"/>
               </tns:Payment_Set_Identifier>
               <tns:Original_Accounting_Date>
                  <xsl:value-of select="ns0:ORIGINAL_ACCOUNTING_DATE"/>
               </tns:Original_Accounting_Date>
               <tns:Invoiced_Line_Accounting_Level>
                  <xsl:value-of select="ns0:INVOICED_LINE_ACCOUNTING_LEVEL"/>
               </tns:Invoiced_Line_Accounting_Level>
               <tns:Override_AutoAccounting_Flag>
                  <xsl:value-of select="ns0:OVERRIDE_AUTOACCOUNTING_FLAG"/>
               </tns:Override_AutoAccounting_Flag>
               <tns:Historical_Flag>
                  <xsl:value-of select="ns0:HISTORICAL_FLAG"/>
               </tns:Historical_Flag>
               <tns:Deferral_Exclusion_Flag>
                  <xsl:value-of select="ns0:DEFERRAL_EXCLUSION_FLAG"/>
               </tns:Deferral_Exclusion_Flag>
               <tns:Payment_Attributes>
                  <xsl:value-of select="ns0:PAYMENT_ATTRIBUTES"/>
               </tns:Payment_Attributes>
               <tns:Invoice_Billing_Date>
                  <xsl:value-of select="ns0:INVOICE_BILLING_DATE"/>
               </tns:Invoice_Billing_Date>
               <tns:Invoice_Lines_Flexfield_Context>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_CONTEXT"/>
               </tns:Invoice_Lines_Flexfield_Context>
               <tns:Invoice_Lines_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_1"/>
               </tns:Invoice_Lines_Flexfield_Segment_1>
               <tns:Invoice_Lines_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_2"/>
               </tns:Invoice_Lines_Flexfield_Segment_2>
               <tns:Invoice_Lines_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_3"/>
               </tns:Invoice_Lines_Flexfield_Segment_3>
               <tns:Invoice_Lines_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_4"/>
               </tns:Invoice_Lines_Flexfield_Segment_4>
               <tns:Invoice_Lines_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_5"/>
               </tns:Invoice_Lines_Flexfield_Segment_5>
               <tns:Invoice_Lines_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_6"/>
               </tns:Invoice_Lines_Flexfield_Segment_6>
               <tns:Invoice_Lines_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_7"/>
               </tns:Invoice_Lines_Flexfield_Segment_7>
               <tns:Invoice_Lines_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_8"/>
               </tns:Invoice_Lines_Flexfield_Segment_8>
               <tns:Invoice_Lines_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_9"/>
               </tns:Invoice_Lines_Flexfield_Segment_9>
               <tns:Invoice_Lines_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_10"/>
               </tns:Invoice_Lines_Flexfield_Segment_10>
               <tns:Invoice_Lines_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_11"/>
               </tns:Invoice_Lines_Flexfield_Segment_11>
               <tns:Invoice_Lines_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_12"/>
               </tns:Invoice_Lines_Flexfield_Segment_12>
               <tns:Invoice_Lines_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_13"/>
               </tns:Invoice_Lines_Flexfield_Segment_13>
               <tns:Invoice_Lines_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_14"/>
               </tns:Invoice_Lines_Flexfield_Segment_14>
               <tns:Invoice_Lines_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:INVOICE_LINES_FLEXFIELD_SEGMENT_15"/>
               </tns:Invoice_Lines_Flexfield_Segment_15>
               <tns:Invoice_Transactions_Flexfield_Context>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_CONTEXT"/>
               </tns:Invoice_Transactions_Flexfield_Context>
               <tns:Invoice_Transactions_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_1"/>
               </tns:Invoice_Transactions_Flexfield_Segment_1>
               <tns:Invoice_Transactions_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_2"/>
               </tns:Invoice_Transactions_Flexfield_Segment_2>
               <tns:Invoice_Transactions_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_3"/>
               </tns:Invoice_Transactions_Flexfield_Segment_3>
               <tns:Invoice_Transactions_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_4"/>
               </tns:Invoice_Transactions_Flexfield_Segment_4>
               <tns:Invoice_Transactions_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_5"/>
               </tns:Invoice_Transactions_Flexfield_Segment_5>
               <tns:Invoice_Transactions_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_6"/>
               </tns:Invoice_Transactions_Flexfield_Segment_6>
               <tns:Invoice_Transactions_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_7"/>
               </tns:Invoice_Transactions_Flexfield_Segment_7>
               <tns:Invoice_Transactions_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_8"/>
               </tns:Invoice_Transactions_Flexfield_Segment_8>
               <tns:Invoice_Transactions_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_9"/>
               </tns:Invoice_Transactions_Flexfield_Segment_9>
               <tns:Invoice_Transactions_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_10"/>
               </tns:Invoice_Transactions_Flexfield_Segment_10>
               <tns:Invoice_Transactions_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_11"/>
               </tns:Invoice_Transactions_Flexfield_Segment_11>
               <tns:Invoice_Transactions_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_12"/>
               </tns:Invoice_Transactions_Flexfield_Segment_12>
               <tns:Invoice_Transactions_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_13"/>
               </tns:Invoice_Transactions_Flexfield_Segment_13>
               <tns:Invoice_Transactions_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_14"/>
               </tns:Invoice_Transactions_Flexfield_Segment_14>
               <tns:Invoice_Transactions_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:INVOICE_TRANSACTIONS_FLEXFIELD_SEGMENT_15"/>
               </tns:Invoice_Transactions_Flexfield_Segment_15>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Context>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_CONTEXT"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Context>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_1"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_1>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_2"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_2>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_3"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_3>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_4"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_4>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_5"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_5>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_6"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_6>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_7"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_7>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_8"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_8>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_9"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_9>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_10"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_10>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_11"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_11>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_12"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_12>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_13"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_13>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_14"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_14>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_15"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_15>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_16>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_16"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_16>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_17>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_17"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_17>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_18>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_18"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_18>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_19>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_19"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_19>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_20>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_20"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_20>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_21>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_21"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_21>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_22>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_22"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_22>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_23>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_23"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_23>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_24>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_24"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_24>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_25>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_25"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_25>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_26>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_26"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_26>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_27>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_27"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_27>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_28>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_28"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_28>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_29>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_29"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_29>
               <tns:Receivables_Transaction_Region_Information_Flexfield_Segment_30>
                  <xsl:value-of select="ns0:RECEIVABLES_TRANSACTION_REGION_INFORMATION_FLEXFIELD_SEGMENT_30"/>
               </tns:Receivables_Transaction_Region_Information_Flexfield_Segment_30>
               <tns:Line_Global_Descriptive_Flexfield_Attribute_Category>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_ATTRIBUTE_CATEGORY"/>
               </tns:Line_Global_Descriptive_Flexfield_Attribute_Category>
               <tns:Line_Global_Descriptive_Flexfield_Segment_1>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_1"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_1>
               <tns:Line_Global_Descriptive_Flexfield_Segment_2>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_2"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_2>
               <tns:Line_Global_Descriptive_Flexfield_Segment_3>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_3"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_3>
               <tns:Line_Global_Descriptive_Flexfield_Segment_4>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_4"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_4>
               <tns:Line_Global_Descriptive_Flexfield_Segment_5>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_5"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_5>
               <tns:Line_Global_Descriptive_Flexfield_Segment_6>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_6"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_6>
               <tns:Line_Global_Descriptive_Flexfield_Segment_7>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_7"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_7>
               <tns:Line_Global_Descriptive_Flexfield_Segment_8>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_8"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_8>
               <tns:Line_Global_Descriptive_Flexfield_Segment_9>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_9"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_9>
               <tns:Line_Global_Descriptive_Flexfield_Segment_10>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_10"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_10>
               <tns:Line_Global_Descriptive_Flexfield_Segment_11>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_11"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_11>
               <tns:Line_Global_Descriptive_Flexfield_Segment_12>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_12"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_12>
               <tns:Line_Global_Descriptive_Flexfield_Segment_13>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_13"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_13>
               <tns:Line_Global_Descriptive_Flexfield_Segment_14>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_14"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_14>
               <tns:Line_Global_Descriptive_Flexfield_Segment_15>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_15"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_15>
               <tns:Line_Global_Descriptive_Flexfield_Segment_16>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_16"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_16>
               <tns:Line_Global_Descriptive_Flexfield_Segment_17>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_17"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_17>
               <tns:Line_Global_Descriptive_Flexfield_Segment_18>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_18"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_18>
               <tns:Line_Global_Descriptive_Flexfield_Segment_19>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_19"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_19>
               <tns:Line_Global_Descriptive_Flexfield_Segment_20>
                  <xsl:value-of select="ns0:LINE_GLOBAL_DESCRIPTIVE_FLEXFIELD_SEGMENT_20"/>
               </tns:Line_Global_Descriptive_Flexfield_Segment_20>
               <tns:Business_Unit_Name>
                  <xsl:value-of select="ns0:BUSINESS_UNIT_NAME"/>
               </tns:Business_Unit_Name>
               <tns:Comments>
                  <xsl:value-of select="ns0:COMMENTS"/>
               </tns:Comments>
               <tns:Enforce_Chronological_Document_Sequencing>
                  <xsl:value-of select="ns0:ENFORCE_CHRONOLOGICAL_DOCUMENT_SEQUENCING"/>
               </tns:Enforce_Chronological_Document_Sequencing>
               <tns:Aux>
                  <xsl:value-of select="ns0:ENFORCE_CHRONOLOGICAL_DOCUMENT_SEQUENCING"/>
               </tns:Aux>
               <tns:C291>
                  <xsl:value-of select='"END"'/>
               </tns:C291>
            </tns:InvoicesList>
         </xsl:for-each>
      </tns:invoicesToCsv>
   </xsl:template>
</xsl:stylesheet>
