<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz" xmlns:tns="http://soa.estrellaroja.com.mx/FinancialsTec" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelBuildInvoicesZip"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns3="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns4="http://soa.estrellaroja.com.mx/FinancialsTec/types"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns5="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:ns6="http://soa.estrellaroja.com.mx/InvoicesBiz/StructursInvoicesBiz"
                xmlns:ns7="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelBuildInvoicesZip.wsdl"/>
            <oracle-xsl-mapper:rootElement name="BuildInvoicesZipRq" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/OSB/FinancialsTec/FinancialsTec.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetReceiptOrInvoicesRq" namespace="http://soa.estrellaroja.com.mx/FinancialsTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU JAN 04 11:49:09 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetReceiptOrInvoicesRq>
         <tns:Module>
            <xsl:value-of select="/ns0:BuildInvoicesZipRq/ns0:DocumentType"/>
         </tns:Module>
         <tns:Informations>
            <xsl:for-each select="/ns0:BuildInvoicesZipRq/ns0:InputDm/ns0:DATA_DS/ns0:Q_CUSTOMER">
               <tns:Information>
                  <tns:RFC>
                     <xsl:value-of select="ns0:RFC"/>
                  </tns:RFC>
                  <tns:PartyName>
                     <xsl:value-of select="ns0:PARTY_NAME"/>
                  </tns:PartyName>
                  <tns:PartyNumber>
                     <xsl:value-of select="ns0:PARTY_NUMBER"/>
                  </tns:PartyNumber>
                  <tns:PartyId>
                     <xsl:value-of select="ns0:PARTY_ID"/>
                  </tns:PartyId>
                  <tns:AccountNumber>
                     <xsl:value-of select="ns0:ACCOUNT_NUMBER"/>
                  </tns:AccountNumber>
                  <tns:CustAccount>
                     <xsl:value-of select="ns0:CUST_ACCOUNT_ID"/>
                  </tns:CustAccount>
                  <tns:CustAccountSiteId>
                     <xsl:value-of select="ns0:CUST_ACCT_SITE_ID"/>
                  </tns:CustAccountSiteId>
                  <tns:PartySiteNumber>
                     <xsl:value-of select="ns0:PARTY_SITE_NUMBER"/>
                  </tns:PartySiteNumber>
                  <tns:SiteUseId>
                     <xsl:value-of select="ns0:SITE_USE_ID"/>
                  </tns:SiteUseId>
                  <tns:SiteUseCode>
                     <xsl:value-of select="ns0:SITE_USE_CODE"/>
                  </tns:SiteUseCode>
                  <tns:PrimaryFlag>
                     <xsl:value-of select="ns0:PRIMARY_FLAG"/>
                  </tns:PrimaryFlag>
                  <tns:Location>
                     <xsl:value-of select="ns0:LOCATION"/>
                  </tns:Location>
                  <tns:LocationId>
                     <xsl:value-of select="ns0:LOCATION_ID"/>
                  </tns:LocationId>
                  <tns:PaymentTerms>
                     <xsl:value-of select="ns0:PAYMENT_TERMS"/>
                  </tns:PaymentTerms>
                  <tns:OrgId>
                     <xsl:value-of select="ns0:ORG_ID"/>
                  </tns:OrgId>
                  <tns:BuName>
                     <xsl:value-of select="ns0:BU_NAME"/>
                  </tns:BuName>
               </tns:Information>
            </xsl:for-each>
         </tns:Informations>
      </tns:GetReceiptOrInvoicesRq>
   </xsl:template>
</xsl:stylesheet>
