<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://soa.estrellaroja.com.mx/InvoicesBiz" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns5="http://soa.estrellaroja.com.mx/InvoicesBiz/DoctosRelacionados"
                xmlns:ns3="http://soa.estrellaroja.com.mx/ElectronicInvoiceAP"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns4="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
                xmlns:client="http://soa.estrellaroja.com.mx/InvoicesBiz/bpelUploadPaymentComplements"
                xmlns:ns6="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"
                xmlns:ns1="http://soa.estrellaroja.com.mx/InvoicesBiz/ERPIntegrationServiceTec">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelUploadPaymentComplements.wsdl"/>
            <oracle-xsl-mapper:rootElement name="UploadPaymentComplementsRq" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../WSDLs/bpelUploadPaymentComplements.wsdl"/>
            <oracle-xsl-mapper:rootElement name="UploadPaymentComplementsRs" namespace="http://soa.estrellaroja.com.mx/InvoicesBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE JAN 02 22:19:27 CST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:UploadPaymentComplementsRs>
         <xsl:if test="/ns0:UploadPaymentComplementsRq/ns0:FailureCount = 0">
            <ns2:Success/>
         </xsl:if>
         <xsl:if test="/ns0:UploadPaymentComplementsRq/ns0:FailureCount > 0">
            <ns2:Errors>
               <xsl:for-each select="/ns0:UploadPaymentComplementsRq/ns0:CarriedErrors/ns2:Error">
                  <ns2:Error>
                     <ns2:ErrorCode>
                        <xsl:value-of select="ns2:ErrorCode"/>
                     </ns2:ErrorCode>
                     <ns2:ShortDescription>
                        <xsl:value-of select="ns2:ShortDescription"/>
                     </ns2:ShortDescription>
                     <ns2:Description>
                        <xsl:value-of select="ns2:Description"/>
                     </ns2:Description>
                     <ns2:BusinessProcess>
                        <xsl:value-of select="ns2:BusinessProcess"/>
                     </ns2:BusinessProcess>
                     <ns2:FailedService>
                        <xsl:value-of select="ns2:FailedService"/>
                     </ns2:FailedService>
                     <ns2:TimeStamp>
                        <xsl:value-of select="ns2:TimeStamp"/>
                     </ns2:TimeStamp>
                  </ns2:Error>
               </xsl:for-each>
            </ns2:Errors>
         </xsl:if>
      </ns0:UploadPaymentComplementsRs>
   </xsl:template>
</xsl:stylesheet>
