<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="wsERPIntegrationServiceTec">
        <plnk:role name="ERPIntegrationTecPortType" portType="ns1:ERPIntegrationTecPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soa.estrellaroja.com.mx/ERPIntegrationServiceTec" location="oramds:/apps/OSB/ERPIntegrationServiceTec/ERPIntegrationServiceTec.wsdl"/>
</wsdl:definitions>
